### ISSUE TITLE
Lighter Strawberry Daiqiri for Mihon Preview

### ISSUE THREAD

**Issue by Rokimichi** [mihonapp/mihon#1005]
### Describe your suggested feature

Bring back the lighter color of Strawberry Daiqiri for Mihon Preview just like the one in Mihon Stable. Thank you so much!🫡

### Other details

![Screenshot_2024-07-11-19-59-40-773_app mihon](https://github.com/mihonapp/mihon/assets/100658783/7cbd67f0-1bc8-4c4b-b58e-3d4e666d52e9)
![Screenshot_2024-07-11-20-00-01-892_app mihon debug](https://github.com/mihonapp/mihon/assets/100658783/8c05793a-36be-4157-9dc8-760cab46b6da)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
No. The contrast before was horrible.
