### ISSUE TITLE
Add a library filter "has duplicate chapters"

### ISSUE THREAD

**Issue by isabella-almeidaa** [mihonapp/mihon#1013]
### Describe your suggested feature

Just a filter for the library that shows which entries has duplicate chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
