### ISSUE TITLE
Pinned 

### ISSUE THREAD

**Issue by Ventus4469** [mihonapp/mihon#102]
### Describe your suggested feature

Whenever I try to add a new manga it auto picks pinned. I'm hoping y'all can disable or least let us auto select all. It's a tiny thing but a little annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Just pin a few of your most frequently used sources, that's what it's there for.

**Comment by Bitals** [comment]
@MajorTanya well I only have my most frequently used sources, this functionality is completely redundant for me and just annoying.

**Comment by MajorTanya** [comment]
> @MajorTanya well I only have my most frequently used sources, this functionality is completely redundant for me and just annoying.

Good/bad for you I guess but there's a lot of people that are using several sources more than just their favourites 👍

**Comment by Bitals** [comment]
> there's a lot of people that are using several sources more than just their favourites 👍

Absolutely, that's not what either me or OP are advocating against. We just ask to have an **option** to make "All" the default filter, not to make everyone else's lives harder to support our evil world domination scheme.

**Comment by BrutuZ** [comment]
In that case how hard it is to pin the handful of sources you do have installed and make it effectively the same as *All*?
Surely less work than going on with this argument

**Comment by hsiayuchih** [comment]
> > @MajorTanya well I only have my most frequently used sources, this functionality is completely redundant for me and just annoying.
> 
> Good/bad for you I guess but there's a lot of people that are using several sources more than just their favourites 👍

I also find this feature a bit obtrusive and suggest adding an option to turn it off instead of the default pinned!

**Comment by hsiayuchih** [comment]
> > there's a lot of people that are using several sources more than just their favourites 👍
> 
> Absolutely, that's not what either me or OP are advocating against. We just ask to have an **option** to make "All" the default filter, not to make everyone else's lives harder to support our evil world domination scheme.

That's what I thought!

**Comment by hsiayuchih** [comment]
Urgently need to add this feature!

**Comment by MajorTanya** [comment]
> Urgently need to add this feature!

Just do the one extra tap to search All sources instead, it's literally one tap.

**Comment by AntsyLich** [comment]
No. Pin your stuff or tap search all

**Comment by soredake** [comment]
Why a user should even do an extra tap if there can be an option to avoid this? I don't understand this at all, I have many extensions, I DON'T want to pin them all, nor do I want to do an extra tap when this can be avoided.

**Comment by AntsyLich** [comment]
> I have many extensions

We don't want you to spam a bazillion extension at the same time. You're not the only guy who's using Mihon I'm the whole wide world. If you don't like Mihon's system don't use it. And stop being entitled you're not paying a single penny to use the app or to use those extensions.

**Comment by CrepeTF** [comment]
> Why a user should even do an extra tap if there can be an option to avoid this? I don't understand this at all, I have many extensions, I DON'T want to pin them all, nor do I want to do an extra tap when this can be avoided.

Well there would be no more "user" if all sources decide to shut down because of constant DDoS would there. If what you want a is a crippled app then feel free to make your own.
