### ISSUE TITLE
App Crashes When Deleting an Untracked Entry After Removing it from Tracker

### ISSUE THREAD

**Issue by CasperKristiansson** [mihonapp/mihon#1023]
### Steps to reproduce

1. Track a specific Entry (Anilist for example)
2. Via the website (anilist) remove it
3. Go back to the app and check the status on the tracking (this will show a popup that "Could not find manga"
4. Try to delete the entry
5. Crash...

### Expected behavior

Shouldn't crash, just handle the exception that it isn't anymore tracked if the provider cant find itcan't

### Actual behavior

Crashes because it tries to remove a entry which is not being trackedan

### Crash logs

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 14 (SDK 34; build UP1A.231005.007.G998BXXSBGXED)
Device brand: samsung
Device manufacturer: samsung
Device name: p3s (p3sxeea)
Device model: SM-G998B
WebView: Android System WebView 126.0.6478.134

--------- beginning of main
07-17 23:16:16.790 21016 21016 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:16:25.793 21727 21727 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:16:25.907 21727 21770 E SQLiteLog: (28) double-quoted string literal: ""
07-17 23:16:25.927 21727 21782 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:16:25.927 21727 21782 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:16:26.192 21727 21829 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 23:16:26.192 21727 21829 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-17 23:21:41.505 24764 24764 E n:error_handler: Not starting debugger since process cannot load the jdwp agent.
07-17 23:21:41.586 24764 24789 E SQLiteLog: (283) recovered 939 frames from WAL file /data/data/app.mihon/databases/tachiyomi.db-wal
07-17 23:21:42.967 24940 24940 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:21:43.034 24940 24973 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-17 23:21:43.077 24940 24990 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:21:43.077 24940 24990 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:21:43.285 24940 25089 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 23:21:43.286 24940 25089 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-17 23:22:13.842 25278 25278 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:22:13.915 25278 25316 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-17 23:22:13.943 25278 25315 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:22:13.943 25278 25315 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:22:14.154 25278 25441 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 23:22:14.154 25278 25441 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-17 23:22:28.720 25555 25555 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:22:28.788 25555 25594 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-17 23:22:28.818 25555 25616 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:22:28.818 25555 25616 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:22:29.037 25555 25735 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 23:22:29.037 25555 25735 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-17 23:27:04.110 28894 28894 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:27:04.220 28894 28956 E SQLiteLog: (283) recovered 213 frames from WAL file /data/data/app.mihon/databases/tachiyomi.db-wal
07-17 23:27:04.254 28894 28961 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:27:04.254 28894 28961 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:27:04.509 28894 29039 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 23:27:04.509 28894 29039 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-17 23:28:01.600 29342 29342 E n:error_handler: Not starting debugger since process cannot load the jdwp agent.
07-17 23:28:03.324 29481 29481 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-17 23:28:03.402 29481 29512 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-17 23:28:03.434 29481 29518 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:28:03.435 29481 29518 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-17 23:28:03.655 29481 29589 E SQLiteLog: (284) automatic index on C(manga_id)
07-17 23:28:03.655 29481 29589 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

### Mihon version

0.16.5

### Android version

Android 14

### Device

Samsung Galaxy S21 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TanishMoral11** [comment]
I'm On It.
