### ISSUE TITLE
Add a way to differentiate tag searching from title searching 

### ISSUE THREAD

**Issue by isabella-almeidaa** [mihonapp/mihon#1026]
### Describe your suggested feature

adding a way to differentiate tag searching from title searching (like adding a symbol first or something like that) would be a good addition.
a + sign for a tag to be included and a - sign for a tag to be excluded for example

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Well differentiating them aside,
You can add a `-` before your query to exclude and just searching for multiple tags also works. 
for example this is a valid query to search for 'comedy' and 'school life' excluding 'romance' `comedy school life -romance`

**Comment by isabella-almeidaa** [comment]
> Well differentiating them aside, You can add a `-` before your query to exclude and just searching for multiple tags also works. for example this is a valid query to search for 'comedy' and 'school life' excluding 'romance' `comedy school life -romance`

I wasn't aware about this! ty

**Comment by Animeboynz** [comment]
Quick note: It has been brought to my attention that you need to add a comma between each tag if you are on Mihon.
But some forks allow you to skip them.
