### ISSUE TITLE
Mihon downloads does not seem to work with vpn. (Proton VPN)

### ISSUE THREAD

**Issue by Dipto-14** [mihonapp/mihon#1027]
### Steps to reproduce

1. Connect to any VPN. 
2. Download a chapter.

### Expected behavior

The chapter should download normally.

### Actual behavior

Mihon sends a notification saying "No network connection available" and chapter does not download.

### Crash logs

It's not really a crash but here you go.
[mihon_crash_logs.txt](https://github.com/user-attachments/files/16277269/mihon_crash_logs.txt)

### Mihon version

0.16.5

### Android version

Android 12

### Device

Redmi Note 10

### Other details

Mihon also fails to download with adblockers that acts like vpn. I have tried to download with "Only with wifi" disabled but it doesn't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Didn't face any such issues. Join our discord for further help.

**Comment by Dipto-14** [comment]
Sorry, couldn't reply to any comments as our dictator govt shut down internet for 6 days to silence protestors. Anyway, I was mistaken, the issue seemed to be my ISP. After the internet blackout downloads with vpn seem to be working.  Though, some sites still refuse to work with vpn through mihon even though browsers work.
