### ISSUE TITLE
Being able to move cache folder or the whole app to sd card

### ISSUE THREAD

**Issue by Solojump8** [mihonapp/mihon#1028]
### Describe your suggested feature

I really appreciate your outstanding efforts in making such a wonderful app available. My only modest request that if it is possible to make the app cache files which are located in 
(internal storage/android/data/app.mihon/cache/tmp)
to be directly generated on sd or if possible not to be generated at all. As i noticed that the app makes cache file for almost every chapter I read. Although I am storing the local folder (which has the series or the chapters) on the sd card.

I tried : 
-moving the app to sd from the settings (but there was no option for that). 
-moving the app using another app (link2sd), the app itself moved to sd yet the cache didn't.
-editing the app source using another apps (appclone) and (apk editor) but either caused crashing or the app moved to sd yet the cache didn't.

Personal notice : Previously I ignorantly used the internal storage of my phone as a temporary place for downloading really lots of very large files then moving them to a hard drive. After some time I read about the writing capacity of the phone's media chip (internal storage) and at some point it will start affecting the performance of the phone. Fortunately I didn't reach that point yet. However I am trying to avoid using the internal storage as much as I could and to use the sd.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Solojump8** [comment]
Thanks for your reply! 

That doesn't prevent cache files from being generated, it deletes the cache of last session on app launch. Hence it still uses the internal storage. My requested feature that I want the app to use sd card instead or to stop generating chapters cache (not the option you mentioned of deleting the cache after being generated).

**Comment by Animeboynz** [comment]
> Personal notice : Previously I ignorantly used the internal storage of my phone as a temporary place for downloading really lots of very large files then moving them to a hard drive. After some time I read about the writing capacity of the phone's media chip (internal storage) and at some point it will start affecting the performance of the phone. Fortunately I didn't reach that point yet. However I am trying to avoid using the internal storage as much as I could and to use the sd.

Umm. I don't think this is really something you should be worried about xD and honestly not something you can control.
Your phone will probably become obsolete and stop receiving updates for apps before you run into the endurance limit of your storage.

**Comment by Solojump8** [comment]
Thnx for ur reply @Animeboynz

Using custom rom doesn't make one care about receiving updates or phone getting obsolete, as long it does its job. All I want to know, is it applicable to make chapters cache files generated directly on sd card or not to be generated at all? I really don't know if that is complicated Android +10 - wise and koltin-wise.

**Comment by cuong-tran** [comment]
Cache on SDCard might be slow, losing the purpose of "cache".
Also, you can't possibly have that much cache generated each time running app, so I think Clear cache is good enough.

**Comment by AntsyLich** [comment]
We could potentially make an option to not do chapter caching (tho no promises on that) but not gonna introduce an option to move cache dir to SD card.

**Comment by Solojump8** [comment]
Thnx for ur reply @cuong-tran, @AntsyLich

I realized that what generating these cache files (.tmp) was that the stored chapters were compressed (.cbz) files, hence when I made all the chapters uncompressed (pics stored in folders) and also I turned off the option of downloading chapters as cbz files, as a result cache files are no longer generated even with the chapters stored on sd.

**Comment by AntsyLich** [comment]
If the cache files are generated from downloaded files that thing has already been disabled/removed in beta version

**Comment by Solojump8** [comment]
Thnx for ur reply @Norsze

Well (.tmp) files were generated in 
(internal storage/android/data/app.mihon/cache/tmp) while using the application with no internet connection and their naming was after the compressed chapters I already read during last session which are downloaded and stored on sd and also their sizes were similar.

**Comment by FooIbar** [comment]
Yeah that's #134, fixed in [preview](https://github.com/mihonapp/mihon-preview/releases).
I won't recommend you to decompress those archives as SAF sucks at reading a bunch of small files.

**Comment by Solojump8** [comment]
Thnx for ur reply @FooIbar

If I stored chapters on sd as (.cbz) then the app while reading them generates (.tmp) files in (internal storage/android/data/app.mihon/cache/tmp) which is undesired behavior since I don't want to use the internal storage but sd instead. 
On the other hand if I stored chapters as folders (uncompressed), this stops generating (.tmp) files however this causes inconvenience as you mentioned (SAF sucks at reading a bunch of small files).
The third way is to stop generating (.tmp) files from the start yet I think that may have a slowing effect as I think generating these (.tmp) files optimizing the app performance while handling (.cbz) files.

**Comment by FooIbar** [comment]
As I said, it has been fixed in mihon preview (the link was posted above), we don't copy archives to temp folder anymore.

**Comment by AntsyLich** [comment]
Your issue has been fixed in preview

**Comment by Solojump8** [comment]
Thnx for ur reply @FooIbar, @AntsyLich
