### ISSUE TITLE
Migrate To Source

### ISSUE THREAD

**Issue by Dunky13** [mihonapp/mihon#1036]
### Describe your suggested feature

I would like a feature that would allow me to migrate to a source, instead of from a source. 
Let's say I have 8 extensions and 86 mangas in my library. Ideally I would like to be as evenly spread as possible. So each extension having 5-15 mangas.
But I find that often half of my extensions have < 5 mangas, and the other half > 15

This makes updates slow, since (rightfully so) we update one manga per source at a time to not overload their versions.
If the number of mangas were to be balanced out it would improve update speeds.

I can go over each high-volume extension and try to migrate one manga at a time, and try to find if I can migrate to said source, with the same (or more) chapters. But that is quite tedious.

The feature I'm requestion is the ability to say: Migrate to <Extension X> and it will go over all mangas not managed by this extension to see if it can be migrated to Extension X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Essentially #14

**Comment by Dunky13** [comment]
> Essentially #14

Sorry, totally missed that. Tried searching for the topic. Thank you for pointing it out 👍
