### ISSUE TITLE
Side by side reading mode NOT VR

### ISSUE THREAD

**Issue by addmo22** [mihonapp/mihon#1040]
### Describe your suggested feature

What I'm asking is if it were posible to make a side by side reading mode but not vr, we're you show two picture of the same image side by side in the app, you would just need to put your reading mode on landscape sbs and just show the same picture twice side by side on landscape mode, and the control we'll it's already there since you could just use a mouse to scroll that way you could just buy one of those cheap "vr" set(they not really vr) were you put your phone in and be able to see it as if it were "vr". If this were to be made possible a simple adjustment control would be good were you just control how separated the images apper on the screen from each other.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
