### ISSUE TITLE
Sideload on IOS through Scarlet

### ISSUE THREAD

**Issue by 00p11** [mihonapp/mihon#1041]
### Describe your suggested feature

IOS build to sideload with [Scarlet sideloader](https://usescarlet.com/). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://mihon.app/docs/faq/general#is-mihon-available-for-ios-ipados
