### ISSUE TITLE
Some themes have encountered anomalies

### ISSUE THREAD

**Issue by Qing-Novel** [mihonapp/mihon#1049]
### Steps to reproduce

Screen recording shows that when using some themes, some UI may have drawing errors, which were not present in previous versions (one or two versions ago)

https://github.com/user-attachments/assets/e0cfc77d-d5c3-4cc2-95cb-530b2852d138

https://github.com/user-attachments/assets/6029b6f4-80be-4446-81d6-26f929bed0b4

### Expected behavior

Screen recording shows that when using some themes, some UI may have drawing errors, which were not present in previous versions (one or two versions ago)
![Screenshot_20240725_230344_app mihon](https://github.com/user-attachments/assets/e34265a8-ec59-46c0-aed8-dc0a183530a4)
![Collage_20240725_231021](https://github.com/user-attachments/assets/5b4b8434-97fc-4a47-ad4d-87f24948af44)

### Actual behavior

Screen recording shows that when using some themes, some UI may have drawing errors, which were not present in previous versions (one or two versions ago)
![Screenshot_20240725_230328_app mihon](https://github.com/user-attachments/assets/6928921a-289e-4bbf-9bc3-2edbb825c7df)
![Screenshot_20240725_230233_app mihon](https://github.com/user-attachments/assets/db06eb15-2e3b-4998-b67d-0608810c9f22)

### Crash logs

[mihon_crash_logs.txt](https://github.com/user-attachments/files/16379822/mihon_crash_logs.txt)

### Mihon version

0.16.5

### Android version

android 10 & android 12

### Device

huawei m6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Was a theme issue. Fixed in beta.
