### ISSUE TITLE
Staggered grid

### ISSUE THREAD

**Issue by Jaybraks** [mihonapp/mihon#1050]
### Describe your suggested feature

Seen this on the j2k app and it makes the covers and the app look more appealing to the eye.
![Screenshot_20240725_185228_TachiyomiJ2K](https://github.com/user-attachments/assets/0269992a-e2db-4af2-bc7e-bb2f466036c3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Nah
