### ISSUE TITLE
Getting hang during reading manga and slow open also not supported a extension.

### ISSUE THREAD

**Issue by MIKO-SEO** [mihonapp/mihon#1055]
### Steps to reproduce

First step when open app it get manga pic and open
Second step was when read it like stuck move to next chapter 
Third issue was proved thanks 

### Expected behavior

I was reading manga and it break down also outside the apk and it getting hang like i already read 670 mangas it not working properly.when i refresh for update it's have limit like 50 or 60 per update and I have 670 manga it's so slow updates and downloading and lot of extension was not working like http error or failed.. and more..
It's crash log -----------------------------------------------------------------------------------
App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 14 (SDK 34; build UP1A.231005.007 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 2127 (2127i)
Device model: V2142
WebView: Android System WebView 126.0.6478.134

--------- beginning of crash
07-23 14:28:28.124 27993 27993 E AndroidRuntime: FATAL EXCEPTION: main
07-23 14:28:28.124 27993 27993 E AndroidRuntime: Process: app.mihon, PID: 27993
07-23 14:28:28.124 27993 27993 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{192a165 u0 app.mihon/androidx.work.impl.foreground.SystemForegroundService}
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2501)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2472)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2780)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:328)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9242)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1995)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1930)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(Unknown Source:0)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.work.impl.Processor.startForeground(Unknown Source:82)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(Unknown Source:267)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.work.Worker$2.run(Unknown Source:2599)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: FATAL EXCEPTION: main
07-26 16:35:25.986 16775 16775 E AndroidRuntime: Process: app.mihon, PID: 16775
07-26 16:35:25.986 16775 16775 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d564441 u0 app.mihon/androidx.work.impl.foreground.SystemForegroundService}
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2501)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2472)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2780)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:328)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9242)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1995)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1930)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(Unknown Source:0)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.work.impl.Processor.startForeground(Unknown Source:82)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(Unknown Source:267)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.work.Worker$2.run(Unknown Source:2599)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of main
07-26 23:02:25.986 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:02:26.077 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:02:26.079 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:02:30.100 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:02:30.146 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:05:32.351 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:05:33.762 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:05:34.753 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:05:34.772 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:06:48.631 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:08:01.666 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:08:02.529 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:08:04.206 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:08:04.235 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:09:26.188 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:09:26.803 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:09:33.167 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:09:36.069 28918 28918 E BLASTBufferQueue: [VRI[MainActivity]#13](f:0,a:1) Applying pending transactions on dtor 1
07-26 23:09:57.216 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:09:57.216 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:09:57.217 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:10:27.463 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:10:32.150 28918 28918 E BLASTBufferQueue: [VRI[MainActivity]#15](f:0,a:1) Applying pending transactions on dtor 1
07-26 23:10:39.347 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:10:39.366 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:13:45.566 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:13:46.211 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:14:53.757 16911 16911 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-26 23:14:53.943 16911 27593 E SQLiteLog: (283) recovered 928 frames from WAL file /data/data/app.mihon/databases/tachiyomi.db-wal
07-26 23:14:54.009 16911 27604 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-26 23:14:54.009 16911 27604 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-26 23:14:54.137 16911 27623 E chromium: [0726/231454.136803:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
07-26 23:14:55.070 16911 27741 E SQLiteLog: (284) automatic index on C(manga_id)
07-26 23:14:55.073 16911 27741 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-26 23:14:59.082 16911 27727 E ion     : ioctl c0044901 failed with code -1: Invalid argument
07-26 23:21:07.749 16911 27596 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:21:07.774 16911 16911 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:21:07.774 16911 16911 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!

### Actual behavior

A lot of time 

### Crash logs

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 14 (SDK 34; build UP1A.231005.007 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 2127 (2127i)
Device model: V2142
WebView: Android System WebView 126.0.6478.134

--------- beginning of crash
07-23 14:28:28.124 27993 27993 E AndroidRuntime: FATAL EXCEPTION: main
07-23 14:28:28.124 27993 27993 E AndroidRuntime: Process: app.mihon, PID: 27993
07-23 14:28:28.124 27993 27993 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{192a165 u0 app.mihon/androidx.work.impl.foreground.SystemForegroundService}
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2501)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2472)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2780)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:328)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9242)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1995)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1930)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(Unknown Source:0)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.work.impl.Processor.startForeground(Unknown Source:82)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(Unknown Source:267)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at androidx.work.Worker$2.run(Unknown Source:2599)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-23 14:28:28.124 27993 27993 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: FATAL EXCEPTION: main
07-26 16:35:25.986 16775 16775 E AndroidRuntime: Process: app.mihon, PID: 16775
07-26 16:35:25.986 16775 16775 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d564441 u0 app.mihon/androidx.work.impl.foreground.SystemForegroundService}
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2501)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2472)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2780)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:328)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9242)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1995)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1930)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(Unknown Source:0)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.work.impl.Processor.startForeground(Unknown Source:82)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(Unknown Source:267)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at androidx.work.Worker$2.run(Unknown Source:2599)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-26 16:35:25.986 16775 16775 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of main
07-26 23:02:25.986 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:02:26.077 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:02:26.079 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:02:30.100 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:02:30.146 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:05:32.351 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:05:33.762 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:05:34.753 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:05:34.772 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:06:48.631 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:08:01.666 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:08:02.529 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:08:04.206 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:08:04.235 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:09:26.188 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:09:26.803 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:09:33.167 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:09:36.069 28918 28918 E BLASTBufferQueue: [VRI[MainActivity]#13](f:0,a:1) Applying pending transactions on dtor 1
07-26 23:09:57.216 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:09:57.216 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:09:57.217 28918 28918 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:10:27.463 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:10:32.150 28918 28918 E BLASTBufferQueue: [VRI[MainActivity]#15](f:0,a:1) Applying pending transactions on dtor 1
07-26 23:10:39.347 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:10:39.366 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:13:45.566 28918 14049 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:13:46.211 28918 13767 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:14:53.757 16911 16911 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
07-26 23:14:53.943 16911 27593 E SQLiteLog: (283) recovered 928 frames from WAL file /data/data/app.mihon/databases/tachiyomi.db-wal
07-26 23:14:54.009 16911 27604 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-26 23:14:54.009 16911 27604 E app.mihon: No package ID 79 found for resource ID 0x790b0007.
07-26 23:14:54.137 16911 27623 E chromium: [0726/231454.136803:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
07-26 23:14:55.070 16911 27741 E SQLiteLog: (284) automatic index on C(manga_id)
07-26 23:14:55.073 16911 27741 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-26 23:14:59.082 16911 27727 E ion     : ioctl c0044901 failed with code -1: Invalid argument
07-26 23:21:07.749 16911 27596 E OpenGLRenderer: Unable to match the desired swap behavior.
07-26 23:21:07.774 16911 16911 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!
07-26 23:21:07.774 16911 16911 E ANDR-VIVO-PERF: IVPerf::tryGetService failed!

### Mihon version

0.16.5

### Android version

Android 14

### Device

V2142

### Other details

Sorry for inconvenience but can add ai like make to make comfort whichever we use mobile or tab get adjust collect data make best environment for readers also a function like manga name and chapter u read was save in gmail or in internet? But I have fun tion idea but for now ok. Thank for apk for all team🥹🥹🥹🥹🥹🥰🥰🎊🎊🤗🤩🥳😀😃😄😁😆😅😂

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The lag will be significantly reduced ik the next release
