### ISSUE TITLE
Default Title Sort option not setting for full library

### ISSUE THREAD

**Issue by DDRook** [mihonapp/mihon#106]
### Steps to reproduce

1.  Select Title
2. select sort
3. sort by chapter number
4. select 3 little dots 
5. select set as default
6. select check box for "Also apply to all entries in my library"
7. select OK

### Expected behavior

should set default sort style for ALL titles in library

### Actual behavior

Set for most but a few sporadically here and there did not change to the default

### Mihon version

Stable 0.16.1

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Did you try to restart the app after applying that setting and checking again? Maybe it glitched out a bit

**Comment by DDRook** [comment]
OOF didn't even think of that, just spent the time and went through each
title and set it as default and moved on
