### ISSUE TITLE
filter by entries with no predicted release date

### ISSUE THREAD

**Issue by isabella-almeidaa** [mihonapp/mihon#1060]
### Describe your suggested feature

some entries end up with no predicted release date, so it never updates. please add a filter to know which ones are like this so we can add custom predictions to those entries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
> some entries end up with no predicted release date, so it never updates

Not the case, at worst entries get the longest interval of 28 days

> the reason for the completed ones is that sometimes, the site will be marked as completed even though it isn't, which messes up smart updates

That's on the source, you should take this one with whoever maintains that extension.

**Comment by isabella-almeidaa** [comment]
> > some entries end up with no predicted release date, so it never updates
> 
> Not the case, at worst entries get the longest interval of 28 days
> 
> > the reason for the completed ones is that sometimes, the site will be marked as completed even though it isn't, which messes up smart updates
> 
> That's on the source, you should take this one with whoever maintains that extension.

> > some entries end up with no predicted release date, so it never updates
> 
> Not the case, at worst entries get the longest interval of 28 days
> 
> > the reason for the completed ones is that sometimes, the site will be marked as completed even though it isn't, which messes up smart updates
> 
> That's on the source, you should take this one with whoever maintains that extension.
I know that you guys don't do extensions and stuff, but I just wanted to make sure if they could actually do something about it, other than MAYBE making the completed stuff just as "publishing finished" or something like that, which wouldn't really be viable imo.

**Comment by AntsyLich** [comment]
Why the fuck did you change your request in the same issue. I'm reverting your edit and closing this.
