### ISSUE TITLE
Get entire chapter/volume at once if it's provided by providers like Komga

### ISSUE THREAD

**Issue by plato79** [mihonapp/mihon#1062]
### Describe your suggested feature

I know this will probably need a huge uplift from the Mihon source code. I checked the code and the extension API only allows getting books "page by page".

Though, with Komga, we keep the books generally as CBZ. Also Komga provides entire book as CBZ via its' API if requested that way.

There is also option to keep the chapters as CBZ in the Mihon's settings menu.

Is it possible to provide an option to download entire books from Komga directly to Mihon?

You may think this as huge PITA, though downloading entire book is much faster than current method.

PS. From "book" I mean "chapter" of a manga, or "volume" of a manga. I usually keep volumes instead of chapters if at all possible. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> though downloading entire book is much faster than current method.

They will be identical (more or less). Not sure how you cake to that conclusion.

Even if I consider that'll be in the future.
