### ISSUE TITLE
Browse Search not working. Sources missing website titles.

### ISSUE THREAD

**Issue by smartacephale** [mihonapp/mihon#1063]
### Steps to reproduce

This happens for most of sources with many other titles, especially the obscure ones like this. Makes me feel like sources scraping/parsing only top titles ignoring unpopular ones.

Example:
1. Install MangaDex source
2. Go to browse search and type _DDT_ or _Miminashi-Hohichi_ (this title on [mangadex](https://mangadex.org/title/3ba57f94-f3f6-4cd4-ba04-ed1c6268fbee/ddt))

### Expected behavior

It should find what mangadex has on it's website.

### Actual behavior

Instead get nothing.

### Mihon version

0.16.5

### Android version

Android 12

### Device

Motorolla idk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you need to enable that content in the extension settings, also this is not related to the app.

**Comment by smartacephale** [comment]
What should be enabled there?
