### ISSUE TITLE
NetTruyenX NetTruyenCO

### ISSUE THREAD

**Issue by HutaoNya** [mihonapp/mihon#1074]
### Steps to reproduce

![20240803170447](https://github.com/user-attachments/assets/8e701871-f0ce-4659-8911-f54fad676b3e)
![20240803170437](https://github.com/user-attachments/assets/634acc29-8706-4d6c-a55d-291f4420c096)
![20240803170431](https://github.com/user-attachments/assets/33e6e82a-7afb-4534-b781-b37dfcf9c971)
![20240803170419](https://github.com/user-attachments/assets/486f20ec-b279-40b3-896c-e69cc9340b3c)
![20240803170325](https://github.com/user-attachments/assets/1359c751-0c4c-47de-9915-d0c77e37c3d6)
![20240803170129](https://github.com/user-attachments/assets/44af4c9d-0a1d-412e-88a5-568e4d4a2f64)
I hope you can fix it, why has this problem been like this since morning? I've tried fake vpn and DNS, but it still won't switch to 3G, and it won't work. Even after waiting for a long time, I still can't. Please, how to fix it. Please and thank you in advance.😞😞😞

### Expected behavior

I hope you can fix it, why has this problem been like this since morning? I've tried fake vpn and DNS, but it still won't switch to 3G, and it won't work. Even after waiting for a long time, I still can't. Please, how to fix it. Please and thank you in advance.🙂

### Actual behavior

Cannot access Net TruyenX and Net TruyenCO while 3g wifi is very strong

### Crash logs

syntax = "proto2";

// serial name 'eu.kanade.tachiyomi.data.backup.models.Backup'
message Backup {
  repeated BackupManga backupManga = 1;
  // WARNING: a default value decoded when value is missing
  repeated BackupCategory backupCategories = 2;
  // WARNING: a default value decoded when value is missing
  repeated BrokenBackupSource backupBrokenSources = 100;
  // WARNING: a default value decoded when value is missing
  repeated BackupSource backupSources = 101;
  // WARNING: a default value decoded when value is missing
  repeated BackupPreference backupPreferences = 104;
  // WARNING: a default value decoded when value is missing
  repeated BackupSourcePreferences backupSourcePreferences = 105;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupManga'
message BackupManga {
  required int64 source = 1;
  required string url = 2;
  // WARNING: a default value decoded when value is missing
  optional string title = 3;
  // WARNING: a default value decoded when value is missing
  optional string artist = 4;
  // WARNING: a default value decoded when value is missing
  optional string author = 5;
  // WARNING: a default value decoded when value is missing
  optional string description = 6;
  // WARNING: a default value decoded when value is missing
  repeated string genre = 7;
  // WARNING: a default value decoded when value is missing
  optional int32 status = 8;
  // WARNING: a default value decoded when value is missing
  optional string thumbnailUrl = 9;
  // WARNING: a default value decoded when value is missing
  optional int64 dateAdded = 13;
  // WARNING: a default value decoded when value is missing
  optional int32 viewer = 14;
  // WARNING: a default value decoded when value is missing
  repeated BackupChapter chapters = 16;
  // WARNING: a default value decoded when value is missing
  repeated int64 categories = 17;
  // WARNING: a default value decoded when value is missing
  repeated BackupTracking tracking = 18;
  // WARNING: a default value decoded when value is missing
  optional bool favorite = 100;
  // WARNING: a default value decoded when value is missing
  optional int32 chapterFlags = 101;
  // WARNING: a default value decoded when value is missing
  repeated BrokenBackupHistory brokenHistory = 102;
  // WARNING: a default value decoded when value is missing
  optional int32 viewer_flags = 103;
  // WARNING: a default value decoded when value is missing
  repeated BackupHistory history = 104;
  // WARNING: a default value decoded when value is missing
  optional UpdateStrategy updateStrategy = 105;
  // WARNING: a default value decoded when value is missing
  optional int64 lastModifiedAt = 106;
  // WARNING: a default value decoded when value is missing
  optional int64 favoriteModifiedAt = 107;
  // WARNING: a default value decoded when value is missing
  repeated string excludedScanlators = 108;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupCategory'
message BackupCategory {
  required string name = 1;
  // WARNING: a default value decoded when value is missing
  optional int64 order = 2;
  // WARNING: a default value decoded when value is missing
  optional int64 flags = 100;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BrokenBackupSource'
message BrokenBackupSource {
  // WARNING: a default value decoded when value is missing
  optional string name = 0;
  required int64 sourceId = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupSource'
message BackupSource {
  // WARNING: a default value decoded when value is missing
  optional string name = 1;
  required int64 sourceId = 2;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupPreference'
message BackupPreference {
  required string key = 1;
  required PreferenceValue value = 2;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupSourcePreferences'
message BackupSourcePreferences {
  required string sourceKey = 1;
  repeated BackupPreference prefs = 2;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupChapter'
message BackupChapter {
  required string url = 1;
  required string name = 2;
  // WARNING: a default value decoded when value is missing
  optional string scanlator = 3;
  // WARNING: a default value decoded when value is missing
  optional bool read = 4;
  // WARNING: a default value decoded when value is missing
  optional bool bookmark = 5;
  // WARNING: a default value decoded when value is missing
  optional int64 lastPageRead = 6;
  // WARNING: a default value decoded when value is missing
  optional int64 dateFetch = 7;
  // WARNING: a default value decoded when value is missing
  optional int64 dateUpload = 8;
  // WARNING: a default value decoded when value is missing
  optional float chapterNumber = 9;
  // WARNING: a default value decoded when value is missing
  optional int64 sourceOrder = 10;
  // WARNING: a default value decoded when value is missing
  optional int64 lastModifiedAt = 11;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupTracking'
message BackupTracking {
  required int32 syncId = 1;
  required int64 libraryId = 2;
  // WARNING: a default value decoded when value is missing
  optional int32 mediaIdInt = 3;
  // WARNING: a default value decoded when value is missing
  optional string trackingUrl = 4;
  // WARNING: a default value decoded when value is missing
  optional string title = 5;
  // WARNING: a default value decoded when value is missing
  optional float lastChapterRead = 6;
  // WARNING: a default value decoded when value is missing
  optional int32 totalChapters = 7;
  // WARNING: a default value decoded when value is missing
  optional float score = 8;
  // WARNING: a default value decoded when value is missing
  optional int32 status = 9;
  // WARNING: a default value decoded when value is missing
  optional int64 startedReadingDate = 10;
  // WARNING: a default value decoded when value is missing
  optional int64 finishedReadingDate = 11;
  // WARNING: a default value decoded when value is missing
  optional int64 mediaId = 100;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BrokenBackupHistory'
message BrokenBackupHistory {
  required string url = 0;
  required int64 lastRead = 1;
  // WARNING: a default value decoded when value is missing
  optional int64 readDuration = 2;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BackupHistory'
message BackupHistory {
  required string url = 1;
  required int64 lastRead = 2;
  // WARNING: a default value decoded when value is missing
  optional int64 readDuration = 3;
}

// serial name 'eu.kanade.tachiyomi.source.model.UpdateStrategy'
enum UpdateStrategy {
  ALWAYS_UPDATE = 0;
  ONLY_FETCH_ONCE = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.PreferenceValue'
message PreferenceValue {
  required string type = 1;
  // decoded as message with one of these types:
  //   message BooleanPreferenceValue, serial name 'eu.kanade.tachiyomi.data.backup.models.BooleanPreferenceValue'
  //   message FloatPreferenceValue, serial name 'eu.kanade.tachiyomi.data.backup.models.FloatPreferenceValue'
  //   message IntPreferenceValue, serial name 'eu.kanade.tachiyomi.data.backup.models.IntPreferenceValue'
  //   message LongPreferenceValue, serial name 'eu.kanade.tachiyomi.data.backup.models.LongPreferenceValue'
  //   message StringPreferenceValue, serial name 'eu.kanade.tachiyomi.data.backup.models.StringPreferenceValue'
  //   message StringSetPreferenceValue, serial name 'eu.kanade.tachiyomi.data.backup.models.StringSetPreferenceValue'
  required bytes value = 2;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.BooleanPreferenceValue'
message BooleanPreferenceValue {
  required bool value = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.FloatPreferenceValue'
message FloatPreferenceValue {
  required float value = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.IntPreferenceValue'
message IntPreferenceValue {
  required int32 value = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.LongPreferenceValue'
message LongPreferenceValue {
  required int64 value = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.StringPreferenceValue'
message StringPreferenceValue {
  required string value = 1;
}

// serial name 'eu.kanade.tachiyomi.data.backup.models.StringSetPreferenceValue'
message StringSetPreferenceValue {
  repeated string value = 1;
}

### Mihon version

0.16.5

### Android version

Android 10

### Device

Redmi9C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
That's definitely a extension relates issue. You should contact whoever maintains it as Mihon does not provide or associate with any extensions. 

Also how did you manage to get that as your crash log? The schema for a backup 🤣
