### ISSUE TITLE
Vibration alert for mihon unlock on app startup

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#1075]
### Describe your suggested feature

add Vibration alert for when mihon unlock on app startup shows up

### Other details

So that i can close my eyes when i wait 30-60 sec for app to start... :) 
Or speed up app startup like when you install only mihon app without addons and app start instantly :()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
takes like 2 seconds for the app to open so definitely an issue with your device

**Comment by Character95** [comment]
> takes like 2 seconds for the app to open so definitely an issue with your device

Ok i'll fix this issue myself... 


I got a new phone

**Comment by AntsyLich** [comment]
I guess that's a solution.
