### ISSUE TITLE
Option to change Open in Webview to Open in Browser

### ISSUE THREAD

**Issue by hpershdzy** [mihonapp/mihon#1077]
### Describe your suggested feature

Toggle that removes the webview option and replaces it with the option to open the webpage in the default browser app instead. I've requested this before but it was rejected because webview is vital for the functionality of the app (issue closed by bot, cant reply). I should clarify that when I said this I didnt mean webview should be removed as a whole I mean that the function of the button changes but webview remains hidden away doing what it needs to do when its needed

### Other details

This means if your browser has extensions installed (e.g. adblocking) you will get that functionality that wont appear in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smognoggler** [comment]
The benefit of having an open in browser option is for seeing the comments section for a chapter. Also potentially a better solution then a toggle, would be having both in the menu in the chapter.
