### ISSUE TITLE
extension issue which lead to a crash

### ISSUE THREAD

**Issue by Modeh121** [mihonapp/mihon#1078]
### Steps to reproduce

![Screenshot_2024-08-05-12-48-47-284_app mihon](https://github.com/user-attachments/assets/80ad8d4c-e023-49ff-8911-7d53d2a173da)
![Screenshot_2024-08-05-12-48-49-462_app mihon](https://github.com/user-attachments/assets/af67830f-aa0b-43f0-bc57-ad030c0fd377)

https://github.com/user-attachments/assets/f80ebf38-696c-4554-aa25-ef6f2f8ecedb

i open a site in webview and it closes itself so i try to refresh but it doesn't the if i press clear cache the app crashes
![Screenshot_2024-08-05-12-48-40-512_app mihon](https://github.com/user-attachments/assets/c907336b-3874-4c8b-b06e-b7ddfa18742f)
![Screenshot_2024-08-05-12-48-43-679_app mihon](https://github.com/user-attachments/assets/5e448900-85dd-49de-aa53-52b8595aa917)
![Screenshot_2024-08-05-12-48-45-266_app mihon](https://github.com/user-attachments/assets/01843815-56c4-48a6-b412-ab22ffe8f76d)

### Expected behavior

it should've refreshed

### Actual behavior

it lagged

### Crash logs

[mihon_crash_logs.txt](https://github.com/user-attachments/files/16494232/mihon_crash_logs.txt)

### Mihon version

0.16.5

### Android version

13

### Device

Xiaomi poco x3 gt 

### Other details

no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
As you were already told on the Discord server, this error has nothing to do with Mihon, as Mihon does not provide or associate with any sources or extensions.

Contact whoever or wherever you downloaded your extensions from. If the extensions were from Tachiyomi, they are no longer supported and you should try find newer versions yourself.

**Comment by FooIbar** [comment]
> this error has nothing to do with Mihon

Not really.
An ill-formed URL should result in a no-op, not a crash.
