### ISSUE TITLE
[Consistency] Trackers should copy URL to clipboard when icon is long-pressed

### ISSUE THREAD

**Issue by mm12** [mihonapp/mihon#1087]
### Describe your suggested feature

When you long press a source, title, tracker title, and many other fields in the app, information is copied to the clipboard. Long-pressing tracker icons currently does nothing. I suggest that it copy the tracker URL to the clipboard. 

### Other details

I can probably implement this myself by the end of the week and open a PR. I'm not too experienced though so no guarantees. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The thing is. Icon open browser is kind of a hidden feature. This become an ultra hidden feature 🫠
