### ISSUE TITLE
App crash or stuck for 30 seconds while taking screenshot on ChromeOS 截屏时应用崩溃或卡死

### ISSUE THREAD

**Issue by zanjie1999** [mihonapp/mihon#1097]
### Steps to reproduce

1. open a comic book  打开一本漫画
2. turn a few pages  翻几页
3. take screenshots multiple times  多次进行截图
4. App crash or stuck for 30+ seconds  应用崩溃或卡死30秒以上
The more screenshots you take, the longer it will take to get stuck, until it crash
当你截图的越多，应用就越卡，直至超时崩溃

I don't encounter this problem in other reading apps, such as Moon+ Reader, ​​Kindle
在其他阅读App没有遇到这个问题，如静读天下，Kindle

### Expected behavior

Apps run normally
程序正常运行

### Actual behavior

App crash or stuck for 30+ seconds
应用崩溃或卡死30秒以上

### Crash logs

java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
![a330cbaebf1e1c085212dc7d5262526a](https://github.com/user-attachments/assets/a80d6056-8b1c-42ea-ae54-1fd5639d8910)

### Mihon version

0.16.5

### Android version

Android9

### Device

Chromebook Duet MT8183

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
ChromeOS is not officially aupported
