### ISSUE TITLE
Set a CBZ Password like in Tachiyomi

### ISSUE THREAD

**Issue by ICyperior** [mihonapp/mihon#1100]
### Steps to reproduce

1. Go to Settings
2. Security and Privacy
3. There should be an option called *Password protect downloads*

### Expected behavior

1. There should be an option called *Password protect downloads*
2. The app shpuld be able to open password protected apps and set a password for them

### Actual behavior

1. There is no option to set a password for downloads.
2. Can't open password protected cbz archives.

### Mihon version

App version: 0.16.5-6793 (standard, de8ef6dad, 7, 2024-08-03T21:19:24Z)

### Android version

andrpid 14

### Device

Xiaomi K40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
no
