### ISSUE TITLE
Kitsu.io domain changed to Kitsu.app

### ISSUE THREAD

**Issue by romulator37** [mihonapp/mihon#1104]
### Steps to reproduce

1. Unable to access site on browser and on app
2. Unable to login using credentials on both browser and app
3. Unable to search entries and track them.

### Expected behavior

Site should be accessible via browser and via Yokai app, and login functionality should work. Search should work.

### Actual behavior

Kitsu.io site is currently down.
Site URL has changed to Kitsu.app 
(https://github.com/hummingbird-me/kitsu-server/commit/244fdccca9754d8579c049e738832843001b33b1)

### Mihon version

0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)

### Android version

Android 14

### Device

Google Pixel 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
While your report is accurate, this is the repository for Mihon, not Yokai. Yokai is an independent fork.

You can keep the issue as-is, just wanted to note that detail.

**Comment by romulator37** [comment]
Apologies, I was writing this as a Yokai issue, realized it needed to be here instead. Missed changing the Yokai reference to Mihon. I'll keep this in mind for any future issues.
