### ISSUE TITLE
Categorize by source

### ISSUE THREAD

**Issue by Farzout** [mihonapp/mihon#1108]
### Describe your suggested feature

I would love to have an option to categorize my Library to their source extension.
so you can know which manga is from which source and switch between categories by source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No

**Comment by BrutuZ** [comment]
The option already exists. Create a category for each source and assign them

**Comment by Farzout** [comment]
> The option already exists. Create a category for each source and assign them

do you mean to add them one by one to each category I creat?

**Comment by Farzout** [comment]
> You can search in your Library the "Source name" and it should filter out the ones from said source (reminder, Mihon doesn't have, associate, or provide any extensions/sources). Otherwise, view the Browse Page > Migrate tab to see what is tied to what.

this seems to be working for me thanks a ton

**Comment by BrutuZ** [comment]
> > The option already exists. Create a category for each source and assign them
> 
> do you mean to add them one by one to each category I creat?

You can assign categories in bulk too.
