### ISSUE TITLE
Add the ability to add different comics issue into one file/comic

### ISSUE THREAD

**Issue by forr34** [mihonapp/mihon#1124]
### Describe your suggested feature

i like reading comics and sometimes the stories are connected with other comics, and it would be easier if you can add a specific issue and add them all together in one file/comic so you don't have to get out -> go to the library -> and look for that one specific issue to continue the story where it left off. I just thought it would be cool if we can do that. Thank you for reading and sorry if my english is bad, its my second language

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
The content provider calls the shots on organization. You're free to organize however you like via Local Entries or Self-Hosting.
