### ISSUE TITLE
Keyboard in tracker adding hides "track" button

### ISSUE THREAD

**Issue by mm12** [mihonapp/mihon#1126]
### Steps to reproduce

1. Get to the "add tracker" screen and press "add" (ie, get `TrackerSearch.kt` to show)
2. Click in the search box to edit a search (this could be while the results are loading)
3. Select a search result (this could be when results from the autofill show up, and the edited search is no longer needed)

### Expected behavior

One of two things should happen: 
1. When a result is selected, the keyboard should hide itself
2. The track button should be pushed above the keyboard

### Actual behavior

The keyboard remains open, and the "track" button is hidden under the keyboard

### Mihon version

0.16.5

### Android version

Android 15 Beta

### Device

Google Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Well, just wondering if your are clicking on the title search at the top, they you are wanting to change the default title and search for something else right? and if you do that the keyboard auto hides when you search. Why would you press the search bar when results are loaded/ loading and you don't search for anything else? 

Either way it would be good for the keyboard to autohide if you select an entry, but shifting the elements up to the keyboard height feels unnecessary as most people only click the track button after completing a search which hides the keyboard either way.

Just my personal take on it tho
