### ISSUE TITLE
Add "Go to series" on download queue items

### ISSUE THREAD

**Issue by mm12** [mihonapp/mihon#1129]
### Describe your suggested feature

In the download queue (accessible by long or double pressing "updates" tab), each items has several menu options. With one of them being "cancel all for series" I think it would be sensible to add a button to go to the series in question. 

### Other details

I can work on this one, probably

### Acknowledgements

- [X] I will fill out all of the requested information in this form.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.

**Comment by AntsyLich** [comment]
No
