### ISSUE TITLE
Extension update shows badge after completed

### ISSUE THREAD

**Issue by mm12** [mihonapp/mihon#1134]
### Steps to reproduce

1. Have an extension that requires an update
2. Update and trust the extension 

### Expected behavior

The badge showing the number of updates should decrease/disappear once it has been dealt with

### Actual behavior

The badge stays until the extensions page is refreshed.

### Mihon version

0.16.5

### Android version

Android 15 Beta

### Device

Google Pixel 8 Pro

### Other details

`updateExtension` in `ExtensionsScreenModel` should refresh the count (called from `ExtensionsTab`)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Fixed in preview
