### ISSUE TITLE
Ability to filter just a single scanlator when sorting chapter sources 

### ISSUE THREAD

**Issue by Prezcot** [mihonapp/mihon#1137]
### Describe your suggested feature

In certain extensions they grab entries from many different scanlators and the list becomes huge. Currently you can only remove certain scanlators from being included. Therefore, it would great if it were possible to include just the scanlators you want instead of going through deselecting everything but the scanlators you want. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
84b2164787a795f3fd757c325cbfb6ef660ac3a3 covers that

**Comment by Prezcot** [comment]
> Has been denied already since it completely removes visibility to any new scanlator. But an option has been added to select all on the dialog (aka exclude all) on preview/beta

Thank you for the prompt reply. Take care :)

**Comment by Animeboynz** [comment]
Thats some record breaking times xD first reply within 4m and closed within 5m

**Comment by Prezcot** [comment]
> Thats some record breaking times xD first reply within 4m and closed within 5m

This was my first ever feature request... XD got insta rejected... A question though... If I were to install the beta version is it unstable?
