### ISSUE TITLE
Shikimori: Use new client

### ISSUE THREAD

**Issue by salmanbappi** [mihonapp/mihon#114]
### Steps to reproduce

To reproduce this you just try to login shikimori 

### Expected behavior

Well yeah it should let me login

### Actual behavior

![Uploading Screenshot_20240118-101449_Brave - Nightly.jpg…]()

 pictures not upload properly use this

https://photos.app.goo.gl/jqYMLKDSUVnjrpXZ8

### Crash logs

Don't have those

### Mihon version

0.16.1

### Android version

Android 13 or android 10 both phone 

### Device

Redmi note 10 pro or Samsung m20 

### Other details

New to this I don't know what to do here

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Frech4k** [comment]
i have the same

**Comment by SkoyKurosawa** [comment]
Same problem

**Comment by SkoyKurosawa** [comment]
You might wanna read this https://shikimori.one/oauth
