### ISSUE TITLE
Add multi user

### ISSUE THREAD

**Issue by mickae1** [mihonapp/mihon#1150]
### Describe your suggested feature

It would be great if you allow multi user account.
By example an account for kids and the other for the father :) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
