### ISSUE TITLE
When 

### ISSUE THREAD

**Issue by demon456blade** [mihonapp/mihon#1155]
### Steps to reproduce

Download the app
Restore backup
![Screenshot_20240824_155604](https://github.com/user-attachments/assets/1cf83438-2184-455c-9dfc-13d636067da2)

### Expected behavior

Read chapters should show up like this 
![Screenshot_2024-08-24-19-22-53-402](https://github.com/user-attachments/assets/b78a1989-0b51-4eb6-a0eb-a21942bcd693)
Transparent

### Actual behavior

This is what actually happens 
![Screenshot_20240824_155604](https://github.com/user-attachments/assets/4bc26625-be72-4c89-a111-3816ca9970a9)

### Mihon version

0.16.5

### Android version

Android 14

### Device

Red magic 9s pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
This isn't Mihon, open whatever issue you're having in the correct fork's GitHub page.
