### ISSUE TITLE
weblate translations

### ISSUE THREAD

**Issue by Bmswad1** [mihonapp/mihon#116]
### Describe your suggested feature

rather than making a pull request for every translation change, it should be easier to translate directly from weblate and ell changes can be merged directly before releasing a new version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Weblate will requires a website for libre projects. Waiting for that to be up.
