### ISSUE TITLE
Opening books directly from local archives without cache copy

### ISSUE THREAD

**Issue by sadboy889** [mihonapp/mihon#1163]
### Steps to reproduce

-go to local mihon folder
-move the cbz/zip archive
-open mihon app
-browse local source
-open local archive 

### Expected behavior

no extra cache copy is created, no sudden spike/increase of memory storage

### Actual behavior

so much extra cache is created, bloating storage and causing problem

### Mihon version

0.16.5

### Android version

9

### Device

Redmi Note 8

### Other details

![IMG_20240826_195327](https://github.com/user-attachments/assets/55569042-157c-4a93-9861-d7a8e459d6bf)

why create so much cache copy from opening local archive? my low storage nearly blow up

i checked several tachiyomi/mihon versions, this problem start after version 0.15.0 to 0.16.5

at tachiyomi 0.14.6 the local archive can be opened directly without creating any extra cache copy, and there is no increase/spike of any memory storage

what to expect: change the behavior when opening local archive back to version 0.14.6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
already fixed in #326, wait for next stable release.
