### ISSUE TITLE
Parallel download

### ISSUE THREAD

**Issue by orrans** [mihonapp/mihon#1166]
### Describe your suggested feature

Need an option to download multi chapters in the same time instead of 1 chapter at a time 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
It's in place so that users don't overwhelm their sources and get banned. You can download manga from different sources at the same time tho.

**Comment by AntsyLich** [comment]
App downloads from 5 source at a time
