### ISSUE TITLE
Add N/A on custom update frequency 

### ISSUE THREAD

**Issue by xdeiimoss** [mihonapp/mihon#1167]
### Describe your suggested feature

There should be a more customized option for when you don't want a specific entry to update, so please add an N/A on the custom update frequency 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Make a new category that's excluded from global updates and anything you don't want updated to that category.
