### ISSUE TITLE
Can't fetch chapters for series with "licensed" status

### ISSUE THREAD

**Issue by 9ary** [mihonapp/mihon#1199]
### Steps to reproduce

Add a series with the "licensed" publication status that still has chapters available.

### Expected behavior

The chapter list should be fetched.

### Actual behavior

Fetching fails with a toast: "Licensed - No chapters to show".

### Mihon version

0.16.5

### Android version

Android 14 (LineageOS 21)

### Device

Pixel 4a

### Other details

This is because Mihon checks the publication status before it even attempts to fetch the chapters:
https://github.com/mihonapp/mihon/blob/8fd1239bea9e14e94515bcab08b91e570995a5e4/source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/HttpSource.kt#L258-L260

Mihon should only raise this exception if fetching fails or returns an empty list, or leave this up to the source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any extensions or content, nor does the app help bypass/access any paid/licensed content.

Check with whoever maintains your extensions instead.

**Comment by 9ary** [comment]
This isn't about bypassing licensed content, did you even read the report?

**Comment by Smol-Ame** [comment]
> This isn't about bypassing licensed content, did you even read the report?

The source & your extensions reports the status into the app, not the other way around

**Comment by 9ary** [comment]
I'm aware, I've read the code.

The source is a scanlation website. It is reporting a status of "licensed", which is accurate, but the pre-existing scanlated chapters are still listed and available to read.
Mihon is what's blocking the fetch here, not the extension. If you think reporting this value is a misuse of the API, I'll report it to the extension developers instead. Otherwise, I believe this is a Mihon bug.

**Comment by Smol-Ame** [comment]
I'll reopen and let the dev/more knowledgeable contributors decide on this if it needs adjustment or if it's something that should be reported to whoever maintains your extensions.

Apologies in advance if it is a valid issue

**Comment by 9ary** [comment]
Thanks!

**Comment by loocool2** [comment]
Looking at the code history, it looks like the check can probably be removed since the check was made initially to fix a long-dead source issue from like 7 years ago but carried over and is now dead code that happened to cause an issue now.

**Comment by 9ary** [comment]
For reference, the commit that introduced this is https://github.com/mihonapp/mihon/commit/5ae0589547489193826b6205f05711a07ceaa16b.
