### ISSUE TITLE
implement reading scheduler (partly implemented by me and need refinement by kotlin dev)

### ISSUE THREAD

**Issue by edi4dev** [mihonapp/mihon#1207]
### Describe your suggested feature

user should be able to schedule which entries to "update" on which days of the week (maybe even on a monthly base). 
user can choose how many chapter should be "updated" on which days.

for example:
user want to read 3 chapters of black clover on Sunday and Thursday. 

update should show on a new scheduler tab or on update tab with a separator (see attachment)

### Other details

i already implemented this feature but not in a very professional way (scheduler is configured by external json and update of scheduler show under update tab) since i am not an android/kotlin developer i am pretty sure i didn't write a code that is fit to push into master, would love if someone can take the code and refine it (off course would love to help as well).

how the updates look on app
![WhatsApp Image 2024-09-08 at 10 06 01_5f7ee698](https://github.com/user-attachments/assets/fedffa49-b1d6-4db1-a280-f134f2a1996c)

external json file:
[json.txt](https://github.com/user-attachments/files/16921197/json.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If you use the Mihon Preview version, you can set a custom update frequency for when Smart Updates will include said entry to check (like every 12 days) by tapping on the hourglass icon in the entry. Mihon Preview also has an Upcoming calendar that shows which titles are scheduled/predicted to get an update as well.

I'm a little confused on the idea of specifying the amount of chapters it should check for, per-series, though.

**Comment by edi4dev** [comment]
> If you use the Mihon Preview version, you can set a custom update frequency for when Smart Updates will include said entry to check (like every 12 days) by tapping on the hourglass icon in the entry. Mihon Preview also has an Upcoming calendar that shows which titles are scheduled/predicted to get an update as well.
> 
> I'm a little confused on the idea of specifying the amount of chapters it should check for, per-series, though.

its not really updates , that why i added the "" i want it be like like a scheduler that remind you to read x chapters from some title. (chapters that was out already long ago) kind of like those app that have task "clean the living room" and when you are done it clear the task (only here once you read it will auto clear) .
with this feature i find it easier to track and not forget any title i wanted to read (even when i read 50 + simultaneously)

**Comment by Smol-Ame** [comment]
After your clarification & checking with other members, this request won't be moving forward. The app is meant to be a reader, not a reminder app.

As the dev has said before, don't be lazy, and read your stuff. The Library page already permanently displays Unread badge count on your titles, along with the ability to filter titles that have Unread chapters, and sort by "Last read" or "Unread count" for more control/awareness of your titles. Maybe also consider divvying up your Library into more categories to quickly view your titles when quick scrolling through your categories.
