### ISSUE TITLE
Batch syncing for trackers

### ISSUE THREAD

**Issue by Kai-0310** [mihonapp/mihon#1208]
### Describe your suggested feature

If possible, a feature where we could sync the trackers all in one go would be useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
So like #390?

**Comment by Kai-0310** [comment]
Close but not quite.  Let's say I have 100+ untracked mangas. Would it be possible to implement a feature where I could select those mangas and track them instead of doing it individually?

**Comment by BrutuZ** [comment]
No. There's no way to match automatically.
At best a "I'm feeling lucky" approach (auto pick first result), but it would be too unreliable and prone to picking the wrong entry in most cases that it's not worth the trouble

**Comment by Kai-0310** [comment]
I see, thanks for clarifying.

**Comment by AminurAlam** [comment]
also trackers may block you for sending too many requests

**Comment by MajorTanya** [comment]
Additionally, trackers may disagree about things like publication status, total chapter number, etc. for various reasons. Reconciling that would be a nightmare.
