### ISSUE TITLE
Edit Categories not sorting alphabetically 

### ISSUE THREAD

**Issue by AndreiSager** [mihonapp/mihon#1210]
### Steps to reproduce

1. Go to More --> Categories 
2. Click AZ to sort categories 
3. Click ok

### Expected behavior

Categories should be sorted alphabetically.

### Actual behavior

The categories are sorted but not alphabetically.

![Screenshot_20240909-174003_Mihon](https://github.com/user-attachments/assets/1a04e0e8-9237-4d63-aac1-eed61a803aa2)
![Screenshot_20240909-172742_Mihon](https://github.com/user-attachments/assets/32d450e4-16e7-4377-b021-5ae0ef84d448)

### Mihon version

0.16.5

### Android version

Android 10

### Device

Samsung Galaxy A7 2018

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AndreiSager** [comment]
I think I understand one problem on my part. I am using icons to start my categories, but for some reason "Y02 -" always comes out on top of the sorting list.

**Comment by AntsyLich** [comment]
Y02 has a <space> in front and others has emojis. They are sorted alphabetically even for non english stuff)
