### ISSUE TITLE
category in the library

### ISSUE THREAD

**Issue by Lucs1s** [mihonapp/mihon#1213]
### Describe your suggested feature

improve the category interface in the library

### Other details

1.Compact categories to fit on your smartphone screen...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
So J2K/Yokai?
