### ISSUE TITLE
All of my downloaded manga disappeared and can't download

### ISSUE THREAD

**Issue by xiayannyan** [mihonapp/mihon#1215]
### Steps to reproduce

Noticed that my downloaded manga was removed, tried to re-download, nothing happened even when clicking the download button

### Expected behavior

Download should start after clicking the download button. 

### Actual behavior

Tried to re-download but nothing happened even after clicking the download button. 

### Mihon version

0.16.5

### Android version

Android 14

### Device

Samsung Galaxy A52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Tap: `...` More → Settings → Advanced → Invalidate downloads index

**Comment by Smol-Ame** [comment]
Do what BrutuZ said, otherwise (and for future reference) coke to the Mihon Discord support channel for help/basic questions

**Comment by xiayannyan** [comment]
It worked.  Thank you!
