### ISSUE TITLE
Feat: Add ability to select text from image 

### ISSUE THREAD

**Issue by thousandsofthem** [mihonapp/mihon#1221]
### Describe your suggested feature

Many modern gallery appps allow selecting text from image directly, via long tap. Example:

![Screenshot_2024-09-13-15-57-19-086_com miui gallery-edit](https://github.com/user-attachments/assets/240e921a-b395-4e21-935d-f3d8dc93a022)

This will help a lot since "translate" can be called directly from context menu 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
i don't see how we can achieve this without making the app size be 500mb+

**Comment by AminurAlam** [comment]
> i don't see how we can achieve this without making the app size be 500mb+

its possible if you preprocess all your files. https://github.com/kha-white/mokuro for example can be used to get a .json file containing all scanned text and their position

**Comment by AminurAlam** [comment]
heres a simplified sample of the processed data
```json
{
  "title": "ARIA",
  "pages": [
    {
      "img_width": 1353,
      "img_height": 1920,
      "blocks": [
        {
          "box": [ 16, 1164, 166, 1599 ],
          "vertical": true,
          "lines_coords": [ [
              [ 16.0, 1166.0 ],
              [ 163.0, 1164.0 ],
              [ 166.0, 1597.0 ],
              [ 20.0, 1599.0 ]
          ] ],
          "lines": [ "ｔｈａｔｔｅｒは" ]
        },
        {
          "box": [ 447, 1800, 909, 1856 ],
          "vertical": false,
          "lines_coords": [ [
              [ 453.0, 1803.0 ],
              [ 892.0, 1800.0 ],
              [ 892.0, 1846.0 ],
              [ 453.0, 1850.0 ]
          ] ],
          "lines": [ "だってこずえ" ]
        }
      ],
      "img_path": "001.avif"
    },
    ...
    {
      "img_width": 1353,
      "img_height": 1920,
      "blocks": [
        {
          "box": [ 16, 1164, 166, 1599 ],
          "lines_coords": [ [
              [ 16.0, 1166.0 ],
              [ 163.0, 1164.0 ],
              [ 166.0, 1597.0 ],
              [ 20.0, 1599.0 ]
          ] ],
          "lines": [ "ｔｈａｔｔｅｒは" ]
        },
        {
          "box": [ 447, 1800, 909, 1856 ],
          "lines_coords": [ [
              [ 453.0, 1803.0 ],
              [ 892.0, 1800.0 ],
              [ 892.0, 1846.0 ],
              [ 453.0, 1850.0 ]
          ] ],
          "lines": [ "だってこずえ" ]
        }
      ],
      "img_path": "331.avif"
    }
  ]
}
```

**Comment by BrutuZ** [comment]
> Many modern gallery appps allow selecting text from image directly, via long tap

Just use those instead?
By the point you're manually selecting the text for each speech balloon, plus the two extra taps to reach the translation button, you've long given up on the reader's conveniences ¯\\_(ツ)\_/¯

**Comment by thousandsofthem** [comment]
> its possible if you preprocess all your files.

I think that's how galleries work, one page at a time. Long tap masks initial analyze step (it is much longer than subsequent long taps)


> i don't see how we can achieve this without making the app size be 500mb+

Thank for the answer!
