### ISSUE TITLE
Ghost Touching

### ISSUE THREAD

**Issue by babababababababababababababababababa** [mihonapp/mihon#1226]
### Steps to reproduce

there's a repeat touch sample. i click on 1 and when i click on 2 it will click on 1 again and goes on . and when i click on updates and click library it will click the updates again which end up download chapter appearing. now when i click library the sort panel is popping.

### Expected behavior

its like im in requiem of golden experience like infinite loop

### Actual behavior

just double touching the last touched and sometimes randomly 

### Crash logs

no respond

### Mihon version

0.16.5

### Android version

android 8.1

### Device

Oppo A5s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by babababababababababababababababababa** [comment]
PS: All my other apps are cool it's just the mihon and tachiyomiSY . I even tested my screen and there's no fail on my display . Display is good and all apps are good I tested all of it. Just the Mihon and tachiyomiSY

**Comment by Smol-Ame** [comment]
Could be a device-related issue not working well with the current version of Compose in the app (example: #70). Try out Mihon Preview (https://mihon.app/download) to see if it improves, or you can wait until Mihon Stable receives an update with a newer version of Compose.

**Comment by babababababababababababababababababa** [comment]
https://github.com/user-attachments/assets/af229fac-3e93-4b12-bac6-fd645158cda6

**Comment by babababababababababababababababababa** [comment]
[mihon_crash_logs.txt](https://github.com/user-attachments/files/17008996/mihon_crash_logs.txt)

**Comment by babababababababababababababababababa** [comment]
i received this crash logs because i tried to spam taps on ui maybe there's a crash logs may appear and get there is

**Comment by Smol-Ame** [comment]
Did you try Mihon Preview as I mentioned before, or is that screen recording the same issue on Mihon Preview?

As for your crash log, it doesn't seem to have captured anything about a crash, however, it indicates your Mihon Stable app is 0.16.3

The current Mihon Stable version is 0.16.5, try updating your Mihon Stable to see if it helps with the issue/to receive future support on this issue.

**Comment by babababababababababababababababababa** [comment]
i tried it on mihon 0.16.5 at my very first now i tried it in different versions until i came to 0.16.3 and still occuring

**Comment by babababababababababababababababababa** [comment]
i'll try to install the oldest mihon version if it still occur i'll try to update it to latest manually inside the app

**Comment by Animeboynz** [comment]
Instead of switching to older and older versions, just try the latest preview instead xD
As Smol-Ame mentioned above just head to [https://mihon.app/download](https://mihon.app/download) and try the one on the right 
![image](https://github.com/user-attachments/assets/9e64dd06-10c5-492a-8046-6eaec78445ab)

**Comment by babababababababababababababababababa** [comment]
@animeboynz blud the problem occurs on 0.16.5 that's why I'm trying it in older version but it's seems it's still the same

**Comment by Smol-Ame** [comment]
@babababababababababababababababababa but what about Mihon Preview version that we've mentioned three times?

**Comment by babababababababababababababababababa** [comment]
@Smol-Ame I tried 0.16.13-15 all the same after that i reformated my phone maybe the problem is on my phone and right now im installing the oldest which is 16.0 and if it still occur i'll update it manually inside the application if it still occur i don't know what todo anymore

**Comment by babababababababababababababababababa** [comment]
I tried the oldest it still occur and updated it inside the application to the latest version and it still happening . i dont know what to do anymore last week mihon isn't like this. even in tachiyomisy

**Comment by Smol-Ame** [comment]
@babababababababababababababababababa I'm not sure if you're misunderstanding, but just to double-check, there's two Mihon app versions, the Stable version (which includes 0.16.0 to 0.16.5) and the Preview version (which is currently 0.16.5-r6887).

The two versions are available on the Mihon GitHub, and the link mentioned before (https://mihon.app/download). If you haven't already, download the "Mihon Preview r6887" version off the website, and see if that works.

If you did download the Preview version, and you're just miswriting the version number, and it still behaves the same, then there's nothing else to check/troubleshoot for at the moment for this issue. Only other thing that might be affecting the app's performance, if it happens for both versions, is if you're using a custom ROM on your device.

**Comment by babababababababababababababababababa** [comment]
i will try to install the beta version lets see if it still happen

**Comment by babababababababababababababababababa** [comment]
UPDATE : I tried the beta version which is the r6887 . Goodnews is the tap glitch is gone hooray bad news is i can't read manhwa and manhua series because the picture are blank its just black pages but i can read manga .

**Comment by Smol-Ame** [comment]
No offense, but if you had followed my first messages instructions, most of the back & forth here wouldn't have been needed.

For your black/blank pages issue, check WebView for errors, otherwise, if they show up fine check with whoever maintains your extensions to see if there's any known issues, or come to Mihon Discord support channel for troubleshooting/help.

Closing this issue since the main issue has been resolved.
