### ISSUE TITLE
Unable to connect to any extension

### ISSUE THREAD

**Issue by PixAnon** [mihonapp/mihon#1228]
### Steps to reproduce

Open an extension or entry

### Expected behavior

The extension connects and the entries are shown

### Actual behavior

A crash message appears on screen:
"SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found"

### Mihon version

0.16.5

### Android version

Android 14

### Device

Xiaomi 21081111RG

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
You didn't let the upload finish so we can't see what it says. Please upload it again and wait for it to finish before sending your comment.

**Comment by Smol-Ame** [comment]
Also, with the error message, see this page of the troubleshooting: https://mihon.app/docs/guides/troubleshooting/common-issues#java-security-cert-certpathvalidatorexception-chain-validation-failed

I would say check WebView for errors, but for pretty much all of the extension connection issues, they are either source-related (dead or down site/server, invalid certificate), extension-related (check with whoever maintains your extensions), or internet-related (as mentioned in troubleshooting guide).

**Comment by PixAnon** [comment]
After i tried all the solutions i found that the problem was internet related, what led to not check it in the beginning was that all the extensions worked when i opened them in browser while they showed me a black screen in webview which i still don't get the reason why.
Thank you for your help.
