### ISSUE TITLE
Crash when loading the library

### ISSUE THREAD

**Issue by A4rold** [mihonapp/mihon#1234]
### Steps to reproduce

- crashed when using the search function
- crashed when loading the library
- uninstall and install didn't fix the problem

### Expected behavior

Work fine before, it's suddenly happen

### Actual behavior

Before this happened i had an issue with the title/library search

### Crash logs

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 14 (SDK 34; build KB2003_14.0.0.602(EX01))
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus8T
Device model: KB2003
WebView: Android System WebView 128.0.6613.146

--------- beginning of crash
09-15 03:57:26.722 17602 17602 E AndroidRuntime: FATAL EXCEPTION: main
09-15 03:57:26.722 17602 17602 E AndroidRuntime: Process: app.mihon, PID: 17602
09-15 03:57:26.722 17602 17602 E AndroidRuntime: java.lang.IllegalArgumentException: Can't represent a width of 275279 and height of 144 in Constraints
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at rikka.sui.Sui.createConstraints(Unknown Source:122)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.material3.TabRowKt$ScrollableTabRowImp$1$1$1$2.invoke(Unknown Source:190)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope$layout$1.placeChildren(Unknown Source:36)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure-3p2s80s$$inlined$createMeasureResult$1.placeChildren(Unknown Source:13)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.Pending$keyMap$2.invoke(SourceFile:20)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.Pending$keyMap$2.invoke(SourceFile:192)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at coil.util.DebugLogger.observe(Unknown Source:59)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:53)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:143)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(Unknown Source:99)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(Unknown Source:118)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(Unknown Source:17)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Unknown Source:29)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Unknown Source:10)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:41)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:183)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer$default(Unknown Source:91)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.RecomposeScopeImpl$end$1$2.invoke(SourceFile:11)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.RecomposeScopeImpl$end$1$2.invoke(SourceFile:35)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place(Unknown Source:30)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:5)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:1)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Unknown Source:29)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Unknown Source:10)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:11)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:2)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Unknown Source:29)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Unknown Source:10)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:41)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:183)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Unknown Source:26)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Unknown Source:4)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.foundation.layout.WrapContentNode$measure$1.invoke(Unknown Source:41)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Unknown Source:90)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at coil.compose.ContentPainterModifier$measure$1.invoke(SourceFile:16)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at coil.compose.ContentPainterModifier$measure$1.invoke(SourceFile:37)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Unknown Source:26)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.lifecycle.FlowLiveDataConversions$asFlow$1$2.invoke(SourceFile:100)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.lifecycle.FlowLiveDataConversions$asFlow$1$2.invoke(SourceFile:23)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at coil.util.DebugLogger.observe(Unknown Source:117)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:53)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:143)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(Unknown Source:96)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.replace$ui_release(Unknown Source:31)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:222)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(Unknown Source:77)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onLayout(Unknown Source:4)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.internalOnLayout$ui_release(Unknown Source:27)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.onLayout(Unknown Source:6)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.View.layout(View.java:24791)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4760)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4013)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2765)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10211)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:994)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:257)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:368)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8839)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
09-15 03:57:26.722 17602 17602 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: FATAL EXCEPTION: main
09-15 04:00:57.613 24311 24311 E AndroidRuntime: Process: app.mihon, PID: 24311
09-15 04:00:57.613 24311 24311 E AndroidRuntime: java.lang.IllegalArgumentException: Can't represent a width of 275279 and height of 144 in Constraints
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at rikka.sui.Sui.createConstraints(Unknown Source:122)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.material3.TabRowKt$ScrollableTabRowImp$1$1$1$2.invoke(Unknown Source:190)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope$layout$1.placeChildren(Unknown Source:36)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure-3p2s80s$$inlined$createMeasureResult$1.placeChildren(Unknown Source:13)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.runtime.Pending$keyMap$2.invoke(SourceFile:20)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.runtime.Pending$keyMap$2.invoke(SourceFile:192)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at coil.util.DebugLogger.observe(Unknown Source:59)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:53)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:143)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(Unknown Source:99)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(Unknown Source:118)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(Unknown Source:17)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Unknown Source:29)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Unknown Source:10)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:41)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.ZIndexNode$measure$1.invoke(SourceFile:183)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer$default(Unknown Source:91)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.runtime.RecomposeScopeImpl$end$1$2.invoke(SourceFile:11)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.runtime.RecomposeScopeImpl$end$1$2.invoke(SourceFile:35)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.place(Unknown Source:30)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:5)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:1)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Unknown Source:29)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Unknown Source:10)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:11)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$IncreaseSemanticsBounds$1$1.invoke(SourceFile:2)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(Unknown Source:23)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(Unknown Source:19)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Unknown Source:29)
09-15 04:00:57.613 24311 24311 E AndroidRuntime: 	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Unknown Source:10)
09-15 04:00:57.613 24311 2431

### Mihon version

0.16.5

### Android version

14

### Device

OnePlus 8t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a short but informative title.
- [ ] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It would be much better to share/send the crash log file instead of copying the whole thing & dumping it here. Also, screenshot the in-app crash screen as well

**Comment by BrutuZ** [comment]
> It would be much better to share/send the crash log file instead of copying the whole thing & dumping it here

Pasting is fine really, even preferable than attaching a file, but the issue template should recommend putting it into a code block to make it easier to read
