### ISSUE TITLE
New Extension

### ISSUE THREAD

**Issue by Nihal621** [mihonapp/mihon#1236]
### Describe your suggested feature

Batcave.biz is pretty impressive sites for comic lovers.  It's collection is vast and good. Would very much like to have it as an extension in mihon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, provide, or create any extensions.

**Comment by Nihal621** [comment]
> Mihon doesn't have, associate, provide, or create any extensions.

Can't you add this extension just like the other ones in the repository?

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any extensions or repositories, go ask whoever/wherever you are getting your extensions from.

**Comment by Nihal621** [comment]
> Mihon doesn't have, associate, or provide any extensions or repositories for extensions, go ask whoever/wherever you are getting your extensions from.

If not you developers didnt provide the repositories for mihon, then who did?

**Comment by Smol-Ame** [comment]
Mihon is a bring-your-own-content reader app, it doesn't have, associate, or provide any extensions or content. How would we know what random things you are adding/installing on your phone? Your device has a photo gallery, does that mean the developers of your device provided all the pictures on your phone?

**Comment by Nihal621** [comment]
> Mihon is a bring-your-own-content reader app, it doesn't have, associate, or provide any extensions or content. What part of "doesn't have, associate, or provide" are you not understanding? How would we know what random things you are adding/installing on your phone? Your device has a photo gallery, does that mean the developers of your device provided all the pictures on your phone?
> 
> Stop asking/commenting in here, look at the Mihon Settings > Browse > Extensions repo page to see what random ass third-party unaffiliated, extension repo you added yourself.

Gotchya. And yeah mind your talking behaviour little bit. If you can't handle your app user's with limited understanding or knowledge of how things works out,  then you're not deserving to interact with them behalf of your apps.

**Comment by AntsyLich** [comment]
Shut the fuck up
