### ISSUE TITLE
Manwa 漫蛙 no page found

### ISSUE THREAD

**Issue by wildtypotomato** [mihonapp/mihon#1240]
### Steps to reproduce

1. Go to manga page with chapter list
2. Open a chapter
3. Bounce back to manga page with chapter list, shows "no page found"
![Screenshot_20240918_215035_Mihon](https://github.com/user-attachments/assets/f0eaf027-b0a9-4255-a311-1d08d28ca120)

### Expected behavior

1. Go to manga page with chapter list
2. Open a chapter
3. Image load

### Actual behavior

Getting an error: "No pages found"

### Mihon version

0.16.5

### Android version

Android 14

### Device

S22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
That seems to be a issue related to your extension. Mihon itself doesn't have, associate, or provide any extensions or repositories, so you would be better asking whoever/wherever you originally got your extensions from.
