### ISSUE TITLE
Tap zones displaced when zoomed out

### ISSUE THREAD

**Issue by sacrish** [mihonapp/mihon#1247]
### Steps to reproduce

1. Enter read mode
2. Select a tap zone setting which has upper and lower zones (e.g. "L shaped")
3. Zoom out the image
4. Try tapping different parts of the screen to turn pages

### Expected behavior

Tap zones remain the same like at the default zoom level (as shown by the app's tap zone overlay)

![Screenshot_20240920_110216_Mihon](https://github.com/user-attachments/assets/17fb84b4-ac69-46dd-a020-1bd74597125b)

### Actual behavior

Tap zones displaced, as if moved downward, making it impossible to turn to the next page by tapping the lower part of the screen (for the default L shaped tap zone setting)

![Screenshot_20240920_110216_Mihon_A](https://github.com/user-attachments/assets/c95fa259-8a0a-4ef6-a198-655cc8be96ef)

Don't know if it's device related but my phone is the foldable Samsung Z Fold 4. I've tried both folded and unfolded form (i.e. different aspect ratios) and both are affected by the issue. 

### Mihon version

0.16.5

### Android version

Android 14

### Device

Samsung Z Fold 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Can you check if the issue persists on the beta build @ https://mihon.app/download

**Comment by sacrish** [comment]
Tried the latest beta r6887, and it seems to be working properly on both aspect ratios.
So I assume the bug has been fixed in beta?

**Comment by AntsyLich** [comment]
yeah
