### ISSUE TITLE
Customize the file name and format of the "autobackup" feature.

### ISSUE THREAD

**Issue by MiyouQ** [mihonapp/mihon#1249]
### Describe your suggested feature

I'm trying to use BOOX_E-Ink's bookshelf cloud drive to automatically back up Mihon's ".tachibk" files, but I found that it doesn't support this format.

1.Be able to set the **AutoBackup** file to be saved in a format such as TXT.
2.Be able to set the **AutoBackup** file to be saved with a custom name, or to overwrite the same file each time instead of creating a new one.(so that the BOOX's bookshelf doesn't get cluttered with multiple Mihon's **AutoBackup** files).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
1. Backups are protobuf files, which is a binary format, not a text format. Storing a backup as txt makes no sense.
2. Backup files are named with the date and time of their creation to avoid ambiguity and name conflicts as well as providing an easy way to check what backup is the newest

**Comment by MiyouQ** [comment]
> 1. Backups are protobuf files, which is a binary format, not a text format. Storing a backup as txt makes no sense.
> 2. Backup files are named with the date and time of their creation to avoid ambiguity and name conflicts as well as providing an easy way to check what backup is the newest

The TXT format is only for the purpose of making the file recognizable by the bookshelf, not for actually reading its content.

Overwriting the file is solely for the purpose of allowing the bookshelf to read the same file and upload it to the cloud drive, rather than having to select a new file to sync each time.

I'm only suggesting adding this as an optional setting, not changing the default setting. I just want to have the flexibility to choose this option if needed.

**Comment by AntsyLich** [comment]
Nah
