### ISSUE TITLE
Inconsistent button height with some languages in "Data and storage"

### ISSUE THREAD

**Issue by lyfja** [mihonapp/mihon#126]
### Steps to reproduce

1. Change app language to German (for example)
2. Go to data and storage settings ("Daten und Speicher")
3. Observe inconsistent button height for backup and restore

### Expected behavior

Both buttons should be the same height

### Actual behavior

One of the buttons is bigger than the other since it has more text in it (see screenshot)

### Mihon version

Beta r6454

### Android version

Android 13

### Device

Motorola Edge 40

### Other details

![Screenshot_20240118-084209](https://github.com/mihonapp/mihon/assets/45209212/0e2b63f3-4ccd-4a92-8784-27853216acf6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
That'll be down to text wrapping I'm guessing, someone should look into that

**Comment by theolm** [comment]
I take this one. Should open a PR soon. ✌️
