### ISSUE TITLE
Request a function

### ISSUE THREAD

**Issue by Naileon** [mihonapp/mihon#1260]
### Describe your suggested feature

I hope to make an extra sort button in the comic catalog interface, instead of folding it in the upper right corner. Because I often need to switch between reverse order and positive order, it is very inconvenient in it.
TY.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
no
