### ISSUE TITLE
Asura Scans: NullPointerException when refreshing manga 

### ISSUE THREAD

**Issue by pluto3210** [mihonapp/mihon#1261]
### Steps to reproduce

1.Try refresh comics from asura scans
2.
![Screenshot_20240925-142347](https://github.com/user-attachments/assets/ee13d3b4-7657-4c16-80d3-7811f997fd7e)

### Expected behavior

Refreshed Chapters

### Actual behavior

Error

### Mihon version

0.16.5

### Android version

Android 13

### Device

Motorola

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any extensions. This is an extension-related issue, nothing we can do here.
