### ISSUE TITLE
"SSLException: unable to parse TLS packet header" - unable to resolve with current knowledge

### ISSUE THREAD

**Issue by TheYoungerSes** [mihonapp/mihon#1263]
### Steps to reproduce

1. I have external repositories Installed from an older tachiyomi install.
2. I trusted one of those sources
3. attempt to browse that source

### Expected behavior

I usually expect the titles from that source to populate the page.

### Actual behavior

In the source Browser, im greeted with an emoticon, and the message of "SSLException: unable to parse TLS packet header". Opening the webview, I see "Webpage not available" "the webpage at -address- coulud not be loaded because" "net::ERR_SSL_PROTOCOL_ERROR"

### Mihon version

0.16.5

### Android version

11

### Device

Moto G power (2020)

### Other details

This issue seems to stem all the way from Tachiyomi. 
I have tried to clear all caches, cookies, etc. and nothing works.
I have browsed FAQ, and there is nothing on resolving SSL errors.
This seems to be a network level problem; as this only happens on my home network, and not on other networks that I use, i.e. at work. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Sounds like the website in question is having issues, please ask your extension providers for help there instead. Mihon doesn't provide extensions nor is it associated with any extension providers.

**Comment by TheYoungerSes** [comment]
The current Extensions that produce this error consistently are Mangareader.to and mangadex

**Comment by MajorTanya** [comment]
Please do not name extensions here and remove the ones you have mentioned.

**Comment by TheYoungerSes** [comment]
> Please do not name extensions here and remove the ones you have mentioned.

yeah, i expected as much; thanks again

**Comment by AntsyLich** [comment]
What exactly are you asking for? Your request doesn't make any sense  and also shouldn't be inside a bug report.

**Comment by MajorTanya** [comment]
> > Sounds like the website in question is having issues, please ask your extension providers for help there instead. Mihon doesn't provide extensions nor is it associated with any extension providers.
> 
> Again, I listed out it seems to a network related error, as when I am at work, and use their network access to the internet, the extensions work fine. Is there a way to configure this level of connectivity from my device, or from the app; or is it even possible as an added function, i.e. could an application update with a new settings option resolve it?

Okay this is sounding more like a networking issue for wherever you were experiencing this issue. Maybe your ISP or Router are messing with the request.

**Comment by TheYoungerSes** [comment]
> > > Sounds like the website in question is having issues, please ask your extension providers for help there instead. Mihon doesn't provide extensions nor is it associated with any extension providers.
> > 
> > 
> > Again, I listed out it seems to a network related error, as when I am at work, and use their network access to the internet, the extensions work fine. Is there a way to configure this level of connectivity from my device, or from the app; or is it even possible as an added function, i.e. could an application update with a new settings option resolve it?
> 
> Okay this is sounding more like a networking issue for wherever you were experiencing this issue. Maybe your ISP or Router are messing with the request.

Ok thanks, will look into it; but highly unlikely to get this resolved; as I am not the admin of my home network.
