### ISSUE TITLE
Feature to make Update happen in batches.

### ISSUE THREAD

**Issue by ToxicCloud69** [mihonapp/mihon#1265]
### Describe your suggested feature

Sorry if this was asked for before **(I have checked beforehand but couldn't find anything)**. 

I basically want a feature that allows the updates to happen in small portions like thirds of the entire library at a time instead of updating the entire library in one go. Bonus points if the portions are adjustable via a setting. 

I ask for this to not break sources and also make updates happen faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Use smart update option

**Comment by Smol-Ame** [comment]
But the app already does this with Smart Updates, not specifically in thirds or whatever, but it's meant to spread out your updates over a predicted release pattern. This already reduces unnecessary requests.

Portions could be "adjusted" by putting stuff into Categories, and selecting which categories are included/excluded from Automatic Updates.

**Comment by ToxicCloud69** [comment]
I do know that smart updates exist but the problem that i am facing with the smart updates is the fact that sometimes content i read go into long hiatuses or just release erratically which messes with the prediction algorithm causing it to not update for a long time and i miss the chapters. And the thing with the categories kind of don't make sense to me cause you are telling me to categorize everything and make some of them not auto-update when what i am suggesting is for the auto update to be more hands off and just portion the updates.
