### ISSUE TITLE
App crash on HyperOS

### ISSUE THREAD

**Issue by BENSTONE101** [mihonapp/mihon#1270]
### Steps to reproduce

Open app , 
Press update 
Go to settings/downloads/more/sources/updates/sources search 
Press back button 
Crash

https://github.com/user-attachments/assets/12864ab9-d159-4345-8afe-66331d49f5a8

### Expected behavior

Go back to back

### Actual behavior

Crashes 

### Crash logs

[mihon_crash_logs.txt](https://github.com/user-attachments/files/17154556/mihon_crash_logs.txt)
![Screenshot_2024-09-26-23-52-33-559_app mihon](https://github.com/user-attachments/assets/bf8d36d2-8c1f-4fb0-a419-a7d528429c6e)

### Mihon version

0.16.5

### Android version

14

### Device

Redmi note 13 pro (12gb MediaTek g99 ultra)

### Other details

Did ask around in the discord Support and they recommended me to post a issue report on github

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BENSTONE101** [comment]
Same Crash when I tried the latest Mihon Beta app (on the recommendation of discord support staff) 
![Uploading Screenshot_2024-09-27-00-11-36-210_app.mihon.debug.jpg…]()

**Comment by AntsyLich** [comment]
This seems like a OS level crash. Can you check if there are android updates and what not?

**Comment by BENSTONE101** [comment]
> This seems like a OS level crash. Can you check if there are android updates and what not?

![Screenshot_2024-09-28-12-34-22-554_com android updater](https://github.com/user-attachments/assets/fc4e6da6-e21a-446f-baab-6c293975c47e)
There aren't any android or OS official updates for my device at the moment .

**Comment by Smol-Ame** [comment]
Closing in favor of #1278
