### ISSUE TITLE
Add option to change UI font 

### ISSUE THREAD

**Issue by adayu753x** [mihonapp/mihon#1271]
### Describe your suggested feature

Would be appreciated to add an option to change the apps UI font to either the system font or to the users own font via an uploaded font file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
It already is?

| Default | Other Font |
|--------|--------|
| ![Screenshot_20240928_092907_Mihon](https://github.com/user-attachments/assets/17715340-0350-4e8b-aa7a-4b675ba940c7) | ![Screenshot_20240928_092851_Mihon](https://github.com/user-attachments/assets/f5fb4a66-ac55-4b59-9f55-acc101f44396) |

**Comment by MajorTanya** [comment]
> It already is?

Pretty sure the request is for Mihon to optionally either
1. Follow system settings (it already does)
2. Have a way to use a different font from the rest of the system

**Comment by AntsyLich** [comment]
Chnage your system font

**Comment by adayu753x** [comment]
Currently on a Boox Poke 5s on android 11, system wide font is currently changed. Seems this could be a platform support issue? Even so a custom font option would still be appreciated especially for those without access to a system wide font change.

**Comment by AntsyLich** [comment]
> Currently on a Boox Poke 5s on android 11, system wide font is currently changed. Seems this could be a platform support issue? 

Could be or your device doesn't do it the correct way. Anyway this seems like an edge case.

> Even so a custom font option would still be appreciated especially for those without access to a system wide font change.

If you can deal with a font system wide you can surely deal with it in a single app
