### ISSUE TITLE
'Set as default' but for specific categories

### ISSUE THREAD

**Issue by hpershdzy** [mihonapp/mihon#1272]
### Describe your suggested feature

When choosing "Filter, Sort, Display" on a specific manga you can choose to set your selection as default and apply it to the entire library. This would add the option to apply this to all manga in an entire category.

### Other details

good for having new manga show up with the first chapter first but then having manga in an up to date or on-going category with the latest chapter first.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
what happens when you have the same entry on 2 categories with different settings?

**Comment by hpershdzy** [comment]
ooh I didn't think of that. maybe depending on which category you open it in the display defaults change? so rather than the settings applying to the specific manga it applies it to a category? that would probably function because rather than needing to apply it every time, if you're viewing it in that category it would automatically view the manga with the specific settings?

**Comment by AntsyLich** [comment]
What you are suggesting won't work cause you open an entry from many different places outside of the library. Closing as something we won't add.
