### ISSUE TITLE
Reset scans change domain

### ISSUE THREAD

**Issue by Oreki4** [mihonapp/mihon#1275]
### Steps to reproduce

![Screenshot_20240929-211343](https://github.com/user-attachments/assets/b96d320f-e985-4b50-aa31-4508a5f6413b)

### Expected behavior

See latest updates

### Actual behavior

HTTP 404, check website WebView

### Mihon version

App version: 0.16.5

### Android version

13.5.0

### Device

Infinix HOT 40 Pro X6837

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon doesn't have, associate, or provide any extensions. This is an extension-related issue, nothing we can do here, check with whoever maintains your extensions instead.
