### ISSUE TITLE
Page loading slowed down after updating from 0.16.3 to 0.16.5

### ISSUE THREAD

**Issue by Fanatiikon** [mihonapp/mihon#1276]
### Steps to reproduce

1. Boot app
2. Pick a Webtoon/Manga(mostly tried on Bato because it every page is a seperate image)
3. Scroll up and down
4. Observe when passing the preload zone the app lags for a second and shows black pages where new pages will load

### Expected behavior

Pages should load at the same speed as previous versions without the app lagging.

### Actual behavior

On 0.16.3 when scrolling up or down and pages need to load it takes less than a second for them to show up so the black pages are barely noticeable. As of 0.16.5 when scrolling and reaching the spot where pages are supposed to load the app lags for about 1 second and you get black unloaded pages for about 1.5-2 seconds and then they load.

### Mihon version

0.16.5

### Android version

Android 10

### Device

Lenovo M10 FHD Plus 2nd Gen

### Other details

I tried Deleting Cache and even resetting everything in the application. I think resetting made the pages load slightly faster but the moment I loaded the backup the issue started occurring again. Downgrading back to 0.16.3 completely fixes this issue. I did not have time to check if 0.16.4 has this issue as well. If completely necessary let me know and I will try to check it on 0.16.4 as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Fanatiikon** [comment]
If this does not reproduce on your side. I'll attempt to pull 2 videos one from 0.16.3 and one from 0.16.5 the upcoming week.

**Comment by AntsyLich** [comment]
Can you check beta? https://mihon.app/download/

**Comment by AntsyLich** [comment]
Given you didn't reply I'm assuming it's fixed
