### ISSUE TITLE
Cant read manga in colamanga

### ISSUE THREAD

**Issue by Narudesuu** [mihonapp/mihon#1280]
### Steps to reproduce

Choise any manga
Choise any chapter 

### Expected behavior

Start read manga

### Actual behavior

![Screenshot_20240930-123155~2](https://github.com/user-attachments/assets/76237fc6-2b0f-473c-8bee-cd0da79a041b)

### Mihon version

0.16.5

### Android version

Android 14

### Device

Sony 1 VI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue, go check with whoever maintains your extensions instead, since Mihon doesn't have, associate, or provide any extensions/sources/content.
