### ISSUE TITLE
Resume update if it crashes in the middle

### ISSUE THREAD

**Issue by aoba-seragakii** [mihonapp/mihon#1281]
### Describe your suggested feature

Sometimes, the app ends up crashing in the middle of an update, and then it starts all over again once the user opens the app again.
Instead of doing that, I think it would be better if the update continued right before the crash, so it doesn't strain the sources by updating the same entries all over again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
lemme guess you disabled all the smart update stuff from settings? enable those back.

**Comment by aoba-seragakii** [comment]
> lemme guess you disabled all the smart update stuff from settings? enable those back.

You guessed wrong
I left only "Predict next release time" and "skip unstarted entries" on but it still crashes for me

**Comment by AntsyLich** [comment]
Well then it skips the one already updated.

**Comment by aoba-seragakii** [comment]
> Well then it skips the one already updated.

Even if I update twice a day?
(At daytime and at night time specifically)

**Comment by AntsyLich** [comment]
It's more or less how the prediction works iirc.
