### ISSUE TITLE
Improve transition between color palettes.

### ISSUE THREAD

**Issue by NishTheFish92** [mihonapp/mihon#1283]
## Description of suggested feature
Mihon offers great flexibility when it comes to changing themes and color palettes and has smooth and interactive animations. But, the animation to change color palette is unrefined and jarring when seen in context with the rest of the application. Although a small detail, The animation to change the color palette can be improved to improve the overall refinement of the app.

## How it currently is
While switching between the different color palettes offered by the application, the app does not smoothly transition between the color palettes. The app Jitters in a jarring manner and then changes the color scheme. 
## Suggestions on how to improve the transition
Either
- Make the color palette transition similar to the theme transition between system, light and dark theme.

OR,
- Darken the screen using a transition for a couple of milliseconds while the color changes so the color change can appear seamless without the jittering being visible to the user.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by blackksheepp** [comment]
I just tested this issue, I cloned the latest repo and ran it in an emulator, and then downloaded the official release.

What I found out was, the jitter is only occurring on on the official release, the current repo code works just fine, this issue might be resolved, but I am not sure.

**Comment by AntsyLich** [comment]
> the animation to change color palette is unrefined and jarring when seen in context with the rest of the application

there is no animation it changes instantly similar to the theme
