### ISSUE TITLE
Stuck in "An update is already running"

### ISSUE THREAD

**Issue by BronzeMaster5000** [mihonapp/mihon#1286]
### Steps to reproduce

1. Open Mihon
2. Try to update the mangas

### Expected behavior

Chapters get updated for the mangas.

### Actual behavior

Nothing happens. The "Library last updated" shows as 22 hours ago.

### Mihon version

0.16.5

### Android version

Android 14

### Device

Google Pixel 6a

### Other details

This happened 22 hours ago and i tried to update it 4 times since then at different times and it doesnt work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
your title and description doesn't match

**Comment by BronzeMaster5000** [comment]
How so? When i try and update the chapters i get the message "An update is already running" and this update has presumably been running since 22 hours ago and doesnt stop.

**Comment by Smol-Ame** [comment]
Try force stopping the app, and maybe make sure Mihon still has notifications permission. Iirc, it should try to update the library again when you open it, see if it's getting stuck on an entry/source.

**Comment by AntsyLich** [comment]
> How so? 

Cause it doesn't. You can't just write a half baked issue and expect everyone to understand it. 

Anyway do what the other comment mentioned and join our discord for further support.

**Comment by BronzeMaster5000** [comment]
> Try force stopping the app, and maybe make sure Mihon still has notifications permission. Iirc, it should try to update the library again when you open it, see if it's getting stuck on an entry/source.

Thanks forcing the app to stop worked.

> > How so?
> 
> Cause it doesn't. You can't just write a half baked issue and expect everyone to understand it.
> 
> Anyway do what the other comment mentioned and join our discord for further support.

What should i have specified more in my Issue? I am genuinely interested in how i can improve in that regard.
