### ISSUE TITLE
Option to Specify the Amount to Download

### ISSUE THREAD

**Issue by 28th-Element** [mihonapp/mihon#1290]
### Describe your suggested feature

It's just a small quality of life change, I wanted to download 100 chapters but I need to press download "next 25 chapter" 4 times. Previously, you can specify the amount, hope it makes a comeback

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
That option was removed in Tachiyomi days already, and Mihon has no plans to bring it back. It puts an incredible load on sources and is patently unnecessary in the vast majority of situations. Please check out the "Download Ahead" feature in the app, together with the "Delete after reading" feature.
