### ISSUE TITLE
Hope you can add more official manga websites in the extension 

### ISSUE THREAD

**Issue by Moonpie123** [mihonapp/mihon#1291]
### Describe your suggested feature

Pls add widely used official websites in Korea  like Ridibooks, lezhin, bomtoon if possible. Sync the purchased chapters. Thanks a lot. 

### Other details

Lezhin.com
Ridibooks.com
bomtoon.tw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions itself nor is it associated with any extension providers or sources. Please do not ask us for extension fixes, updates, or additions.
