### ISSUE TITLE
[Feature Request] Custom File Naming

### ISSUE THREAD

**Issue by hakarune** [mihonapp/mihon#1295]
### Describe your suggested feature

Other programs don't recognize downloaded files by name. So I'd like to request The ability to set custom file naming like "MangaName - Chapter ##.cbz" OR Name - ChapterName_##.cbz" or other custom styles being able to chose delimiters/spacers and number style 

### Other details

I want to use library on other apps too like simple CBZ comic readers so it's all in 1 app but still downloaded and updated by mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Use a dedicated downloader program
