### ISSUE TITLE
Able to see already download chapters from other sources

### ISSUE THREAD

**Issue by riojano0** [mihonapp/mihon#1296]
### Describe your suggested feature

When I change/migrate sources I lose access to all previously downloaded chapters, is there a way to prevent them from being hidden or displayed as from external sources?
Or give an option to avoid deleting all chapters downloaded from the previous source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Manga A from Source X, Manga from Source Y is no different than Manga A from Source X, Manga B from Source Y from the app's perspective (also why you can migrate to a different manga and it'll still migrate).

The app has no way to know if another manga (or downloads) is the same manga but from different source. I would suggest reading all the downloaded chapters and migrating afterwards.

**Comment by riojano0** [comment]
Ahh I undesrtand, is not a way for example keep a table on sqlite like a table

MIGRATE_HISTORY
FROM_MANGA_ID, TO_MANGA_ID, FROM_SOURCE_iD, TO_SOURCE_iD, PRESERVE_DOWNLOADS

And on some way attach that download to the list show on the chapter list on the new source?

**Comment by MajorTanya** [comment]
I mean in the first place, there's no way to know if the chapters downloaded can even be matched to the new source. Like when one source provides one "chapter" per volume while the other does chapter by chapter.

**Comment by riojano0** [comment]
> I mean in the first place, there's no way to know if the chapters downloaded can even be matched to the new source. Like when one source provides one "chapter" per volume while the other does chapter by chapter.

Is not needed to match, only avoid to delete that already downloaded chapters. Or maybe exist other way that I don't know? I see that we already are able to filter or show some chapters base on the source. But my doubt or behavior is already we have download 200 chapters from a manga and the source is dead, when is change to a new source to get the 201 avoid to delete the previous 200 chapters.

**Comment by AntsyLich** [comment]
Or maybe read the 200 chapters and migrate afterwards? I see no point in investing time in this.
