### ISSUE TITLE
Long pages: better page split logic

### ISSUE THREAD

**Issue by thousandsofthem** [mihonapp/mihon#1299]
### Describe your suggested feature

When splitting long pages into chunks, search for a better cut line.

Proposed schema:

For lines e.g. +100...-100 around initial cut line, calculate value for each line:

For every pixel of line, calculate brightness change between pixel and next pixel in line, sum values.

Choose line with lowest value, with tied values choose lowest distance from zero-th line. 

This way app won't cut text in the middle, and, if possible, will choose empty space instead of cutting dialogs in half

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Why?

**Comment by thousandsofthem** [comment]
Hard to read text split in half.
Example:
![Solo Leveling - Vol 1 Ch 90 - 6](https://github.com/user-attachments/assets/790f533c-a792-4d8e-8277-7abdba524965)
---cut----
![Solo Leveling - Vol 1 Ch 90 - 7](https://github.com/user-attachments/assets/c8f284b5-b89f-4b03-a9ec-d660248b542a)

**Comment by AntsyLich** [comment]
Use "Long Strip" reading mode not "Long Strip with gaps"
