### ISSUE TITLE
Suggestions that should be included in the extensions.

### ISSUE THREAD

**Issue by FrankieD777** [mihonapp/mihon#1303]
### Describe your suggested feature

‎Dear community members,
‎
‎I hope this message finds you in good health and high spirits. Today, I want to reach out to you to request your valuable support and collaboration on an issue that, in my view, could bring significant benefits to a large number of users and enhance our collective experience.
‎
‎As many of you may know, about six months ago, we faced an unfortunate incident related to copyright issues. This unforeseen event not only impacted our ecosystem of apps and extensions but also resulted in the loss of numerous essential extensions, including those so beloved and used by the community like Tachiyomi's. In response to this situation, we have seen the rise of various forks, third-party extensions, and the successor known as Mihon, which is a testament to the community's capacity for innovation and adaptation. Additionally, in the past, filters have been implemented in various extensions, significantly visible in examples like Olympus 2.0.
‎
‎For this reason, I am motivated to share a proposal with you that I believe could greatly improve our user experience. My idea is as follows: I suggest that we incorporate a tag search feature that operates globally across the entire application, instead of individually on each extension. I am convinced that this improvement could streamline and simplify the search process for all of us.
‎
‎To illustrate my proposal, I refer to that old application that allowed users to explore sections of popular genres separately. This system later evolved to include not only more specific genre filters but also effective search tools that succeeded in consolidating a much more organized and easy-to-navigate interface. I would like us to adopt a similar approach, combining both methods on our platform. By doing so, when accessing each extension, we could find a small search icon that would allow us to quickly scan for keywords, thus enhancing user experience and offering a more professional, organized, and efficient environment.
‎
‎Anticipating concerns that may arise, I would like to address a few points. On one hand, I understand there might be a fear that this additional functionality could increase the application's size or cause blocks from the sites we use. To mitigate these risks, I propose implementing an automatic data cleaner carefully designed not to delete users' history or personal downloads. Additionally, I suggest the automatic update, at predefined time intervals, of the application's user agent. This measure would aim to prevent unnecessary blocks, thus maintaining the fluidity and accessibility to which we are accustomed.
‎
‎I would like to express my deepest gratitude for your attention and understanding of this initiative. I trust that, by working together, we can continue to build a community where user experience is at the heart of everything we do.
‎
‎Kind regards to all,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
> I suggest that we incorporate a tag search feature that operates globally across the entire application, instead of individually on each extension. I am convinced that this improvement could streamline and simplify the search process for all of us.

1. Please don't fluff up a simple proposal like this with an essay.
2. This is infeasible for various reasons, starting with inconsistencies across sources with simple things like naming of tags (is it Shonen or Shounen? Does the source differentiate between the two for some reason?) as well as more big-picture problems: How would Mihon know how a search in a source works? What about sources that don't support tag searches at all?
3. You can already search your library for tags by just searching for the tag word in the normal search bar (Searching for `Romance` for example will show all titles that are tagged with Romance or have the word in their title)

**Comment by AntsyLich** [comment]
Ai detected opinion rejected. Even ESL is more acceptable than this garbage chatgpt spit out.

![image](https://github.com/user-attachments/assets/44d5a5a1-4089-45d0-b21e-f24185fe1f4a)
