### ISSUE TITLE
Can't delete chapter in a excluded category 

### ISSUE THREAD

**Issue by vampdx** [mihonapp/mihon#1306]
### Steps to reproduce

1. Create a category
2. In Settings->Downloads->Delete Chapters, add category to "excluded categories"
3. Add a manga to excluded category
4. Download a chapter
5. Manually delete chapter

### Expected behavior

I expect the setting to only deactivate automatic delete of read chapters and not a manuel delete as well. 

### Actual behavior

Chapter is kept instead of deleted

### Mihon version

0.16.5

### Android version

Android 14

### Device

Xiaomi 13T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
> I expect the setting to only deactivate automatic delete of read chapters and not a manuel delete as well.

Why would you expect that? The section is named "Delete chapters" not "Auto-delete Chapters"

**Comment by AntsyLich** [comment]
> But I am willing to adjust my expectations with a example why you would block deletes without auto deletes

So you don't accidentally delete it?

**Comment by AntsyLich** [comment]
@vampdx got a counter argument? or should i close the issue.
