### ISSUE TITLE
Download speed too slow

### ISSUE THREAD

**Issue by AfkSinceBirth** [mihonapp/mihon#1307]
### Steps to reproduce

1.go to any manga 
2.click on download icon next to any chapter
3.The download speed is extremely slow.

### Expected behavior

The chapter should have downloaded at a decent speed close to my wifi's download speed.

### Actual behavior

The download speed is 100 times slower than my wifi's download speed(6 MBps).
The download speed is somewhere about 40-60 KBps.

### Mihon version

0.16.5

### Android version

Android 14

### Device

Realme GT 6T

### Other details

The loading speed is good, so the chapters are easily readable with an active internet connection, but the download speed is horrible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any extensions/content. Just cause you have internet/"fast download speed" doesn't mean there isn't other factors.

Could be ratelimited by the source or whatever extension you're using to reduce the chance of you getting blocked from them. Check with whoever maintains your extensions instead to see if there's anything they know about this.
