### ISSUE TITLE
App frequently crashes at random

### ISSUE THREAD

**Issue by RazredgeBR** [mihonapp/mihon#1316]
### Steps to reproduce

Using the app, eventually, after a while, when pressing "back" to exit, the app will crash.

### Expected behavior

Shouldn't crash, just close.

### Actual behavior

Crashes and gives the option to restart or save the log.

### Crash logs

[gvTbxhWV.txt](https://github.com/user-attachments/files/17347964/gvTbxhWV.txt)

### Mihon version

App version: 0.16.5-6909

### Android version

Android 14

### Device

Samsung Galaxy Flip Z4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Known crash, just restart the app and should be fine.

`LibraryTab:currentTab was used multiple times`
