### ISSUE TITLE
How do I separate different groups in mihon

### ISSUE THREAD

**Issue by Anshuman2259** [mihonapp/mihon#1319]
### Steps to reproduce

Search any manga, ex - blue lock
Use extention such as comick
You will see that there are duplicate chapter of ever chapter because of the group feature in comick 
![Screenshot_20241013_090715](https://github.com/user-attachments/assets/4a389dbb-0a76-455c-b1b3-fe35d581c3fd)

### Expected behavior

How do I remove the duplicated ch?

### Actual behavior

How do I remove the duplicated ch?

### Mihon version

0.16.5

### Android version

13

### Device

Vivo v20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Top of the entry, there's a filter button, tap the filter button (three lines icon) and choose the scanlators you want.

Come to the Mihon Discord support channel next time for these basic questions/issues.
