### ISSUE TITLE
Plugins  Roumanwu  Enter error

### ISSUE THREAD

**Issue by laohaner** [mihonapp/mihon#1322]
### Steps to reproduce

JsonDecodingException: Expected start of the
object '{', but had 'EOF' instead at path: $
JSON input:

### Expected behavior

JsonDecodingException: Expected start of the
object '{', but had 'EOF' instead at path: $
JSON input:

### Actual behavior

JsonDecodingException: Expected start of the
object '{', but had 'EOF' instead at path: $
JSON input:

### Crash logs

JsonDecodingException: Expected start of the
object '{', but had 'EOF' instead at path: $
JSON input:
![image](https://github.com/user-attachments/assets/5906ebd1-cccc-42ed-ad41-e6e42aaf54d7)

### Mihon version

0.16.5

### Android version

12

### Device

k40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon does not provide extensions or support for extensions. Please go to your extension repository provider for assistance with this issue.
