### ISSUE TITLE
Stuttering while reading webtoons

### ISSUE THREAD

**Issue by sillysack69** [mihonapp/mihon#1325]
### Steps to reproduce

This tends to be the case for all webtoons. I am demonstrating it on Bones. 
1. Open Bones on Comick
2. Open the chapter 1.1
3. Start scrolling through the pages
4. Experience the stutter every times the page changes
5. And a really bad stutter just below that one

### Expected behavior

No stutter. Just smooth scrolling, shouldn't be able to tell when the page changes. Should feel like a continuous page. 

### Actual behavior

It lags and stutters like a madman. 
Not as noticeable in the screen recording, because of the low frame rate, but it's driving me mad. It's at the part where it says "And the awakened started appearing". That's the mild stutter. These are everywhere. But now the uber lag has appeared at the part where it says "I'm just a loser". These tend to be at either at page breaks or long pages. Tachiyomi AZ does not have this problem. It's almost smooth as butter, like the old tachiyomi used to be before it ditched the hamburger style side bar and became more modern with the tabs at the bottom. Yes, I'm saying tachiyomi just before it abandoned had this problem as well. It's getting worse with each iteration. 

Here's a link where I have uploaded a video so you can see the problem: https://youtu.be/K2ZHjirfQqo

### Mihon version

0.16.5

### Android version

Android 13

### Device

Redmi Note 12 4G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
there are some changes that help it in beta, you can try using that if not you're only options is download them and enable split tall images or find a site that splits them already.

**Comment by sillysack69** [comment]
Just tried the dev version and the current beta seems to fix this issue. The chapter select page is all messed up though. Really glitches out on scrolling. Pretty good if only the good parts make it to the stable build.
