### ISSUE TITLE
Add badge to entries in history

### ISSUE THREAD

**Issue by aoba-seragakii** [mihonapp/mihon#1329]
### Describe your suggested feature

The badge would indicate that the entry has been updated since and how many updates it has
Basically something like the badges in the library which indicates how many entries hasn't been read yet but in the history section instead

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
I genuinely can't see a point to this, like please make me understand. You have multiple ways of knowing that you have unread chapters. 
1. You get a damn notification when there are updates.
2. The entire updates tab that's dedicated to that.
3. The badges you mention that already exist in the library. (If you really want you can even sort your library to last read, showing you things in the same order as history and with badges)
