### ISSUE TITLE
Make the "Has results" filter stay on by default

### ISSUE THREAD

**Issue by Snyret** [mihonapp/mihon#133]
### Describe your suggested feature

Add the option to have the **Has results** button active at all times on the browse section in settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cbussa** [comment]
I agree! It's not at all hard to enable again, but I sure wish it was sticky as well between searches or even multiple sessions.

**Comment by Gaebuh** [comment]
I second this and add a toggle that all filters while browsing should be sticky. Hate having to include and exclude tags every time I'm searching.

**Comment by AntsyLich** [comment]
> add a toggle that all filters while browsing should be sticky. Hate having to include and exclude tags every time I'm searching.

Unrelated and also a very nieche feature so won't bother
