### ISSUE TITLE
Genz Toons URL Change

### ISSUE THREAD

**Issue by JannisJo** [mihonapp/mihon#1342]
### Steps to reproduce

Open Genz Toons source

### Expected behavior

Source loads

### Actual behavior

Source does not load due to url change

### Mihon version

0.16.5

### Android version

Android 14

### Device

Realme 12

### Other details

Old URL: genztoons.com
New URL: genzupdates.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any extensions, go ask whoever/wherever you get your extensions from.
