### ISSUE TITLE
Cannot read Downloaded chapters and invalidate download index not working 

### ISSUE THREAD

**Issue by EULASTHIGH** [mihonapp/mihon#1343]
### Steps to reproduce

1.download any manga 
2.restart the device or open mihon after some hours 

### Expected behavior

After restarting the downloaded chapters should stay intact and we should be able to read them with no issue

### Actual behavior

But i cant actually read them and the downloaded mark disappears and if i try to open the file with data turned off i get an error saying "failed to connect to ____(the extension you are using).

### Mihon version

0.16.5

### Android version

Android 14

### Device

Iqoo neo 9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Join discord for further support since it is definitely working
