### ISSUE TITLE
Anchor pages to screen side

### ISSUE THREAD

**Issue by phly95** [mihonapp/mihon#1350]
### Describe your suggested feature

I'd like to be able to anchor the page to the top of the screen instead of to the center. So if I'm holding my phone from the bottom in reverse portrait I essentially have a borderless view of the manga, since the border is where I'm holding the phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
what?

**Comment by AminurAlam** [comment]
left aligned instead of centre aligned?

**Comment by phly95** [comment]
Basically, if the phone is in portrait view, there are normally back/white bars at the top and bottom. I'm suggesting that you can have one large bar on the top or the bottom instead of two smaller ones on the top and bottom.

**Comment by AntsyLich** [comment]
What black bar? There's no black bar

**Comment by phly95** [comment]
![Screenshot_2024-10-20-17-55-18-17_551f7f0ca926862b368845ce7ee433aa~2](https://github.com/user-attachments/assets/05d1b8cd-9df8-4b61-8adc-c9d82f77c26f)
This part.

**Comment by phly95** [comment]
If you have a tall phone, the back bars are there. Theoretically, you could have one big bar instead to anchor the page to the top or bottom of the screen.

**Comment by AntsyLich** [comment]
Given that you'll probably gonna be the only one to use it it's a no.

**Comment by phly95** [comment]
That's fair. I think tall phones are fairly common, but it's understandable that most people wouldn't use that option.
