### ISSUE TITLE
Hide Smart Updates Button

### ISSUE THREAD

**Issue by Snyret** [mihonapp/mihon#1357]
### Describe your suggested feature

Add the option to hide the hourglass button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
> - [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

#1031
