### ISSUE TITLE
Toast saying Tracker updated to chapter always shows after remove tracker

### ISSUE THREAD

**Issue by cuong-tran** [mihonapp/mihon#1369]
### Steps to reproduce

1. Add a tracker to manga
2. Remove all trackers from that manga
3. Swipe to mark read

### Expected behavior

No toast shown

### Actual behavior

A toast saying "Tracker updated to chapter..." always shows even though no trackers avaiable.

### Mihon version

latest dev build

### Android version

Android 14

### Device

AVD

### Other details

Close/Start app again, the issue still persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
<img src="https://github.com/user-attachments/assets/c3638856-357d-4a12-90e6-a7b5294d8e3d" alt="drawing" width="80"/>
