### ISSUE TITLE
Library update not working

### ISSUE THREAD

**Issue by haecnvs** [mihonapp/mihon#137]
### Steps to reproduce

New chapters are not loading / updating in library 

### Expected behavior

Global update should update library entries 

### Actual behavior

It isn't, have to manually go to each entry and refresh to load new chapters.

### Mihon version

0.16.1

### Android version

Android 11

### Device

Oneplus Nord 2 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TruePadawan** [comment]
I ran into this too, I fixed it by going to Settings -> Library -> Smart Update
Uncheck `predict next release time`

**Comment by AogamiKiryuu** [comment]
Im also having a same issue, the library wont update globally, expect if i refresh some series that i look then they start to update.

**Comment by MajorTanya** [comment]
> I ran into this too, I fixed it by going to Settings -> Library -> Smart Update Uncheck `predict next release time`
> 
> You might also want to uncheck `Skip entries with unread chapters` as an extra since it.............skips entries with unread chapters

Those options exist to lessen the load on sources from too many unneeded requests, after all, most sources/entries probably don't need to be checked every time your auto-update is running. Please consider re-enabling the Prediction feature again.


> Im also having a same issue, the library wont update globally, expect if i refresh some series that i look then they start to update.

It isn't an “issue”, it's a feature meant to lessen source load, as I stated above. Manually check entries you want to read in the moment, and then rely on the Predictive Updates to eventually show you the rest of new releases.

**Comment by MuhammadSalmanGalileo** [comment]
i think it would be better to differentiate between auto update and manual update. for auto update it makes sense to use smart update because we were passively waiting, but for manual update most users will think it would update every entry. maybe make some settings to deactivate smart update for manual update?

**Comment by sln45** [comment]
I completely understand the need for discretion in terms of pinging host servers for updates, but I think this feature may not be working correctly and that's why it's so noticeable. For example, I just manually updated Shadows House (via MangaSee) and see a missed chapter on Jan 11 _and_ Jan 17. This is on the normal schedule for Shadows House, and so it's strange to see it not update at all.

**Comment by huffstler** [comment]
I've had this issue, and think I found the fix for it after poking around the settings.

More -> Settings -> Library -> Global Update Section -> Categories

Select the Categories you want to update automatically (whether that's an automatic or manual library update.) You'll see a checkbox. A second press on the checkbox will _exclude_ that category from being updated. You'll see an 'X' in the checkbox.

For good measure I've also turned off the 'Predict next release time' Smart update feature, but left all the others on. With these changes my 'Default' category will pull any updates when I pull to refresh (or on the daily automatic update) while not hammering the host for all the non-started and finished series that I have in other categories.

**Comment by rahaaatul** [comment]
At least show a notification to point out what is stopping mihon from updating the library. I thought something was wrong with my device. Thanks to @huffstler, this fixed the issue for me.

**Comment by melnation-com** [comment]
My recommendation
"Smart Update" (option somewheren in "Library")
4 options at the time of typing, I suggest turning ON "Skip unstarted entries"; I highly suggest turning OFF "Predict next release time" cause it influences when to check specific manga on global/category updates, it still tries to predcit whens the next release visually but now it's included in your "Automatic updates" settings.

"Automatic Updates" (option somewheren in "Library")
How often you like, shortest was "Every 12 hours"

"Categories" (option somewheren in "Library")
"Include:" Is needed to be "All" you do this by leaving nothing checked.
"Exclude:" This is simple, anything that has X will show here, usually Nhentai stuff or H manhua.
Basically anything that has X won't be updated, ✔ mark is redundant if not feels unlucky for me so I have nothing checked, Nhentai freezes entries, so there was never a need to "check" for new chapters, their new chapters are released like a Manga. In any case, "Default" should neither have X nor ✔.

"Auto-downoads" (option somewheren in "Downloads")
"Download new chapters" if turned on, downloads new chapters on manga you bookmarked.
"Categories" (option somewheren in "Downloads" different from "Library")
Same explanation as from "Categories" (option somewheren in "Library"), should automatically mirror there, but doublecheck just incase.

"Save as CBZ archive" (option somewheren in "Downloads")
saves the manga images as a zipped CBZ file, saving more space for your phone. It's up to you, but I guess many would love to leave this on.

Other options are also important but not as important as these to only be discover later.

**Comment by BrutuZ** [comment]
> "Save as CBZ archive" (option somewheren in "Downloads")
saves the manga images as a zipped CBZ file, _saving more space for your phone_.

Fake News. Mihon creates archives with no compression (images don't compress well anyway), they're akin to folders.

**Comment by melnation-com** [comment]
My recommendation
"Smart Update" (option somewheren in "Library")
4 options at the time of typing, I suggest turning ON "Skip unstarted entries"; I highly suggest turning OFF "Predict next release time" cause it influences when to check specific manga on global/category updates, it still tries to predcit whens the next release visually but now it's included in your "Automatic updates" settings.

"Automatic Updates" (option somewheren in "Library")
How often you like, shortest was "Every 12 hours"

"Categories" (option somewheren in "Library")
"Include:" Is needed to be "All" you do this by leaving nothing checked.
"Exclude:" This is simple, anything that has X will show here, usually Nhentai stuff or H manhua.
Basically anything that has X won't be updated, ✔ mark is redundant if not feels unlucky for me so I have nothing checked, Nhentai freezes entries, so there was never a need to "check" for new chapters, their new chapters are released like a Manga. In any case, "Default" should neither have X nor ✔.

"Auto-downoads" (option somewheren in "Downloads")
"Download new chapters" if turned on, downloads new chapters on manga you bookmarked.
"Categories" (option somewheren in "Downloads" different from "Library")
Same explanation as from "Categories" (option somewheren in "Library"), should automatically mirror there, but doublecheck just incase.

"Save as CBZ archive" (option somewheren in "Downloads")
saves the manga images as a zipped CBZ file, It's up to you, but I guess many would love to leave this on.

Other options are also important but not as important as these to only be discover later.

**Comment by melnation-com** [comment]
> > "Save as CBZ archive" (option somewheren in "Downloads")
> > saves the manga images as a zipped CBZ file, _saving more space for your phone_.
> 
> Fake News. Mihon creates archives with no compression (images don't compress well anyway), they're akin to folders. I love you.

I dont know what you are talking about 😉

**Comment by melnation-com** [comment]
> Fake News. Mihon creates archives with no compression (images don't compress well anyway), they're akin to folders. I love you.

I dont know what you are talking about 😉

**Comment by melnation-com** [comment]
> Fake News. Mihon creates archives with no compression (images don't compress well anyway), they're akin to folders. I love you.

I dont know what you are talking about. 

And; Flattered, thank you very much😉
