### ISSUE TITLE
Myreadimgmanga "NOT FOUND" issue

### ISSUE THREAD

**Issue by ad-co1997** [mihonapp/mihon#1371]
### Steps to reproduce

1. open a manga belonging to the "myreadingmanga" extension.
2. Open the Webview
3. Bypass cloudflare

### Expected behavior

1. open a manga belonging to the "myreadingmanga" extension. Then shows "failure bypass cloudflare"
2. Open the Webview 
3. Resolve captcha
4. pass cloudflare

### Actual behavior

1. open a manga belonging to the "myreadingmanga" extension. Then shows "failure bypass cloudflare"
2. Open the Webview but only thing is a "Not found" message 

### Crash logs

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 14 (SDK 34; build UP1A.231005.007.A057MUBU5CXH3)
Device brand: samsung
Device manufacturer: samsung
Device name: a05s (a05sub)
Device model: SM-A057M
WebView: Android System WebView 129.0.6668.100

--------- beginning of main
10-24 14:12:51.611  2366  2366 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
10-24 14:12:52.222  2366  2601 E app.mihon: No package ID 77 found for resource ID 0x770b000f.
10-24 14:12:52.223  2366  2601 E app.mihon: No package ID 77 found for resource ID 0x770b000f.
10-24 14:12:52.825  2366  2700 E chromium: [1024/141252.821266:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
10-24 14:12:55.456  2366  2953 E SQLiteLog: (284) automatic index on C(manga_id)
10-24 14:12:55.456  2366  2953 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-24 14:14:50.782  2366  3520 E chromium: [ERROR:quota_settings.cc(126)] Unable to compute QuotaSettings.
10-24 14:15:14.913  6151  6151 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
10-24 14:15:15.957  6151  6251 E app.mihon: No package ID 77 found for resource ID 0x770b000f.
10-24 14:15:15.962  6151  6251 E app.mihon: No package ID 77 found for resource ID 0x770b000f.
10-24 14:15:19.337  6151  6524 E SQLiteLog: (284) automatic index on C(manga_id)
10-24 14:15:19.337  6151  6524 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-24 14:15:21.326  6151  6949 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/app.mihon/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
10-24 14:15:21.326  6151  6949 E chromium: [ERROR:simple_index_file.cc(620)] Could not reconstruct index from disk
10-24 14:15:21.327  6151  6929 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/app.mihon/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
10-24 14:15:21.327  6151  6929 E chromium: [ERROR:simple_index_file.cc(620)] Could not reconstruct index from disk
10-24 14:16:53.066  6151  6151 E chromium: [ERROR:aw_browser_terminator.cc(166)] Renderer process (6922) crash detected (code -1).
10-24 14:17:54.029  6151  6151 E chromium: [ERROR:aw_browser_terminator.cc(166)] Renderer process (7986) crash detected (code -1).
10-24 14:18:24.253  6151  6151 E chromium: [ERROR:aw_browser_terminator.cc(166)] Renderer process (9662) crash detected (code -1).
10-24 14:18:45.883 10357 10357 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
10-24 14:18:46.327 10357 10393 E app.mihon: No package ID 77 found for resource ID 0x770b000f.
10-24 14:18:46.328 10357 10393 E app.mihon: No package ID 77 found for resource ID 0x770b000f.
10-24 14:18:50.489 10357 10621 E SQLiteLog: (284) automatic index on C(manga_id)
10-24 14:18:50.489 10357 10621 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

### Mihon version

0.16.5

### Android version

Android 14

### Device

Galaxy A05s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any extensions/content.
