### ISSUE TITLE
Sync all trackers' progress when manually set progress on 1 tracker

### ISSUE THREAD

**Issue by cuong-tran** [mihonapp/mihon#1379]
### Describe your suggested feature

In the case where 1 entry has multiple trackers, if user manually edit 1 tracker to change its progress, there should also sync that change across to other trackers as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
#390?
