### ISSUE TITLE
Add Face Unlock Support to App Lock

### ISSUE THREAD

**Issue by Akshar062** [mihonapp/mihon#1382]
### Describe your suggested feature

I would like to propose the addition of a face unlock feature for the app lock functionality in Mihon. Currently, the app offers fingerprint authentication, which is great, but integrating facial recognition would provide users with an additional, convenient option for unlocking the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The app uses devices lock settings and has no control over the process
