### ISSUE TITLE
extension categories

### ISSUE THREAD

**Issue by developer861** [mihonapp/mihon#1383]
### Describe your suggested feature

add a feature to categorize the extentions and search only in those extension 
for example manhwa, manga, comic....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #92

Search the existing issues before opening a new one
