### ISSUE TITLE
Weird gap above library after reindexing

### ISSUE THREAD

**Issue by sadboy889** [mihonapp/mihon#1387]
### Steps to reproduce

![Screenshot_2024-10-27-09-00-22-064_app mihon](https://github.com/user-attachments/assets/24f5d13c-6772-470f-ae73-0ee0c6eef341)

### Expected behavior

the layout is back to normal

### Actual behavior

it's weird 

### Mihon version

0.17.0

### Android version

9

### Device

Redmi Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Does this persist when you force close the app? Like, from the App Info screen or whatever that is called in your phone's OS?

**Comment by sadboy889** [comment]
> Does this persist when you force close the app? Like, from the App Info screen or whatever that is called in your phone's OS?


Uploading Screenrecorder-2024-10-27-10-11-48-493.mp4…

**Comment by sadboy889** [comment]
Uploading Screenrecorder-2024-10-27-10-11-48-493.mp4…

**Comment by Smol-Ame** [comment]
You hit send before it fully uploaded to GitHub, try again

**Comment by sadboy889** [comment]
> You hit send before it fully uploaded to GitHub, try again


https://github.com/user-attachments/assets/9d54d2f5-8fab-422a-b4e8-320898f76a3c

**Comment by hualiong** [comment]
I have the same situation, my device is Mi 6, the android version is also Android 9

**Comment by umutacetin** [comment]
In my case that weird gap happens after authenticating myself. (I used a security setting that asks me my fingerprint to open the app.)

**Comment by sadboy889** [comment]
https://github.com/user-attachments/assets/a23c5772-1f4c-4963-8e4e-82a6179e2993

from the latest preview release (r6990), the gap is there immediately without reindexing

**Comment by MajorTanya** [comment]
@sadboy889 why are you closing this?
