### ISSUE TITLE
Feedback: New Theme Disappoints

### ISSUE THREAD

**Issue by prem12321kumar** [mihonapp/mihon#1389]
### Describe your suggested feature

I have been using Dark Lavender for a long time, but I strongly dislike the new color theme. I really preferred the old one.

This includes the colors of:
- Overlay display for downloaded and unread chapters' count
- Toggle switch
- Resume button
- Genre tags
- Bottom menu bar
- Inverse fill

Could you please consider reverting to the old theme? It would be greatly appreciated.

### Other details

(G)Old:
![IMG_20241027_135344](https://github.com/user-attachments/assets/a9887ebc-51bf-4934-bb02-2aab304de4c6)

![IMG_20241027_134907](https://github.com/user-attachments/assets/ea65534c-e373-4bac-bcbe-beb73351b7b8)

![IMG_20241027_135755](https://github.com/user-attachments/assets/d9ebbff6-5e27-47d0-a919-8d67badade5a)

![IMG_20241027_135705](https://github.com/user-attachments/assets/934d700c-4edf-4228-9207-ad40e469af1a)

![IMG_20241027_135057](https://github.com/user-attachments/assets/09f41b90-9a3f-4b16-9424-bcb9afd23ff5)

![IMG_20241027_135520](https://github.com/user-attachments/assets/10c24188-f37d-49e9-98a2-7bd6eb88d2f9)

New:
![IMG_20241027_135312](https://github.com/user-attachments/assets/e26feb7b-3ede-418b-b51f-059e4d984dce)

![IMG_20241027_134942](https://github.com/user-attachments/assets/88976dce-794c-4a8e-8935-ebe3161c0e09)

![IMG_20241027_135826](https://github.com/user-attachments/assets/4bfbd2ee-35ef-4a7e-b63a-23b924c827b9)

![IMG_20241027_135722](https://github.com/user-attachments/assets/2497f5ad-da25-442a-883f-17dba3a70253)

![IMG_20241027_135113](https://github.com/user-attachments/assets/97c7df08-d8a0-4171-96cb-2d943e62c7b6)

![IMG_20241027_135533](https://github.com/user-attachments/assets/b8efa212-0819-45a6-86aa-d9f5f4d1d607)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by prem12321kumar** [comment]
@CrepeTF 
@AntsyLich

**Comment by Smol-Ame** [comment]
Don't ping, they'll look & comment if they want to.

But for now, gonna close to follow earlier ruling:
![image](https://github.com/user-attachments/assets/38ee47e0-5b83-464b-8a42-842b3f96cdc1)

**Comment by prem12321kumar** [comment]
Ohk
