### ISSUE TITLE
Indicator/Overlay text contrast issue

### ISSUE THREAD

**Issue by azeunkn0wn** [mihonapp/mihon#1391]
### Steps to reproduce

1. Select a theme (Midnight Dusk) 
2. enable overlays (download count, language, etc)
3. observe text

### Expected behavior

Text should have lighter color

### Actual behavior

Text is black, making it hard to read on darker background color 

### Mihon version

0.17.0

### Android version

Android 13

### Device

Poco F3

### Other details

HyperOS 1.0.3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by azeunkn0wn** [comment]
I tested switching between light and dark mode. It looks like the text in the overlays are following the brightness.

text turns white on light mode, and black on dark mode.

some themes are not affected like Lavender.

**Comment by MajorTanya** [comment]
Can you post a screenshot of the specific graphical bit you're talking about?

**Comment by azeunkn0wn** [comment]
> Can you post a screenshot of the specific graphical bit you're talking about?

this text/count was white before 0.17.0. Now it is black when in dark mode

![Screenshot_2024-10-28-07-38-43-280_app.mihon-edit.jpg](https://github.com/user-attachments/assets/ab4e3a78-0e35-4fd2-b5f7-2d783bb42af9)

**Comment by BrutuZ** [comment]
Seems somewhat related to #1389 which was closed based on this reply:
![image](https://private-user-images.githubusercontent.com/155411819/380483030-38ee47e0-5b83-464b-8a42-842b3f96cdc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzI4NzMsIm5iZiI6MTczMDA3MjU3MywicGF0aCI6Ii8xNTU0MTE4MTkvMzgwNDgzMDMwLTM4ZWU0N2UwLTViODMtNDY0Yi04YTQyLTg0MmIzZjk2Y2RjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QyMzQyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmRmNTM1ODMwM2ViZWY0MDg1ZWMyYTVmNGM5YzUwMTJjNWFlMmE1ZTYxZDc5ZjdlMjk4YjdlZjg0YWYxZDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t1pfBPEFzl0qQ0BcsBuKo8-CUulH2HYW9u4eZ2GYEHo)

**Comment by azeunkn0wn** [comment]
> Seems somewhat related to #1389 which was closed based on this reply:

Oh, that's too bad.
All of the themes are bad and the one I got used to is now messed up. 😔
I hope they return the original theme.

**Comment by MajorTanya** [comment]
> All of the themes are bad
Wow, that is quite the rude thing to put here. You could have just said you don't like them, but calling them bad is pretty out there. If they are so unbelievably bad, make your own that isn't and try to PR it yourself.
Themes won't be reverted back because their previous iterations had bad contrast ratios in several places.

**Comment by azeunkn0wn** [comment]
ofc it's just my opinion.

**Comment by ObesiD** [comment]
So to clarify, it's not a bug? I was going to raise the issue too, as I was having difficulty with the neon/black contrast ratio for Midnight Dusk.

**Comment by kattjevfel** [comment]
I too am using Midnight Dusk and it is quite hard to read with it being black on hot pink..
