### ISSUE TITLE
Surya scans HTTP Error 404

### ISSUE THREAD

**Issue by masdabazz** [mihonapp/mihon#140]
### Steps to reproduce

Update any entry from Surya Scans

### Expected behavior

Should update normally

### Actual behavior

Says HTTP Error 404. When you click on webview it says the page is not found. When you go on the extention tab and click webview it redirects you to suryatoons. Maybe change the sourece?

### Mihon version

0.16.1

### Android version

Andriod 12

### Device

Redmi Note 9

### Other details

The extensions repository takes me to the tachiyomi one which is closed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide support for extensions, go ask the people you got the extensions from.

**Comment by masdabazz** [comment]
I just used a backup from tachiyomi and uploaded it to mihon today. And since they have ceased development, what should I do?

**Comment by masdabazz** [comment]
I am very new to all this

**Comment by masdabazz** [comment]
I did not get it from anyone specific, I just downloaded the extension when I had tachiyomi and when I ported the backup to mihon, it came with it. Could you please give me any advice on how to do this myself? If you cannot.

**Comment by MajorTanya** [comment]
If this is a legacy Tachiyomi extension, you will need to find a third party repo that provides fixed and up to date extensions, that is all I can tell you.
