### ISSUE TITLE
Unable read any chapters after v.0.17 update 

### ISSUE THREAD

**Issue by Shravan-Shirodkar** [mihonapp/mihon#1403]
### Steps to reproduce

1 After installation of v.17 I got exited about new feature but after that when I was ready to read new chapter I am unable to see any chapters on my screen . The only thing that I was able to read is the scannslater banner like Asura Scans that it . 

### Expected behavior

I can only see partial chaper when I minimise the total size of actual chapter It should be solved properly 

### Actual behavior

So I deleted newest version and downgrade to v.0.16.4  but now with this I am unable to update my entries  

### Mihon version

0.17.0 | 0.16.4

### Android version

Android 10

### Device

Redmi 8A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Please actually check for duplicates before opening new issues. And also don't put source names/scanlator names, thanks.

**Comment by Shravan-Shirodkar** [comment]
Where can I find solution for this please tell me!!!

**Comment by Shravan-Shirodkar** [comment]
Thanku very much for the tip!

**Comment by Shravan-Shirodkar** [comment]
Problem is still not fixed!

**Comment by MajorTanya** [comment]
We know. @Smol-Ame literally told you that. Patience while we try to work out how this happens without any way to reproduce it.
