### ISSUE TITLE
Browse Doujindesu terjadi masalah, 

### ISSUE THREAD

**Issue by arrosyid7su** [mihonapp/mihon#1404]
### Steps to reproduce

1. Browse
2. Doujindesu (id) 
3. Populer/Last/Filter
4. Super Slow loading
5. not the popular one or not the last update

### Expected behavior

![Screenshot_20241029-173955](https://github.com/user-attachments/assets/c0c0d2d5-7f6b-40de-81ca-a2b5f46eccae)
![Screenshot_20241029-174009](https://github.com/user-attachments/assets/aca8530b-2c97-4c95-8da7-4a5fed15f4b8)
![Screenshot_20241029-174012](https://github.com/user-attachments/assets/cc9e44c5-042e-4b68-842f-81c1852128c1)

### Actual behavior

![Screenshot_20241029-173723](https://github.com/user-attachments/assets/6693b3d5-6c31-4495-bf89-a148079ef269)
![Screenshot_20241029-173519](https://github.com/user-attachments/assets/133b90e0-f99e-41de-91e8-6f0aaec3baa7)
![Screenshot_20241029-173448](https://github.com/user-attachments/assets/4fa5d534-ccc7-4470-b0da-12a5835961fb)
![Screenshot_20241029-173640](https://github.com/user-attachments/assets/cf7d71d9-ad42-4351-b647-2b537753433e)

SS from Tachiyomi 0.15.1

### Mihon version

0.17.0

### Android version

Android 13

### Device

Infinix gt 10pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
So many things wrong with this issue...
1. Don't post NSFW images
2. Mihon doesn't provide any extensions itself, it doesn't provide support for them, and it isn't affiliated with anyone that does.
3. Use English for filing issues.
4. Please remove these images while you're at it
