### ISSUE TITLE
Doujindesu browse Error

### ISSUE THREAD

**Issue by arrosyid7su** [mihonapp/mihon#1405]
### Steps to reproduce

1. Browse
2. Doujindesu (id)
3. Populer/Last/Filter
4. Super Slow loading
5. not the popular one or not the last update

### Expected behavior

1. Browse
2. Doujindesu (id) ![Uploading Screenshot_20241029-173955.jpg…]()
3. Populer/Last/Filter
4. the last update appears, the most popular appears, the filter has no errors

### Actual behavior

most popular, last updated, and filters, don't work

### Mihon version

0.17.0

### Android version

Android 13

### Device

Infinix gt 10pro

### Other details

normal in previous versions of mihon and in tachiyomi 0.15.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
You were already told in your deleted issue #1404 that Mihon doesn't do support for extensions. Go to whomever you're actually getting these from.
