### ISSUE TITLE
E-hentai extension bug

### ISSUE THREAD

**Issue by D1o2c3** [mihonapp/mihon#1406]
### Steps to reproduce

1. Going to e-hentai and selecting a manga.

2. Able so access manga and view details susch as genre and chapters 

3. When selecting chapters, an error shows up that there are no pages and so downloads also fails. Manga chapters however shows to have existing pages on the web view of extension.

### Expected behavior

Able to download and open chapters in e-hentai because there is are existing pages and the manga is not deleted 

### Actual behavior

Cannot open manga chapters and download chapters with a "no pages" error even though there are existing pages and manga is not deleted 

### Mihon version

0.17.0

### Android version

Android 11

### Device

RealMe c25s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions itself, it doesn't provide support for them, and it is not affiliated with any extension providers. Go ask your extension maintainers for support in fixing it.
