### ISSUE TITLE
Add button to download all chapters in the download menu

### ISSUE THREAD

**Issue by LilleAndersen** [mihonapp/mihon#141]
### Describe your suggested feature

As it is now you can only download all unread chapters or Next chapter variants. If you're already read a series and you'd like to download it you have to mark it as unread and then do download unread.

### Other details

Tachiyomi had this feature in before removing it in version 15.0
![Screenshot_2024-01-19-23-35-30-40_afd66b7916d19a60815f56273408b73e](https://github.com/mihonapp/mihon/assets/71332089/2808cdd2-7c53-4dea-b2d0-0de569ba499b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Hint: There's a Select All button when you select any chapter, you can then tap the download button ~~and bully the server with thousands of requests in the process~~

**Comment by AntsyLich** [comment]
No
