### ISSUE TITLE
No Images Displayed on E-hentai Source

### ISSUE THREAD

**Issue by Norton00** [mihonapp/mihon#1410]
### Steps to reproduce

1. Open the app and select the E-hentai source.

2. Open a comic chapter.

3. The page displays “No pages found”.

### Expected behavior

The comic content should display normally.

### Actual behavior

“No pages found”message is shown.
![Uploading Screenshot_2024-10-30-11-39-29-004_app.mihon-edit.jpg…]()

### Mihon version

0.17.0

### Android version

Android 14

### Device

Redmi K70

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1. Learn to search and read before opening a new issue & acknowledging that you searched when you clearly didn't.
2. Mihon doesn't have, associate, or provide any extensions.
3. Not an app-related issue
