### ISSUE TITLE
Unable to update library 

### ISSUE THREAD

**Issue by Shravan-Shirodkar** [mihonapp/mihon#1411]
### Steps to reproduce

1 Open mihon 
2 select Update button 
3 swip down / click to update .

### Expected behavior

After clicking or swip down in update section the whole library should be updated but it's not happening 

https://github.com/user-attachments/assets/babb5ff9-5510-4f17-802c-777bc8dab2d3

### Actual behavior

It should able to update automatically or manually 

### Mihon version

0.17.0 

### Android version

10

### Device

Redmi 8A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Working as intended, learn more about Smart Updates & how it reduces unnecessary requests + spreads out your Library Updates over a predicted release pattern. Also check out the Upcoming calendar

https://mihon.app/docs/faq/updates/smart

https://mihon.app/docs/faq/updates/upcoming
