### ISSUE TITLE
Mihon Library Sorting development (suggestions) PLZ READ

### ISSUE THREAD

**Issue by jhoney0102** [mihonapp/mihon#1420]
### I wanted to suggest some new app features that can contemplated, and possibly be reflected and be updated in the future.

For now, it seems like users can only set keywords for categories, and only sort my library under those generated keywords.

The issue i wanted to submit today is whether categorization of books can be a bit more specific?
The thing about Japanese manga and Korean webtoons is that they are mostly updated daily, and yes there is a function to
"sort books by latest updates", however i think it will be more neat if you can make subsections in each library so it looks cleaner.

I tried my best to draw out the feature... You'll get the gist.

### **1. Daily update sorting (Mon,Tues,Weds.. with probably a subsection of each in one page)** 
![123](https://github.com/user-attachments/assets/040c0cf9-348d-4093-a784-189dd96d295a)

If abovementioned idea could be developed further, it would be amazing, and will suggest good readability on locating books in my library.

Much appreciated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
First of all, thank you for enjoying Mihon. A few things before I address your actual requests:
1. We really don't need to know what sources you use (and actually strongly prefer if you don't name/show any of them). It would be preferable if you could remove those source names as they're completely irrelevant.
2. We don't need screenshots of your sources or your categories for what's in your request. Considering how much space those two screenshots take up on the page, it would be nice if you could remove those two from your issue.
3. _For future requests_: Only request one (1) thing per issue, it makes our job of sorting through them all a lot easier. Also, put the actual feature you're requesting in the title, not some vague "Please read". It makes finding specific issues later on a nightmare. For this issue, leave it as it is, but do edit for points 1) and 2) above.

Your first suggestion, categorising by weekday of update, requires a sort of grouping of titles _inside_ a category, which is not a concept Mihon has, nor one I believe would be added. You can refer to the new "Upcoming" feature introduced in Mihon 0.17.0 to see when Mihon has predicted new chapters for certain releases in a Calendar with a list of each title listed beneath. Do you have a good reason why that would not be sufficient?

Your second suggestion, categorising by extension/source, has already been denied before (see #1108 for example). If you need to look at things in your library from one source only, using the source name in the search box already filters for that source. If you wanted to make source-by-source categories, you could make the new category, search for the source name, select all the titles Mihon finds, then select adding them to the source's category you made.
Consider this part of the request denied.

**Comment by jhoney0102** [comment]
> 1. Got it, sorry i'm new to all these github stuff, please understand my noob mistake. I'll be editing my post.
> 2. Ok, i initially thought it would be quite challenging to verbally explain precisely what my wanted feature looked like, as English is not my first language. I've deleted the screenshots as well.
> 3. Sorted it, I've amended the title a bit more specifically. I'll leave this post as query 1) and forget about query 2). I've deleted the second question.


> Your first suggestion, categorising by weekday of update, requires a sort of grouping of titles inside a category, which is not a concept Mihon has, nor one I believe would be added. You can refer to the new "Upcoming" feature introduced in Mihon 0.17.0 to see when Mihon has predicted new chapters for certain releases in a Calendar with a list of each title listed beneath. Do you have a good reason why that would not be sufficient?

> A) The new calendar and upcoming feature definitely provides a good sense of when the new chapter will be released. However, the issue I'm struggling with is that I wish to separate categorisation more specifically. For example, let's say I mainly read two genre of libray. Japanese Manga/Korean webtoons. 

Even within Korean webtoons, there are 2-3 different platforms. So, as of now, I've categorised them by platforms
**eg. Category 1) Japanese Manga
Category 2) Korean Webtoon Platform A 
Category 3) Korean webtoon Platform B 
Category 4) Korean Webtoon Platform C.**

This is great so far, however, i wanted to sort again by daily updates within this categorisation (with a subsection if possible)
eg. Japanese Manga
(Mon: Manga A, B, C, D.... Tues: Manga A, B, C, D.....)

Korean Webtoon Platform A
(Mon: Manga A, B, C, D.... Tues: Manga A, B, C, D.....)  

Korean Webtoon Platform B
(Mon: Manga A, B, C, D.... Tues: Manga A, B, C, D.....)

If you get what i precisely mean. 

In the mihon library, so many books are just scattered in one big chunk of category page from various extension website.
I thought it would be nice at least to be able to organize the books again in one page of category. (doesn't matter if i had to sort them manually or can be sorted automatically). However, I assume this feature would be impossible in the future updates then?

**Comment by MajorTanya** [comment]
As a side note, when you use the > you put it before the things _someone else_ has said, and not before your own reply. I'm currently unable to look into this further but I'll leave the issue open.

**Comment by jhoney0102** [comment]
Cheers. hope there could be improvement. Wish the best, have a great day

**Comment by AntsyLich** [comment]
No
