### ISSUE TITLE
Private extension installer

### ISSUE THREAD

**Issue by Gamefire238** [mihonapp/mihon#1422]
### Describe your suggested feature

Can private extension installer be used in stable version?

### Other details

Just asking😄 and sorry I use a translator

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. Move to beta if you want to use it

**Comment by Gamefire238** [comment]
Okay, looks like it's only for the Beta version😔
