### ISSUE TITLE
I can't link shikimori account to mihon

### ISSUE THREAD

**Issue by Frech4k** [mihonapp/mihon#143]
### Steps to reproduce

I go to the settings, then to the “tracking” tab, then click on the “shikimori” icon.

### Expected behavior

after all the steps described above, I should just log into my account and track the manga, like for example I can do with MAL

### Actual behavior

A tab opens with the text: "The requested redirect uri is malformed or doesn't match client redirect URI"

### Mihon version

0.16.1

### Android version

android 11

### Device

mi 9t

### Other details

I think this may be because shikimori recently did something to their site address.  
P.S. I am writing using Google translator, sorry for any errors and misunderstandings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ZerOri** [comment]
> Update: I need to wait 1 day before i can make a new api client

Bangumi also has the same issue.
