### ISSUE TITLE
Bulk Trust Extensions

### ISSUE THREAD

**Issue by KrispeeIguana** [mihonapp/mihon#1430]
### Describe your suggested feature

I install most of the extensions from the default repo. This is great for extension diversity, that is until that time of the year when half or even all of the extensions need an update. I understand that trust should definitely not be a single button-press for everything, but at least have a repo trust system.

### Other details

I thought I saw something similar to this request, but when I tried searching issues I got nothing. Maybe it was in an old Tachyomi issue or a reddit thread.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
What the hell is the default repo? Mihon doesn't associate or provide any repos, much less have a default one.

And there is already is trust by repo. If all your extensions were installed from a specific repo and that repository is also added to your extension repos list they are automatically trusted. (If it's not visually updating restart the app)

**Comment by Animeboynz** [comment]
Well he check the box saying he was on 0.17.0
Also duplicates of #320 #884 #487

**Comment by KrispeeIguana** [comment]
My bad with the repo part, I probably just forgot exactly where it came from. I've used it since I've started using this app. 

Either way, the automatic trust feature is not functioning on my Samsung Galaxy Note 9

**Comment by KrispeeIguana** [comment]
That is unless there is a toggle for that that I haven't found yet hidden in the settings

**Comment by AntsyLich** [comment]
Remove the repo from settings and add it back. Restart the app afterwards. If it doesn't work complain to whoever owns the repo
