### ISSUE TITLE
Invalid Location during download, but not during backup or autobackup. 

### ISSUE THREAD

**Issue by Rjv-RY** [mihonapp/mihon#1431]
### Steps to reproduce

1. Create custom folder/choose location for storage.
2. Download from any title from any source.
3. Works fine for months.
4. Haven't downloaded anything since update v0.17.0.
5. Try downloading.
6. 'Invalid location:name/of/folder/here' notification. 

### Expected behavior

When created and used, the new folder/location should have 

1. A downloads folder with sources and titles.
2. An autobackup folder(s)?
3. A local folder. 

### Actual behavior

That was the case for all the time, till the recent update I think. Now, everytime I try to download something, it creates a new empty downloads folder while not accessing the old one, and says 'invalid location'.

The new downloads folders are created like 2-3 folders per download attempt, indexed like 'downloads(1)', 'downloads(2)' and so on. They are all created and remain empty.

The same is for autobackup folders in terms of indexing/name, new folders are created each backup. But they aren't empty, they have backup files.

The original downloads folder has all the previously downloaded titles. But even after giving access to it using the storage settings, the downloaded titles don't appear in the library.

All I have noted is that these errors are recent. 

### Mihon version

0.17.0

### Android version

Android 10

### Device

Samsung S9+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Closing as user-error in storage location choice, come to the Mihon Discord support channel for help/troubleshooting.
