### ISSUE TITLE
Category not updating

### ISSUE THREAD

**Issue by viveksampath3** [mihonapp/mihon#1433]
### Steps to reproduce

Library -> a category -> Update -> nothing happens

### Expected behavior

When u update a category, all comics in that category should update and have no. of new chaps on their covers.

### Actual behavior

Previously, only frequently read comics(around 70) would update, not every comic in the category. 
Understandable cuz i have a lot in a category. 
Now, it doesn't even update frequently read comics, I have update each one manually.

sorry for poor quality, but it conveys the issue.

https://github.com/user-attachments/assets/164ee6e0-b1e5-4b26-969b-d40ffefa7208

### Crash logs

App version: 0.17.0 (standard, 38d5fc9, 8, 2024-10-26T17:39:14Z)
Android version: 12 (SDK 31; build SKQ1.211019.001 test-keys)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: excalibur (excalibur_in)
Device model: Redmi Note 9 Pro Max
WebView: Android System WebView 130.0.6723.58

i shared twice via share crash logs option, they all have same data

### Mihon version

17

### Android version

Android 12

### Device

Redmi note 9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Nothing is wrong with it. Join our discord for further support
