### ISSUE TITLE
Trouble with opening chapter and downloading 

### ISSUE THREAD

**Issue by Maromy77** [mihonapp/mihon#1437]
### Steps to reproduce

1.the first thing is that when i open a chapter it will not work at all it will just show a faded green circle and it will not work 
2. Downloading 20 chapters took over 1 day to be downloaded 

### Expected behavior

1.the chapter usually open immediately 
2.the downloading usually maximum 2hours not a full day and I made sure I was connected to the Internet 

### Actual behavior

1. Chapter doesn't work anymore .
2. Downloads take a very long time .

### Crash logs

![Screenshot_20241103_023304_Samsung Internet](https://github.com/user-attachments/assets/2263f2dc-9ddc-4d39-8b06-708a51049ef5)
![Screenshot_20241102_025605_Mihon](https://github.com/user-attachments/assets/62fb1e20-8b85-4c50-98f9-916e1686c152)
![Screenshot_20241102_025917_Mihon](https://github.com/user-attachments/assets/c0c1417b-c2b6-47e0-a807-91aa20f2269b)

### Mihon version

0.17.0

### Android version

Android 11

### Device

Samsung galaxy A23 

### Other details

That's all thank u 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not an app issue. Complain to whoever you got the extensions from

**Comment by cuong-tran** [comment]
Try switch to internal storage.
