### ISSUE TITLE
Search ongoing load circle indication has gone in newest beta (screen record attached)

### ISSUE THREAD

**Issue by trancephormer** [mihonapp/mihon#1438]
### Steps to reproduce

Search in any extension.
No visual indication until search finishes and then results pop up. 
Screen record attached[

https://github.com/user-attachments/assets/24e2dda7-aff6-4566-853c-0e92e63c7f45

](url)

### Expected behavior

Visual load circle displays while search is ongoing 

### Actual behavior

It doesn't show up. 

### Mihon version

App version: 0.17.0-6990

### Android version

A14

### Device

Moto G85

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
can't reproduce
