### ISSUE TITLE
Comment view feature

### ISSUE THREAD

**Issue by jhoney0102** [mihonapp/mihon#1439]
### Describe your suggested feature

Hello, I was wondering if devs are planning on applying "comment viewing feature" on mihon?
For eg, in specific extension websites, there are comments of people talking about the current episode.

Was wondering if feature can be developed and also be seen on mihon app?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
no
