### ISSUE TITLE
Parallel downloads

### ISSUE THREAD

**Issue by FroggerHH** [mihonapp/mihon#1442]
### Describe your suggested feature

I can't access internet all the time and read offline, so I download everything I might like to read and it takes a lot of time because mihon is downloading each chapter one by one and parallel downloads can solve this problem. 

P.S. Unfortunately I don't know Kotlin language, otherwise I would implement it myself and make a pull request. And sorry for my English...

### Other details

I think this feature should be turned off by default. 
Maximum parallel downloads should be configurable and be equal to 5 by default.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon downloads 3 images from 5 source at a time (that's 15 images). Keep your eggs in different basket.
