### ISSUE TITLE
Android 14 system phones cannot update/download plugins

### ISSUE THREAD

**Issue by dty285767** [mihonapp/mihon#1447]
### Steps to reproduce

Click to download/update plugin

### Expected behavior

Successfully downloaded/updated plugin and application installation program pops up

### Actual behavior

Display waiting, downloading, and then there is no follow-up

### Mihon version

0.17.0

### Android version

Android 14

### Device

OnePlus Ace 3V

### Other details

My other phone，Realme GT Neo  Android 13。
The test can be used normally。
I have looked up this question many times, but there is no result. I request your help，Thanks。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
I doubt this is an Android 14 issue, considering my phone uses a variant of Android 14 and has no problems installing extensions.

**Comment by Smol-Ame** [comment]
Come to the Mihon Discord support channel for basic troubleshooting of chinaphone issues.
