### ISSUE TITLE
Mihon sometimes stops detecting installed extensions

### ISSUE THREAD

**Issue by lord-ne** [mihonapp/mihon#145]
### Steps to reproduce

Not sure yet. This just happens occasionally, and persists until app restart.

### Expected behavior

When opening the app, installed extensions should be shown in the "extensions" tab.

### Actual behavior

Installed extensions are not shown in the "extensions" tab (all extensions from repo show a download button instead of a gear icon), and "sources" tab only shows local source. "Migrate" tab shows "extension not installed" for every extension. Downloaded chapters are still readable, but non-downloaded chapters cannot be read.

Fixed by restarting app, but this has happened to me multiple times in the last few days.

### Mihon version

Observed in stable 0.16.0 through 0.16.3

### Android version

Android 13 (EDIT: Specifically, MIUI 14, Xiaomi.eu build, rooted with Magisk, Shizuku installed)

### Device

Poco F5

### Other details

I know this isn't a lot of details, I'm mainly posting so someone can tell me which logs to pull next time this happens so we can actually diagnose this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lord-ne** [comment]
Still experiencing in 0.16.3

**Comment by AntsyLich** [comment]
Are you still facing this? Can you check preview build?

**Comment by WorldEnd-Formatting** [comment]
I'm still facing this (0.16.5). I'll check preview

**Comment by lord-ne** [comment]
I'm still facing this (0.16.5). I'll  check preview.

**Comment by lord-ne** [comment]
Confirmed this is still happening on the latest preview (r6674)

**Comment by lord-ne** [comment]
I'm on MIUI, not HyperOS. The battery optimizations were already disabled. I went into the permissions section and enabled Mihon to get info about installed apps "always" (the default was "only when running"). 

I'll update if I continue to see the issue, and if I don't see it within a few days I'll close this bug.

**Comment by gogito** [comment]
I also have the same issue on HyperOS

**Comment by lord-ne** [comment]
On MIUI 14 (at least on my build), the way to turn on "always allow" for accessing the app list is actually Settings -> Apps -> Permissions -> Permissions -> (Permissions tab) -> Get info about installed apps -> Mihon -> (Select "always allow"). That is, it doesn't show up under the app info permission settings, you have to go find the list of all the permissions instead.

After doing those steps the issue hasn't occured for me (it's been a few weeks), so I assume that fixed it.
