### ISSUE TITLE
In game Split screen support

### ISSUE THREAD

**Issue by XDKOZ** [mihonapp/mihon#1452]
### Describe your suggested feature

![Uploading Screenshot_20241107_144500_c28519d624689b8d548e2809af584b0c.jpg…]()

### Other details

Like as u can see there's some apps that supports split screen so u guys might make mihon split screen supported (if not possible then add a option for floting screen I mean that split screen actually a floting screen if it's in game)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by XDKOZ** [comment]
![Uploading Screenshot_20241107_144500_c28519d624689b8d548e2809af584b0c.jpg…]()

**Comment by MajorTanya** [comment]
You didn't let GitHub finish the upload of your screenshot, twice now.

**Comment by Smol-Ame** [comment]
Pretty sure it's up to your device's/device brand's capabilities/features/settings?

![Screenshot_20241107_175826_Mihon.png](https://github.com/user-attachments/assets/610f6174-838f-4ca3-8778-d3c34720f31f)

![Screenshot_20241107_175817_Mihon.png](https://github.com/user-attachments/assets/02b7ebc5-e7ad-41bc-b1fe-bf0e414b628e)

![Screenshot_20241107_175841_Mihon.png](https://github.com/user-attachments/assets/69fbb2af-76f1-4ce8-96df-067590f273f9)

![Screenshot_20241107_175852_Mihon.png](https://github.com/user-attachments/assets/f037721e-9762-443c-8267-29b90f858ba7)

**Comment by AminurAlam** [comment]
@xdkoz you can force all apps to support split screen in android's developer options

**Comment by Smol-Ame** [comment]
^ Another valid option (if applicable)

Closing as user error/user device issue

**Comment by XDKOZ** [comment]
@AminurAlam 
here
@Smol-Ame friend 💘 here's a screenshot and if amazon and cap cut supports then I think mihon has a chance (if it has)
Oh ya another thing my phone can open everything in split screen but this some apps just has support of floting screen
And split screen in game is pretty bad to use so I hope you'll get it what I mean


![Screenshot_20241109_163039_c28519d624689b8d548e2809af584b0c](https://github.com/user-attachments/assets/a8b49959-3492-4412-99af-678841c1f237)

**Comment by AminurAlam** [comment]
thats not how floating windows work

goto recent apps and long press on mihon

**Comment by XDKOZ** [comment]
@AminurAlam That's how it works in my phone 😄 there another way...let me show you

-----
I used chat gpt and it says
- To add a feature in your app that allows more apps to use game PiP mode, here are a few approaches to consider:

1. Use Android’s PiP API: If your app is targeting Android 8.0 (Oreo) and above, you can leverage Android’s Picture-in-Picture API. This API allows apps to enter PiP mode programmatically. You can create a custom interface that enables selected apps to launch in PiP within your app, depending on permissions and compatibility. Google’s PiP documentation explains this in detail.


2. Create a Floating Window or Overlay: If full PiP isn’t feasible, consider adding a floating window or overlay mode. Using WindowManager and SYSTEM_ALERT_WINDOW permissions, you can allow supported apps to appear in a floating mode that simulates PiP. Note, though, that this will require user permission for overlay, as it affects the app's battery usage.


![Screenshot_20241110_091220](https://github.com/user-attachments/assets/0ba56b03-d9d1-4751-9528-9e6307625aca)
