### ISSUE TITLE
Invalid location 

### ISSUE THREAD

**Issue by thisas200416** [mihonapp/mihon#1458]
### Steps to reproduce

After tge new update, when I start to download chapters it says "Invalid location"

how to fix it?
![Screenshot_20241109_073931_app mihon](https://github.com/user-attachments/assets/3f6fbee8-f66e-43c0-a6af-2d7a14966186)

### Expected behavior

This should happen whenever start downloading chapters

### Actual behavior

We can read online but can't download and read offline

### Mihon version

0.17.0

### Android version

Android 10

### Device

Huawei Nova 5T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Come to the Mihon Discord support channel for basic questions/troubleshooting instead
