### ISSUE TITLE
Customizable touch zones

### ISSUE THREAD

**Issue by F-shark** [mihonapp/mihon#1464]
### Describe your suggested feature

Make touch zones more customisable,
Let people place lines on where they want their touch zones to be eg if I wanted most of the touch screen to be next and a small bit at the for the menu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Highly doubt this would ever be done, the behind the scenes of this would be a nightmare. Use what's there and cope.
