### ISSUE TITLE
Problem with Anilist tracking

### ISSUE THREAD

**Issue by ch13696** [mihonapp/mihon#1470]
### Steps to reproduce

1. Go to Settings > Tracking
2. Choose Anilist
3. Login to Anilist and authorize Mihon

### Expected behavior

After authorizing Anilist it should check off in the list and start tracking.

### Actual behavior

After authorizing Anilist it doesn't check off. Therefore it doesn't track. After attempting to choose Anilist again the browser opens and then quickly closes.

### Crash logs

App version: 0.17.0-7001 (standard, 9df21583d, 8, 2024-11-09T21:19:01Z)
Android version: 14 (SDK 34; build UP1A.231005.007.S928USQS3AXI1)
Device brand: samsung
Device manufacturer: samsung
Device name: e3q (e3qsqw)
Device model: SM-S928U
WebView: Android System WebView 130.0.6723.86

Problematic extensions:
- Kavita
  Installed: 1.4.15 / Available: ?
  Obsolete: true

--------- beginning of main
11-10 06:41:48.932 31655 31729 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
11-10 06:42:06.599 31655 15180 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/app.mihon.debug/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
11-10 06:42:06.599 31655 15180 E chromium: [ERROR:simple_index_file.cc(620)] Could not reconstruct index from disk
11-10 06:42:06.886 31655 31655 E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (15181) crash detected (code -1).
11-10 06:42:09.120 31655 31655 E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (15369) crash detected (code -1).
11-10 06:42:10.689 31655 31655 E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (15477) crash detected (code -1).
11-10 06:42:22.338 31655 31655 E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (15817) crash detected (code -1).
11-10 06:42:24.163 31655 31655 E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (15927) crash detected (code -1).
11-10 06:44:16.967 31655 31655 E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (16499) crash detected (code -1).
[mihon_crash_logs.txt](https://github.com/user-attachments/files/17691834/mihon_crash_logs.txt)

### Mihon version

Beta r7001

### Android version

Android 14

### Device

Samsung Galaxy S24 Ultra

### Other details

This was first noticed on my Boox Onyx Ultra Tab C running Android 11. I've tested it on my Samsung Galaxy S24 Ultra and it's the same issue. I then proceeded to downgrade from the beta version to 0.17.0 and the same problem persists.

Revoking permissions in Anilist also doesn't work. When choosing Anilist afterwards it will ask to authorize and then proceed to the same problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
AniList is having issues on their end, check their annoucements/Discord first, or come to the Mihon Discord support channel for basic issues/troubleshooting.

**Comment by ch13696** [comment]
Thank you. That explains why it's happening on multiple versions of Mihon and recently started happening. I'll join both Discords and keep track from there.
