### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Key-explanation** [mihonapp/mihon#1471]
### Steps to reproduce

1. Download manhwa18 extension 
2. Open it
3. HTTP 404 error 
4. But webview works

### Expected behavior

Should be able to read manhwa without problem 

### Actual behavior

The website shows 404 error

### Mihon version

0.17.0

### Android version

Android 11

### Device

Vivo Y15 

### Other details

It works in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Can't believe it's not our problem

Mihon doesn't have, associate, or provide any extensions.
