### ISSUE TITLE
Crash when using the "mark above as read" button

### ISSUE THREAD

**Issue by CatGamer23** [mihonapp/mihon#1479]
### Steps to reproduce

1. Press & hold on first chapter
2. Press the Check mark with the down arrow button
3. Instant crash

### Expected behavior

Shouldn't crash

### Actual behavior

It crashes

### Crash logs

![Screenshot_20241113-005000](https://github.com/user-attachments/assets/32676916-6ba7-4631-9e5c-20ab10c8e73b)

### Mihon version

0.17.0

### Android version

Android 15

### Device

Google Pixel Tablet/Google Pixel 7

### Other details

This bug is repeatable between reinstall, different devices, and different manga, so it isn't a me problem.

From what I can tell, whoever implemented the feature simply didn't check if the selected item was the first element in a list, and it subtracts one and gets a invalid index, then tries to access the, now invalid, index.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Fixed in this commit https://github.com/mihonapp/mihon/commit/f508d10ad13560d7316df8642bc93fe66c05b9a8 wait for another release or switch to preview
