### ISSUE TITLE
problem updating library

### ISSUE THREAD

**Issue by Key-explanation** [mihonapp/mihon#148]
### Steps to reproduce

1. Update library
2. An update error pops up showing that there is no chapter found

### Expected behavior

The library should be updated without any error

### Actual behavior

"No chapter found" error pops up

### Crash logs

App version: 0.16.1-6454 (standard, 6018aa99e, 2, 2024-01-17T19:32Z)
Android version: 11 (SDK 30; build RP1A.200720.012 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 1901 (1901)
Device model: vivo 1901
WebView: Android System WebView 120.0.6099.210

--------- beginning of main
01-20 07:10:29.565 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:10:29.604 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:10:29.631 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:10:29.633 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:10:38.374 27872 29972 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
01-20 07:10:39.978 27872 29972 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
01-20 07:10:40.074 27872 27872 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (6991) crash detected (code -1).
01-20 07:10:40.079 27872  7165 E Surface : freeAllBuffers: 19 buffers were freed while being dequeued!
01-20 07:10:40.090 27872  7156 E Surface : freeAllBuffers: 19 buffers were freed while being dequeued!
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: onViewTypeAvailable 
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: java.lang.NullPointerException: Attempt to get length of null array
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.Parcel.createException(Parcel.java:2371)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.Parcel.readException(Parcel.java:2354)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.Parcel.readException(Parcel.java:2296)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at WV.zt.c(chromium-TrichromeWebViewGoogle6432.aab-stable-609921033:59)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at org.chromium.components.autofill.AutofillProvider.onServerPredictionQueryDone(chromium-TrichromeWebViewGoogle6432.aab-stable-609921033:69)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.MessageQueue.next(MessageQueue.java:339)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.os.Looper.loop(Looper.java:208)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at android.app.ActivityThread.main(ActivityThread.java:8192)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at java.lang.reflect.Method.invoke(Native Method)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
01-20 07:12:50.008 27872 27872 E cr_AutofillHintsService: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
01-20 07:13:30.287 27872 27872 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (7539) crash detected (code -1).
01-20 07:20:37.461 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:20:37.520 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:20:41.967 27872 29972 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
01-20 07:20:42.293 27872 29972 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
01-20 07:20:42.456 27872 27872 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (10335) crash detected (code -1).
01-20 07:20:42.460 27872 10528 E Surface : freeAllBuffers: 19 buffers were freed while being dequeued!
01-20 07:20:42.464 27872 10519 E Surface : freeAllBuffers: 19 buffers were freed while being dequeued!
01-20 07:34:24.740 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:34:24.811 27872 29972 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
01-20 07:34:31.611 27872 29972 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
01-20 07:34:31.639 27872 29972 E chromium: [ERROR:image_reader_gl_owner.cc(306)] no buffers currently available in the reader queue
01-20 07:34:31.887 27872 27872 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (17970) crash detected (code -1).
01-20 07:34:31.902 27872 18137 E Surface : freeAllBuffers: 19 buffers were freed while being dequeued!
01-20 07:34:31.917 27872 18143 E Surface : freeAllBuffers: 19 buffers were freed while being dequeued!

### Mihon version

0.16.1

### Android version

Android 11

### Device

Vivo y 15

### Other details

![Screenshot_20240120_074339](https://github.com/mihonapp/mihon/assets/103259523/b0c7f7a8-6eb5-4343-a0d6-9bcd80bd3d54)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We don't and won't provide support for extension issue
