### ISSUE TITLE
Split Vertical Pages

### ISSUE THREAD

**Issue by purepani** [mihonapp/mihon#1483]
### Describe your suggested feature

Currently, there is a feature to split wide pages for the case when art is meant to be on two manga pages.
There is a rarer case when some manga is concatenated together vertically:
![Screenshot_20241113-235649](https://github.com/user-attachments/assets/2e1f5067-73c5-4370-8343-fcdfe3e19a51)
The case of this manga has every page of the manga in one long strip

In this case, it would be good if there were some way to split them as it's inconvenient to read in vertical format.
This certainly isn't the easiest thing to detect but I had a view ideas:
There's often a black bar, so this could be used to detect.
There could be a user-set split for the pages since usually the pages would be the same size. This wouldn't be too much of a problem to ask the user to set manually I think, since the cases where this happens will be a bit uncommon. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This setting exists for newly downloaded chapters. Downloads > Split Tall Images.
