### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by jixiuy** [mihonapp/mihon#1491]
### Steps to reproduce

Hello author, I would like to ask why it is useless to switch the system language after I hit the debug package, which is always English.

### Expected behavior

null

### Actual behavior

null

### Mihon version

0.17.0

### Android version

Android11

### Device

RedmiK40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Remove this line and rebuild https://github.com/mihonapp/mihon/blob/5a91d5c611faacacf5cf6fa135e93863c0332475/app/build.gradle.kts#L104
