### ISSUE TITLE
The problem of updating the library

### ISSUE THREAD

**Issue by saoRAKEYA722** [mihonapp/mihon#1492]
### Steps to reproduce

When I try to refresh the page, I get this error.
![upload_2024_11_17_23_59_01_383](https://github.com/user-attachments/assets/5ddb5e1d-f8d0-4635-bdfe-6cd72ee07d76)

### Expected behavior

.

### Actual behavior

And page don't refreshed

### Crash logs

.

### Mihon version

0.17.0

### Android version

Android 14

### Device

Samsung Galaxy A16 5G

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [ ] I have updated all installed extensions.
- [ ] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue
