### ISSUE TITLE
Triggered the crash

### ISSUE THREAD

**Issue by gankumangcao** [mihonapp/mihon#1493]
Sorry for my poor English, I used Google Translate。Phone: Xiaomi 14 ultra, Android 14，I'm updating the comics，Clicking on the status bar to jump to Mihon triggers the crash

![mihon_crash_logs.txt](https://github.com/user-attachments/files/17792684/mihon_crash_logs.txt)

**Comment by MajorTanya** [comment]
Duplicate of #282
