### ISSUE TITLE
After new update i cant download anymore

### ISSUE THREAD

**Issue by Wobbles12** [mihonapp/mihon#1496]
### Steps to reproduce

[

https://github.com/user-attachments/assets/85ce8219-9781-4c59-9989-f03a50d10c4a

](url)

### Expected behavior

It should download without no problem

### Actual behavior

When you clicked download it will go pause

### Mihon version

0.17

### Android version

Android 10

### Device

Huawei Nova 7 JEF-Nx9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Come to the Mihon Discord support channel for troubleshooting. But don't put this video since it will violate the server's rule 10.

Mention your issue in there
