### ISSUE TITLE
Select all chapters in-between two selected ones

### ISSUE THREAD

**Issue by nirodhvana** [mihonapp/mihon#1498]
### Describe your suggested feature

It should work like this:
For eg: i want to select chapters from 1 to 200. Then the steps should be:
1. Select chapter 1 and 200
2. click on the select option button for this feature.
3. the chapters in between 1 and 200 also get selected.
4. I can perform various action on them like downloading or marking read

### Other details

Should be detailed enough :)
No rush thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
You can hold tap chapter 1 and 200 and it'll select in-between
