### ISSUE TITLE
Auto/Smart Detection of Reading Mode

### ISSUE THREAD

**Issue by KenzKD** [mihonapp/mihon#150]
### Describe your suggested feature

Automatically set the Reading Mode based on what the user is reading.

For Example,

Manga -> Paged (Right to Left)
Comics -> Paged (Left to Right)
Webtoon -> Long Strip

Ideally this comes with default options that can be can be configured manually in the More -> Settings->"Reader" Menu

This is idea is based on the smart detection feature that used to be in MangaRock before it got shut down.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
I don't see how this could be done as it doesn't host anything and would have no context if the series it's displaying is a comic or manga.

So there's no way for it to differentiate manga or comics

**Comment by BrutuZ** [comment]
It could look for tags under the `SManga.genre` field that the user would populate on their self-hosting application of choice ;)

**Comment by AntsyLich** [comment]
I would rather just let the source decide

**Comment by BrutuZ** [comment]
But the user _is_ the source, right? :fumosmug:

**Comment by KenzKD** [comment]
It seems that TachiyomiSY already has a similar feature but just for Webtoons.
![image](https://github.com/mihonapp/mihon/assets/65004578/f0811295-d786-49b5-9815-2876029427ef)

**Comment by BrutuZ** [comment]
> It seems that TachiyomiSY already has a similar feature but just for Webtoons. 
> Edit: I just downloaded Tachiyomi SY to try it. The auto detect works for some works but not all webtoons.

Haven't looked at that code but I'd assume it just does a simple check like _if page is tall as a building_ to switch the reading mode

**Comment by AntsyLich** [comment]
> > It seems that TachiyomiSY already has a similar feature but just for Webtoons.
> > Edit: I just downloaded Tachiyomi SY to try it. The auto detect works for some works but not all webtoons.
> 
> Haven't looked at that code but I'd assume it just does a simple check like _if page is tall as a building_ to switch the reading mode

More like if has this tags mark it as webtoon
