### ISSUE TITLE
Rocks manga extension always show "no results found"

### ISSUE THREAD

**Issue by El-Nice** [mihonapp/mihon#1500]
### Steps to reproduce

Search anything or try updating an existing manga added from Rocks manga

### Expected behavior

Should ahow available manags

### Actual behavior

Showing "no results found "

### Mihon version

0.17.0

### Android version

Android 14

### Device

Redmi 9 running custom rom (crdroid 10.9)

### Other details

This problem happens only in rocks manga but not other extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions and therefore doesn't provide support for any of them. Ask your extensions repo provider for support, not us.
