### ISSUE TITLE
Option to disable badge on Browse of nav bar.

### ISSUE THREAD

**Issue by Palloxin** [mihonapp/mihon#1503]
### Describe your suggested feature

An option to disable the badge on browse when there are avaiable plugin updates
![Screenshot_2001_1](https://github.com/user-attachments/assets/f8ea83ad-a68b-48d6-b2bb-e32bd14109fd)

### Why
It's an aesthetic preference. 
I think it's common to enter a kind of "compulsive mode" and update the stuff JUST to remove the badge.

### Other details

I prefer to do so only when it breaks, but the badge purpose is to induce the user to update, but i dont want to.
I am sure game players know the feeling.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
How come?

Android notification settings allow to disable them. They know.it can be annoying.

https://github.com/user-attachments/assets/f401fa97-90d0-46e3-9832-647255dd3b97

**Comment by Soitora** [comment]
We want users to have updated extensions though?

**Comment by Palloxin** [comment]
Mihon doesnt support repos by itself i recall. I dont know why u would want that.
Also users might not want to update.

**Comment by Soitora** [comment]
> Mihon doesnt support repos by itself i recall. I dont know why u would want that.

Of course Mihon "supports repos", it's in the app for a reason? Sharing and what not other potentially illegal and harmful extensions or repos is however not supported, as we don't support any third-party content, only your own.

> Also users might not want to update.

Literally who cares about "rebel" users? More times than not, based on years of experience, these kind of people bring more trouble than not, and then comes to us complaining.
