### ISSUE TITLE
Extension Delete Itself

### ISSUE THREAD

**Issue by Ayam908** [mihonapp/mihon#1506]
### Steps to reproduce

1. Open app
2. Open Manhwa but can't because extension not install
3. Install extension
4. Read normally
5. Close the app
6. Reopen the app and extension deleted
7. Need to reinstall to proceed to read

https://github.com/user-attachments/assets/c9fa2bc8-fa5b-4383-9978-a552c59d297f

### Expected behavior

Shouldn't delete by itslef whenever I close the app

### Actual behavior

Extension deleted by itself every time app close.

### Crash logs

N/A

### Mihon version

0.17.0

### Android version

Android 15

### Device

Redmi K70

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Either Android 15 is fucking with you, or just shit chinaphone issues.

> ## Issues with Xiaomi devices:
> * Mihon encounters a variety of issues with MIUI/HyperOS due to Xiaomi's nonstandard practices.
> * Learn more [here](<https://dontkillmyapp.com/xiaomi>) to reduce the chances of Mihon being killed in the background.
> 
> ### When using Mihon:
> * Use an alternative file manager when restoring your backup into Mihon, do not use MIUI's file manager.
> * In your Phone Settings > Developer Options, __turn off system optimization/MIUI Optimization__
>     * If you don't see this setting, at the bottom of Developer Options, tap "Reset to default values" multiple times until it appears.
> ### Extra step for HyperOS users:
> * This extra permission is only on __certain regional versions of HyperOS__, if you don't see this optional permission, ignore this portion of the message.
> * Go to Mihon app info (not in-app), and in the Permissions > Other Permissions, set "Access List of Installed Apps" to Always Allow.
