### ISSUE TITLE
unable to read on  flame comics 

### ISSUE THREAD

**Issue by Pradeepking19** [mihonapp/mihon#1507]
### Steps to reproduce

Open the mihon app.
Go to the extensions section and install/enable "Flame Comics."
Try to browse or load comics using the "Flame Comics" extension.

### Expected behavior

The comics should load and display correctly within the mihon app through the "Flame Comics" extension.

### Actual behavior

When trying to load comics through the "Flame Comics" extension in the app, it does not work (no comics are displayed or an error occurs).
However, if I use the "Open in Web View" option for "Flame Comics," the comics load correctly in the web browser.

### Mihon version

0.17.0

### Android version

Android 11

### Device

Realme 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon STILL does not provide extensions NOR do we provide support for them. Go ask your EXTENSIONS PROVIDER for support.
