### ISSUE TITLE
take more paths as the Storge location

### ISSUE THREAD

**Issue by Rw-Ro** [mihonapp/mihon#1508]
### Describe your suggested feature

more path,
Take the input text as the path,
Not limited to SAF,Not limited to /storage/emulated,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
not possible on newer android versions

**Comment by Rw-Ro** [comment]
Application internal data directory is possible

**Comment by Rw-Ro** [comment]
> not possible on newer android versions

Application internal data directory is available

**Comment by AntsyLich** [comment]
Having a backup in internal storage is same as having no backup

**Comment by Rw-Ro** [comment]
> not possible on newer android versions

I don't know about this,but i know my Feature request is possible on android13(API 33).
In any case, this request has no harm.

**Comment by Rw-Ro** [comment]
> > not possible on newer android versions
> 
> Application internal data directory is available

The reason I made this issue is to improve safety and efficiency.
External storage is not private enough, SAF and external storage(FUSE) are inefficient.
efficiency is very important because mihon put chapter downloads in the Storge location.
