### ISSUE TITLE
Re: Separate storage for backups and for downloads

### ISSUE THREAD

**Issue by schklom** [mihonapp/mihon#1511]
### Describe your suggested feature

> The app now uses scoped storage meaning it will only have access to a single folder that user has granted access to. It's a requirement for targeting newer Android version.

_Originally posted by @AntsyLich in https://github.com/mihonapp/mihon/issues/9#issuecomment-1893746188_

I don't see anything in https://developer.android.com/training/data-storage/shared/documents-files#document-tree-access-restrictions that suggests that apps can only access one unique folder.

I use Tasker via Scoped Storage, and it frequently accesses multiple folders in the background. I'm not an Android pro, but it looks like there might be a misunderstanding. Is there?

This feature would be important to me, as my backup folder is nearing 1GB because of the downloads, and this is taking up a lot of unnecessary space on my cloud storage.

### Other details

Sorry to create a new issue but you prevent additional comments on the previous one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
> This feature would be important to me, as my backup folder is nearing 1GB because of the downloads, and this is taking up a lot of unnecessary space on my cloud storage.

Mihon doesn't upload anything anywhere, so that's a you issue. You need to better manage your cloud synchronization tool by only uploading the `autobackup` sub-folder instead of the whole Mihon parent folder

**Comment by schklom** [comment]
@Norsze
Wasn't aware of Discord, my bad
Wasn't my issue
I only opened one issue: this one
I only found one issue about this. I linked it, and so did you. Do you mean this gets asked on Discord a lot?

@BrutuZ
> You need to better manage your cloud synchronization tool by only uploading the autobackup sub-folder instead of the whole Mihon parent folder

I would, but it doesn't let me do that for now: https://github.com/newhinton/Round-Sync/issues/272

> that's a you issue

Isn't the point of Github issues to raise issues?
It's also not just a me issue: according to @Norsze this is a problem for a lot of people.

**Comment by schklom** [comment]
Got it

**Comment by AntsyLich** [comment]
Not sure why I said it's limited to one directory or if I meant something else. But the limit is actually much higher than that, while there is no clear documentation it was previously 128 files and directories which was later bumped on Android 11 or 12 (not sure) to 512 files and directories.

The reason I'm declining separate folder options is for ease of usage on my side. I may consider this in the future but it is not something I'm willing to do for the time being.
