### ISSUE TITLE
An extension is not working

### ISSUE THREAD

**Issue by Willian00175** [mihonapp/mihon#1513]
### Steps to reproduce

Go to forts and access the extension

### Expected behavior

Being able to access the works and wepview

### Actual behavior

Unable to access obas and wepview
![Screenshot_20241126-094339](https://github.com/user-attachments/assets/19708ddb-9c0c-4c9c-8d10-f0f80a159423)
![Screenshot_20241126-094417](https://github.com/user-attachments/assets/c8e25bb6-0339-4e95-81de-ca6b9ae5eaa3)

### Mihon version

Mihon 0.17.0

### Android version

Android 11

### Device

Google moto g(20)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's an extension-related issue, please go contact whoever maintains your extensions instead, since Mihon doesn't have, associate, or provide any extensions.

**Comment by Willian00175** [comment]
Thanks
