### ISSUE TITLE
No page found error from E-hentai

### ISSUE THREAD

**Issue by KageShiroe** [mihonapp/mihon#1519]
### Steps to reproduce

https://github.com/user-attachments/assets/111256b2-c769-45c2-805a-bb5c738305e2

### Expected behavior

opening of the actual chapter

### Actual behavior

when trying to open a chaper it says no pages found

### Mihon version

0.17.0

### Android version

android 14

### Device

fold 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
if you got the video from an issue on mihon you should read the answer. mihon doesn't have extensions. go ask where you got the extension.
