### ISSUE TITLE
Updating library through update tab is inconsistent

### ISSUE THREAD

**Issue by seanbsu** [mihonapp/mihon#1524]
### Steps to reproduce

1. Have different manga's in libraries from mangasee source in app library
2. navigate to Update tab on bottom of app screen
3. try updating library either by pulling down to refresh or through the update icon
4. after update is complete check magasee website to see if any updates did not appear in the update tab
5. if so go to the library tab and choose that manga and update from there. The maga will then update

### Expected behavior

when updating from the update tab all updates  should appear in the updates list without having to go to individual mangas in the library and updating them

### Actual behavior

when updating from the update tab very few updates appear in the update list. You have to go to the library tab and to individual manga's and run separate updates for each to get the updated list

### Mihon version

0.17.0

### Android version

Android 10

### Device

Samsung galaxy s9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
1. Mihon doesn't support any sources other than [Local Source](https://mihon.app/docs/guides/local-source)
2. You're just describing [Smart Updates](https://mihon.app/docs/faq/updates/smart) working as intended.
