### ISSUE TITLE
Add Option to Hide Unread and Local Source Icon

### ISSUE THREAD

**Issue by riki270601** [mihonapp/mihon#1527]
### Describe your suggested feature

Currently, the "Unread" and "Local Source" icons are always visible in the interface. While they are useful for some users, others might prefer a cleaner interface without these elements. To improve user experience and customization, I suggest adding an option to hide these icons.
![IMG_20241129_184947](https://github.com/user-attachments/assets/3ff0d9cf-cccf-4a7f-bbca-251a944d51ca)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Just a quick note, you can turn the Local Source badge off in the Filter -> Display Settings. But currently not the unread badge.

**Comment by BrutuZ** [comment]
As for the Unread badge, previously denied on #539
