### ISSUE TITLE
Add transition animation when switching between tabs.

### ISSUE THREAD

**Issue by iLikeCake10** [mihonapp/mihon#1530]
### Describe your suggested feature

Switching between tabs just suddenly opens the tab and it doesn't feel good. Add the transition that is used in the more page.

P.S. even play store is testing it.

### Other details

https://github.com/user-attachments/assets/763184cc-22a2-4323-ae79-187edf41406f

https://x.com/AssembleDebug/status/1832088264624525377?t=m1JHrPDm8eqFhS2uRblTXQ&s=19

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
There is a fade in and fade out animation
