### ISSUE TITLE
Mihon's Network State Handling and Connectivity Checks

### ISSUE THREAD

**Issue by Baba-Yagan** [mihonapp/mihon#1536]
### Steps to reproduce

When using a firewall application such as [AFWall](https://github.com/ukanth/afwall), which allows fine-grained control over network access for individual applications, Mihon behaves inconsistently under certain conditions. Specifically, if the internet check service reports that the internet is unavailable and Android's `DownloadManager` is blocked, Mihon shows unexpected behavior.

- Install AFWall (or any similar firewall app that operates with IPtables) on your Android device.
- Set the firewall to whitelist and allow internet access for Mihon.
- Attempt to use Mihon’s downloader (either the general downloader or the extension downloader).
- Notice that the downloader fails with an error, while other features (like manga reading or extension manga browsing) continue to work fine.

### Expected behavior

- Mihon should handle network connectivity in a more robust manner, independently of Android’s `DownloadManager` and network state flags.
- Testing connectivity by **pinging** (or a similar method) instead of relying on the Android connectivity status flag would likely resolve this issue.

### Actual behavior

- **DNS resolution** works fine, and Mihon can make internet requests and receive results without timeouts.
- **Online manga reading** functions as expected.
- The **manga downloader** errors out (respecting the state that's obtained [here](https://github.com/mihonapp/mihon/blob/cc96f859bc3b1681e065f2c64a3b0642890b7dc0/app/src/main/java/eu/kanade/tachiyomi/util/system/NetworkStateTracker.kt#L28C5-L28C12) from the android API)
- The **extension downloader** (using `DownloadManager` to download APKs) fails and is stuck loading ignoring the cancel button, effectively blocking the webview button.

### Mihon version

0.17.0

### Android version

Android 15

### Device

 Samsung Galaxy Z Fold 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> - Mihon should handle network connectivity in a more robust manner, independently of Android’s `DownloadManager` and network state flags.

Ignoring Android's `DownloadManager` which I also hate for some it's quirk how is one supposed get connectivity state without using the device provided network state flags?

> - Testing connectivity by pinging (or a similar method) instead of relying on the Android connectivity status flag would likely resolve this issue.

I read an article couple of weeks ago on how a site was being DDoSed because a dev with millions of users thought it was ok to ping test on that site. Also if the site goes for some reason the whole check will break.

**Comment by Baba-Yagan** [comment]
>Ignoring Android's `DownloadManager` which I also hate for some it's quirk how is one supposed get connectivity state without using the device provided network state flags?

it should just read the state of if the device is connected to cellular/wifi
>I read an article couple of weeks ago on how a site was being DDoSed because a dev with millions of users thought it was ok to ping test on that site. Also if the site goes for some reason the whole check will break.

i'd either use the update check or just ping whatever url comes first be it the git update check resolve, some search query, addons list update, the reader trying to fetch updated metadata, etc and just assume that if this one does return ping the device is online. the reader loading images ignores the no internet connection state (connected, but network not available) anyways and it's not like anything would happen if there were no network available and mihon would attempt to connect/download stuff it would just time out.

**Comment by cuong-tran** [comment]
Downloading is currently performed by Android's WorkManager with constraints requiring network connected. So even though Mihon is whitelist but probably the WorkManager is not so the job won't get started at all.

**Comment by Baba-Yagan** [comment]
the issue i opened here can be skipped entirely by disabling [Captive Portal Checkin](https://xdaforums.com/t/guide-how-to-avoid-the-captive-portal-checkin-to-google.3927561/)

```
 For Android 8/9:
1. Open a terminal on your phone (via terminal apps).

2. Type the following command:
- su
- su
- pm disable com.android.captiveportallogin
- settings put global captive_portal_detection_enabled 0
- settings put global captive_portal_server localhost
- settings put global captive_portal_mode 0

3. Then reboot your phone (via hardware buttons, system or terminal app).


For Android 7:
1. Open a terminal on your phone (via terminal apps).

2. Type the following commands:
- su
- settings put global captive_portal_detection_enabled 0
- settings put global captive_portal_server localhost
- settings put global captive_portal_mode 0

3. Then reboot your phone (via hardware buttons, system or terminal app).
```

**Comment by MajorTanya** [comment]
There are several issues I have with this. First of all, Mihon is Android 8+ only.
Second, disabling a system component via the terminal seems dicey at best, especially when it's neither Mihon's nor the system's fault you're experiencing this.
Third, how does this affect connecting to an actual captive portal network? Does it just brick those completely? Seems like taking a rocket launcher to kill a pigeon. A pigeon who is only there because you asked for it to be there.

**Comment by loocool2** [comment]
I don't think this is worth the effort to support at all. Most users are not rooting along with using root-level firewalls like afwall+, making this usecase a niche within a niche. As your issue can be fixed on your device by disabling that system component, then do so I guess.
