### ISSUE TITLE
Unable to update extensions via all methods

### ISSUE THREAD

**Issue by cccp6** [mihonapp/mihon#1539]
### Steps to reproduce

1.Open Mihon and go to extensions 
2.Click on update button for any extensions.
3.A.If shizuku or packageinstaller is selected, then the throbber just disappears and the update button reappears.
   B.If legacy installer is selected, the apk install dialog appears, but shows error parsing the package and exits.

### Expected behavior

The extensions should install/update.

### Actual behavior

Installation fails without prompt.

### Crash logs

App version: 0.17.0 (standard, 38d5fc9, 8, 2024-10-26T17:39:14Z)
Android version: 15 (SDK 35; build CPH2609_15.0.0.200(EX01))
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP5D35L1 (PJE110)
Device model: PJE110
WebView: Android System WebView 131.0.6778.39

Problematic extensions:
- Bato.to
  Installed: 1.4.41 / Available: 1.4.42
  Obsolete: false
- Imitui Manhua
  Installed: 1.4.13 / Available: ?
  Obsolete: true

--------- beginning of main
12-05 01:44:29.261 18001 18001 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@d058f13
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: Failed to install extension 37 content://app.mihon.provider/ext_files/Download/tachiyomi-all.batoto-v1.4.42-19.apk
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: java.io.FileNotFoundException: open failed: EACCES (Permission denied)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:363)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:239)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at androidx.core.content.FileProvider.openFile(Unknown Source:83)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentProvider.openAssetFile(ContentProvider.java:2300)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:2478)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:2545)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:685)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2069)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1884)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1554)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller$processEntry$1.invokeSuspend(Unknown Source:58)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-05 01:44:33.130 18001 18047 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-05 01:44:33.733 18001 18001 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@297c578

### Mihon version

0.17.0

### Android version

Android 15

### Device

OnePlus Ace 3 (12R)

### Other details

Manually installing the extensions' apk files does not work either. But through other root-based installer apps like IwanSettings works.
This issue first occurred on both ColorOS and OOS 14, and later persists on Android 15.
I believe there's something to do with extensions packaging.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by dty285767** [comment]
Similar to my question, I have provided feedback before, but it has not been resolved yet. After searching for some solutions, my current solution is to use my old phone (Android 13) to download (update) and then transfer it to my new phone (Android 15) to solve the problem. In addition, my phone is OnePlus ACE3V. I hope it's helpful to you
