### ISSUE TITLE
r6990 fixed blank page issue, r7015 broke it again

### ISSUE THREAD

**Issue by PrParadoxy** [mihonapp/mihon#1541]
### Steps to reproduce

Thanks to [AntsyLich](https://github.com/AntsyLich/AntsyLich) the blank page issue as described https://github.com/mihonapp/mihon/issues/1436 was fixed in [r6990](https://github.com/mihonapp/mihon-preview/releases/tag/r6990), however, [r7015](https://github.com/mihonapp/mihon-preview/releases/tag/r7015) broke it again. (Is going back to legacy mode by the choice of user not possible?)

P.S: I couldn't find out whether this is the right place for posting preview issues or not.

### Expected behavior

To see pages properly.

### Actual behavior

  see https://github.com/mihonapp/mihon/issues/1436 

### Mihon version

r7015

### Android version

Android 8.1

### Device
Samsung SM-t585 (gtaxlite)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by infyProductions** [comment]
Try changing this to a lower value: (More>Settings>Advanced>Custom Hardware Bitmap Threshold)
_Also introduced in r7015 (I'm running r7021 but the option is also available there):_
![image](https://github.com/user-attachments/assets/6b68f930-5a4c-4388-b517-16ec3456ef97)

**Comment by PrParadoxy** [comment]
@infyProductions Thanks for the response, I set it to the lowest value 2048 and still didn't work, I wonder why.

**Comment by MajorTanya** [comment]
> @MajorTanya Yes. I just doubled checked. Also force stopping it (from android app settings), didn't help.

Did you just select the lowest value or did you try out the other in between as well?

**Comment by PrParadoxy** [comment]
@MajorTanya I just tested for all values, nothing works. Tested on different sources.

**Comment by MajorTanya** [comment]
Then I'm afraid there isn't much else we can do for you at this time. I'll keep this issue open, maybe someone with more knowledge of the situation will have further ideas.

**Comment by MajorTanya** [comment]
It appears as though the entire lineup of Samsung Galaxy devices running Android 8 have severe problems with specifically the stuff Mihon tries to use for this. This will require a different approach from our side.

If possible, could you join our Discord Server? Ping me in the support channel there (same username, `majortanya`), we may have found a possible workaround for this issue.

**Comment by MajorTanya** [comment]
> It appears as though the entire lineup of Samsung Galaxy devices running Android 8 have severe problems with specifically the stuff Mihon tries to use for this. This will require a different approach from our side.
> 
> If possible, could you join our Discord Server? Ping me in the support channel there (same username, `majortanya`), we may have found a possible workaround for this issue.

@PrParadoxy this was directed to you by the way
