### ISSUE TITLE
Application or extension failure

### ISSUE THREAD

**Issue by Koujy23** [mihonapp/mihon#1551]
### Steps to reproduce

The application closes or restarts

### Expected behavior

The open the sleeve without closing or restarting it 

### Actual behavior

I enter the aplication, but when i try to open a manga from tumangaonline and lectormanga, the application closes or restarts

### Mihon version

0.17.1 

### Android version

Android 9

### Device

Samsung j4+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Send the crash log in the Mihon Discord support channel instead, this issue request provides no information about the actual crash
