### ISSUE TITLE
"Playlist" of unread chapters from different entries

### ISSUE THREAD

**Issue by ShaiPol** [mihonapp/mihon#1554]
### Describe your suggested feature

A user selects one or more entries in their library and presses a button that starts the Reader with the selectes entries' unread chapters.

The chapters will be loaded in a FIFO format of the entries' selection, with chapters of the same entry grouped together in a row of course.
E.g. entry A with 2 unread chapters was selected, then entry B with 1 unread chapter was selected and the user pressed the button - order of chapters is A1->A2->B1, regardless of any other sorting order.

Alternatively, a menu can pop up each time (as long as more than one entry is selected) that will allow for sorting the chosen entries according to desired reading order. This alternate option can be added to the Library's settings, but should be turned off by default in my opinion.

### Other details

The button to start the playlist could be a floating action button with a "play" icon in the middle of the screen, slightly above the bottom bar.

This should also work for cases where only one entry is selected.

When even one of the selected entries doesn't have any unread chapters, it might be better to remove the option to start the playlist altogether to avoid confusion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Maybe something @jobobby04 wants for his fork
