### ISSUE TITLE
Myreadingmanga extension not working

### ISSUE THREAD

**Issue by BangtanExo27** [mihonapp/mihon#1557]
### Steps to reproduce

Go into the extention and it says failed to bypass cloudfare, so click on webview, says "not found". The site is working when you use browser so there shouldn't be any problem. 

### Expected behavior

It should be loading normally, I thought it would be fixed or reported by now but it's been about a month already. 

### Actual behavior

Failing to load. Cloudfare bypass problems, when using webview it's reporting "not found" 

![Screenshot_20241209_165322_app mihon](https://github.com/user-attachments/assets/4c82ea91-7a1b-4931-8cbc-9dbd6b6001c7)
![Screenshot_20241209_165327_app mihon](https://github.com/user-attachments/assets/9d84978d-0b69-41e2-8d41-7441c7daed5c)

### Mihon version

0.17.1

### Android version

Android 11

### Device

HUAWEI P30 LITE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
> I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).

**Comment by BangtanExo27** [comment]
I've gone through all of the troubleshooting and FAQ, that's why I posted this here, none of that is working.

**Comment by AntsyLich** [comment]
You clearly didn't read https://mihon.app/docs/faq/browse/extensions#what-are-some-recommended-extensions-and-sources
