### ISSUE TITLE
Restoring backup from Tachiyomij2k

### ISSUE THREAD

**Issue by untalanerds** [mihonapp/mihon#156]
### Steps to reproduce

![Backup Error](https://github.com/mihonapp/mihon/assets/59647442/afbf14b7-48d5-4472-b63c-2844637d5247)
When restoring back, its giving me this error.

### Expected behavior

Restoring back up should work right?

### Actual behavior

It's giving me an error.

### Mihon version

0.16.1

### Android version

Android 13

### Device

Itel P55

### Other details

My Tachiyomij2k is still working, all manga and manhuas are still working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
Mihon only takes backups ending in ".tachibk".

Backups ending in .json are legacy backups and are not supported. I am unsure how you created a .json backup as afaik the latest j2k versions has already dropped json backups entirely.

You could convert the backup by restoring it into TachiyomiAZ and then creating a .tachibk from there.

**Comment by untalanerds** [comment]
@CrepeTF thank you so much! It's working now.
