### ISSUE TITLE
error no results found

### ISSUE THREAD

**Issue by HutaoNya** [mihonapp/mihon#1562]
### Steps to reproduce

Please tell me how to fix this error. This morning I got the error even though I tried deleting the webview
![Screenshot_2024-12-11-15-38-27-885_app mihon](https://github.com/user-attachments/assets/70d1b620-1626-4a92-82f9-f706be5c1fc6)
![Screenshot_2024-12-11-15-38-36-289_app mihon](https://github.com/user-attachments/assets/84c7ea21-298f-49e8-96ca-5c071cef93b3)
![Screenshot_2024-12-11-15-38-27-885_app mihon](https://github.com/user-attachments/assets/a0433a75-a34d-4584-bbdf-edb1359d485d)

### Expected behavior

I hope the developer will fix it or show me how to fix it. Thank you very much

### Actual behavior

Please tell me how to fix this error. This morning I got the error even though I tried deleting the webview
![Screenshot_2024-12-11-15-38-36-289_app mihon](https://github.com/user-attachments/assets/88fbdd4d-2cca-4fdd-afda-ceced2ec01d4)
![Screenshot_2024-12-11-15-38-27-885_app mihon](https://github.com/user-attachments/assets/ce5a1c35-e7f3-41b0-8839-34f8923ac3e5)

### Mihon version

0.17.1

### Android version

Android 10

### Device

Redmi 9C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue, go check with whoever/wherever you get your extensions from
