### ISSUE TITLE
Animated GIF unable to play

### ISSUE THREAD

**Issue by Johnwong-wqy** [mihonapp/mihon#1568]
### Steps to reproduce

1. When open the manga gif, suppose to be able play the animated gif.
2. When Open, it will show multiple layer of image
3. When open manga via browser, the animated gif look normal (able to play)

### Expected behavior

Should be able play animated gif

### Actual behavior

The picture was 'stacking' together (in layer) ?
![screenshot](https://github.com/user-attachments/assets/e57936d4-31f4-448d-b2f9-ca89cd14079c)

### Mihon version

0.17.1

### Android version

Android 14

### Device

Vivo X 100 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Check with whoever/wherever you get your extensions from first, also no NSFW pictures for future reference
