### ISSUE TITLE
manga was marked as complete wrongly

### ISSUE THREAD

**Issue by EnderAvaritia** [mihonapp/mihon#1570]
### Steps to reproduce

NO step

### Expected behavior

i hope i can have a method to choose the manga is ongoing or complete 
the info at the website might be incorrect and this will lead to cant update the mange

### Actual behavior

manga was marked as complete wrongly and it will not be updated even if i set the  smart update

### Mihon version

r7031

### Android version

android14

### Device

mi pad 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
You can still update the entry by pulling down to refresh in the entry itself. This is unaffected by Smart Updates settings.

The underlying problem is on your source of choice being mistaken in marking it as completed.

Ways to edit entry status and other info have been requested many times before, please read through other issues first before making new ones (like the Acknowledgement section of the template asks you to).

**Comment by MajorTanya** [comment]
> > You can still update the entry by pulling down to refresh in the entry itself. This is unaffected by Smart Updates settings.
> > The underlying problem is on your source of choice being mistaken in marking it as completed.
> > Ways to edit entry status and other info have been requested many times before, please read through other issues first before making new ones (like the Acknowledgement section of the template asks you to).
> 
> sorry for create duplicate issue because of my searching wrong keywords
> although i can refresh it in the entry itself , when i have over 300 mangas , it is hard for me to find the manga especially
> what i needed is not "smart" update, i hope i can update it when i update the whole library
> 
> well, i also wish to have a manga info editor after reading #5 ,i have a manga storage for my own ,i know the manga there will never be updated but they are all marked as ongoing they will be updated everytime :(

1. Please don't misuse big headline formatting like this.
2. You can disable the Smart Updates skip of Completed series in the settings if it is this much of an inconvenience to you. **However**, please make sure that you isolate _actually completed_ series into their own category if you do this. There is _no reason_ to hammer sources with new chapter requests when you _know_ there won't be any more chapters. This is why we _strongly recommend_ you keep all Smart Updates options enabled.

**Comment by MajorTanya** [comment]
> 
> 
> 
> 
> > > > You can still update the entry by pulling down to refresh in the entry itself. This is unaffected by Smart Updates settings.
> > > > The underlying problem is on your source of choice being mistaken in marking it as completed.
> > > > Ways to edit entry status and other info have been requested many times before, please read through other issues first before making new ones (like the Acknowledgement section of the template asks you to).
> > > 
> > > 
> > > sorry for create duplicate issue because of my searching wrong keywords
> > > although i can refresh it in the entry itself , when i have over 300 mangas , it is hard for me to find the manga especially
> > > what i needed is not "smart" update, i hope i can update it when i update the whole library
> > > well, i also wish to have a manga info editor after reading #5 ,i have a manga storage for my own ,i know the manga there will never be updated but they are all marked as ongoing they will be updated everytime :(
> > 
> >     1. Please don't misuse big headline formatting like this.
> > 
> >     2. You can disable the Smart Updates skip of Completed series in the settings if it is this much of an inconvenience to you. > **However**, please make sure that you isolate _actually completed_ series into their own category (and exclude this category > from automatic updates!) if you do this. There is _no reason_ to hammer sources with new chapter requests when you _know_ > there won't be any more chapters. This is why we _strongly recommend_ you keep all Smart Updates options enabled.
> 
> sorry for use wrong format . i dont know use dividing line will lead to  big headline
> i will try to disable the Smart Updates skip of Completed series but there are only several mangas have this problem against 300 mangas work correctly. 
> according to what you say, i can set different updating  strategy for different category?
> thanks for your help 

You cannot set different strategies for different categories. But you can explicitly exclude categories from the automatic update.
If you put all the series that are correctly marked as completed into category A for example, you can exclude category A from the automatic updates (check the settings for it).
If you keep all the manga that are wrongly marked as completed in another category together with the ongoing ones (let's call it category B), you can tell Mihon to include only category B in automatic updates.

1. Settings > Library > Global update section > Categories
2. Tap that and a popup will show your categories
3. Exclude category A (tap it in the list until the box is an X)
4. Include category B (tap it in the list until the box is a checkmark tick)

Done. ![Screenshot_2024-12-16-16-26-26-771_app.mihonya.debug.png](https://github.com/user-attachments/assets/607cacb3-17f6-47e3-944a-c2c41f5f08c7)

Something like this.

This will tell Mihon to only automatically update stuff in category B and to never automatically update stuff in category A. You can still update entries in A manually if you really want to though, obviously.
You can exclude or include as many categories as you want, just make all the ones you don't want to be updated automatically into X shapes. Similarly for categories you want to include.
