### ISSUE TITLE
Latis Books (en.latisbooks) changed website

### ISSUE THREAD

**Issue by ORLOX93** [mihonapp/mihon#1578]
### Steps to reproduce

1. Go to Latis Books.
2. Open Bodysuit 23
3. Refresh chapters

### Expected behavior

New chapters should appear when refreshing.
There have been 4 new numbered chapters and some unnumbered chapters that show up on webview but not on mihon itself.

### Actual behavior

Refreshing lead to the "no chapters found" message to appear.

### Mihon version

0.17.1

### Android version

Android 14

### Device

Samsung Galaxy Tab A9+

### Other details

The problem is caused because the website changed. It's no longer called Latis Books but Megahzone.
This is the new site: https://bodysuit23.mehgazone.com/archive/

Also another comic has been added to this new website, done by the same author, and i was wondering if it could be added to the extension as well: https://a-kats-god-awful-blessing.mehgazone.com/archive/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions itself nor do we provide support. Go ask whoever you got this from, which is not us.

**Comment by ORLOX93** [comment]
It was a little misunderstanding on my part, this type of issues where handled by the Tachiyomi crew in the past. I got the right github to report the issue now.
