### ISSUE TITLE
Add feature account ( to save bookmark ( library ) manga/manhwa etc )

### ISSUE THREAD

**Issue by vxyzview** [mihonapp/mihon#1579]
### Describe your suggested feature

Make a feature that can signup/login to save bookmark ( library ) into the account to make if change devices or anything like reset phone and etc, and if download mihon again and login with previous account the bookmark ( Library ) that have been save before, the bookmark is not gone and still exist like before, so basically this is to make more simple and no need to download one by one to copy manga/manhwa etc

**This is almost same as tracking feature but have different feature to make more simple**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Thanks for generously offering to shoulder all the costs with servers infrastructure and maintenance, as well as the lawyers to deal with potential legal shenanigans for handling user data

**Comment by AntsyLich** [comment]
Unless you want me to shoulder the cost by selling your reading list to FBI it's a no
