### ISSUE TITLE
Missing exception field

### ISSUE THREAD

**Issue by Y-Shian** [mihonapp/mihon#1586]
### Steps to reproduce

1. Open mihon app
2. Go to extension
3. Open Hitomi extension 

### Expected behavior

See latest list

### Actual behavior

missingfieldexception: field 'hasjxl' is required for type with serial name 'eu.kanade.tachiyomi.extension.all.hitomi.image file', but it was missing at path: $.files[0]

### Mihon version

0.17.1

### Android version

Android 13 

### Device

Xperia 1 III

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue, go check with whoever/wherever you get your extensions from instead.
