### ISSUE TITLE
La extensión Eternal mangas no funciona 

### ISSUE THREAD

**Issue by Melody0246** [mihonapp/mihon#1587]
### Steps to reproduce

Cuando busco un manga en el navegador aparece qué no se pudo encontrar la lista de cómics 

### Expected behavior

La extensión debería mostrarme los mangas con el respectivo título pero no encuentra ningún comic

### Actual behavior

En ves de mostrarme los mangas no muestra nada pero si lo abro del web View si los muestra pero solo los populares o actualizados los demás no

### Crash logs

![Screenshot_20241218_115041_app_mihon_MainActivity](https://github.com/user-attachments/assets/31bea09d-2ced-4283-befa-f78d356b7d92)

### Mihon version

0.17.1

### Android version

Android 11

### Device

Honor X8a

### Other details

Ya intente borrar las cookis y datos de navegación al igual que desinstalar y volver a instalar la extensión y no funciona 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue, since Mihon doesn't have, associate, or provide any extensions, sources, or content.

Check with whoever/wherever you get your extensions from.
