### ISSUE TITLE
[Question] How do I check if "Download Ahead" option is working.

### ISSUE THREAD

**Issue by dajotim937** [mihonapp/mihon#1588]
### Steps to reproduce

I checked "Download Ahead" option but I don't understand when I should work. I start reading chapter, completed it, return to manga page and next chapters are not downloaded and app is not downloading anything. I tried to add to library, download first chapter (that I will read), clear cache, set 2-10 chapters to download ahead and still can't see difference when option enabled\disabled.

### Expected behavior

Chapters are downloaded ahead.

### Actual behavior

Chapters aren't downloaded ahead.

### Mihon version

0.17.1

### Android version

Android 8/9

### Device

Xiaomi 5/Nokia 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Did you read the full thing about the feature? To first have two chapters downloaded before it downloads ahead?

![Screenshot_20241219_101605_Mihon.png](https://github.com/user-attachments/assets/0ae5c273-d76d-4b31-8102-b9e6062ec2f3)
