### ISSUE TITLE
Chapter selection

### ISSUE THREAD

**Issue by Rishi1232** [mihonapp/mihon#1590]
### Describe your suggested feature

It was a feature in fork of tachiyomi (tachiyomij2k) when selecting chapter instead of selecting one by one you can select all by selecting first chapter and last chapter till you want to select and middle chapter automatically selected.
It help in easily marking chapter and download and delete certain chapter easily and fast.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
What you're looking for is Range Selection, and Mihon does have it.

1. Select the first chapter you want
2. Long press on the last chapter you want to select
Mihon will be selecting the first and last chapter and then select all the chapter in between as well.

**Comment by Smol-Ame** [comment]
Feature already exists in Mihon, explore the app or search the issues (both open and closed)

Hold down to select a chapter, go to another chapter and hold select that one to select everything in between.

Ask basic questions/troubleshooting in Mihon Discord support channel
