### ISSUE TITLE
manga reader extension not working properly 

### ISSUE THREAD

**Issue by Mrnoooobodyyyy** [mihonapp/mihon#1591]
### Steps to reproduce

The extension name manga reader was working fine until recently but suddenly it stops working by stop I mean when I open any manga it works till it load number of pages and then it stop it does not load the image itself the loading circle just goes on  and on at first I thought it was network issue but other extensions are working fine, I am not sure why is it acting like that please tell me what can I do to fix it 

### Expected behavior

It should first load the number of images or we can say interface then images itself but it does not load the image 

### Actual behavior

it stuck on loading screen 

### Crash logs

there are no crasher it just stuck there 

### Mihon version

0.17.1

### Android version

Android 11

### Device

Redmi 9i sport 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
You probably got rate-limited or something by the source, read less or check with whoever/wherever you get your extensions from.

Not an app-related issue
