### ISSUE TITLE
Multi language site not work 

### ISSUE THREAD

**Issue by salimbougrinat** [mihonapp/mihon#1592]
### Steps to reproduce

1. Install mangadex.org extension as multi lang
2. Search for manga
3. Found that site shows only English version 
![Screenshot_20241219-095642](https://github.com/user-attachments/assets/d15bee94-385a-4b19-adf4-29d56c2dafb1)
![IMG_20241219_095931](https://github.com/user-attachments/assets/91a860bc-6371-4239-8cc0-ff6197a7ac16)
![Screenshot_20241219-100020](https://github.com/user-attachments/assets/00b0c665-37c2-4758-b5a0-b09b8b03ca30)

### Expected behavior

All manga languages versions are supported to be found 

### Actual behavior

Just English versions 

### Mihon version

0.17.1

### Android version

Android 8

### Device

Honor 7c 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon has nothing to do with any extensions. Go ask whoever made/maintains these, not us.

**Comment by Smol-Ame** [comment]
That's from whoever/wherever you get your extensions from, not an app-related issue
