### ISSUE TITLE
Extensions 

### ISSUE THREAD

**Issue by Kirakip** [mihonapp/mihon#1597]
### Steps to reproduce

![Screenshot_20241220_120622_Mihon](https://github.com/user-attachments/assets/6c3dfe1c-9b79-4daf-bc0f-c37c29bafb3a)
![Screenshot_20241220_120613_Mihon](https://github.com/user-attachments/assets/06a68dc7-3fbb-4fb6-9359-5fd9dc45b5d2)
![Screenshot_20241220_120605_Mihon](https://github.com/user-attachments/assets/1f73ac3c-d095-4cfe-91be-71fb14f8e558)
![Screenshot_20241220_120542_Package installer](https://github.com/user-attachments/assets/744610fd-3ff0-434f-8bec-531c8c210b49)
![Screenshot_20241220_120536_Mihon](https://github.com/user-attachments/assets/029b1747-2b5b-46fc-a539-ecf3fcfbeb4e)

### Expected behavior

It should be updated and not be on the update list

### Actual behavior

But it is still in update list even after updating it refreshing it or reinstalling it

### Mihon version

0. 17. 1

### Android version

Android 14

### Device

Galaxy A05

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Mihon doesn't have, associate, or provide any sources, extensions, or content.

Check with whoever/wherever you get your extensions from instead for help.
