### ISSUE TITLE
Invalid Extension Repo on 0.17.1

### ISSUE THREAD

**Issue by LostFl0ptrop1can** [mihonapp/mihon#1600]
### Steps to reproduce

1. Go to keiyoushi's extension repo webpage
2. Press "Add repository"
3. A box should appear. Press "Add"
4. Restart the app.
![Screenshot_20250102-215246](https://github.com/user-attachments/assets/6789c46a-93ed-4613-bce4-b1c2ed62889d)

### Expected behavior

The extension repo should be listed now and the extensions should now be available and downloadable.

### Actual behavior

Instead, it'll froze for a few moments and spit the message "Invalid Extension Repo".
![Screenshot_20250102-215250](https://github.com/user-attachments/assets/6f4cbc18-2336-44b0-9c53-57370c7918d4)

### Crash logs

N/A

### Mihon version

0.17.1 - ArmV7a 

### Android version

Android 10 Go

### Device

MyPhone MyT8 (SC9832E)

### Other details

![Uploading Screenshot_20250102-215246.png…]
![Screenshot_20250102-215250](https://github.com/user-attachments/assets/e01b7711-4fa7-475c-9bf3-e34e46bbe990)
()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1. Don't name extension repos please, for legal reasons
2. Check with whoever the maintainers are first for any known issues, this is a user-error
