### ISSUE TITLE
使用部分扩展看漫画内容时闪退回上一页面并提示"Too many follow-up requests: 21"

### ISSUE THREAD

**Issue by 3049298988** [mihonapp/mihon#1602]
### Steps to reproduce

1.安装好包子漫画扩展
2.在包子漫画上进入一个漫画的阅读界面
3.之后会自动回退上一个页面并弹出toast"Too many follow-up requests: 21"

### Expected behavior

在第3.应该进入漫画阅读界面

### Actual behavior

回退上一个界面并弹出toast"Too many follow-up requests: 21"

### Crash logs

[mihon_crash_logs.txt](https://github.com/user-attachments/files/18215451/mihon_crash_logs.txt)

### Mihon version

0.17.1

### Android version

Android14

### Device

Redmi Note 11T Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue, check with whoever/wherever you get your extensions from.
