### ISSUE TITLE
Kavita Integration - No Books Displayed

### ISSUE THREAD

**Issue by Its-Ashish-RanJan** [mihonapp/mihon#1604]
### Steps to reproduce

Add the extension repository URL from the Kavita wiki:
https://raw.githubusercontent.com/Kareadita/tachiyomi-extensions/repo/index.min.json.
Install the Kavita extension.
Enter the OPDS URL for Kavita in Mihon.
Restart the Mihon app.
Navigate to Sources -> Kavita (1) -> Latest.
Observe that no books are displayed.
Click on Open WebView, log in to Kavita via the login page, and close the WebView.
Check Sources -> Kavita (1) -> Latest again.

### Expected behavior

Books from Kavita's feed should display under Sources -> Kavita (1) -> Latest after logging in and integrating with Kavita.

### Actual behavior

No books are displayed under Sources -> Kavita (1) -> Latest, even after successfully logging into Kavita via the WebView.

### Crash logs

App version: 0.17.1 (standard, 3a100c7, 9, 2024-12-06T17:14:05Z)
Android version: 11 (SDK 30; build RMX2180_11_C.13)
Device brand: realme
Device manufacturer: realme
Device name: RMX2180 (RMX2180)
Device model: RMX2180
WebView: Android System WebView 131.0.6778.135

--------- beginning of system
12-21 15:22:14.739 20715 20715 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
12-21 15:26:35.774 26683 26683 E libEGL  : Invalid file path for libcolorx-loader.so

### Mihon version

0.17.1

### Android version

Android 11

### Device

realme c15

### Other details

The WebView successfully logs into Kavita, but the books are not synced or displayed in Mihon.
Restarting the app or re-adding the extension does not resolve the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Sounds like something you should check with Kavita instead

**Comment by Its-Ashish-RanJan** [comment]
Thank you for your feedback! I’ve already verified that Kavita is working as expected.

Since the issue appears to be on Mihon, could you provide guidance on how to resolve this? 
If this falls under Mihon’s scope, I’d appreciate any advice on reporting this to their team effectively.

**Comment by Smol-Ame** [comment]
This issue request is the reporting to the team. Though in my opinion, it still seems like something between your extension & Kavita server.

Maybe double-check your Kavita extension settings, or sign in again. Otherwise, my only other suggestion while you wait for someone more knowledgeable with Kavita to respond, is to maybe go to Mihon Settings > Advanced, and see if you can "Clear database" for Kavita (if possible).

**Comment by Its-Ashish-RanJan** [comment]
Thank you for your help! After trying multiple things, I discovered that my manga files are in the .epub format. I tried using .cbz files, and they worked fine. Sorry for the trouble!

It would be great to have support for .epub files, especially for novels and light novels. Thanks again for your assistance!

**Comment by BrutuZ** [comment]
Mihon is a image viewing app at its core, there other apps for reading purely text content like novels
