### ISSUE TITLE
Capability to edit cookie

### ISSUE THREAD

**Issue by Jacfger** [mihonapp/mihon#1607]
### Describe your suggested feature

Some sites work by having some special cookie to bypass some limitation. And there's seemed to be no way to edit cookie as of right now.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
That's an extension issue. Extensions can have their own independent settings. If an extension wishes to do something with special values or cookie values or whatever, it can provide the settings for that (Browse > Extensions > gear icon on whatever extension you are thinking of > gear icon on whatever language you're using the extension with).

Extensions that require logins or similar cookie things are also able to access the WebView and its data for the source at hand. 

If the extension you're thinking of doesn't provide this, go ask your extension maintainers for help there. We don't provide extensions or support for their issues.
