### ISSUE TITLE
Error while updating tracker

### ISSUE THREAD

**Issue by Key-explanation** [mihonapp/mihon#1609]
### Steps to reproduce

1. Read a chapter
2. Anilist won't update the chapter

### Expected behavior

Anilist should update my library 

### Actual behavior

Anilist showing "http error 400"

### Mihon version

0.17.1

### Android version

Android 11 

### Device

Vivo Y15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine, unlink & relink your tracker

Come to the Mihon Discord support channel if you need help, or for any basic troubleshooting/issues/questions.
