### ISSUE TITLE
App crash log

### ISSUE THREAD

**Issue by Fateh-Inder** [mihonapp/mihon#1610]
![mihon_crash_logs.txt](https://github.com/user-attachments/files/18266638/mihon_crash_logs.txt)

**Comment by Fateh-Inder** [comment]
Im sorry I didn't know there was a format to it. Could you please tell me
where to find it? It was my first time experiencing a crash. I didn't know
what to do.

**Comment by Smol-Ame** [comment]
Closing as invalid issue request

From the crash logs, seems like it's your device's/OS's own issue where it killed the app prematurely, nothing we can do about it.

Also, for crash logs (which it says in the crash screen), send it to the Mihon Discord support channel instead for quick troubleshooting/discussion first.
