### ISSUE TITLE
Can't install extension. 

### ISSUE THREAD

**Issue by dark-f1are** [mihonapp/mihon#1613]
### Steps to reproduce

1. Enable incognito mode 
2. Try to install any extension 

### Expected behavior

The extension should get installed like usual. 

### Actual behavior

The extension installing gets stuck at pending. 

### Mihon version

App version: 0.17.1-7043 (standard, c5655e880, 9, 2024-12-21T21:18:57Z) Android version: 11 (SDK 30; build RP1A.200720.012 release-keys) Device brand: vivo Device manufacturer: vivo Device name: 1906 (1906) Device model: vivo 1906 WebView: Android System WebView 131.0.6778.104

### Android version

"Android 11" 

### Device

"Vivo Y11" 

### Other details

I don't know if it's supposed to be not install extension during incognito mode. So, it might be either a feature or a bug. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Works fine, and Incognito only pausing reading history.

Change your Installer type if needed in Mihon Settings > Advanced, change it to something else (but not Shizuku). Anything else is either user error or device/OS-related issues.
