### ISSUE TITLE
Number of entries instead of percentages when updating the library

### ISSUE THREAD

**Issue by Mjiopytr** [mihonapp/mihon#163]
### Describe your suggested feature

Would be possible to show the library updates with the number of titles being updated instead of percentages? It would help in keeping in check the amount of series added to the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> It would help in keeping in check the amount of series added to the library.

Library Filter -> Display -> Show number of items.

**Comment by Mjiopytr** [comment]
It's not the same thing since the numbers in the updates would show how many series are being updated in total.

**Comment by Mjiopytr** [comment]
> > It would help in keeping in check the amount of series added to the library.
> 
> Library Filter -> Display -> Show number of items.
It's not the same thing since the numbers in the updates would show how many series are being updated in total (which would also help in being aware of how each update impacts sites)
