### ISSUE TITLE
Windows/Linux Desktop Port?

### ISSUE THREAD

**Issue by matte22ladde** [mihonapp/mihon#167]
### Describe your suggested feature

Mihon should work like Tachidesk on desktop, as both have been inspired by Tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
That's the dumbest reason I've ever heard.

**Comment by Bmswad1** [comment]
Use WSA on windows 11, or use any emulator.
This is the best experience you will get on PC
