### ISSUE TITLE
Add Latest Tab Feed like Tachiyomi SY

### ISSUE THREAD

**Issue by KenzKD** [mihonapp/mihon#169]
### Describe your suggested feature

I really like this Latest Tab feed feature from Tachiyomi SY since I am someone who constantly checks for updates.

![image](https://github.com/mihonapp/mihon/assets/65004578/3e7ac545-73d5-429a-92ec-27c3dcee0a9d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
