### ISSUE TITLE
Manga filter (scanlator) improvement

### ISSUE THREAD

**Issue by mazyuin** [mihonapp/mihon#170]
### Describe your suggested feature

The filter should be able to : 
-> include/display chapters by certain scanlators only.
-> chapters with no scanlator should be an option to exclude-include too.

### Other details

Maybe show  ✅️  when include is enabled.
The point of this feature is to make the filter universal, as of now many extension have chapters with no scanlator detail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> include/display chapters by certain scanlators only.

Not a good thing UX wise as you'll never know if some other guy picked up the series

> chapters with no scanlator should be an option to exclude-include too.

If for some reason one chapter has scanlator and other doesn't you should take it up to the extension dev to add some fallback.

> as of now many extension have chapters with no scanlator detail.

Extension issue. I'm not gonna accommodate for it.

**Comment by mazyuin** [comment]
>> Not a good thing UX wise as you'll never know if some other guy picked up the series
Would it even matter? As i see it, with the current scanlator filter, it still show all new chapters in updates even if you set the filter to exclude other scanlator. This way you can actually see someone picked up new series.

>> If for some reason one chapter has scanlator and other doesn't you should take it up to the extension dev to add some fallback.
So it's not possible to select no scanlator as an option, alright.

**Comment by mazyuin** [comment]
> Not a good thing UX wise as you'll never know if some other guy picked up the series

Would it even matter? As i see it, with the current scanlator filter, it still show all new chapters in updates even if you set the filter to exclude other scanlator. This way you can actually see someone picked up new series.

> If for some reason one chapter has scanlator and other doesn't you should take it up to the extension dev to add some fallback.

So it's not possible to select no scanlator as an option, alright. Thank you for the reply

**Comment by mazyuin** [comment]
@AntsyLich 
> Not a good thing UX wise as you'll never know if some other guy picked up the series

Would it even matter? As i see it, with the current scanlator filter, it still show all new chapters in updates even if you set the filter to exclude other scanlator. This way you can actually see someone picked up the series, and if it shouldn't work like that, this may be an idea for improvement.

> If for some reason one chapter has scanlator and other doesn't you should take it up to the extension dev to add some fallback.

So it's not possible to select no scanlator as an option, alright. Thank you for the reply.
