### ISSUE TITLE
Add notifications when a library is updating

### ISSUE THREAD

**Issue by 74kb** [mihonapp/mihon#172]
### Describe your suggested feature

It should have a notification like this (tachiyomi 0.14.7)
![_795252d85d346970f4fd7fe1b2acc495_1455518940_Screenshot_2024-01-21-18-44-37-104_eu kanade](https://github.com/mihonapp/mihon/assets/64794158/0c0a09ac-730d-4928-a554-3aaef5c396bc)
![_3f0e18009e1d405aff6b0bab21d9f724_1733412085_Screenshot_2024-01-21-18-45-20-896_eu kanade](https://github.com/mihonapp/mihon/assets/64794158/e5f1f6ed-1d8a-433e-97ae-bd6f05698213)

But in tachiyomi 0.15.0 and later versions there's only a icon disappeared suddenly within a second
![_adcaf4624bd15bb426594692b8941239_-382183222_Screenshot_2024-01-21-18-47-36-838_app](https://github.com/mihonapp/mihon/assets/64794158/a158e578-897c-4f0b-a1d0-1b7948eaeb13)

### Other details

I'm not sure if it is a bug or only occurs in my devices which runs MIUI14 by Android13.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Can't reproduce on my device or emulator. Make sure you don't have notification blocked or something by one of the system settings.

**Comment by 74kb** [comment]
> Can't reproduce on my device or emulator. Make sure you don't have notification blocked or something by one of the system settings.

I got it! The new feature 'Smart update' causes the problem. When I turned off the option, everything went back.
