### ISSUE TITLE
Add a mark all as read button in manga page

### ISSUE THREAD

**Issue by rithgan** [mihonapp/mihon#175]
### Describe your suggested feature

Currently the mark as read button is only available from notifications panel.
If notifications are disabled or you accidentally dismiss the notification, there is no way to mark all chapters as read in the particular manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Select All -> Mark as Read
