### ISSUE TITLE
Extensions are not being updated (and it's not clear why)

### ISSUE THREAD

**Issue by asdkant** [mihonapp/mihon#179]
### Steps to reproduce

Take an outdated extension and try to update it

### Expected behavior

APK should be installed correctly, and if not an error message explaining why it didn't should appear somewhere. If there are known conditions where an extension updated APK will not be installed, the main app should catch those and warn the user

### Actual behavior

Extension update APK fails silently and user it not notified in any way

### Mihon version

0.16.1

### Android version

11 (Samsung OneUI 3.1)

### Device

Galaxy Tab S5e

### Other details

This happens for every extension that has updates, I'm not sure if it's because the extensions provider is messing with APK signing or what. The only workaround I found is to uninstall the extensions and then install the newer version (maybe the best solution is to have the app do that?)

The troubleshooting guide points to Split APK Installer (SAI) for diagnosis of this kind of issue but the app doesn't work with my android version (at least the play store doesn't let me install it)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Fixed by cb068984303f811692531bf6f14902ae118d8ac7

**Comment by AugustoPerezRomero** [comment]
How do I fix it. I don't get it can someone tell me what to do

**Comment by asdkant** [comment]
@AugustoPerezRomero try uninstalling the extension and then installing it again.

**Comment by AugustoPerezRomero** [comment]
Okay thanks that works!!
