### ISSUE TITLE
Chapters problem

### ISSUE THREAD

**Issue by Mingo3347** [mihonapp/mihon#180]
### Steps to reproduce

Opening anything to read whether it's manga or manhwa from any source, after clicking on the chapter, the chapter pages keeps going black between every page which is like every 2 secs, and I have to go up and then down again and repeating this process which is not practical at all and I can't read because of this bug

### Expected behavior

From the pages to appear normally without keeping on going black every pages 

### Actual behavior

Pages blacks out 

### Mihon version

0.16.1

### Android version

Android 11

### Device

Samsung a70 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Did you enable "Flash on page change" setting?

**Comment by Mingo3347** [comment]
Oh thank you, I didn't know about this. It's all good now.Sent from my Galaxy
-------- Original message --------From: AntsyLich ***@***.***> Date: 1/22/24  4:32 AM  (GMT+02:00) To: mihonapp/mihon ***@***.***> Cc: Mingo3347 ***@***.***>, Author ***@***.***> Subject: Re: [mihonapp/mihon] Chapters problem (Issue #180) 
Did you enable "Flash on page change" setting?
