### ISSUE TITLE
Add Trust All Extension Button

### ISSUE THREAD

**Issue by arfannn88** [mihonapp/mihon#183]
### Describe your suggested feature

Trusting one by one every extension is annoying after every extension update. You should add trust all extension button. One click trust is a must need feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by hsiayuchih** [comment]
agree

**Comment by Jaykoerner** [comment]
It's a hold over from when tachiyomi was self signing and hosting extensions, I'm near certain something will change, personally I'm in favor of my own request of fully removing the extension trust system, since it and it's current state does not actually protect against anything.

**Comment by SofiarDav** [comment]
I think that  keep that extension trust system. As a protective circumvention, or as a warning before adding.

**Comment by WGmg23** [comment]
i hpe that

**Comment by AntsyLich** [comment]
#320
