### ISSUE TITLE
App crashes after a restore from backup (r6454)

### ISSUE THREAD

**Issue by infyProductions** [mihonapp/mihon#185]
### Steps to reproduce

1. Create backup in phone and upload to cloud service (from Mihon Stable)
The backup I created contains:
- Library entries
- Categories
- Chapters
- History

(Backup creation on my phone)
![Screenshot_2024-01-22-10-56-49-48_551f7f0ca926862b368845ce7ee433aa](https://github.com/mihonapp/mihon/assets/31158494/9799db75-3f2c-43d9-bbaa-5cd0f1c58af3)

2. Download from cloud service and restore the backup (to Mihon Beta)
I just restored the following:
- Library
(Restore operation on WSA)

![Screenshot 2024-01-22 111856](https://github.com/mihonapp/mihon/assets/31158494/c46c8e6c-5c2b-416f-b714-640202bb1dd6)

3. Once it reaches 100%, it just pops up an error on the app but it successfully restores without any errors.

### Expected behavior

The crash screen shouldn't appear after finishing the restore process.

### Actual behavior

It crashes when the notification for the backup appears (although the backup was successfully restored without errors)
(Image: the notification of Mihon in Windows Action Center)
![Screenshot 2024-01-22 113002](https://github.com/mihonapp/mihon/assets/31158494/76afa582-fece-4b17-9f5c-e1ec143870df)

### Crash logs

(The problematic part starts at around line 25)

[tachiyomi_crash_logs_1-22-2024.txt](https://github.com/mihonapp/mihon/files/14004508/tachiyomi_crash_logs_1-22-2024.txt)

### Mihon version

Beta r6454

### Android version

Android 13

### Device

WSA version 2311.40000.5.0

### Other details

The backup was created on a stable version of Mihon (0.16.1) using a phone (Realme 6i), the restore target is on my WSA with version 2311.40000.5.0 (GAPPS patched) utilizing a beta version of Mihon (r6454)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Is this still an issue on newer beta/stable versions?

**Comment by infyProductions** [comment]
I'll try to test if it still crashes on a newer stable (0.16.3) and beta (r6499) combination.

Backup and restore test as of Jan/31/2024 with stable 0.16.4 and beta r6499:

- Backup (from beta - WSA) and Restore (to release - phone): No crash screen after restore

- Backup (from stable - phone) and Restore (to beta - WSA): No crash screen after restore

Screenshot 1:
![Screenshot 2024-01-31 142933](https://github.com/mihonapp/mihon/assets/31158494/9b5b8a74-e740-4ea0-99b0-9607305618d8)
Screenshot 2:
![image](https://github.com/mihonapp/mihon/assets/31158494/9d8577b1-d8bd-49aa-8925-e4303cd57cb9)

Note:
The backup and restore error in screenshot 2 is different since it's related to a chapter duplication in one of my entries but it's the only entry in my library in all categories.

**Comment by AntsyLich** [comment]
#647
