### ISSUE TITLE
Extensions not updating after restoring backup from Tachiomi

### ISSUE THREAD

**Issue by theolm** [mihonapp/mihon#192]
### Steps to reproduce

1. Install Mihon
2. Restore a Tachiomi backup with extensions not updated
3. Add the extension repo in Mihon
4. Mihon should find updates for the extensions
5. Hit update
6. Updates don't fail, but it doesn't work either.

### Expected behavior

After hit Update all OR a single update, the extension should be updated.

### Actual behavior

The update does not work.

### Crash logs

App version: 0.16.1 (standard, 6018aa9, 2, 2024-01-17T19:32Z)
Android version: 13 (SDK 33; build TKQ1.221013.002 test-keys)
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: nabu (nabu_global)
Device model: 21051182G
WebView: Android System WebView 120.0.6099.230

Problematic extensions:
- AnimaRegia
  Installed: 1.4.10 / Available: ?
  Obsolete: true
- Arthur Scan
  Installed: 1.4.36 / Available: 1.4.37
  Obsolete: false
- Drope Scan
  Installed: 1.4.36 / Available: 1.4.37
  Obsolete: false
- Gekkou Scans
  Installed: 1.4.33 / Available: 1.4.35
  Obsolete: false
- Illusion Scan
  Installed: 1.4.32 / Available: 1.4.33
  Obsolete: false
- Império Scans
  Installed: 1.4.33 / Available: 1.4.35
  Obsolete: false

--------- beginning of system
01-20 10:56:39.761 17093 17093 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
01-22 09:00:53.609 23880 23880 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
01-22 09:09:22.101  9550  9550 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
--------- beginning of main
01-22 09:15:55.240  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:15:55.515  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:15:55.764  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:01.092  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:02.818  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:02.846  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:04.939  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:04.982  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:05.033  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:05.033  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:06.437  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:06.519  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:06.562  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:09.891  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:22.115  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:22.187  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:47.639  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:16:57.997  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:00.163  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:12.712  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:12.826  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:12.964  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:16.966  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:17.547  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:25.679  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:25.767  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:25.993  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:26.015  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:27.739  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:29.907  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:31.085  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:34.650  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:35.895  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:36.775  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:40.105  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:41.095  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:44.605  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:44.634  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:48.685  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:52.417  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:17:59.856  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:02.252  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:03.296  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:06.119  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:07.269  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:38.969  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:45.644  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:46.763  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:46.763  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:47.122  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:47.194  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:57.240  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:57.257  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:58.208  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:59.700  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:59.790  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:18:59.810  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:19:07.975  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:19:15.854  9550  9550 E FileUtils: err write to mi_exception_log
01-22 09:19:19.102 20853 20853 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
01-22 09:19:19.312 20853 20853 E FileUtils: err open mi_exception_log errno=2
01-22 09:19:19.312 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:19.320 20853 24284 E SQLiteLog: (283) recovered 138 frames from WAL file /data/data/app.mihon/databases/tachiyomi.db-wal
01-22 09:19:19.331 20853 20853 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
01-22 09:19:19.367 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:19.400 20853 24299 E chromium: [ERROR:variations_seed_loader.cc(37)] Seed missing signature.
01-22 09:19:19.760 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:19.818 20853 24359 E SQLiteLog: (284) automatic index on C(manga_id)
01-22 09:19:19.818 20853 24359 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-22 09:19:19.879 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:19.879 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:19.889 20853 24290 E libEGL  : pre_cache appList: ,,
01-22 09:19:20.153 20853 24290 E LB      : fail to open node: No such file or directory
01-22 09:19:22.352 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:23.627 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:31.256 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:39.228 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:19:40.396 20853 20853 E BinderMonitor: err open binder_delay errno=2
01-22 09:19:40.396 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:29:01.126 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:29:02.152 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:29:06.896 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:29:18.487 20853 20853 E FileUtils: err write to mi_exception_log
01-22 09:29:20.572 20853 20853 E FileUtils: err write to mi_exception_log

### Mihon version

0.16.1

### Android version

13

### Device

MiPad 5

### Other details

Video of the bug

https://github.com/mihonapp/mihon/assets/9647399/7f8a6f71-b4c9-40a1-8648-15b3c2ec6d8f

- Removing the extension and installing it again solve the problem.
- IDK how the extensions work, but I think it's related to the fact that my device already had these extensions installed.
-  Even outdated, the extensions seem to work fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Jaykoerner** [comment]
Old extensions from tachi were built by different person then the new ones added  by any of the new repos, the issue you're having is the signatures of the apps are mismatching... And the os is refusing to install. This is not something mihon can fix. This is a basic Android security feature built into the OS. The only thing mihon could possible do is scan both the extisting extension and then new one and warn of a mismatch(something I feel is possibly outside of scope at the moment)


The exact same problem will happen if you move from one repo to another with the same extension available in both. This is an ongoing issue that cannot be fixed from mihons end without inherently reworking how extensions function

**Comment by asp616848** [comment]
The challenge you're facing stems from the fact that the older extensions from Tachi were developed by a different person compared to the new ones added by various repositories. The issue lies in the mismatch of signatures between these apps, leading to the operating system rejecting the installation. It's essential to understand that this is not something Mihon can directly resolve, as it is a fundamental Android security feature embedded in the OS.

Addressing this problem involves a complex scenario where moving between repositories with the same extension can trigger a similar issue. Unfortunately, this is an ongoing challenge that cannot be entirely resolved by Mihon without a significant overhaul in how extensions function. One potential workaround could be for Mihon to perform a scan of both the existing and new extensions, providing a warning in case of a signature mismatch. However, implementing such a feature might be beyond the current scope of Mihon's capabilities.

**Comment by theolm** [comment]
@Jaykoerner @asp616848 Thank you very much for the context. The explanations make a lot of sense, and the described fix wouldn't be practical for the application, as it would be too much work. That said, this scenario will still be very common for everyone transitioning from Tachiyomi to Mihon. I believe we could at least include an alert in the onboarding, informing the user that they must reinstall all extensions.

Should I close the issue?

**Comment by dthunes** [comment]
I had the same issue. Would it be sufficient to place the warning under Settings > Browse > Extension repos, or would that be too confusing because the problem only presents under Browse > Extensions?

**Comment by theolm** [comment]
I would add a warning in the onboarding with a link to a wiki page. It would be easier to maintain.
