### ISSUE TITLE
Clean downloaded chapters

### ISSUE THREAD

**Issue by CodeSpoof** [mihonapp/mihon#193]
### Describe your suggested feature

Like in J2K some kind of method to get rid of all chapters, that aren't in the Library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Closing in favor of #565 (more detailed & somewhat of a discussion)
