### ISSUE TITLE
Sort order per category in Library

### ISSUE THREAD

**Issue by stinger-devel** [mihonapp/mihon#198]
### Describe your suggested feature

In Library, instead of applying selected sort to all categories, each category should have its own seperate sort order (like in J2K).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Already a thing. Explore the app.
