### ISSUE TITLE
Is the app licensed MPL, Apache?

### ISSUE THREAD

**Issue by nonproto** [mihonapp/mihon#199]
### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Crash logs

N/A

### Mihon version

N/A

### Android version

N/A

### Device

N/A

### Other details

GitHub thinks the app is license Apache, the readme says MPL.  Which one is it?

If it's MPL please begin to add headers as required.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The codebase will remain Apache for the foreseeable future. The license change in readme was an oversight. I'll change it back.

**Comment by AntsyLich** [comment]
New Files/Modifications will be under Mihon still under Apache 2.0 license.
