### ISSUE TITLE
It doesnt inherit downloads

### ISSUE THREAD

**Issue by IntensityIntensifies** [mihonapp/mihon#2]
### Steps to reproduce

Install tachiyomi
Download something through an extension
Install mihon
Set it to the same file as tachiyomi

### Expected behavior

I expected files that are downloaded to show up in both apps since they have the same directory 

### Actual behavior

The files done show as downloaded

### Tachiyomi version

Mihon 1.16, Tachiyomi 1.15.2

### Android version

Android 13

### Device

Samsung a52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Tsuukaima** [comment]
Close the app, clear your cache in android settings (should be under Storage), reopen the app and your downloads should be there if you set it to the same path as you previously used.

**Comment by SadmL** [comment]
Also u can make backup in Tachiyomi, then restore it in Mihon.

**Comment by Neshura87** [comment]
Closing the App and clearing Cache is required even after restoring a Backup. Imo this should be displayed somewhere more prominently because it's something most users migrating will need to know.

**Comment by SadmL** [comment]
> Closing the App and clearing Cache is required even after restoring a Backup. Imo this should be displayed somewhere more prominently because it's something most users migrating will need to know.

Idk, I just installed Mihon, restored backup and it works without app closing and cache clearing 🤷
