### ISSUE TITLE
Manga/YaoiLib extension??

### ISSUE THREAD

**Issue by RoniAlberich04** [mihonapp/mihon#200]
### Steps to reproduce

Hello!

I recently saw, that Tachiomi closed down and I found this app, trying to download third party extension that worked previously on Tachiomi pretty fine,, but I find it confusing on how to add it to Mihon...

### Expected behavior

This extension is must be in index.min.json to add this to Mihon 

### Actual behavior

This 3rd party extension does not have official app or the Jason extension, so I have 0 idea what to do...

### Mihon version

0.16.1

### Android version

One UI 6.0

### Device

Samsung Galaxy S23 Ultra

### Other details

I just downloaded the app and was too scared to update.... I am too confused in how to use the extensions that supposed to be available...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This is not the place to ask for extensions, go ask whoever is providing your repo, and don't name repos here 👍

**Comment by RoniAlberich04** [comment]
I'm asking for extensions, I'm asking what should I at least do? I don't understand how to add them...

**Comment by MajorTanya** [comment]
This is still not the place to do that, ask your repo maintainer for instructions
