### ISSUE TITLE
Whether batch downloads can be added

### ISSUE THREAD

**Issue by wbmins** [mihonapp/mihon#203]
### Describe your suggested feature

Check the basic comic as unread, then check the basic comic download unread, there are no download tasks in the download queue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Did you check that it didn't just take a moment for the chapters to appear in the download queue and start downloading?

I did a test with an entry of about 50 unread chapters and it took Mihon a few moments before the downloading notification (and Large Downloads warning) appeared and subsequently filled the queue.

**Comment by wbmins** [comment]
> Did you check that it didn't just take a moment for the chapters to appear in the download queue and start downloading?
> 
> I did a test with an entry of about 50 unread chapters and it took Mihon a few moments before the downloading notification (and Large Downloads warning) appeared and subsequently filled the queue.
I really haven't noticed this. I'll try it again and give you feedback later.

**Comment by wbmins** [comment]
I really haven't noticed this. I'll try it again and give you feedback later.
