### ISSUE TITLE
Shinigami: There are no chapters other than "Siapa sangka"

### ISSUE THREAD

**Issue by rzlCL** [mihonapp/mihon#220]
### Steps to reproduce

After I change my user agent strings, in Shinigami extension there are no chapters than "Siapa sangka" but if I don't change my user agent strings, I can't bypass the cloudflare thing.

### Expected behavior

There must be a chapter appeared in manhwa inside shinigami.

### Actual behavior

But no one appear other than "Siapa Sangka"
![Screenshot_20240124-182846_Mihon](https://github.com/mihonapp/mihon/assets/156214524/a5240f04-2341-40c7-bdfb-43fd169b4018)

### Mihon version

0.16.1

### Android version

Android 11

### Device

Realme 5i

### Other details

No chapters appear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon doesn't provide extension support
