### ISSUE TITLE
Yo!

### ISSUE THREAD

**Issue by adilhyz** [mihonapp/mihon#226]
### Steps to reproduce

A little question how to add a new extension previously I used tachiyomi

### Expected behavior

-

### Actual behavior

-

### Crash logs

-

### Mihon version

0.16.1

### Android version

Android 11

### Device

Oppo A54

### Other details

I miss the more extensions old tachiyomi to have :disappointed: 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by sdaqo** [comment]
Refer to this: https://mihon.app/docs/faq/browse/extensions#what-are-some-recommended-extensions-and-sources and this: https://mihon.app/docs/guides/getting-started#adding-sources (under "External Repositorys").

**Comment by adilhyz** [comment]
> Refer to this: https://mihon.app/docs/faq/browse/extensions#what-are-some-recommended-extensions-and-sources and this: https://mihon.app/docs/guides/getting-started#adding-sources (under "External Repositorys").

Well, if that's the solution, I now understand why the extension had to manually search for itself. I understand that the core Tachiyomi project is no longer under active development due to recent events involving the threat of Kakao Entertainment Corp.

https://tachiyomi.org/news/2024-01-13-goodbye

well thanks dude for making a very useful project for reading comics I look forward to good achievements ahead :D
![emoji-4827090__480](https://github.com/mihonapp/mihon/assets/100203867/ebe675dd-8bd1-435b-93be-c45ac9e08b1d)
