### ISSUE TITLE
folder extension and private categories 

### ISSUE THREAD

**Issue by Vierilukmantia** [mihonapp/mihon#227]
### Describe your suggested feature

add a feature to hide categories and you can create folders for extensions to make it neater and if you can update Mihon with your own UI, make Mihon fresher, that's all. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Hidden categories have been denied before in #72.
Folders for extensions I can't see happening.
"own UI" as in "Custom/own Themes" isn't happening either.

Closing as not planned. If you have further questions, join the Support Discord and ask there.
