### ISSUE TITLE
Please Include this TachiyomiJ2k features to Mihon

### ISSUE THREAD

**Issue by epti123** [mihonapp/mihon#228]
### Describe your suggested feature

When You Have A Long list Of Title you are reading, you can't keep track all of them. So by adding TachiyomiJ2k (Not-Started and In Progress) features you can easily track them.
![Screenshot_2024-01-25-08-06-35-09_5901a79de973a50c74cff4cbb6149856](https://github.com/mihonapp/mihon/assets/90287176/6da0386b-f22f-4774-aea4-7425dceae598)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment]
its already there? 
in library filter (started)

**Comment by peepincreepin** [comment]
> its already there? in library filter (started)

Yep, you're correct, you can achieve the same thing by toggling ![this filter.](https://github.com/mihonapp/mihon/assets/83149496/15e9caa9-b5d5-4c9e-b5e8-76dddea7ff26).
