### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Gabriel062323** [mihonapp/mihon#229]
### Describe your suggested feature

add an option for multi profiles or for put a photo here that represents the user
![Screenshot_2024-01-24-23-43-36-347_app mihon debug](https://github.com/mihonapp/mihon/assets/155345383/6edd444c-8d75-4181-9d74-37384b0598ce)
where the logo is
I think this will create a more user-friendly interface

### Other details

like the multi user in Facebook or Netflix , youtube etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment]
I don't see how this would be worth focusing time on when there is no login system / profile system
