### ISSUE TITLE
Can't download gallert in WSA.

### ISSUE THREAD

**Issue by shereshiia** [mihonapp/mihon#230]
### Steps to reproduce

Can‘t download gallery in WSA, the "Continue" button on the download page will automatically change to pause when pressed.

### Expected behavior

Able to download gallery.

### Actual behavior

Couldn't download any gallery, I think it's a document management system empowerment issue with WSA.
My storage path is /storage/emulated/0/Android/media/mihon

### Crash logs

App version: 0.16.1 (standard, 6018aa9, 2, 2024-01-17T19:32Z)
Android version: 13 (SDK 33; build TQ3A.230901.001)
Device brand: Windows
Device manufacturer: Microsoft Corporation
Device name: windows_x86_64 (windows_x86_64)
Device model: Subsystem for Android(TM)
WebView: Android System WebView 118.0.5993.111

--------- beginning of main
01-25 17:26:17.598  2946  3349 E app.mihon: open_verbose_path:56: Could not open '/dev/goldfish_pipe_dprctd': No such file or directory
01-25 17:26:17.598  2946  3349 E app.mihon: open_verbose:128: both vsock and goldfish_pipe paths failed

### Mihon version

0.16.1

### Android version

android 13

### Device

wsa

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon doesn't officially support WSA

**Comment by infyProductions** [comment]
Fellow WSA user here. You can't pick (or use) the "Android" folder due to the popular: "`Can't Use This Folder, To Protect Your Privacy, Choose Another Folder`" error.

Try changing the storage location to a user-accessible folder (like /storage/emulated/0/Mihon) and try again.
