### ISSUE TITLE
Bluestacks Support Please

### ISSUE THREAD

**Issue by Baniita** [mihonapp/mihon#231]
### Describe your suggested feature

Hi, trying to install Mihon onto x64 Bluestacks, Android 7.1.1, all the versions was given
"There was a problem parsing the package."

I don't have any more room on my phone to mass-farm Bilibili atm lol;;

Halp?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
You need Android 8 to run Mihon
