### ISSUE TITLE
Can't scan for update library

### ISSUE THREAD

**Issue by SogenMugen** [mihonapp/mihon#235]
### Steps to reproduce

When you press update library it doesn't update, it only run like 1sec and done. You need to manually update each one individually because it doesn't work if you scan all

### Expected behavior

After updating the libraries to give new updates of new updated manga chapters it should give you the latest chapters

### Actual behavior

When you press the "Update library button" it doesn't give you the latest manga updates unless you manually scan then one by one

### Mihon version

16.0.1

### Android version

Android 12

### Device

Huawei Nova 7 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by molitar** [comment]
If the updates is this way then this is a broken POS app. It is impossible to be updating single files when I have 157 mangas I follow. At this time it's back to TachiyomiSY

**Comment by MajorTanya** [comment]
If you asked in the Discord, we could properly take time to explain this to you. Closing and locking the issue as it's not an issue.

**Comment by kalanyah** [comment]
so you guys are telling me that a function called "update library", which should update all you manga automatically, is not doing what it's supposed to but in your terms it's "expected behavior" and even though theres this option i have to manually update all my stuff?

its like having a drive through but you still have to get off the car, go inside the store and pay/get your food
