### ISSUE TITLE
Can't read on mangageko

### ISSUE THREAD

**Issue by Chaosmayme** [mihonapp/mihon#237]
### Steps to reproduce

![Screenshot_20240126_084638](https://github.com/mihonapp/mihon/assets/94779387/c039f226-8f75-446c-a9ae-e11f849c11a8)

### Expected behavior

When opening it should show library

### Actual behavior

Error page

### Mihon version

0.16.1

### Android version

Android 14

### Device

Iqoo 9 se

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Source/Extension issue, not Mihon issue. Please ask whoever you get this extension from for help or instructions, not Mihon.

**Comment by Nul-led** [comment]
their cert expired, website is at fault here
