### ISSUE TITLE
crash log update

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#239]
### Steps to reproduce

when you try to enable trust with macro recorder 3x faster

### Expected behavior

just continue run the app🤣

### Actual behavior

app display crash log

### Crash logs

tachiyomi/mihon_crash_logs

App version: 0.16.1-6458 (standard, 38d6ab80c, 2, 2024-01-20T21:14Z)
Android version: 11 (SDK 30; build RP1A.200720.011)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia (begonia_eea)
Device model: Redmi Note 8 Pro
WebView: Android System WebView 122.0.6261.5

--------- beginning of system
--------- beginning of main
01-26 07:53:17.248 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:17.414 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:18.712 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:20.042 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:21.363 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:22.621 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:23.836 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:24.029 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:25.321 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:32.810 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:33.329 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:39.275 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:40.620 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:41.189 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:41.981 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:43.234 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:43.864 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:44.605 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:46.043 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:46.916 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:47.258 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:48.804 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:53:49.547 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:16.007 14829 14829 E app.mihon.debu: Invalid ID 0x00000000.
01-26 07:54:19.263 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:19.846 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:19.896 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:20.255 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:20.702 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:21.687 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:22.186 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:23.566 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:23.643 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:24.492 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:25.415 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:25.927 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:26.269 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:26.682 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:30.713 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:31.189 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:31.681 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:33.463 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:33.723 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:35.947 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:37.141 14829 14829 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:37.345 22473 22473 E g:error_handle: Not starting debugger since process cannot load the jdwp agent.
01-26 07:54:37.459 22491 22491 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
01-26 07:54:37.559 22473 22515 E SQLiteLog: (283) recovered 607 frames from WAL file /data/data/app.mihon.debug/databases/tachiyomi.db-wal
01-26 07:54:37.579 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:37.591 22473 22473 E g:error_handle: Invalid ID 0x00000000.
01-26 07:54:37.714 22491 22550 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
01-26 07:54:38.458 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.484 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.507 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.531 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.552 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.572 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.594 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.614 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.640 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.689 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.703 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.722 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.742 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.758 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.779 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.800 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.819 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.838 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.860 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.882 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.888 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.902 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.922 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.924 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.950 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.951 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.968 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.985 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:38.990 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.012 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.017 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.032 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.046 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.059 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.076 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.080 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.097 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.109 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.115 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.136 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.148 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.154 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.177 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.197 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.217 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.233 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.239 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.256 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.260 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.279 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.288 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.302 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.320 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.325 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.340 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.343 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.373 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.401 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.430 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.437 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.458 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.459 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.476 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.491 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.496 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.508 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.523 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.546 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.565 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.583 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.600 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.619 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.638 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.657 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.658 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.671 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.686 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.693 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.717 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.718 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.740 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.759 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.766 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.789 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.800 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.820 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.826 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.846 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.856 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.863 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.887 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.929 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.961 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.982 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:39.995 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.017 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.025 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.047 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.055 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.071 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.086 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.116 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.118 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.144 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.149 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.168 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.181 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.213 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.245 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.264 22473 22473 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.273 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.307 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.360 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.393 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.434 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.483 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.569 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.623 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.642 22473 22520 E ion     : ioctl c0044901 failed with code -1: Invalid argument
01-26 07:54:40.648 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.681 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.744 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.807 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.849 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.877 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.931 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:40.971 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.012 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.041 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.080 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.119 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.359 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.387 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.452 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.494 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.527 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.600 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.640 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.686 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.897 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.937 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:41.979 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:42.094 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:42.133 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
01-26 07:54:42.169 22491 22491 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"

### Mihon version

0.16.1

### Android version

Android 11

### Device

begonia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Remake the issue if you can reproduce without using external software
