### ISSUE TITLE
Cant log in to google linked account in Mihon web view

### ISSUE THREAD

**Issue by Naanaa28** [mihonapp/mihon#242]
### Steps to reproduce

1. Enter into bilibilicomics extension
2. access webview login page
3. log in via Google.

### Expected behavior

I just wish to be able to successfully log in and access my library

### Actual behavior

![Screenshot_20240127-105144_Mihon](https://github.com/mihonapp/mihon/assets/151754223/442a3859-78b8-4fe5-9f0d-f2e94e6f7162)

### Crash logs

It says to have javascript turned on. Can this be done?

_No response_

### Mihon version

0.16.1

### Android version

Android 10

### Device

Galaxy Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Google doesn't like WebView which we use for login. Try with some regular email password combination.

**Comment by Naanaa28** [comment]
> Google doesn't like WebView. Try with some regular email password combination.

but that's the account I have with all the unlocked chapters. Is there no way to be able to access it at all?? QAQ

**Comment by AntsyLich** [comment]
Not through Mihon.
