### ISSUE TITLE
customize the reading mode for each category

### ISSUE THREAD

**Issue by You2420** [mihonapp/mihon#247]
### Describe your suggested feature

Could you please add a feature allows to customize the reading mode for each category

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. Also you didn't consider what happens when a manga is in two categories did you?
