### ISSUE TITLE
Custom color filter settings per comic

### ISSUE THREAD

**Issue by WoxWik** [mihonapp/mihon#248]
### Describe your suggested feature

Since I have a color ereader, I need to apply grayscale to the bw comics to get full resolution.

 I have to turn this on and off depending on what I’m reading each time. Would be nice if it was saved per comic instead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not worth the maintenance hassle as this is very niche feature.
