### ISSUE TITLE
Error HTTP 403 Tracking

### ISSUE THREAD

**Issue by ChronoLux616** [mihonapp/mihon#262]
### Steps to reproduce

Tracker option show the error 403
![WhatsApp Image 2024-01-28 at 1 16 43 PM](https://github.com/mihonapp/mihon/assets/42309285/741f6f61-cb0f-4ea6-b680-f29a107366cf)

### Expected behavior

Update read chapters with the tracker I added.

### Actual behavior

it only shows the error mentioned above

### Crash logs

[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14077455/mihon_crash_logs.txt)

### Mihon version

0.16.2

### Android version

12

### Device

Galaxy A21s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by masdabazz** [comment]
I have the same as this expect mine says HTTP error 401

**Comment by AntsyLich** [comment]
Logout and login
