### ISSUE TITLE
Tracking link to myAnimeList not working

### ISSUE THREAD

**Issue by masdabazz** [mihonapp/mihon#266]
### Steps to reproduce

Go on tracking in settings. Click MyAnimeList. It will take you to webpage with login.

### Expected behavior

Enter login details, it connects to MyAnimeList and all entries are tracked.

### Actual behavior

I enter in my login details and the login goes away and just pops back up again. I am entering in the correct details as I used them log into mal on chrome on my phone and laptop.

### Mihon version

0.16.1

### Android version

Andriod 12

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Update your app

**Comment by masdabazz** [comment]
Yh sorry, there was no notification for new update for mihon so I had to check
