### ISSUE TITLE
[Feature Request] Bookmark images

### ISSUE THREAD

**Issue by matte22ladde** [mihonapp/mihon#270]
### Describe your suggested feature

When an image is bookmarked, the filter also works for the bookmarked image. 

### Other details

It helps reducing bandwith.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.2](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Could you elaborate a bit more on what you are looking for? I don't understand what you mean by the filters also applying or how it would reduce bandwidth

**Comment by AntsyLich** [comment]
No intention to implement
