### ISSUE TITLE
Opening the App requires unlocking, Pin, Password or Fingerprint!

### ISSUE THREAD

**Issue by LandonFZ** [mihonapp/mihon#277]
### Describe your suggested feature

I saw this function in the "K App" application, it works like this:
- First you go to settings > Security and Privacy, there would be an Application Protection option where you select a form of Protection (PIN, Password, Pattern, Fingerprint) saved and Restart the application, and when you open it it will ask to unlock the application using the form of Protection you chose.
- 
- Note: the image below is where you find this idea interesting and I think it would be a great option to add to Mihon!  
- 
- 
- Sorry for the inconvenience!!

### Other details

Images of the Function in the Other App, which I am suggesting to be Added here:
![Screenshot_20240129-143944-031](https://github.com/mihonapp/mihon/assets/137662523/1bd12fc8-14c5-45b0-a25a-9174cb7a6f1e)
I couldn't take a screenshot to show... Sorry!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.2](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
You can already do so. Check settings

**Comment by LandonFZ** [comment]
Thank you very much and sorry for the inconvenience!!
