### ISSUE TITLE
Bring back the Update Extension Function without Uninstalling, within the App.

### ISSUE THREAD

**Issue by LandonFZ** [mihonapp/mihon#278]
### Describe your suggested feature

My suggestion is to bring back the function of just clicking and updating the extension within the Application that it had before the Problems with the boring Korean company "Kko".  
 

### Other details

Uninstalling and reinstalling is a hassle with all due respect, the old versions before this "Reliable Extension" were better, now it's a lot of work, and you click to download (install a new one) or to download and install the Extension Update, it doesn't Update and has to be uninstalled, and when there is no need to uninstall the Extension it is resent to that "Trusted Extension", when it works and when it doesn't You have to close the application and open it again for the Extension to appear as installed, honestly it sucks.

Sorry for the bad words, and sorry for bothering you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.2](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This is a known bug and not the intended way for it to work. A fix is being worked on.
The "uninstall & reinstall" method is a workaround around this particular bug.
