### ISSUE TITLE
Can't add extensions 

### ISSUE THREAD

**Issue by ininyer** [mihonapp/mihon#281]
### Steps to reproduce

1. Open the extensions tab 

### Expected behavior

View a list of extensions 

### Actual behavior

ಥ⁠‿⁠ಥ
"that's strange"
![Screenshot_20240129-155708](https://github.com/mihonapp/mihon/assets/70581238/d82bce3a-a9e7-4d22-8a73-4817367a63b5)

### Mihon version

App version: 0.16.2

### Android version

Android 12

### Device

Motorola g60

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.2](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
There are no first part extensions

**Comment by WGmg23** [comment]
search tachiyomi extensions in google
