### ISSUE TITLE
Crash when pressing back to exit app

### ISSUE THREAD

**Issue by pudup** [mihonapp/mihon#282]
### Steps to reproduce

It's a bit difficult to reproduce but I have it happen quite often

First the app needs to be launched normally. 

Then leave the app without force closing it so that it's in the background.

Then the app needs to be removed from memory normally by the OS

Then when you open the app, it will resume but first it will show the splash screen, but definitely resumed from a cached state seemingly.

Then when you press back, the app crashes.

### Expected behavior

Should just exit normally

### Actual behavior

Crashes instead 

### Crash logs

App version: 0.16.2 (standard, 222e111, 3, 2024-01-27T18:31Z)
Android version: 13 (SDK 33; build T1SSIS33.1-75-7-3)
Device brand: motorola
Device manufacturer: motorola
Device name: rhodei (rhodei_g)
Device model: moto g62 5G
WebView: Android System WebView 120.0.6099.230

--------- beginning of main
01-29 23:57:30.175 25464 25464 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
01-29 23:57:30.276 25464 25497 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
01-29 23:57:30.353 25464 25522 E chromium: [ERROR:variations_seed_loader.cc(37)] Seed missing signature.
01-29 23:57:30.904 25464 25498 E SQLiteLog: (284) automatic index on C(manga_id)
01-29 23:57:30.904 25464 25498 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

### Mihon version

0.16.3

### Android version

13

### Device

Moto G62

### Other details

I've had this issue since Tachiyomi 0.15.3. AFAIK 0.15.2 and prior versions did not have it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.2](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by matheuscsoares** [comment]
I was about to open a new issue as this exact problem is also happening to me.
Here's my crash log, if it helps.
[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14088604/mihon_crash_logs.txt)

**Comment by pudup** [comment]
Thanks for providing a backdoor cuz my crashlog is broken.
It takes a bit of effort for me to reproduce it manually cuz phones these days have way too much RAM, so I couldn't regenerate the log.

**Comment by pudup** [comment]
@matheuscsoares Thanks for providing a log cuz my crashlog is broken.
It takes a bit of effort for me to reproduce it manually cuz phones these days have way too much RAM, so I couldn't regenerate the log.

**Comment by pudup** [comment]
Managed to reproduce it so I could get the error screen.

![Screenshot_20240130-013203](https://github.com/mihonapp/mihon/assets/35901162/fb6c89df-1166-4456-aec7-f8a2e140b18c)

![Screenshot_20240130-013209](https://github.com/mihonapp/mihon/assets/35901162/4f5a5542-ed18-4508-b103-749a364f99e1)

**Comment by CactusTheGuy** [comment]
Sorry about the mention above in issue #287, didn't know this opened, the closed is self close for being dumb dumb…

**Comment by CactusTheGuy** [comment]
I watched the app behavior before the crash. Able to know how to reproduce this reliably. But it require the app to be suspended by the OS.

Before the crash when exiting, when you enter the app, the app will freeze for a moment. That is when you have high chance to crash the app

**Comment by pudup** [comment]
To me it just seems like it's trying to move back to an activity that does not exist.

As an aside, if you move to another tab, like the Updates tab, and then back, it will not crash.

**Comment by dgw** [comment]
In #436 it was suggested that this could have something to do with edge-swipe gestures. However I see regular navigation buttons in screenshots on this ticket, so that idea is probably a red herring.

**Comment by pinglebon-orig** [comment]
[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14744062/mihon_crash_logs.txt)
Adding my own crash log as it doesn't seem to match the others.

**Comment by lin-ycv** [comment]
Here's my crash log, I use swipe gestures, only happens when I try to exit the app using the back gesture.
[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/15315278/mihon_crash_logs.txt)

**Comment by MajorTanya** [comment]
> Here's my crash log, I use swipe gestures, only happens when I try to exit the app using the back gesture. [mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/15315278/mihon_crash_logs.txt)

This log does not contain anything actionable nor any sort of crash data.

**Comment by lin-ycv** [comment]
> This log does not contain anything actionable nor any sort of crash data.

I pressed `share crash logs` from the crash screen, and chose Google drive, that was what it saved. 

The crash was something about currentTab used multiple times

**Comment by MajorTanya** [comment]
> > This log does not contain anything actionable nor any sort of crash data.
> 
> I pressed `share crash logs` from the crash screen, and chose Google drive, that was what it saved.
> 
> The crash was something about currentTab used multiple times

It's sadly a known problem where the "actual" crash doesn't make it to the log file sometimes (not any user's fault) - there is a fix for this in the works but may be some time before it's released in Mihon stable.

The currentTab key issue is well-known and currently without a fix or workaround.

**Comment by daredevil2033** [comment]
[mihon_crash_logs.txt](https://github.com/user-attachments/files/16680390/mihon_crash_logs.txt)
Finally found the appropriate issue. Have a bunch of these logs with corresponding screenshots. This one conveniently has a stack trace already included. Never used swipe gestures so that has to be a dead end.
