### ISSUE TITLE
add custom download back

### ISSUE THREAD

**Issue by WGmg23** [mihonapp/mihon#286]
### Describe your suggested feature

![Screenshot_2024-01-29-22-01-12-595_app mihon](https://github.com/mihonapp/mihon/assets/157928760/d8a7c7f5-f713-4904-a1d2-8e03c74aa842)

### Other details

....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
