### ISSUE TITLE
Downloaded Manhwa/Manga/Manhua Shareit

### ISSUE THREAD

**Issue by KenItsMe** [mihonapp/mihon#296]
### Describe your suggested feature

If you have a downloaded manhua/manga/manhwa you can share it to a friend through QR code. Like shareit app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Like, share the downloaded files with them?

**Comment by BrutuZ** [comment]
Open in WebView > Share

**Comment by infyProductions** [comment]
From Entry -> Kebab menu (More options) [The three dots on the top-right] -> Share -> <insert an app that allows you to create a QR code URL like `QR & Barcode Scanner` on F-droid>
