### ISSUE TITLE
Edit manga information

### ISSUE THREAD

**Issue by kevin930321** [mihonapp/mihon#297]
### Describe your suggested feature

Enable to edit manga's name, tags, writer information

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Duplicate of #5, please check before opening new issues.
