### ISSUE TITLE
"No Pages Found" bato.to

### ISSUE THREAD

**Issue by Axolki** [mihonapp/mihon#299]
### Steps to reproduce

1. Click on any manhwa/manga from bato.to extension
2. Click on any chapter, not downloaded before
3. "No Pages Found" error appears

### Expected behavior

Chapter opening because pages do exist if you check in web view

### Actual behavior

Tried clicking on a chapter and it didn't open

![Screenshot_20240131_145345_Mihon](https://github.com/mihonapp/mihon/assets/114354071/56d4a1cc-ae7f-4c73-8735-98a28f1ff49a)

### Mihon version

App version: 0.16.3

### Android version

Android 14

### Device

Samsung Galaxy S22 Ultra

### Other details

I tried updating the app and extension, clearing the data and cache, and changing default user agent string. Nothing worked.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
This is probably not related to the app and you will have to contact the repo where you got the extension.
