### ISSUE TITLE
Komga tracking not enabled by default when adding an entry to the library

### ISSUE THREAD

**Issue by brewkunz** [mihonapp/mihon#306]
### Steps to reproduce

1. Install de Komga extension (1.4.50) and setup
2. Explore the newly configured Komga server
3. Long tap on an entry to add it to the Mihon library
4. Open the newly added entry, tracking is not enabled by default

### Expected behavior

Step 3 should add the Komga's entry to Mihon library and enable tracking.

### Actual behavior

Step 3 adds the Komga's entry to Mihon library but does not enable tracking.

EDIT: I had the same issue with Tachiyomi.

### Mihon version

0.16.3

### Android version

Android 13

### Device

Pixel 4a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
> Is your extension name matching `eu.kanade.tachiyomi.extension.all.komga.Komga` ? (https://github.com/mihonapp/mihon/issues/304)
> From what I remember, it was working as long as you have the right name and had enabled it in the settings.

I can reproduce this from original tachiyomi and is probably related to #88 and can confirm tracking works just the tracker doesn't get added automatically on long press.

**Comment by brewkunz** [comment]
> Is your extension name matching `eu.kanade.tachiyomi.extension.all.komga.Komga` ? (#304) From what I remember, it was working as long as you have the right name and had enabled it in the settings.

I'm gonna have to check that. But yes as @THElegend5 pointed out, the tracking works but you have to manually enable it for every entries you add to the library, instead of it being enabled automatically when long pressing an entry.

**Comment by brewkunz** [comment]
> Is your extension name matching `eu.kanade.tachiyomi.extension.all.komga.Komga` ? (#304) From what I remember, it was working as long as you have the right name and had enabled it in the settings.

I checked, it is matching the name you mentioned : `eu.kanade.tachiyomi.extension.all.komga`.

**Comment by WorldTeacher** [comment]
Issue still persists on Mihon 0.16.5
Komga Version is 1.4. 57 and the name is 'all.komga'

Also happens on latest preview build of TachiyomiSY

**Comment by AntsyLich** [comment]
Closed via #1298
