### ISSUE TITLE
Allow user to change the items per row

### ISSUE THREAD

**Issue by connery0** [mihonapp/mihon#307]
### Describe your suggested feature

In the current version of the app it shows 2 covers per row, filling up my entire screen with a 2x2 collection of items.

This makes it more tedious to find any specific ones I'm looking for in categories with more entries, so I would like to be able to increase the number of items per row, scaling down their covers to accommodate.
As was possible in previous versions of the other one

![two sliders with a selectable number of items in portrait mode and landscape mode](https://i.imgur.com/gyxKBxy.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Library Filter -> Display
