### ISSUE TITLE
Novel reader/ Book reader

### ISSUE THREAD

**Issue by piyushk2000** [mihonapp/mihon#314]
### Describe your suggested feature

Integrating extentions and readers for novel, books and all would be good idea , manga readers also read novels and books, but we either have to download the whole book by searching it somewhere , or in case of novels we have to go to websites to read with ads

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Xori71** [comment]
Mihon doesn’t affiliate itself with extensions. You’ll have to ask elsewhere.

**Comment by piyushk2000** [comment]
> Mihon doesn’t affiliate itself with extensions. You’ll have to ask elsewhere.

Then what about reader functionality, i mean if creators approve of it

**Comment by Xori71** [comment]
> > Mihon doesn’t affiliate itself with extensions. You’ll have to ask elsewhere.
> 
> Then what about reader functionality, i mean if creators approve of it

The reader functionality is there, provided the book is in a supported format (e.g. .cbz). You can download it and store it locally.

**Comment by Seishirou101** [comment]
https://mihon.app/docs/faq/general#can-i-read-light-novels and it has already been rejected before so won't be added.

**Comment by H1ghSyst3m** [comment]
> > https://mihon.app/docs/faq/general#can-i-read-light-novels and it has already been rejected before so won't be added.
> 
> Thnx for this i didn't knew it

I can recommend you "[lnreader](https://github.com/LNReader/lnreader)" for novels.
