### ISSUE TITLE
Option to change app icon theme?

### ISSUE THREAD

**Issue by Mehrad-Minimal** [mihonapp/mihon#32]
### Describe your suggested feature

You posted two icons on the discord server with different colors. Please give us an option to switch between in the actual app.
I know this is rather unnecessary but the dark mode one looks cooler 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
There is no native way to support icon changing and I'll rather not go with the hack and workarounds.

P.S. The dark icon is for Preview builds

**Comment by Mehrad-Minimal** [comment]
oh that's aight but telegram has it
