### ISSUE TITLE
Add the auto refresh setting

### ISSUE THREAD

**Issue by Snyret** [mihonapp/mihon#321]
### Describe your suggested feature

The moment you enter a manga on feed, this one auto-refreshes without you pulling the top of the entry.

### Other details

Could be added on advanced settings or the browse section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Feeds? Are you sure this and #322 shouldn't be on the fork's repo instead?
