### ISSUE TITLE
Latest chapter and chapter count when migrating source

### ISSUE THREAD

**Issue by ss7vegetto** [mihonapp/mihon#324]
### Describe your suggested feature

Please add this feature to better compare sources at a glance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
This will require to make x numbers of call on n numbers of sources for y number of users..... Seems like a DDoS bot net to me.
