### ISSUE TITLE
unable to install this mobile application on my device

### ISSUE THREAD

**Issue by 2380757563** [mihonapp/mihon#327]
### Steps to reproduce

I am unable to install this mobile application on my device, possibly due to Android 7 not being adapted. Can I make an adaptation for lower Android versions？

### Expected behavior

Successfully installed this app

### Actual behavior

unable to install this mobile app on my device

### Mihon version

0.16.3

### Android version

android7

### Device

HUAWEI M3

### Other details

我希望这个应用增加对安卓7的支持

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Support for Android 6 and 7 was dropped when Mihon was forked. This is in line with things like WebView deprecations and such. Closing as not planned.
