### ISSUE TITLE
Saved searches

### ISSUE THREAD

**Issue by derinakcay8** [mihonapp/mihon#33]
### Describe your suggested feature

ı think saved search is very useful feature and ı know tachiyomiSY already have but it be good see this feature in mihon 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Closing in favor of more detailed #164
