### ISSUE TITLE
Extensions crash phone

### ISSUE THREAD

**Issue by CinderBH** [mihonapp/mihon#331]
### Steps to reproduce

When I install, update, uninstall or set any extension to trusted, the phone crashes and I get a "System UI isn't responding" error, and the only recourse is to reboot it or wait for the UI to restart, after which it works normally.

### Expected behavior

The above shouldn't happen.

### Actual behavior

The above happens.

### Crash logs

[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14149421/mihon_crash_logs.txt)

### Mihon version

0.16.3

### Android version

Android 8

### Device

Samsung Galaxy A5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
A very interesting case, do you get some type of crash screen as well? If so, is the error shown the same as the one that appears a lot of times over in your attached crash logs? If not, would you be able to provide a screenshot of said crash screen?

**Comment by armangido** [comment]
I think the problem is the app doesn't have permission this was stated in the tachiyomi troubleshooting [https://tachiyomi.org/docs/guides/troubleshooting/common-issues](url)

**Comment by CinderBH** [comment]
> A very interesting case, do you get some type of crash screen as well? If so, is the error shown the same as the one that appears a lot of times over in your attached crash logs? If not, would you be able to provide a screenshot of said crash screen?

Not sure, but what happens basically is that everything freezes (and sometimes the screen goes dark) and I get the above error message after a few second with the choices "Close app" and "Wait".

**Comment by CinderBH** [comment]
Well, my phone was stolen and the new one doesn't experience the same glitch, so I guess this issue can be closed.
