### ISSUE TITLE
Large downloaded or local chapters take too long to load

### ISSUE THREAD

**Issue by demonic-avenger** [mihonapp/mihon#332]
### Steps to reproduce

To reproduce the issue
Step 1. Install the luscious.extenshion.
Step 2. Go to luscious settting and click the merge chapters and set mirrors to members.
Step 3. Now a download a gallery of 800+ images
Step 4. Now try to open that merged gallery chapter

### Expected behavior

As the merged chapter is fairly large it is expected to take a few seconds a few seconds to load the first time when you open it, but after that when you exit and open the chapter a second time it should load instantaneously

### Actual behavior

But instead, the second loading time is as slow the first loading time. The funny thing is, when you try to open the chapter without downloading it the second time, it actually loads instantly

### Mihon version

0.16.3

### Android version

Android 13

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closed by #326
