### ISSUE TITLE
Kenmei as tracking server

### ISSUE THREAD

**Issue by okaywhatfine** [mihonapp/mihon#333]
### Describe your suggested feature

Add Kenmei.co to Tracking Services

### Other details

I use it more than the other available ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
they don't have an api
