### ISSUE TITLE
Webtoons.com extention not working!!

### ISSUE THREAD

**Issue by beyondieee** [mihonapp/mihon#334]
### Steps to reproduce

tried, ain't working, would be pleasured if it was fixed

### Expected behavior

it should work 😭😭🙏

### Actual behavior

it kept making me wait

### Mihon version

0.16.3

### Android version

11

### Device

Samsung A54

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kitsumed** [comment]
Mihon is a manga/picture **local** reader. This is a extension issue, report it to where you got the extension from.

**Comment by AntsyLich** [comment]
We don't provide support for 3rd party extensions

**Comment by beyondieee** [comment]
> We don't provide support for 3rd party extensions

ok okay, sorry for that
