### ISSUE TITLE
f-droid 

### ISSUE THREAD

**Issue by cannnAvar** [mihonapp/mihon#346]
### Describe your suggested feature

Can we get updates from fdroid.
on fdroid there is tachiyomi's old apk.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Duplicate of #1

**Comment by cannnAvar** [comment]
> Duplicate of #1

Sory i didn't see that one
