### ISSUE TITLE
Yugenmangas.com 

### ISSUE THREAD

**Issue by arorva-326** [mihonapp/mihon#347]
### Describe your suggested feature

yugenmangas in Spanish moved its domain to ikigaimangas.com, please can you change that

### Other details

If this is not the correct forum to ask them to fix this, I apologize but I couldn't find another place

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jasshira266** [comment]
They have removed it because the extension is already added, look for it with the new domain:)

**Comment by AntsyLich** [comment]
Mihon doesn't provide 3rd part extension support

**Comment by arorva-326** [comment]
> They have removed it because the extension is already added, look for it with the new domain:)

Wher can i find this extension, I searched on mihon and couldn't find it

**Comment by jasshira266** [comment]
It is found in Spanish, they are in all of them, it appears normally, or if not, search manually in the reposts

**Comment by arorva-326** [comment]
> It is found in Spanish, they are in all of them, it appears normally, or if not, search manually in the reposts

Just appear invalid repo url with "ikigaimangas.com.index.min.json"

**Comment by jasshira266** [comment]
Wow, I do have the extension and it works normally, unless you give me your email and I'll send it to you or your discord

**Comment by MajorTanya** [comment]
Stop soliciting or distributing extension repositories in Mihon's Discord or GitHub please.

**Comment by arorva-326** [comment]
> Wow, I do have the extension and it works normally, unless you give me your email and I'll send it to you or your discord

Alejandromendoza8485@gmail.com
Srry this is the kas message

**Comment by NorseFenris** [comment]
Man you dumb, shared your email publicly

**Comment by arorva-326** [comment]
> Man you dumb, shared your email publicly

I'm not that stupid this is the email that i use for thins like this
