### ISSUE TITLE
PDF reading support in local file

### ISSUE THREAD

**Issue by soreat** [mihonapp/mihon#358]
### Describe your suggested feature

please add pdf reading support in local. As pdf can contain svg format , thats why its file size can be very low. if i go to convert into CBZ or CBR 10mb file becomes 250-300mb

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Ferk** [comment]
Some CBZ readers support svgs on them, like evince. Probably it would be easier and better to support that instead of pdfs

**Comment by HanaO00** [comment]
Sometimes the books are in PDF, it would be practical to be able to read the PDFs directly, MuPDF is very light and perhaps it is possible to integrate it with Mihon

**Comment by soreat** [comment]
.
