### ISSUE TITLE
Long press to copy introduction

### ISSUE THREAD

**Issue by Smile8848** [mihonapp/mihon#359]
### Describe your suggested feature

Make it the same as other long press copy options
![S40207-18143214](https://github.com/mihonapp/mihon/assets/31927778/3ca78645-1369-423c-85d2-1c05a73dc431)
![S40207-18142317](https://github.com/mihonapp/mihon/assets/31927778/edc2396f-71cd-499b-81c3-03bfa78d47f9)
like this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
People are more likely to copy a snippet instead of the whole thing
