### ISSUE TITLE
Notes should be included with the descriptions 

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [mihonapp/mihon#362]
### Describe your suggested feature

Searching a title/series in the app should include something like "Notes" or another set of details where the app should be able to show alongside the main descriptions of the series' titles.

These notes are quite handy, especially to some **licensed** series who are not available anymore, but was still given details what happened to the scanlations.

i.e. _the project was given a DMCA notice_ or something similar

This is helpful for those who are quickly browsing titles through the app alone.

### Other details

For reference of a "licensed" series.
Go to [THIS](https://mangadex.org/title/d8a959f7-648e-4c8d-8f23-f1f3f8e129f3/one-punch-man)
and look for Notes below the main descriptions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Ask repo maintainers to append note to description
