### ISSUE TITLE
Support for proxies (Socks5 if possible) per extension based or app based.

### ISSUE THREAD

**Issue by MrBasicX** [mihonapp/mihon#366]
### Describe your suggested feature

I think if possible adding proxies support per extension will be great or even with the app only. Some sources have very slow download speeds and using VPN does not always v due to cloudflare on some sources that I have encountered. I may be missing something, but just wanted to confirm if this will be a possibility.

From my limited knowledge of Android dev and googling, OkHttpClient does have proxy support.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Prabhu-K4T** [comment]
+1

**Comment by AntsyLich** [comment]
Closing based on my rationale here https://github.com/mihonapp/mihon/pull/519#issuecomment-2051107252
