### ISSUE TITLE
Can't read and download chapters on manganato

### ISSUE THREAD

**Issue by Baymax325** [mihonapp/mihon#369]
### Steps to reproduce

1. Select random manga
2. Try reading a chapter
3. Doesn't work

### Expected behavior

Should be able to read and download chapters 

### Actual behavior

Unable to read (Failed to connect)

### Mihon version

0.16.3

### Android version

Android 13

### Device

Mipad 4

### Other details

I tried fixing it thorough the methods in the website but it doesn't seem to work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Baymax325** [comment]
It was working fine a just yesterday

**Comment by MajorTanya** [comment]
Mihon doesn't provide extension-related support. Go ask whoever you got this extension from.
