### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by Anitabizz** [mihonapp/mihon#37]
### Steps to reproduce

I installed mihon on a new device and restore my backup from tachi but I don't have any extensions available even the ones I previously have. I tried installing the mihon as well on an old device that had the tachi app and I see my old extensions although I still can't search for new ones 

### Expected behavior

I should see at least my old extensions in the app 

### Actual behavior

I installed mihon on a new device and restore my backup from tachi but I don't have any extensions available even the ones I previously have. I tried installing the mihon as well on an old device that had the tachi app and I see my old extensions although I still can't search for new ones 

### Mihon version

Ver 16

### Android version

Android 13

### Device

Samsung A9 tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
There is no first party extension support

**Comment by Anitabizz** [comment]
Can you pls tell me how I can read my library if there are no extensions?

**Comment by AntsyLich** [comment]
You find 3rd party maintained extensions

**Comment by AntsyLich** [comment]
you don't need to manually install. you can just add the 3rd party repo to the app. Most should have instructions on how to do so.
