### ISSUE TITLE
Same content inside chapters with same name after download

### ISSUE THREAD

**Issue by kazu696** [mihonapp/mihon#371]
### Steps to reproduce

1: first pictures shows  2 chapters with same name
![WhatsApp Image 2024-02-09 at 8 05 14 PM](https://github.com/mihonapp/mihon/assets/159556072/0aa7168a-b93e-4ada-a1d9-9b8ad7ea9b6d)
2: i opened first chapter with same name. as you can see it has 1 picture
![WhatsApp Image 2024-02-09 at 8 05 54 PM](https://github.com/mihonapp/mihon/assets/159556072/e550798d-8a62-4166-a03c-84b532424ce9)
3: i opened second chapter with same name. as you can see it has 2 pictures
![WhatsApp Image 2024-02-09 at 8 06 14 PM](https://github.com/mihonapp/mihon/assets/159556072/ee3f9f9d-954e-43ab-b79a-4966da2fb5d2)
means even tho name is same content is different
4: i downloaded only one same name chapter. now all chapters with same name downloaded and showing same content
![WhatsApp Image 2024-02-09 at 8 06 37 PM](https://github.com/mihonapp/mihon/assets/159556072/ec746556-bbac-4ceb-b245-7e3f06acbaf4)

### Expected behavior

i expect it to show me the content i see before downloading same name chapters
![WhatsApp Image 2024-02-09 at 8 05 54 PM](https://github.com/mihonapp/mihon/assets/159556072/f8b1491b-891e-4c30-9330-80a893274090)
![WhatsApp Image 2024-02-09 at 8 06 14 PM](https://github.com/mihonapp/mihon/assets/159556072/1c47f457-c0f4-4b91-aa8b-ad07815e9899)
i uploaded 2 pictures. both these 2 has same name for chapters but different content

### Actual behavior

when i download even one same name chapter for some reason all same name chapters show downloaded and when open all same name chapters has same content

### Mihon version

beta r6501

### Android version

android 12

### Device

redmi note 11 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Closing in favor of #1395
