### ISSUE TITLE
More Download Option

### ISSUE THREAD

**Issue by JDKamalakar** [mihonapp/mihon#375]
### Describe your suggested feature

Ability to Download Last Chapters & Bookmarked chapters.

### Other details

Add option to auto Download Bookmarked Chapters (Auto Download section)

In download menu add option to Download last x chapters.

Last Chapter (Last read/Latest Chapters).

Note if the last read chapter in series in not in X Latest then only download latest X. 

Auto Download chapter after migration of source. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
How would "Auto download bookmarks" even work? Don't you usually bookmark after reading? Auto downloads are the ones happening when a library update happens and new chapters are detected. Those can't have bookmarks yet because they haven't existed in your Mihon yet.

**Comment by JDKamalakar** [comment]
Eg: when you restore backup, it will backup bookmarked chapters but if you don't transfer the downloaded files then they will remain bookmarked but will not be downloaded automatically, plus when you read it online then bookmark you will have to download it manually. 

And last senerio if you accidentally delete the file or the chapter.

**Comment by BrutuZ** [comment]
Filter [v] Bookmark [x] Downloaded > Select All > Download ?

**Comment by JDKamalakar** [comment]
It will take more steps than just downloading by pressing a single button.

**Comment by BrutuZ** [comment]
Got it, so you want someone else to waste their time instead programming a shortcut because you can't be bothered by a couple extra taps once

**Comment by JDKamalakar** [comment]
It would help a lot of people while they are transferring between devices, plus it would be useful for new users.

And even if there is a way to download bookmarked chapters but there is no way to download the last 3 chapters/new chapters (Even if readed)

**Comment by JDKamalakar** [comment]
> > It would help a lot of people while they are transferring between devices, plus it would be useful for new users.
> 
> I don't think that shortcut is happening still.
> 
> > And even if there is a way to download bookmarked chapters but there is no way to download the last 3 chapters/new chapters (Even if readed)
> 
> Actually thinking about it, the "Last X chapters" sounds like a not too bad option to me, could probably be done.
> 
> > And auto Download chapters after source migration (Download chapter that were downloaded previously, Either by auto deleting & downloading from new source or just moving the files).
> 
> Moving files isn't possible because the sources might be completely different in content. Auto downloading would be possible to do but feels unlikely, as it would be more automated download requests and Mihon tries to limit those as much as possible.

Solution, give a pop-up asking users if they want to download chapters when they migrate (Optional Show the bookmarked chapters that will be downloaded)

**Comment by JDKamalakar** [comment]
> > And even if there is a way to download bookmarked chapters but there is no way to download the last 3 chapters/new chapters (Even if readed)
> 
> Actually thinking about it, the "Last X chapters" sounds like a not too bad option to me, could probably be done.
> 

Yup.

**Comment by MajorTanya** [comment]
> 
> > Moving files isn't possible because the sources might be completely different in content. Auto downloading would be possible to do but feels unlikely, as it would be more automated download requests and Mihon tries to limit those as much as possible.
> 
> Solution, give a pop-up asking users if they want to download chapters when they migrate (Optional Show the bookmarked chapters that will be downloaded)

Chapter number might still not match. It's frustratingly common for some sources to upload split chapters (1.1, 1.2,...) while other go for full chapters (1, 2, 3,...) and yet others just upload volumes instead of single chapters.
This makes bookmark transfers unreliable at best and impossible at worst.

As to whether a user wants to download chapters from the newly migrated title, they can just use the normal download menu that's accessible to them immediately once they have migrated. Adding download options to the migration dialog or putting a popup dialog after the migration would not save any steps. The sequence goes
1. Go to menu
2. Select Migrate
3. Search equivalent title
4. Select the title
5. Confirm migration options
6. (you're now in the newly migrated title screen) Select the Download icon
7. Select your number of downloads of choice.

I don't think this is inconvenient for a user at all.

**Comment by JDKamalakar** [comment]
> > 
> > > Moving files isn't possible because the sources might be completely different in content. Auto downloading would be possible to do but feels unlikely, as it would be more automated download requests and Mihon tries to limit those as much as possible.
> > 
> > Solution, give a pop-up asking users if they want to download chapters when they migrate (Optional Show the bookmarked chapters that will be downloaded)
> 
> Chapter number might still not match. It's frustratingly common for some sources to upload split chapters (1.1, 1.2,...) while other go for full chapters (1, 2, 3,...) and yet others just upload volumes instead of single chapters.
> This makes bookmark transfers unreliable at best and impossible at worst.
> 
> As to whether a user wants to download chapters from the newly migrated title, they can just use the normal download menu that's accessible to them immediately once they have migrated. Adding download options to the migration dialog or putting a popup dialog after the migration would not save any steps. The sequence from the origin title page goes:
> 1. Go to menu
> 2. Select Migrate
> 3. Search equivalent title
> 4. Select the title
> 5. Confirm migration options
> 6. (you're now in the newly migrated title screen) Select the Download icon
> 7. Select your number of downloads of choice.
> 
> I don't think this is inconvenient for a user at all. 

Ok let go of the auto Download for the migrated series, but the rest of them makes sense.

**Comment by TheKingTermux** [comment]
Ahh please add Download for all Chapter (Read and unread chapters) for 1 entries, instead of selecting download button for a chapters that have been read

**Comment by TheKingTermux** [comment]
Ahh please add Download for all Chapter (Read and unread chapters) for 1 entries, instead of selecting download button for a chapters that have been read

**Comment by MajorTanya** [comment]
> Please add Download for all Chapter (Read and unread chapters) for 1 entries, instead of selecting download button for a chapters that have been read, it is very helpful for entries that have a lot of chapters

There won't be a "Download All" button in Mihon.

**Comment by AntsyLich** [comment]
The only thing I'll consider us downloading last x (read, unread doesn't make sense) chapters and not the other ones. Make a separate issue just for that.

**Comment by JDKamalakar** [comment]
> The only thing I'll consider us downloading last x (read, unread doesn't make sense) chapters and not the other ones. Make a separate issue just for that.

Ok, that also works.
