### ISSUE TITLE
Asura Scans (TR) extention 

### ISSUE THREAD

**Issue by beyondieee** [mihonapp/mihon#381]
### Describe your suggested feature

I was using tachiyomi before and I had it, now I tried to find it and couldn't. I would be happy if it was added to the extentions and I could download it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
You were told in your issue #334 that we do not provide extensions or extension support, and you even [commented on the closed issue about five minutes before opening this one](https://github.com/mihonapp/mihon/issues/334#issuecomment-1937517759).

No extensions here. No requests, no support, no fixes. Go and ask whoever you're getting your extensions from instead.
