### ISSUE TITLE
Manually typing the read chapters number doesn’t update the tracker

### ISSUE THREAD

**Issue by Xori71** [mihonapp/mihon#382]
### Steps to reproduce

1. Go to a manga.
2. Tap on the Tracker icon.
3. Manually input the number of read chapters, and then tap OK.

### Expected behavior

Normally, the number of read chapters should update to the one inputted.

### Actual behavior

What actually happens is that the number doesn’t update, and it instead remains what it originally was.

### Mihon version

0.16.3

### Android version

Android 14

### Device

Redmi Note 9 Pro

### Other details

https://github.com/mihonapp/mihon/assets/101265862/729b4cea-1b9c-46e6-bcaa-33a9b19f8c9b

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Sometimes, these kinds of updates are put into a queue of updates to be done, which will be handled later. Give it some time and see if it gets updated eventually.

You might also be hitting AniList's rate limit with too many updates at once, which will make Mihon try to wait until it's clear to post these up AniList.

**Comment by cuong-tran** [comment]
this was fixed with #1209

**Comment by Xori71** [comment]
Marking it as closes, seeing as that the behavior has been altered.
