### ISSUE TITLE
Make setting up the app possible without a file explorer installed

### ISSUE THREAD

**Issue by MissingNerd** [mihonapp/mihon#383]
### Describe your suggested feature

I was trying to set this up in my Jailbroken Tolino Reader but since Tachi 0.15. it apparently requires you to set a folder for downloads before being able to use the app. This is impossible in the heavily modified Android of these devices.

Please make it possible to get the app usable without this step. Make a default folder an option or something in that direction

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dean-Sean** [comment]
Not sure if my issue is the same as this.
I just tried to install it on my Realme Stick (running Google TV), and I couldn't get past the setup.
Tried installing other file explorers, but none were detected to work for the setup. Looked it up and saw lots of people on XDA having the same problem.

https://github.com/mihonapp/mihon/assets/159751719/83b66fd2-afd3-446c-abd6-f592ccb516fd

**Comment by AntsyLich** [comment]
To support newer versions of Android we now require the User to give us permission to write to a folder instead of having access to every single file and folder. So selecting a folder is crucial.

Also file picker is a core Android component. If it's missing from your build then you should complain to the devs of that build.
