### ISSUE TITLE
Image not opening bug (Downloaded chapters) Preview app

### ISSUE THREAD

**Issue by JDKamalakar** [mihonapp/mihon#384]
### Steps to reproduce

Download chapter from any source from any source.
Opening it will show image can't be loaded. 

### Expected behavior

Should open the chapters/pages

### Actual behavior

Gives error with retry option. (Which doesn't works)

### Mihon version

0.16.3-6505 app.mihon.debug

### Android version

Android 14

### Device

Google pixel 6A

### Other details

https://github.com/mihonapp/mihon/assets/101495154/d42b815b-fa2f-48ac-88e0-71088fa70477

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JDKamalakar** [comment]
Did it multiple times or only doesn't work in the preview app.

**Comment by AntsyLich** [comment]
Works fine for me

**Comment by JDKamalakar** [comment]
> Works fine for me

Not for me.

**Comment by MajorTanya** [comment]
Only that exact chapter? Try deleting it from Mihon and then go check the download folder Mihon is using for some temporary download in the same location. If you see this same chapter but with a _tmp in its name/folder name, delete that too, then invalidate your download index (Advanced Settings), and try to download it again.

If it persists after this, try reading it not downloaded. If it still persists, check the chapter in WebView. If it works there but still not in Mihon after all this, go ask your extension repo maintainer for help with this extension.

**Comment by MajorTanya** [comment]
Did you try to invalidate the download index from the advanced settings?

**Comment by JDKamalakar** [comment]
Yes

**Comment by MajorTanya** [comment]
I just saw you're using A14 on a Pixel 6A, does that mean you're in the QDPR betas for Android 14 on Pixels? Because we've seen some issues with those versions specifically.

Also, does the next chapter in this series work properly to download?

**Comment by JDKamalakar** [comment]
Yes I am in qpr beta, no downloading the next chapter won't open the chapters (preview app only) only of its Downloaded. 

Stable works fine.

**Comment by MajorTanya** [comment]
Curious issue
could you try downgrading to the r6501 preview of Mihon? If it doesn't work there, go down to latest stable. Downgrading might force you to reinstall the preview and/or stable apps, so make sure you have a fresh backup available 👍 

Looking back through the changes made in the meantime I don't see an obvious culprit for any of these.

**Comment by JDKamalakar** [comment]
Okay, I'll try it. Downloading my app version in few days and update the forum.

**Comment by JDKamalakar** [comment]
> Okay, I'll try it. Downloading my app version in few days and update the forum.
After installing older version of preview app it seems till version r6499 every thing works fine but something changed in r6501 that is causing this issue tried it multiple times.

**Comment by JDKamalakar** [comment]
0.16.3-6530 - debug
0.16.4 - Stable
Bug still occurs only in  preview build.

**Comment by JDKamalakar** [comment]
As of version 0.16.4-6560 (Preview App) bug seems to be fixed.
