### ISSUE TITLE
Downloading an single images doesn't work

### ISSUE THREAD

**Issue by Zambales7** [mihonapp/mihon#388]
### Steps to reproduce

1. Open one Manga or manhwa
2. Select a chapter
3. Hold the image panel
4. Error appears in notification that says **Error** _/storage/emulated/0/Pictures/Mihon_

### Expected behavior

Download the images panel into my files/gallery

### Actual behavior

I got error in notification that says **Error** _/storage/emulated/0/Pictures/Mihon_ instead of downloading the image panel to my files/gallery 

### Crash logs

**Error**
### Mihon version

0.16.1

### Android version

Android 9

### Device

Huawei y9 2019

### Other details

I just make account just to report this since I don't trust social media than you guy's 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Give the app storage permission under Android settings

**Comment by MajorTanya** [comment]
Does this issue still occur for you in newer versions (0.16.4)?

**Comment by AntsyLich** [comment]
Closing due to lack of information
