### ISSUE TITLE
Set `hasFragileUserData` to `yes` in `AndroidManifest.xml`

### ISSUE THREAD

**Issue by soredake** [mihonapp/mihon#39]
### Describe your suggested feature

This will allow user to **optionally** retain all data in Android/data/<app-id> after uninstall.

TachiyomiAZ have this enabled:
![Screenshot_20240116-173832_Package installer](https://github.com/mihonapp/mihon/assets/5204968/7fb6ba9d-7f33-435b-8f59-7e6525442153)

### Other details

https://github.com/az4521/TachiyomiAZ/blob/95e5651ad99378c5c24c0a23d8711106b50e80b6/app/src/main/AndroidManifest.xml#L31

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Why? I see 0 benefit and people now potentially have orphaned data they can't remove

**Comment by soredake** [comment]
> people now potentially have orphaned data they can't remove

They can, either by file manager on older android versions, or with file manager with shizuku support, or by installing and removing again.

> I see 0 benefit

This folder can probably be big if you have many manga, and if you for example only have mobile data which have limited traffic you've probably want to retain this so mihon will not redownload this.

**Comment by AntsyLich** [comment]
Very highly unlikely people will uninstall the app just to reinstall it again in couple of minutes

**Comment by soredake** [comment]
If they don't plan to use it anymore after uninstalling, why they will select to keep app data?
