### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by Kraken1220** [mihonapp/mihon#392]
### Steps to reproduce

1.On extension when we update it shows as downloading
2.Then it shows as installing
3.When it's done again it shows as extension needs to be updated

### Expected behavior

I want to update my extensions 

### Actual behavior

No matter how many times I download over and over again it shows it has to be updated 

### Mihon version

0.16.3

### Android version

13

### Device

Samsung a03s 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Closing in favor of #496
