### ISSUE TITLE
Black and white images showing as blue-ish/badly decoded

### ISSUE THREAD

**Issue by chocoboSan** [mihonapp/mihon#403]
### Steps to reproduce

On my Nova 3 Color (Boox e-reader) once I migrated to Mihon from Tachiyomi, the same Chapter from Komga shown in Tachiyomi in proper Black and white, shows blue-ish where it is supposed to be black. 

I tried fiddling with the 32 bits colors but that did not change the output colors. 

### Expected behavior

Should show black as black. 

### Actual behavior

Shows black as blue-ish tint. 

### Crash logs

No crash. 

### Mihon version

0.16.3

### Android version

Android 10

### Device

Nova Boox 3 Color

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by chocoboSan** [comment]
I want to add as a generic comment that I'd be happy to give a hand on that topic as much as my dev knowledge can help you if you do not possess ways to reproduce the issues mentioned ! 👍 

(If we get there,and my help is needed, I'd just could use a pointer as to where the images are being rendered by Tachiyomi😅 )

**Comment by chocoboSan** [comment]
I feel like an extra dummy because indeed Nova had probably changed this or afaik I was not aware that there was now an e-ink profile per opened app.

The default profile adds 60 (out of 100) "color vividness" which 100% ressembled the issue I had and turned that slider back down to 0. 

The behavior between Mihon and Tachiyomi is now identical. 


Thanks for the maintenance and quick replies. This issue can be closed, just wondering if this could be part of the FAQ 🤔  !

**Comment by Xori71** [comment]
> I feel like an extra dummy because indeed Nova had probably changed this or afaik I was not aware that there was now an e-ink profile per opened app.
> 
> The default profile adds 60 (out of 100) "color vividness" which 100% ressembled the issue I had and turned that slider back down to 0.
> 
> The behavior between Mihon and Tachiyomi is now identical.
> 
> Thanks for the maintenance and quick replies. This issue can be closed, just wondering if this could be part of the FAQ 🤔 !

Glad I was of help! And I don’t think that this can be included in FAQ, since it doesn’t concern Mihon, but your device.

**Comment by chocoboSan** [comment]
> since it doesn’t concern Mihon, but your device.

Arguably, yes, but as it can happen to Mihon more than once (I think e-readers are common devices for this software) and as the FAQ is required to be read before opening an issue, I just thought it could reduce the total amount of opened issues in the long run 👍
