### ISSUE TITLE
Add entry to library when clicking Download

### ISSUE THREAD

**Issue by khanghugo** [mihonapp/mihon#412]
### Describe your suggested feature

Previously in Tachiyomi, clicking download will have a dialogue asking to add to library or not.

It doesn't happen here.

I am on Mihon 0.16.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
I checked and it did pop up for me immediately. Mihon also hasn't touched that part of the code base at this point.

**Comment by khanghugo** [comment]
It does not show up when you press the download button on the top. Please reconsider

Uploading Recording_2024-02-17-11-05-07.mp4…

**Comment by khanghugo** [comment]
https://github.com/mihonapp/mihon/assets/29143195/3b3b352d-aec9-483e-a71c-9b7c0a513ae1

**Comment by MajorTanya** [comment]
https://github.com/mihonapp/mihon/assets/39014446/88622033-135d-497e-ae05-126b1881d5b9

Seems to be working fine for me? Try refreshing the entry and doing the download thing again

**Comment by khanghugo** [comment]
Yea refreshing the entry works. Thanks.

I swear it never happens when I was using Mihon. The screen recording I have up there is corrupted for some reasons but it shows that it does not pop up.

**Comment by MajorTanya** [comment]
> It does not show up when you press the download button on the top. Please reconsider
> 
> Uploading Recording_2024-02-17-11-05-07.mp4…

This happens when you send the comment before the upload finishes. The reason it worked for the next comment is because you waited long enough for the upload to finish 👍
