### ISSUE TITLE
CAPTCHA solver

### ISSUE THREAD

**Issue by Boy656** [mihonapp/mihon#414]
### Describe your suggested feature

This will help improve the completion of the CAPTCHA quickly and easily without forcing you to choose the image that matches the text or other means of CAPTCHA. The solution is as follows: Add access to the Google page via WebView, then give us the opportunity to register with our Google account right on the webview site, then mihon will save my Google login from us.  It will enable us to shorten or facilitate the completion of CAPTCHA to the click of a single button

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
https://github.com/mihonapp/mihon/issues/242#issuecomment-1912946610
