### ISSUE TITLE
implment limiting for own choose for downloading from sources

### ISSUE THREAD

**Issue by Ayush62** [mihonapp/mihon#438]
### Describe your suggested feature

the idea is to make it so that the user can limit how many downloads be used. The idea came to me when i got problem from importing tachiyomi to Mihon. when i tried to download all my manga's i noticed that my phone was slowing down considerably. 

for that reason would this be useful. because you can then still use your phone without a have to much problems. Also this gives the user the choose to pick how many he wants to download at the same time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment]
or just don't mass download at the same time...?
