### ISSUE TITLE
Locally imported manga files disappear/deleted at random time

### ISSUE THREAD

**Issue by jonnyli** [mihonapp/mihon#440]
### Steps to reproduce

It isn't really an issue that I can reproduce because it is something that just happens. I do not know the trigger or cause. This is also something happened with all variants of Tachiyomi too.

### Expected behavior

Downloads/Delete chapters - all options are turned off.

My expectation is that files stay on the device until I manually delete manga files.

### Actual behavior

Import manga into local directory successful
Reading files on Mihon successful.
Reading for about 2 weeks and suddenly when I open Mihon, all the files are deleted. The folders holding the Manga and thumbnail remain but all .cbz files are gone.

### Crash logs

App version: 0.16.3 (standard, 139663a, 4, 2024-01-29T20:34Z)
Android version: 13 (SDK 33; build TP1A.220624.014)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: yunluo (yunluo_eea)
Device model: 22081283G
WebView: Android System WebView 121.0.6167.178

--------- beginning of main
02-23 17:18:02.268 31222 31222 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
02-23 17:18:02.539 31222 31263 E QT      : [QT]file does not exist
02-23 17:18:02.987 31222 31254 E SQLiteLog: (284) automatic index on C(manga_id)
02-23 17:18:02.987 31222 31254 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-23 17:18:03.043 31222 31222 E FBI     : Can't load library: dlopen failed: library "libmagtsync.so" not found
02-23 17:18:03.064 31222 31260 E libMiGL : libmigl:This GPU version is note support Variable Shading Rate
02-23 17:18:03.066 31222 31260 E libEGL  : pre_cache appList: ,,
02-23 17:18:03.608 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.639 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.788 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.831 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.838 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.863 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.903 31222 31333 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.937 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.973 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:03.992 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.001 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.005 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.019 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.029 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.141 31222 31333 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.172 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.175 31222 31333 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.182 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.196 31222 31333 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.204 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.205 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.216 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.241 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:04.263 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:06.254 31222 31330 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
02-23 17:18:06.299 31222 31260 E app.mihon: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288

### Mihon version

0.16.3

### Android version

Android version: 13

### Device

Redmi PAD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Did you try Advanced Settings > Invalidate Download Index?

**Comment by jonnyli** [comment]
I haven't touched this option before. What does this forcing app to recheck downloaded chapters do?

**Comment by MajorTanya** [comment]
> I haven't touched this option before. What does this forcing app to recheck downloaded chapters do?

It would make Mihon check the folders for the files of chapters. But I see now you said your files are completely gone? Like, gone in your file explorer too?
