### ISSUE TITLE
Unable to load large WebP

### ISSUE THREAD

**Issue by SapryWenInera** [mihonapp/mihon#441]
### Steps to reproduce

- Have a folder or a .cbz file on local
- A webp file on the folder on .cbz * tested with a ~500mb webp
- App identifies that page exists but is unable to load the image

### Expected behavior

It should load the image

### Actual behavior

Image doesnt load

### Crash logs

There was no crash on the app

### Mihon version

0.16.3

### Android version

android 13

### Device

Samsung Galaxy S10e

### Other details

The webp is using the webp_anim extension, but with smaller file sizes it doesnt seen to be a problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Xori71** [comment]
Compress the pages. There is no reason for an manga page to be 500 MBs.

**Comment by BraveDude8** [comment]
Pretty much any device or program is going to struggle with a 500mb image. Try opening it in a web browser, and you'll likely see the same result.

**Comment by AntsyLich** [comment]
Very niche case to not dedicate development time to. Just compress it.
