### ISSUE TITLE
It doesn't download some chapters of the mangas already added and when I try to enter webview it doesn't let me enter.

### ISSUE THREAD

**Issue by Carmen010601** [mihonapp/mihon#442]
### Steps to reproduce

In BL mangas it does not download the chapters, it says that there are no pages and that also happens in other types of mangas, just like when I try to open them through the webview, it does not open and the Google Chrome home page appears even though I am already logged in.
![Screenshot_20240224-075115](https://github.com/mihonapp/mihon/assets/133518906/b63df569-af37-4dff-8506-4c588359867d)
![Screenshot_20240224-075115](https://github.com/mihonapp/mihon/assets/133518906/07f34b43-953e-4df2-81cb-3a92d7967ed6)

### Expected behavior

I hope that all the chapters download normally as they did before without problems and that it allows me to open the webview correctly

### Actual behavior

It does not download the BL chapters of the series even though I heard that I have started downloading and it does not open the manga chapter in the webviw, it returns me to the Google Chrome home page even though I set it to open a chapter.
![Screenshot_20240224-075115](https://github.com/mihonapp/mihon/assets/133518906/4b11e2d9-b65b-4333-8c58-b0718a8c33ae)
 

### Mihon version

0.16.3

### Android version

Android 12

### Device

Motorola g30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We don't provide help with extension issue
