### ISSUE TITLE
Can't install sites after downloading 

### ISSUE THREAD

**Issue by Robiiiiiii12** [mihonapp/mihon#45]
### Steps to reproduce

After downloading sites from extension I can't install them. It says app not installed after trying to install. 

### Expected behavior

It should install after i install 

### Actual behavior

It shows app not installed after trying to install 

### Mihon version

Version 0.16.0

### Android version

Android 11

### Device

Realme Narzo 10a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mjo0ody09** [comment]
I Delete the sites first and download Again then you can install

**Comment by AntsyLich** [comment]
Should be fixed on the later versions of the app
