### ISSUE TITLE
mangaraw plus http 400 error

### ISSUE THREAD

**Issue by kevin930321** [mihonapp/mihon#453]
### Steps to reproduce

Install mangaraw plus 1.4.36
Open it

### Expected behavior

Show manga correctly

### Actual behavior

Http 400 error

### Mihon version

App version: 0.16.3-6520 (standard, 840b647b4, 4, 2024-02-17T21:13Z) Android version: 14 (SDK 34; build UKQ1.230924.001.34.0304.2004.75 release-keys) Device brand: asus Device manufacturer: asus Device name: ASUS_AI2202 (WW_AI2202) Device model: ASUS_AI2202_B WebView: Android System WebView 121.0.6167.178

### Android version

Android 14

### Device

Asus ZenFone 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We don't support 3rd party extensions
