### ISSUE TITLE
Tracker Login not working as It should

### ISSUE THREAD

**Issue by KaguyaUchiha** [mihonapp/mihon#454]
### Steps to reproduce

1. Go to Tracking Page
2. Login to your MAL account
3. Choose allow in MyAnimeList
![Screenshot_20240226-131231_Brave](https://github.com/mihonapp/mihon/assets/112609547/4a0f85dd-111e-4806-abbe-433d03447409)

### Expected behavior

After clicking allow the app should take myanimelist as one of its trackers and start tracking.

### Actual behavior

Whats happening is that after I click allow on the MyAnimeList website it redirects me to app but it just buffers 
![Screenshot_20240226-131227_Mihon](https://github.com/mihonapp/mihon/assets/112609547/80885aff-fb2b-4e49-8009-19dff434e079)

### Mihon version

0.16.3

### Android version

Android 13

### Device

Redmi Note 10 Pro 

### Other details

It used to work fine on tachiyomi. I had my trackers and all backed up on tachiyomi...after switching to mihon i just used the backup file and the tracker got imported as well but the tracker wasn't tracking so i logged it out from mihon then tried logging in again but then faced this issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by brunnom2** [comment]
I'm in version 0.16.4 that promised to solve this, for now nothing, I'm waiting.

Keep this great personal job

**Comment by brunnom2** [comment]
> > I'm in version 0.16.4 that promised to solve this, for now nothing, I'm waiting.
> > Keep this great personal job
> 
> Go to Mihon Settings > Advanced, and change the default user-agent

Which agent?
you could inform me?

**Comment by brunnom2** [comment]
> > > > I'm in version 0.16.4 that promised to solve this, for now nothing, I'm waiting.
> > > > Keep this great personal job
> > > 
> > > 
> > > Go to Mihon Settings > Advanced, and change the default user-agent
> > 
> > 
> > Which agent? you could inform me?
> 
> Basta ir ao Google para um e ver se funciona. Nunca há realmente um recomendado devido a diferenças na internet, dispositivos, região, fontes, etc etc.

I changed the agent to one of Opera and worked perfectly, was instantanio, thank you very much.

**Comment by KaguyaUchiha** [comment]
> MAL is currently blocking Mihon & apparently some other apps, please wait for them to be cool

MAL is being really annoying for quite some time...IG its time I give AniList a try...
