### ISSUE TITLE
Library setting

### ISSUE THREAD

**Issue by srcsvl** [mihonapp/mihon#456]
### Describe your suggested feature

It would be nice if we could group the sources of the manga we add to the library separately according to their source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #378
