### ISSUE TITLE
Add back option for separate backup location

### ISSUE THREAD

**Issue by techmccat** [mihonapp/mihon#458]
### Describe your suggested feature

Previous versions (as is still shown on [the backup guide](https://mihon.app/docs/guides/backups)) allowed the user to specify a folder for automatic backups, I think it would be useful to have ithe option back.

My use case is uploading automatic backups directly to Nextcloud, without the need a separate application to sync folders.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Won't be back as we have transitioned to a newer (required for new Android versions) storage API
