### ISSUE TITLE
Add another way to open the reader settings menu

### ISSUE THREAD

**Issue by MaksNPC** [mihonapp/mihon#462]
### Describe your suggested feature

Add to the reader settings the ability to choose how to open the settings menu while reading
![Screenshot_20240229-131959_Mihon~2](https://github.com/mihonapp/mihon/assets/55586822/3b455071-75bc-4919-85c2-ffbd38cc4d11)

1. By pressing
2. By holding

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. Just tap in the middle

**Comment by MaksNPC** [comment]
> No. Just tap in the middle

You didn't understand what I meant.  I read by flipping pages rather than pressing the edges, and almost always there is an accidental click and the settings menu appears, which is noted in the screenshot, and I'm sure I'm not the only one who has experienced this.  Therefore, I proposed adding the ability to change touch to hold to call this menu.
