### ISSUE TITLE
Please upgrade to Compose 1.6

### ISSUE THREAD

**Issue by Malus-risus** [mihonapp/mihon#464]
### Describe your suggested feature

Please upgrade to Compose 1.6 for better performance and bug fixes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We are on compose `1.7.0-alpha01`
