### ISSUE TITLE
Some chapters not deleted after read. 

### ISSUE THREAD

**Issue by Aadityaryal** [mihonapp/mihon#468]
### Steps to reproduce

1. Enabled 'After reading automatically delete.' 
2. Read some chapters
3. Some chapters with gap not being deleted.

### Expected behavior

Chapter should have been deleted. 

### Actual behavior

Only few chapters being deleted. 

### Mihon version

0.16.4

### Android version

Android 11

### Device

Vivo V2026

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Nekuskus** [comment]
Also mentioned in #421.
