### ISSUE TITLE
Add back settings for maximum saved backups.

### ISSUE THREAD

**Issue by davinngo** [mihonapp/mihon#47]
### Describe your suggested feature

Older versions of Tachiyomi had a setting to set how many of the latest backups you would like to keep. This feature is no longer present in the current version of the app.

### Other details

If the maximum is set to 2, all but the latest 2 backups will be deleted from your device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This was removed in e3b70ca08d1c5a09a448891ff66102fd696d7098, which set the number of kept automatic backups to 4 (as seen [here](https://github.com/mihonapp/mihon/blob/ccec5c3efeea699124d4bb7448d6fe9718cb883f/app/src/main/java/eu/kanade/tachiyomi/data/backup/create/BackupCreator.kt#L144)), with the reasoning that the backup creation code would be getting busy with the syncing functionality originally planned.

I don't see much of a need to bring this setting back as 4 seems like a reasonable number of automatic backups, and considering backup files are at best a few MB large, storage shouldn't be an issue either. I also don't think this auto cleanup ever applied to manual backups, as deleting those on a schedule sounds like a Really Bad Idea™.

Any utility reasons for why you want this back, other than having it would be nice for customisation?
