### ISSUE TITLE
Update and BackUp not working

### ISSUE THREAD

**Issue by PondelekB** [mihonapp/mihon#475]
### Steps to reproduce

Update library or backup the data

### Expected behavior

Library updates it self and backup is done 

### Actual behavior

Library does not update itself and backup trows errors

### Crash logs

![Screenshot_2024-02-29-14-23-44-73_551f7f0ca926862b368845ce7ee433aa](https://github.com/mihonapp/mihon/assets/72188018/5625c150-d7be-4034-8c85-7beb184414eb)

### Mihon version

0.16.4

### Android version

Android 12.1

### Device

Oppo reno 3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Extension issue nothing to do with Mihon
