### ISSUE TITLE
Search for chapter

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [mihonapp/mihon#477]
### Describe your suggested feature

Add search for a chapter by number

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
???

**Comment by AbdelrahmanElnezamy121** [comment]
> ???

I mean that i hope to search for a chapter instead of scrolling

**Comment by AntsyLich** [comment]
Don't be lazy
