### ISSUE TITLE
Automatic updating chapter count. 

### ISSUE THREAD

**Issue by JDKamalakar** [mihonapp/mihon#478]
### Describe your suggested feature

Update the count of chapters read on MAL after clicking the mark chapter as read (Online & Offline).

Used to work with Tachiyomi Preview. 

### Other details

When I press the mark chapter as read tracker should update the ch count for the series on the service.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
No it didn't and please don't. I don't want my progress and the non-editable activity messages tied to it being messed up because I marked duplicate chapters as read to filter them out

**Comment by JDKamalakar** [comment]
I read manga on different devices on Android I use mihon but many times I use my Chromebook to read manga At that time I use dedicated sites like mangadex & stuf so many manga are never read on mihon app.

**Comment by BrutuZ** [comment]
You're already going through the trouble of manually marking the chapters as read, just go the extra mile and manually set the tracking on that same window.
Or if that's too much, only mark as read up to the second last you would, then open the last one as if you'd read it and just drag the slider all the way to the end as soon as it opens, boom, trackers updated.
