### ISSUE TITLE
bato does not work?

### ISSUE THREAD

**Issue by tobionia** [mihonapp/mihon#48]
### Steps to reproduce

i mostly used the batoto extension before it got removed. will it not be available in mihon too? i can see it in my extensions and i can see the series but i can't read the chapters. it shows the same error in tachi.

### Expected behavior

i should read it just fine

### Actual behavior

i can't read the chapters

### Mihon version

0.16.0

### Android version

Android 14

### Device

Samsung Galaxy S23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No 2st part extension support
