### ISSUE TITLE
Add search button beside missing extension name

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#486]
### Describe your suggested feature

When extension is removed in Library / under manga name it says that extension is missing and you need to install it (extension name/!\)
Make search button beside missing extension name or option to 1.long-press extension name and that will copy name of missing extension and automaticly open to the search in extension tab and paste a name and 
2.you will only need to install or just add trust to extension...

On short-tap there is allready search manga by extension in library option

what i want is if there is uninstalled extension you can long-hold on extension name and will directly search extension name in extensions you just need to click 2 times to install extension, 
instead you need to:
1. remember extension name
2.  go to extensions
3.enter extension name
4.install extension

Pictures for location
![310396115-ac5898f6-cd91-403a-b182-56e5823fe8f5](https://github.com/mihonapp/mihon/assets/25694091/d0e20492-562e-44e2-bd3a-96e46bc4b260)
![310396151-737477bf-ca89-43a8-af75-02a3988aecfe](https://github.com/mihonapp/mihon/assets/25694091/b089aa13-e7ca-4fb0-83bb-32ae31c51986)

### Other details

Easy to add missing extensions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
You can copy the ID from the Migrate tab. Searching for that number works too

**Comment by MajorTanya** [comment]
Also, please don't share source names in future and just censor them as well.
