### ISSUE TITLE
Crashing when trying to download extentions 

### ISSUE THREAD

**Issue by Rex30525** [mihonapp/mihon#488]
### Steps to reproduce

Will try and update or download extension will not try to install and after 20 secs or so will crash

### Expected behavior

Should download extention 

### Actual behavior

Does not and crahses

### Crash logs

App version: 0.16.4 (standard, a4f5dfa, 5, 2024-02-26T16:26Z)
Android version: 14 (SDK 34; build UP1A.231005.007.S928USQU1AXB7)
Device brand: samsung
Device manufacturer: samsung
Device name: e3q (e3qsqw)
Device model: SM-S928U
WebView: Android System WebView 122.0.6261.105

--------- beginning of system
03-06 14:06:58.202  2163  2525 E ActivityThread: Failed to find provider info for downloads
03-06 14:11:12.357 14664 14953 E ActivityThread: Failed to find provider info for downloads
03-06 14:12:30.082 18433 18702 E ActivityThread: Failed to find provider info for downloads
03-06 14:20:54.537 20435 28422 E ActivityThread: Failed to find provider info for downloads
--------- beginning of main
03-06 14:27:56.529 28540 28571 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
03-06 14:28:10.979 29054  2342 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
03-06 14:28:11.028 29054  2375 E SQLiteLog: (284) automatic index on C(manga_id)
03-06 14:28:11.028 29054  2375 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-06 14:28:11.048 29054 29054 E app.mihon: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
03-06 14:30:46.722 29054  2342 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
03-06 14:31:17.799 29054  2342 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
03-06 14:31:58.024 29054  5420 E ActivityThread: Failed to find provider info for downloads
03-06 14:31:58.092 28540 28571 E Adreno-AppProfiles: QSPM AIDL service doesn't exist
03-06 14:32:38.649  7141  7141 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
03-06 14:32:38.741  7141  7211 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
03-06 14:32:38.778  7141  7239 E chromium: [0306/143238.777997:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
03-06 14:34:30.141 28540 28571 E Adreno-AppProfiles: QSPM AIDL service doesn't exist

### Mihon version

0.16.4

### Android version

Android 14

### Device

S24 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
If you get a crash screen please share a screenshot of that here too.
Also, do you have some steps to reproduce this or does it seem to happen randomly?

**Comment by MajorTanya** [comment]
> I was getting the same issue as OP before I found this thread. Any attempt to install an extension would go as follows:
> 
>     1. Tap the download button by the extension.
> 
>     2. Wait 10-15 seconds with nothing happening. The download icon never changes to the spinning loader, but one is still able to navigate within the app and otherwise interact with it normally.
> 
>     3. A fullscreen crash reporter comes up with the crash report in a text field and buttons to save the error log or restart the app.
> 
> 
> This crash persisted through clearing cache/data, force closing, restoring from a Tachiyomi backup, or disabling certain memory hardening tweaks in GrapheneOS. After installing a system update that just came out today, after which some apps were optimized, the issue is no longer occurring. Here's a typical crash log:
> 
> > App version: 0.16.4 (standard, [a4f5dfa](https://github.com/mihonapp/mihon/commit/a4f5dfab1a874f4875d3bbfd67472a6803e7a7cf), 5, 2024-02-26T16:26Z)
> > Android version: 14 (SDK 34; build 2024030900)
> > Device brand: google
> > Device manufacturer: Google
> > Device name: bluejay (bluejay)
> > Device model: Pixel 6a
> > WebView: Vanadium System WebView 122.0.6261.105.0
> > --------- beginning of system
> > 03-12 11:50:06.334 19999 20529 E ActivityThread: Failed to find provider info for downloads
> > 03-12 11:50:06.343 19999 20540 E ActivityThread: Failed to find provider info for downloads
> > 03-12 11:51:06.011 20675 20760 E ActivityThread: Failed to find provider info for downloads
> > 03-12 11:51:06.018 20675 20753 E ActivityThread: Failed to find provider info for downloads
> > 03-12 11:59:40.934 23565 23682 E ActivityThread: Failed to find provider info for downloads
> > --------- beginning of main
> > 03-12 12:00:32.506 24337 24337 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
> > 03-12 12:00:32.639 24337 24337 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 03-12 12:00:32.754 24337 24337 E app.mihon: Unable to find pattern file or unable to map it for am
> > 03-12 12:00:32.923 24337 24383 E SQLiteLog: (28) double-quoted string literal: ""
> > 03-12 12:00:32.927 24337 24337 E WebViewLibraryLoader: can't load with relro file; address space not reserved
> > 03-12 12:00:33.149 24337 24403 E SQLiteLog: (284) automatic index on C(manga_id)
> > 03-12 12:00:33.149 24337 24403 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
> > 03-12 12:00:33.588 24337 24410 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 03-12 12:01:16.421 24337 24337 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@64fc7e5 was not the current floating action mode! Expected null
> > 03-12 12:01:25.153 24337 24337 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 136012815
> > 03-12 12:02:20.625 24337 24407 E ActivityThread: Failed to find provider info for downloads
> > 03-12 12:03:46.584 24790 24790 E n:error_handler: Not starting debugger since process cannot load the jdwp agent.
> > 03-12 12:03:46.658 24790 24790 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 03-12 12:03:46.752 24790 24790 E app.mihon:error_handler: Unable to find pattern file or unable to map it for am
> > 03-12 12:03:46.849 24790 24790 E WebViewLibraryLoader: can't load with relro file; address space not reserved
> > 03-12 12:03:47.094 24790 24835 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 03-12 12:03:50.093 24954 24954 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
> > 03-12 12:03:50.186 24954 24954 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 03-12 12:03:50.326 24954 24954 E app.mihon: Unable to find pattern file or unable to map it for am
> > 03-12 12:03:50.513 24954 24998 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
> > 03-12 12:03:50.532 24954 24954 E WebViewLibraryLoader: can't load with relro file; address space not reserved
> 
> If OP or anyone else is still getting the issue, rebooting the phone or installing a system update might resolve it. That's all I have to offer.

That log doesn't seem to contain anything related to this issue, if it's reproducible, I'd like to see a screenshot of the crash screen. Sadly there is a weirdness about the log files that sometimes don't contain the actual stacktrace shown in the crash screen.

**Comment by AntsyLich** [comment]
make a new issue with crash screen screenshot if it still occurs
