### ISSUE TITLE
Add 'Migrate' to the Pop-up menu for duplicate entries

### ISSUE THREAD

**Issue by DrStoner90** [mihonapp/mihon#489]
### Describe your suggested feature

when attempting to add a series to the library that is already added, users will be given a popup that prompts them to "show entry" , "cancel" or "add". 

![Screenshot 2024-03-06 145516](https://github.com/mihonapp/mihon/assets/162504952/2c31b52b-8a82-4689-8600-cdf60a65d49c)

it would be nice if "Migrate" was also an option provided on this pop-up. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sirlag** [comment]
![image](https://github.com/mihonapp/mihon/assets/1882979/8e933f8f-edd1-4cf3-be19-8358a94fe13f)
 Took a look because this seems like a helpful feature. Unfortunately Material Design supports up to 3 options in the dialog natively without switching to a stacked view or switching away from a dialog.
