### ISSUE TITLE
fitur translate screen 

### ISSUE THREAD

**Issue by Vierilukmantia** [mihonapp/mihon#490]
### Describe your suggested feature

I need a feature that is rarely found in comic reading apps, namely the translate screen, maybe it could be added in the future for more comfort in reading comics

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Just to be clear, you're asking Mihon to include some sort of automatic series translation? Or do you just want to change your app's language (More > Settings > Appearance > App language)

**Comment by Vierilukmantia** [comment]
> Untuk memperjelas, Anda meminta Mihon menyertakan semacam terjemahan seri otomatis? Atau apakah Anda hanya ingin mengubah bahasa aplikasi Anda (Lainnya > Pengaturan > Tampilan > Bahasa aplikasi)

I want a feature to automatically translate the comics I want to read

**Comment by MajorTanya** [comment]
Yeah, that's not happening. Completely and wildly out of anything even near Mihon's actual scope. Find a source that has translations for the series you want, or learn to translate yourself.
