### ISSUE TITLE
Updating Extension Does Not Update Extension, No Error

### ISSUE THREAD

**Issue by dabreadman** [mihonapp/mihon#496]
### Steps to reproduce

1. Open App
2. Browse (there's number)
3. Extension (updates pending)
4. Update All (or individual)

### Expected behavior

Extension updated, download button missing

### Actual behavior

No error, extension not updated, can restart the process but extension not updated

### Mihon version

0.16.4

### Android version

Android 8.0.0

### Device

Huawei Nova 2i

### Other details

https://github.com/mihonapp/mihon/assets/43485369/44d9aed2-6cfc-407d-b47c-c9f2976e41d8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by zii007** [comment]
Same here

**Comment by Someone777** [comment]
Same problem, android 13

This has been a problem since the need to "trust" extensions has been added.

**Comment by MaximeJeanRey** [comment]
Hello,

I had the same issue, but I solved it by following these steps:

Settings > Advanced > Extensions > Installer > Changed it from Package Installer to Legacy.
Then it correctly asked for my permission when trying to install extensions.

**Comment by JokeTea** [comment]
> Hello,
> 
> I had the same issue, but I solved it by following these steps:
> 
> Settings > Advanced > Extensions > Installer > Changed it from Package Installer to Legacy. Then it correctly asked for my permission when trying to install extensions.

Unfortunately this did not work for me. :/ very annoying bug.

**Comment by aymaba110** [comment]
If they're the extensions you had with tachiyomi before switching over, you might have to go through and uninstall and reinstall each extension that's not updating. You'll have to trust them and then it should work. That's what I did and it fixed the issue.

**Comment by AntsyLich** [comment]
Should be fixed by 21145144cdf550aa775047603e06e261951ebc42
