### ISSUE TITLE
Feature: search for page count

### ISSUE THREAD

**Issue by sjiawjbssj** [mihonapp/mihon#498]
### Describe your suggested feature

I'd like to be able to search for entries based on their page count within the library.

For example:
pages:>30
pages:<30
pages:<=30

Everything from nhentai has one chapter so it's not possible to find something short/long to read without opening every entry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not possible as Mihon doesn't know how many page a chapter has until you open it
