### ISSUE TITLE
Feature: web service, reading comics in broswer

### ISSUE THREAD

**Issue by luo-chuan** [mihonapp/mihon#501]
### Describe your suggested feature

The screen of smart phone is not big enough. Sometimes, user want to read comics in a larger screen. I hope mihon APP add this feature, then user can read comics in PC's broswer, like edge or chrome, using the url like "192.168.0.111:8888".

Some other APP provide this feature, like [legado](https://github.com/gedoor/legado) and [siyuan](https://github.com/siyuan-note/siyuan).

The legado is a novel reading app, there are some screenshot:
![图片](https://github.com/mihonapp/mihon/assets/33930736/0a475112-4c42-4087-9d95-f952af4f71cf)
![图片](https://github.com/mihonapp/mihon/assets/33930736/9745d83c-a3f5-4761-930e-c965cf8e31a1)

The siyuan is a markdown noting app, there are some screenshot:
![图片](https://github.com/mihonapp/mihon/assets/33930736/fd7d2800-30b0-4c53-9936-f947e2f7ca27)
![图片](https://github.com/mihonapp/mihon/assets/33930736/caf06b9f-b8e5-49e7-b4a6-61562fb08466)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
You can either read directly from the source or if it really *must* be via Mihon for some reason there's always [scrpy](https://github.com/Genymobile/scrcpy/) 👍

**Comment by luo-chuan** [comment]
> You can either read directly from the source or if it really _must_ be via Mihon for some reason there's always [scrcpy](https://github.com/Genymobile/scrcpy/) 👍

Thanks for replying. I think scrcpy is a way which is tedious and high power consumption. The web service is more cool and convenient, because user don't need to find the source and current progress of comics again, as well as don't be troubled with the sync problem.

**Comment by AntsyLich** [comment]
Not really interested in embedding a whole website inside of Mihon
