### ISSUE TITLE
New filtering feature

### ISSUE THREAD

**Issue by MaxNPC** [mihonapp/mihon#505]
### Describe your suggested feature

add a new element to the "last read" filter so that the last chapter you read is always first in the list, so you can see which chapter you left off on
![IMG_20240311_000904_211](https://github.com/mihonapp/mihon/assets/55586822/8f5d222a-462e-4e47-883d-d76a2e63ceb0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Seems pretty dumb to add a filter for that. If you have better idea then feel free to make a new issue
