### ISSUE TITLE
In-App Update from 0.16.3 to 0.16.4 does not work

### ISSUE THREAD

**Issue by Void2258** [mihonapp/mihon#507]
### Steps to reproduce

1) App informs you there is an update.
2) User clicks download.
3) Nothing happens, update notice closes. Version unchanged.

### Expected behavior

1) App informs you there is an update.
2) User clicks download.
3) Update downloaded and applied. Version changed.

### Actual behavior

No download, no update. Update notice closed. Notice repeats every few days without ever actually doing anything. No notification, errors, or activity at all, simply goes back to the app main screen with nothing occurring.

### Mihon version

0.16.3

### Android version

11

### Device

Galaxy Tab S 7

### Other details

In order to submit, I have checked that I updated to 0.16.4, but this is not the case as the issue is with the updating. There is no way to submit the issue without having so indicated, which makes it technically impossible to submit issues with the update process without lying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
The app is supposed to give you a notification that the download has completed and that you can install the app by tapping the notification. Can you check that Mihon is allowed to send notifications?

**Comment by Void2258** [comment]
Yup, notifications were not allowed. Allowed them and it worked. 

This moves the issue back to this being opaque to the user who may not know why it's not working.
