### ISSUE TITLE
Add new information about chapters

### ISSUE THREAD

**Issue by MaxNPC** [mihonapp/mihon#509]
### Describe your suggested feature

Add page count information next to the date or next to the chapter download button

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
That'll require us to make separate call for each chapters so no
