### ISSUE TITLE
Ability to edit buttons

### ISSUE THREAD

**Issue by MaxNPC** [mihonapp/mihon#510]
### Describe your suggested feature

Add the ability to change the order of buttons under title names and buttons in the search engine
![IMG_20240312_230827_952](https://github.com/mihonapp/mihon/assets/55586822/8b2295bb-9dc6-4c43-9bea-4ab1c754883b)
![IMG_20240312_230934_891](https://github.com/mihonapp/mihon/assets/55586822/78f0eb1f-c751-4925-99b3-d3c025086b72)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
