### ISSUE TITLE
User agent per source can't bypass cloudflare

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [mihonapp/mihon#511]
### Steps to reproduce

1. Set a user agent for a specific source
2. Try the source

### Expected behavior

Cloudflare bypassed without webview

### Actual behavior

doesn't bypass cloudflare on its own, try webview, still can't bypass it manually.

### Mihon version

0.16.4

### Android version

Android 10

### Device

Samsung A9

### Other details

Maybe specified DNS server in settings doesn't get used? I have it set to cloudflare instead of default

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Extension issue and doesn't concern the app. Also you should learn more on what DNS is and how it works cause you have a misconception of it.

**Comment by Omar-Abdul-Azeez** [comment]
@AntsyLich sorry but you seem to have misunderstood, the user agent I use with the cloudflare DNS bypass cloudflare when set in the settings, that's how I'm using them right now. But not per source... There is no explanation for this other than the fact that cloudflare can detect the method used then, which implies it being different than the method used in the case of no custom user agent per source. Isn't Mihon the one responsible for this?
