### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by MarshMeadow** [mihonapp/mihon#52]
### Describe your suggested feature

i do not like how you guys used the latest release of tachi because it does not have the extension list and now I have to go get the repo to get the list and download them and I am still not sure how that works I can't find the list..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Even if Mihon was based on an earlier release before 0.15.0, the extensions list wouldn't work, as the original repository with all those extensions in it plain old does not exist anymore. In fact, using versions after 0.15.x is actually better for users, as there won't be repeated error messages about "Failed to fetch extensions list" or something like that.
There is no extensions support from Mihon itself.

**Comment by not-fried-dumplings** [comment]
Please go read the FAQ on the Tachiyomi website. You need to bring your own extensions from now on. Like MajorTanya said, even if you have a previous version, you can't install new or update the existing extensions,

**Comment by Seishirou101** [comment]
see above.
