### ISSUE TITLE
Rework the "trusted extensions" system

### ISSUE THREAD

**Issue by s1nistr4** [mihonapp/mihon#521]
### Steps to reproduce

Right now the current trusted extensions system makes the app nearly unusable. After manually adding a repo, you have to tap each source and trust each and every one. Then after they update you have to trust them again. This is after having nothing to go off of to ensure the extension repo is trusted, it doesn't link you to the source code or anything so the entire system is just a cumbersome set of dialog boxes. 

This is fine for a couple repos but if you have 20-50 repos it becomes a nightmare. A better solution to this would be to trust the repository rather than each and every extension repo.

### Expected behavior

.

### Actual behavior

.

### Mihon version

0.16.4

### Android version

Android 13

### Device

Pixel 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#320
