### ISSUE TITLE
[Feature] Allow show filename like [Show Page Number]

### ISSUE THREAD

**Issue by CrayonSSR** [mihonapp/mihon#522]
### Describe your suggested feature

**The option for `show file name` could be placed within the `[General]` section**

![image](https://github.com/mihonapp/mihon/assets/93774795/28f233af-b2d4-4613-8936-85047666fbe3)

**The filename can be pinned at the top of the screen, akin to the `page number` placement found at the bottom.**

![image](https://github.com/mihonapp/mihon/assets/93774795/b8f81e8f-2863-4d4c-a0ef-d606712333d9)
<br><br>

### Reason

While I recognize that showing file names might not hold much practicality in the context of reading comics,

However, this feature proves particularly useful within collections of images or personal compiled packages, It enables users to glean information about story background, characters, authors, and more directly from the filenames.

And having immediate access to image titles within the reader is clearly more convenient than navigating through `File Manager` -> `Opening mihon/local/xxx` -> `Manually checking each image` -> `Obtaining the filename`.
<br><br>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not interested
