### ISSUE TITLE
Extension MangaGalaxy broken

### ISSUE THREAD

**Issue by Twilikid** [mihonapp/mihon#524]
### Steps to reproduce

The extension of mangagalaxy is broken en doenst want to load up or view in the extensions tab with browsing.

### Expected behavior

Should work when opened and load manga's

### Actual behavior

Doesnt load and doesnt lets you see the manga that has been posted on the manga galaxy extension

### Mihon version

0.16.4

### Android version

Android 14

### Device

Samsung Galaxy S22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Twilikid** [comment]
Ohh sorry i didnt know that, as i used the repo that was recommended by mihon.

My bad :(

**Comment by MajorTanya** [comment]
> Ohh sorry i didnt know that, as i used the repo that was recommended by mihon.
> 
> My bad :(

Mihon doesn't recommend any repos.
