### ISSUE TITLE
Change extension page

### ISSUE THREAD

**Issue by Jhondeivis12** [mihonapp/mihon#532]
### Describe your suggested feature

update InariManga extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon doesn't provide support for 3rd party extensions
