### ISSUE TITLE
Add back to top button 

### ISSUE THREAD

**Issue by StrangePeanut** [mihonapp/mihon#535]
### Describe your suggested feature

Some titles have hundreds of chapters. Adding a back to top button would make navigating through Mihon a lot more intuitive.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Go back and enter the title again. Don't be lazy.

**Comment by MajorTanya** [comment]
Also, fling-scrolling / the scroll bar should be sufficient for this situation
