### ISSUE TITLE
Can you add this function "Hide unread badges"？

### ISSUE THREAD

**Issue by Maybeyok** [mihonapp/mihon#539]
### Describe your suggested feature

After adding this function（Hide unread badges)，, the bookshelf looks more beautiful.
![Screenshot_2024-03-19-00-01-55-071_eu kanade tachiyomi j2k](https://github.com/mihonapp/mihon/assets/127712226/3ba8f8cf-f719-41a6-a277-c0661b1e8762)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Read your stuff
