### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by LegacyPhil** [mihonapp/mihon#54]
### Describe your suggested feature

If i make a backup files for my tachiyomi library i should be able to use it on mihon since it's the same system.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Pipixel** [comment]
Yes, it's compatible between Tachiyomi and Mihon because it's based on the last version of the app and the only changes right now is only the name and logo

**Comment by m-a-hannan** [comment]
Are you facing problem? 
I restored my last backup from tachiyomi without any problem.

**Comment by Seishirou101** [comment]
unless you have a really old version, backups should restore fine.
