### ISSUE TITLE
The source request option

### ISSUE THREAD

**Issue by Mingo3347** [mihonapp/mihon#540]
### Describe your suggested feature

Was just wondering why the source request option is not available anymore 

Also if their any possibility for the (Azora) source to come back and why was it removed 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Mihon never hosted sources and unlikely it will

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions itself, you need to find an external extension repo to add to it. That'd also be the place to request stuff, not here.
