### ISSUE TITLE
Trust Extension 

### ISSUE THREAD

**Issue by jingoniii** [mihonapp/mihon#546]
### Steps to reproduce

1. Open Mihon App
2. Update Extensions
3. Trust Multiple Extensions

### Expected behavior

I expect it to be smooth and no loads. I have other fork but I notice that Mihon is the only problem with trusting extension that it loads and freezes. The UX/UI is not very pleasant to me.

### Actual behavior

Whenever I click "trust" extension sometimes it does not work, it freezes or load so I have to click multiple times. This is a problem when I update multiple extension at once and I have to click "trust" again. Earlier versions have this issue too.

### Crash logs

No crash for this issue.

### Mihon version

0.16.4

### Android version

Android 13

### Device

Realme C25

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Yutasj** [comment]
Agree

**Comment by AntsyLich** [comment]
Fixed in preview
