### ISSUE TITLE
Updates time bug

### ISSUE THREAD

**Issue by x-tj** [mihonapp/mihon#551]
### Steps to reproduce

open app
go to update tab 
update the ongoing manga

### Expected behavior

based on time of update sort updates into today or yesterday

### Actual behavior

If the update time is before 6:00 AM . It sorts update updates into Yesterday instead of today

### Mihon version

0.16.4

### Android version

Android 13

### Device

Redmi Note 10S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Isn't this a duplicate of #58, which was fixed in #402? Can you check which Mihon version you're using because this issue should be fixed from what I know. Go to More > About > tap Version > paste here.

**Comment by x-tj** [comment]
I am on stable 0.16.4(26/02/24 9:56 pm). It is a duplicate of #58 , but for me it occurs at 6.00am

**Comment by sirlag** [comment]
It's based on your local time, this is currently fixed in Mihon Preview with #402 if you want the fix early, otherwise this issue can be closed.

**Comment by x-tj** [comment]
Ok. Thanks for the help

**Comment by MajorTanya** [comment]
I forgot 0.16.4 didn't include anything other than the MAL fix. But also, I asked you to tap the Version display because that copies some data about Mihon and your device into your clipboard, and pasting that here could be helpful at times for some issues.

**Comment by x-tj** [comment]
It's ok bro. 
App version: 0.16.4 (standard, a4f5dfa, 5, 2024-02-26T16:26Z)
Android version: 13 (SDK 33; build TP1A.220624.014)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: secret (secret_in)
Device model: M2101K7BI
WebView: Android System WebView 122.0.6261.105
Never knew it did this.
I was using a laptop to report bug. It is a hassle to transfer to transfer text from mobile to pc. So i just typed the version.
