### ISSUE TITLE
[Insert chapter name] x.5 becomes Chapter 5 when displaying as chapter number

### ISSUE THREAD

**Issue by Xori71** [mihonapp/mihon#554]
### Steps to reproduce

1. Find the One-Punch Man manga in a well-known source.
2. Go towards the end and find the “Mag Version” 193.5 and 194.5 chapters.
3. Display as chapter number.

### Expected behavior

The chapter names should change to “Chapter” but the number remains the same.

### Actual behavior

The chapter name changes to “Chapter” but the number turns from x.5 to 5.

### Mihon version

0.16.4

### Android version

Android 14

### Device

Redmi Note 9 Pro

### Other details

https://github.com/mihonapp/mihon/assets/101265862/78af4608-8145-42d2-a9a6-946e2100c92f

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
While we understand why you're naming a source, please remove the name from your issue.

**Comment by Xori71** [comment]
> While we understand why you're naming a source, please remove the name from your issue.

Is this okay? Or should I remove any traces entirely?

**Comment by MajorTanya** [comment]
> > While we understand why you're naming a source, please remove the name from your issue.
> 
> Is this okay? Or should I remove any traces entirely?

This is fine, thank you 👍

**Comment by Xori71** [comment]
> > > While we understand why you're naming a source, please remove the name from your issue.
> > 
> > 
> > Is this okay? Or should I remove any traces entirely?
> 
> This is fine, thank you 👍

You’re welcome.
