### ISSUE TITLE
App not installing 

### ISSUE THREAD

**Issue by NKJibu02** [mihonapp/mihon#57]
### Steps to reproduce

Downloaded the app on github but refuses to install 

### Expected behavior

It should have show app installed 

### Actual behavior

It said app not installed

### Mihon version

16.0

### Android version

Android 10 

### Device

Infinix SMART 6/X657C 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ShahrukhAbrar** [comment]
It might be because you are trying to install a different variant of app. Try installing this [Mihon.apk](https://github.com/mihonapp/mihon/releases/download/v0.16.0/mihon-v0.16.0.apk)

**Comment by NKJibu02** [comment]
It works thanks.

**Comment by NKJibu02** [comment]
It working, thanks.
