### ISSUE TITLE
No Page found 

### ISSUE THREAD

**Issue by Sarah-Hussain** [mihonapp/mihon#575]
### Steps to reproduce

I just installed the app and I can't open any chapters from any source and have tried all the solutions and nothing works I click on the chapter and it kicks me out and I tried downloading the chapter but it says no Page found 

### Expected behavior

Open and read the chapter 

### Actual behavior

Can't open any chapter

### Crash logs

App version: 0.16.4 (standard, a4f5dfa, 5, 2024-02-26T16:26Z)
Android version: 8.1.0 (SDK 27; build TAB11_OTEETO_V2.0_20231121)
Device brand: OTEETO
Device manufacturer: OTEETO
Device name: TAB11 (TAB11)
Device model: TAB11
WebView: Chrome 122.0.6261.105

--------- beginning of main

### Mihon version

0.16.4

### Android version

8.1.0

### Device

TAB11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
We don;t provide support for 3rd party sources
