### ISSUE TITLE
Ninehentai error 405

### ISSUE THREAD

**Issue by ob-shk02** [mihonapp/mihon#576]
### Steps to reproduce

![Screenshot_20240325-022459](https://github.com/mihonapp/mihon/assets/142179108/3162e116-9223-4d58-a155-9d768a765405)

### Expected behavior

To open the library for the website

### Actual behavior

![Screenshot_20240325-022459](https://github.com/mihonapp/mihon/assets/142179108/96b48150-a49f-4c81-b249-719fc7184523)

### Mihon version

0.16.4

### Android version

Android 13

### Device

Motorola edge 20 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide, associate with, or provides support for, extensions. This is an extension issue and therefore not Mihon's responsibility.
