### ISSUE TITLE
add non-apk way to add library 

### ISSUE THREAD

**Issue by lin0kin** [mihonapp/mihon#578]
### Describe your suggested feature

sometime, mihon can't reading Library, i have to reopen the app. use text-basing way for Library, maybe easy to edit the Library and avoid this statements.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
what?

**Comment by MajorTanya** [comment]
I have absolutely no idea what you're actually asking, but maybe check out the Invalidate Download Index option in the Advanced Settings if your downloaded chapters are disappearing
