### ISSUE TITLE
Anyway to force complete download? 

### ISSUE THREAD

**Issue by shahriar-17** [mihonapp/mihon#579]
### Steps to reproduce

While downloading a chapter from a particular website, the download stops for the last few pages like 1-8 pages.
An error massage shows saying disconnected from that website.
I don't actually need those last pages. So, my query is any way to force complete the download without last few pages? You see without downloading I can't read offline. So, is there a way to only view the downloaded pages from mihon? (not from file explorer) 

### Expected behavior

It should download completely. 

### Actual behavior

Download is not completing.

### Crash logs

failed to connect to pbwpodg.iufztcmvahdv.hath.networ...

### Mihon version

0.16.4

### Android version

Android 13

### Device

Realme C25S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. It's not Mihon's fault
