### ISSUE TITLE
Wrong date label in updates and history

### ISSUE THREAD

**Issue by not-fried-dumplings** [mihonapp/mihon#58]
### Steps to reproduce

Open any library entry and then go to the history tab.

### Expected behavior

Updates/history should show the correct date.

### Actual behavior

Updates/history shows "yesterday" (or yesterday's date, if relative timestamps is off). 

### Mihon version

0.16.0

### Android version

Android 14

### Device

Samsung Galaxy S21+

### Other details

Possibly caused by the timezone used in the app? Happens in every Tachiyomi version starting from v 0.15+ as well. Reading anything at around 10 PM (my local time), does show "today" instead of "yesterday". Turning relative timestamps off does not help. Choosing another date format also does not help either.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Eragonnogare** [comment]
This is happening to me as well, +1. It's driving me insane.

**Comment by timeholder0** [comment]
I'm facing the same issue (Android 14)
