### ISSUE TITLE
Comics cannot be loaded due to API usage

### ISSUE THREAD

**Issue by salamander7456** [mihonapp/mihon#581]
### Steps to reproduce

On the comic catalog page, click webview and the comics can be loaded normally.

However, after entering a specific chapter on the table of contents page, the comic cannot be loaded.

Then, click on the Webview here and find that the website uses links with the word API, so that the picture only has the name but no content.

https://github.com/mihonapp/mihon/assets/87372595/6816b18d-0338-4da9-84f6-a16248e375a7

Currently, this problem only occurs in the extension "happymh"

### Expected behavior

Comics open normally

### Actual behavior

Webview page only has text and no picture

### Mihon version

0.16.4

### Android version

Android 13

### Device

Poco F5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide support for extension problems, please ask whoever made this extension instead.

**Comment by PennyJim** [comment]
I might be confused, but that looks like an extension issue, not Mihon.

Mihon does not provide support for extensions

**Comment by salamander7456** [comment]
> I might be confused, but that looks like an extension issue, not Mihon.
> 
> Mihon does not provide support for extensions

You're right, I overlooked this aspect. I thought it might be a problem with cloud flare, but it seems to be a problem with this extension.I got some information from the extension publisher's GitHub, thanks for the heads up!
