### ISSUE TITLE
local manga on external storage

### ISSUE THREAD

**Issue by ourslfs** [mihonapp/mihon#583]
### Describe your suggested feature

Kind of niche, but would be nice to have an option to store local manga on sdcard instead of internal storage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Nekuskus** [comment]
While I haven't tested it myself, you should be able to select a different folder for your library, including those on your sd card.

**Comment by AntsyLich** [comment]
Change storage location from "Data and storage"
