### ISSUE TITLE
The "Flash on page change" flashing of black screen is not enough to combat ghosting

### ISSUE THREAD

**Issue by d4rky-pl** [mihonapp/mihon#585]
### Steps to reproduce

On certain cheap e-ink readers (Likebook Mars in my case) just flashing the black screen is not enough to clear the ghosting effect. The screen flashes but ghosting remains.

https://github.com/mihonapp/mihon/assets/284395/973965fc-16ef-479c-a35d-7ebc596d1685

### Expected behavior

The screen should likely do a full cycle of flashing white, then black to clear the ghosting correctly. The way Kindle solves it is by flashing a negative of the image but implementing this might be more complex. Additionally, a 1.5s delay is not necessary and does not actually help with the ghosting, it's mostly just annoying.

### Actual behavior

The screen flashes to pitch black with some ghosting remaining, then after (too long) 1.5s delay switches to the next page while the previous page contents remain in the form of ghosting

![IMAGE 2024-03-27 12:06:22](https://github.com/mihonapp/mihon/assets/284395/41a87e72-cc48-44d3-ab91-324ee7f70f40)

### Mihon version

0.16.4

### Android version

Android 8

### Device

Likebook Mars (t80d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
So white -> black -> next page and no delay in-between?

**Comment by BrutuZ** [comment]
There is a reverse colors filter in the reader already, so the Kindle technique might not be that complex to implement

**Comment by vodkapmp** [comment]
If any changes are to be implemented here, could there be added an option to flash white-black every x page?

Personally the minor amount of ghosting that happens per page change isn't that much of an annoyance for me, as the display on my Onyx Boox Max Lumi is quite good for ghosting.
The flashing every page is much more annoying, but a refresh is needed every now and then to clear it up when it accumulates over 4-5 pages.

**Comment by d4rky-pl** [comment]
@AntsyLich some delay may be required because eink displays have very slow refresh rate so they're skipping frames like crazy. Definitely not 1.5s though, I don't think that helps with anything

**Comment by sirlag** [comment]
I know we are trying in general to cut down on settings, but given the differences in behavior across e-ink displays and the relative level of niche, I think making this configurable but hidden might make the most sense

**Comment by koshisan** [comment]
I am not sure how feasible this is, since it might be even more niche, but the boox/onyx devices do provide an API for eink display related stuff. 

https://github.com/onyx-intl/OnyxAndroidDemo?tab=readme-ov-file

Not only can you trigger a refresh as intended, you could even use different screen modes for different things. For example I like to read my manga in HD mode, but that of course is way too slow to browse through the library...
