### ISSUE TITLE
Manga Chapters Not Updating Correctly in Mihon Android App

### ISSUE THREAD

**Issue by sreeram3015** [mihonapp/mihon#59]
### Steps to reproduce

> Open Mihon App

> Navigate to any of the categories

> Update the library

### Expected behavior

A progress bar is being shown in the notification bar. After it reaches 100% new chapters of mangas will be updated in the app.
![Screenshot_20240117-055552](https://github.com/mihonapp/mihon/assets/114813900/38a12167-e157-432f-84ee-eb6eeebf506a)

### Actual behavior

No progress bar is shown. Updates are not happening properly.

### Mihon version

0.16.0

### Android version

Android 13

### Device

Moto g32

### Other details

The same error did happen in the latest version of tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Winded2** [comment]
im here for possible updates on this cause i have same issue

**Comment by MalGamerz** [comment]
+1 on Redmi Note 12 pro 5G, is it a bugs? Cause I notice the same with TachiyomiSY

**Comment by schwarzpen** [comment]
The problem is caused by the smart update. Go to setting and then go to Library. Select smart update and I deselect Predict next release time.

**Comment by sreeram3015** [comment]
> The problem is caused by the smart update. Go to setting and then go to Library. Select smart update and deselect Predict next release time.

It's working! Thankyou for your help.

**Comment by Anutrix** [comment]
Same issue. Nothing happens after 'Updating Categories' message is seen
