### ISSUE TITLE
lag when switching chapters with scroll

### ISSUE THREAD

**Issue by gabro09805** [mihonapp/mihon#590]
### Steps to reproduce

Scroll from chapter to next

https://github.com/mihonapp/mihon/assets/80535287/ab4c9021-d87c-4567-92d4-a508e8f30312

### Expected behavior

I expected a fairly smooth transition

### Actual behavior

Big freeze/lag when pass to a chapter to another

### Mihon version

0.16.4

### Android version

Android 14

### Device

Samsung Galaxy S24 Plus (exynos)

### Other details

I have enabled the option split tall images and deactivate 32 bit color but the problem persist. I tried various forks of Tachiyomi / Mihon but the same problem is present on all except Tachiyomi j2k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by gabro09805** [comment]
Resolced with new samsung firmware update

**Comment by raxod502** [comment]
I experienced the same behavior, and implemented https://github.com/mihonapp/mihon/pull/728 which resolves it for me.
