### ISSUE TITLE
More customizable?

### ISSUE THREAD

**Issue by Itsyua** [mihonapp/mihon#60]
### Describe your suggested feature

Like more settings for making it look cool like custom backgrounds or etc just asking

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Ekidoxx** [comment]
In terms of customisation, I'dd rather have different layout style, like J2K's vertical expandable categories

![Screenshot_20240122-033619_TachiyomiJ2K](https://github.com/mihonapp/mihon/assets/14035306/373ccfd9-dcee-413e-94b5-add869e950b5)

**Comment by AntsyLich** [comment]
No
