### ISSUE TITLE
Add a switch to temporarily disable or enable repository url

### ISSUE THREAD

**Issue by pheotry** [mihonapp/mihon#601]
### Describe your suggested feature

like this
![IMG_20240330_232910](https://github.com/mihonapp/mihon/assets/43376740/04c5efba-05df-42da-a6e7-5142fcab9df0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
why?
