### ISSUE TITLE
Add support for in App hosts setting

### ISSUE THREAD

**Issue by Just-A-Pony** [mihonapp/mihon#603]
### Describe your suggested feature

Since a lot of website is behind cloudflare,or can't be access in some region,it might need to force some domain to use some specific ip address.
For desktop,it very easy. But for phones,it is nearly impossible to modify hosts without unlock and root the phone.It will be much easier to have a built-in app hosts setting.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Ask the extension maintainer to do something about it.
