### ISSUE TITLE
Feature to convert local manga to mihon cbz

### ISSUE THREAD

**Issue by ghost** [mihonapp/mihon#608]
### Describe your suggested feature

Not sure how possible it is. But the feature would work by scanning the local folder. Then it would auto sort cand convert the chapters.  It can just be a button that says convert local manga in the local source extension of the browse tab.

I have hundreds of manga that I downloaded from another app sometime ago. Attached is how the folders and chapters are sorted. Although the name of the chapters is likely to be different for others.

![Screenshot_20240331_121328_My Files](https://github.com/mihonapp/mihon/assets/62684510/08c5f463-deea-4e71-b37a-ae2fc83c506b)

![Screenshot_20240331_121339_My Files](https://github.com/mihonapp/mihon/assets/62684510/9575d0c2-6959-4b15-8433-25c71d464c55)

![Screenshot_20240331_121351_My Files](https://github.com/mihonapp/mihon/assets/62684510/f65f85c0-3723-4d59-af87-d02983baa217)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
What?

**Comment by AntsyLich** [comment]
Ask the other app to make an exporter for Mihon or use Local Source
