### ISSUE TITLE
Can you increase backup to webdav and recover from Webdav

### ISSUE THREAD

**Issue by wbmins** [mihonapp/mihon#614]
### Describe your suggested feature

Can you increase backup to webdav and recover from Webdav

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

- [ ] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.

- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
Duplicate of #472
