### ISSUE TITLE
Edit Manga Source

### ISSUE THREAD

**Issue by Helio098** [mihonapp/mihon#618]
### Describe your suggested feature

Being able to change the source address of the manga is constantly changing and we have to wait to correct the extension that is often discontinued. 
This way, we can edit the link and continue accessing our manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not Mihon's concern. Ask the your repo maintainer.
