### ISSUE TITLE
Allow disabling reader zoom out

### ISSUE THREAD

**Issue by StrangePeanut** [mihonapp/mihon#62]
### Describe your suggested feature

I've never intentionally zoomed out whilst reading. It would be great to have the option to disable reader zoom out.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenwhat68** [comment]
Like the tachij2k? I hope so too i really like it

**Comment by StrangePeanut** [comment]
> Like the tachij2k? I hope so too i really like it

@stevenwhat68 yep
