### ISSUE TITLE
Mangagekko not working on mihon 

### ISSUE THREAD

**Issue by Stratify23** [mihonapp/mihon#626]
### Steps to reproduce

Tried to add mangagekko through the extension repo since it appears when searching the extension. But does not show up on mihon.

### Expected behavior

I should be seeing mangagekko on the mihon with the extension repo that was provided when downloading.

### Actual behavior

Mangagekko not showing up.

### Mihon version

0.16.4

### Android version

Android 14 

### Device

Samsung s21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions nor is it associated with any extension repos out there. As such, Mihon doesn't provide any support for malfunctioning extensions either. Please ask your extension repo maintainer for assistance instead.
