### ISSUE TITLE
Mal tracking not working

### ISSUE THREAD

**Issue by Astrokinng** [mihonapp/mihon#628]
### Steps to reproduce

1.open mihon preview version 
2. Open the tracker on a particular manga
3. Http 401 error 
4. Logged out of mal from everywhere updated the user agent still error persists 

### Expected behavior

The manga on mal should pop up

### Actual behavior

Http 401 error pops up 

### Mihon version

App version: 0.16.4-6604

### Android version

Android 14

### Device

Samsung galaxy s23ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
In order for MAL tracking to work, you will have to change your User-Agent in the advanced settings. We don't know which one will work for you, but from reports, modern, up-to-date browser UAs seem to be giving good results.

If a particular UA isn't working for you, you may have to restart Mihon and/or unlink and re-link MAL to get it working again.

I'm pretty sure other issues have been filed about this before, so please check for duplicates in future, or ask in the Discord server if you're unsure.
