### ISSUE TITLE
Revoke trust for each extension

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#630]
### Describe your suggested feature

Please add to remove trust for individual extensions.

When an extension trust is added, the only option is to revoke trust for all extensions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Morph21** [comment]
Can't you just delete the extension?

**Comment by infyProductions** [comment]
Is this the "Revoke trusted unknown extensions" option in (More _> Settings -> Advanced) supposed to untrust those extensions in one go?

**Comment by AntsyLich** [comment]
Why?
