### ISSUE TITLE
Copy migrate source name insted of id number

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#631]
### Describe your suggested feature

Copy the source name instead of the ID number during a long hold, and paste it into the extension tab to search for it.

### Other details

Currently, it copies the ID number for extensions, but when you paste it into the search on the extension tab, it can't find it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Character95** [comment]
Or fix the extension search by ID number.

**Comment by Character95** [comment]
Ok thanks for explanation

**Comment by AntsyLich** [comment]
ID is the better option to search for a particular extension so no
