### ISSUE TITLE
SMB support

### ISSUE THREAD

**Issue by kanocence** [mihonapp/mihon#634]
### Describe your suggested feature

I want to use SMB to connect to my NAS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sirlag** [comment]
If you already have a NAS, you can take a look at something like [Komga](https://komga.org/) to serve your media to mihon.

**Comment by damian-anlauf** [comment]
This should be possible through the use of something like [CIFS Documents Provider](https://github.com/wa2c/cifs-documents-provider) or [RSAF](https://github.com/chenxiaolong/RSAF). 
Do note that using Mihon in this way is not officially supported and may lead to issues (especially when you lose connection to your NAS).

**Comment by AntsyLich** [comment]
Install something like Komga on your NAS and access your library through Komga's extension
