### ISSUE TITLE
Mihon constantly crashes, unable to start the app

### ISSUE THREAD

**Issue by bailinhuang** [mihonapp/mihon#639]
### Steps to reproduce

Not sure how to reproduce this.

Happened a while after restarting my Pixel 7. It shows the following error and crashes and reloads the error.

I'm not able to send a crash log
![Screenshot_20240408-202831](https://github.com/mihonapp/mihon/assets/24628727/447870e5-e8d7-4605-9dc9-600c271f5147)

### Expected behavior

Mihon should load as an app and show main page 

### Actual behavior

Crashes with a black screen and shows crash log momentarily before doing it again and again 
![Screenshot_20240408-202831](https://github.com/mihonapp/mihon/assets/24628727/1babea0d-4984-42ec-8737-cb7f52acb2cf)

### Mihon version

0.16.4

### Android version

Android 14

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This has been reported plenty of times before, please check the issues (opened AND closed) before opening a new one. Examples of previous reports: #624, #623, #616, #582, #363.
