### ISSUE TITLE
Page indicator style is broken

### ISSUE THREAD

**Issue by kidonng** [mihonapp/mihon#651]
### Steps to reproduce

1. Launch app
2. Open any manga
3. See issue

### Expected behavior

0.16.4:

![IMG_20240411_170513](https://github.com/mihonapp/mihon/assets/44045911/4e817234-202e-4e02-b08e-b069c6846c0a)

### Actual behavior

0.16.5

![IMG_20240411_170524](https://github.com/mihonapp/mihon/assets/44045911/83534d3a-9482-41c9-88f6-da3475ad2d0f)

### Mihon version

0.16.5

### Android version

Android 13

### Device

Redmi Note 10 Pro (chopin)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Xori71** [comment]
> It is not broken it is the new material design 3 elements from Google https://m3.material.io/components/sliders/overview
> 
> You'll have to live with it until they decide to change it again.
> 
> What is broken is the right to left reading slider being filled at page 1 though.

Actually, it actually does look broken.

The Material 3 slider has two sections, the active section, the inactive section, and a divider between the two. Meanwhile, Mihon has the active section, the divider, and... no inactive section. Furthermore, the slider looks overlayed on top of the dots representing the pages. My suggestion would be to completely get rid of the dots, and use the full slider. The steps would still be there, only the dots would disappear.

![Screenshot_20240411-130127_Chrome~2](https://github.com/mihonapp/mihon/assets/101265862/90df8a94-2969-43a5-9f95-a28ece96413d)
![Screenshot_20240411-130107_Mihon~2](https://github.com/mihonapp/mihon/assets/101265862/af9cde46-12fa-411d-b788-41f61257e5e6)

**Comment by Xori71** [comment]
> It's literally what I said. Check the left to right reading mode, it works as intended. The one that is broken is the right to left reading mode as that is now set by language
> 
> ![Screenshot_20240411_121836_Firefox.jpg](https://private-user-images.githubusercontent.com/66540317/321594196-3b1b6ef2-0cd9-450a-89b7-a033db4c5a0b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzExMjQsIm5iZiI6MTcxMjgzMDgyNCwicGF0aCI6Ii82NjU0MDMxNy8zMjE1OTQxOTYtM2IxYjZlZjItMGNkOS00NTBhLTg5YjctYTAzM2RiNGM1YTBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEwMjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNDQ2ZTFkNjc4NDBiOTAxZDU3YmRkZGY4ZTJiNjRiMjRiOWY3ZDVmOGQwMjczOWNlOGI2MTlhZWVkODI3OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw8O6AqE31A_TqUyoPnTUOe9NUOUO225pDXuokR6Umw)

Shit, my bad. I misread your reply.

**Comment by Xori71** [comment]
> I wonder if this could be solved by reversing the colors? Like take this discrete slider and just reverse the colors on them? Or does that break the theming everywhere else?
> 
> ![Screenshot_20240411_123043_Firefox.jpg](https://private-user-images.githubusercontent.com/66540317/321598020-6210ee93-9e2a-4514-a81e-2c3ff4904c23.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzE5NzQsIm5iZiI6MTcxMjgzMTY3NCwicGF0aCI6Ii82NjU0MDMxNy8zMjE1OTgwMjAtNjIxMGVlOTMtOWUyYS00NTE0LWE4MWUtMmMzZmY0OTA0YzIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEwMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTI0ODIwZjgxYWM3OTQwNmU0MGNiZGFiM2NmMGNmOTgxMDg5MzI0MzE2ZGU0YmExYTM3N2FjMWI0ZGRmZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDI5jWGgRtZsxKN0E7cGL1tcXjrmBNBAEfUia_j5_EA)

I am not familiar with Material Design frameworks, but in this instance, the segment doesn’t appear at all in the slider. Reversing the colors would probably just make the slider grey.

**Comment by MajorTanya** [comment]
Some themes were created with a colour palette that doesn't 100% match with what Material Design expects. Sometimes, attributes that are expected to be visually different have historically been set to the same value, causing these newer component designs to end up using the same colour twice.

M3 colours palettes are defined by a long list of attributes, like `primary` and `primaryInverse` (I believe there are about 30 or so different attributes).

"Fixing" these colour sets by making the attributes these components use actually distinct would mean going back and trying to recreate every theme with the modern palette definitions. While this is technically possible, it would be painstaking work and also end up with most themes appearing differently (because of the newly differing colours).

Some themes intentionally define different attributes as the same colour to preserve the aesthetic of the theme, and would end up appearing extremely different if they defined their colours exactly to spec.

This affects several of these progress components across the app, not just the chapter slider.

**Comment by Xori71** [comment]
> Some themes were created with a colour palette that doesn't 100% match with what Material Design expects. Sometimes, attributes that are expected to be visually different have historically been set to the same value, causing these newer component designs to end up using the same colour twice.
> 
> M3 colours palettes are defined by a long list of attributes, like `primary` and `primaryInverse` (I believe there are about 30 or so different attributes).
> 
> "Fixing" these colour sets by making the attributes these components use actually distinct would mean going back and trying to recreate every theme with the modern palette definitions. While this is technically possible, it would be painstaking work and also end up with most themes appearing differently (because of the newly differing colours).
> 
> Some themes intentionally define different attributes as the same colour to preserve the aesthetic of the theme, and would end up appearing extremely different if they defined their colours exactly to spec.
> 
> This affects several of these progress components across the app, not just the chapter slider.

So we basically have to pray that Google does something about this themselves.

**Comment by MajorTanya** [comment]
> > Some themes were created with a colour palette that doesn't 100% match with what Material Design expects. Sometimes, attributes that are expected to be visually different have historically been set to the same value, causing these newer component designs to end up using the same colour twice.
> > 
> > M3 colours palettes are defined by a long list of attributes, like `primary` and `primaryInverse` (I believe there are about 30 or so different attributes).
> > 
> > "Fixing" these colour sets by making the attributes these components use actually distinct would mean going back and trying to recreate every theme with the modern palette definitions. While this is technically possible, it would be painstaking work and also end up with most themes appearing differently (because of the newly differing colours).
> > 
> > Some themes intentionally define different attributes as the same colour to preserve the aesthetic of the theme, and would end up appearing extremely different if they defined their colours exactly to spec.
> > 
> > This affects several of these progress components across the app, not just the chapter slider.
> 
> So we basically have to pray that Google does something about this themselves.

They won't. They're using the palette attributes they say should be visually different but some themes don't define them to be such. The sections not being different colours is a design issue with most of Mihon's themes.

**Comment by Xori71** [comment]
> > > Some themes were created with a colour palette that doesn't 100% match with what Material Design expects. Sometimes, attributes that are expected to be visually different have historically been set to the same value, causing these newer component designs to end up using the same colour twice.
> > > M3 colours palettes are defined by a long list of attributes, like `primary` and `primaryInverse` (I believe there are about 30 or so different attributes).
> > > "Fixing" these colour sets by making the attributes these components use actually distinct would mean going back and trying to recreate every theme with the modern palette definitions. While this is technically possible, it would be painstaking work and also end up with most themes appearing differently (because of the newly differing colours).
> > > Some themes intentionally define different attributes as the same colour to preserve the aesthetic of the theme, and would end up appearing extremely different if they defined their colours exactly to spec.
> > > This affects several of these progress components across the app, not just the chapter slider.
> > 
> > 
> > So we basically have to pray that Google does something about this themselves.
> 
> They won't. They're using the palette attributes they say should be visually different but some themes don't define them to be such. The sections not being different colours is a design issue with most of Mihon's themes.

Oh, okay-okay.

**Comment by okt-olgak** [comment]
Even without RTL/LTR issues, the following issues are still present:
* Progress bar does not exist until 1/6 through the manga
* Dividing line is too thick for page count
* Dividing line has big gaps on both sides, making some pages look like they don't fit in either "read" or "unread".
![image](https://github.com/mihonapp/mihon/assets/107189901/57d5c610-14bc-4aa1-97da-5631698d06b0)
![image](https://github.com/mihonapp/mihon/assets/107189901/db77ff24-76f8-49d7-81dc-584022d5a1a9)

All of those issues are probably caused by the progress bar not being designed for 40 discrete stops. I think this just means this M3 Discrete progress bar is not fit for Mihon purposes.

**Comment by Xori71** [comment]
> All of those issues are probably caused by the progress bar not being designed for 40 discrete stops. I think this just means this M3 Discrete progress bar is not fit for Mihon purposes.

This is not the case.

![Screenshot_20240411-191456_Mihon~2](https://github.com/mihonapp/mihon/assets/101265862/fd0862a5-f4ab-46b5-ab2c-2d5b4ecb2373)
![Screenshot_20240411-191500_Mihon~2](https://github.com/mihonapp/mihon/assets/101265862/a8da8201-165e-446b-9da9-28e5e5c345d8)

**Comment by MajorTanya** [comment]
![screenshot](https://github.com/mihonapp/mihon/assets/39014446/46358b57-4028-4511-b806-66f8dc1b064e)
works correctly with a small number of pages, so I don't think this is somehow Mihon's fault.

**Comment by MajorTanya** [comment]
> > All of those issues are probably caused by the progress bar not being designed for 40 discrete stops. I think this just means this M3 Discrete progress bar is not fit for Mihon purposes.
> 
> This is not the case.
> 
> ![Screenshot_20240411-191456_Mihon~2](https://private-user-images.githubusercontent.com/101265862/321707461-fd0862a5-f4ab-46b5-ab2c-2d5b4ecb2373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM4ODEsIm5iZiI6MTcxMjg1MzU4MSwicGF0aCI6Ii8xMDEyNjU4NjIvMzIxNzA3NDYxLWZkMDg2MmE1LWY0YWItNDZiNS1hYjJjLTJkNWI0ZWNiMjM3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODhmYzI0MzY3ZDZjOTQ3MTVkMzI5MTJlNDM4MTc3ZDk1NmIxMzdhZWYxNDczMGY2MmQ1NGNkNDY5MDQ4NmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IWdVojhAqkbsu11mRtJQE-8g83kjeYvEVP1jcqrvLVg) ![Screenshot_20240411-191500_Mihon~2](https://private-user-images.githubusercontent.com/101265862/321707467-a8da8201-165e-446b-9da9-28e5e5c345d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM4ODEsIm5iZiI6MTcxMjg1MzU4MSwicGF0aCI6Ii8xMDEyNjU4NjIvMzIxNzA3NDY3LWE4ZGE4MjAxLTE2NWUtNDQ2Yi05ZGE5LTI4ZTVlNWMzNDVkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDg3MTk5NzJmZGFkYWU4YTY1YTI4MTc4YTEwNDY2NDI4ZWNmOWE1NDFlZDZlYTgxZWFmMDZlMzRiZTVjYjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q3QTz6RknwziiFVW2ffNPjNyW-X_NsuKuhfuSYYhdA8)

I'm not sure I understand what you mean by "This is not the case" here, to be honest.

**Comment by Xori71** [comment]
> > > All of those issues are probably caused by the progress bar not being designed for 40 discrete stops. I think this just means this M3 Discrete progress bar is not fit for Mihon purposes.
> > 
> > 
> > This is not the case.
> > ![Screenshot_20240411-191456_Mihon~2](https://private-user-images.githubusercontent.com/101265862/321707461-fd0862a5-f4ab-46b5-ab2c-2d5b4ecb2373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM4ODEsIm5iZiI6MTcxMjg1MzU4MSwicGF0aCI6Ii8xMDEyNjU4NjIvMzIxNzA3NDYxLWZkMDg2MmE1LWY0YWItNDZiNS1hYjJjLTJkNWI0ZWNiMjM3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODhmYzI0MzY3ZDZjOTQ3MTVkMzI5MTJlNDM4MTc3ZDk1NmIxMzdhZWYxNDczMGY2MmQ1NGNkNDY5MDQ4NmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IWdVojhAqkbsu11mRtJQE-8g83kjeYvEVP1jcqrvLVg) ![Screenshot_20240411-191500_Mihon~2](https://private-user-images.githubusercontent.com/101265862/321707467-a8da8201-165e-446b-9da9-28e5e5c345d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM4ODEsIm5iZiI6MTcxMjg1MzU4MSwicGF0aCI6Ii8xMDEyNjU4NjIvMzIxNzA3NDY3LWE4ZGE4MjAxLTE2NWUtNDQ2Yi05ZGE5LTI4ZTVlNWMzNDVkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNjM5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDg3MTk5NzJmZGFkYWU4YTY1YTI4MTc4YTEwNDY2NDI4ZWNmOWE1NDFlZDZlYTgxZWFmMDZlMzRiZTVjYjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q3QTz6RknwziiFVW2ffNPjNyW-X_NsuKuhfuSYYhdA8)
> 
> I'm not sure I understand what you mean by "This is not the case" here, to be honest.

It was a stupid reply. I thought about it some more, and yeah, your point stands. It’s a mix of Mihon sometimes cramping too many dots inside the progress bar, and Google not having the spacing dynamically changing after a certain point threshold has been passed.

**Comment by MajorTanya** [comment]
FWIW, I tried checking the M3 spec for these new "Sliders" as these are actually called, but the specs don't talk about a maximum number of steps, or about not colouring anything before 1/6.

**Comment by Xori71** [comment]
> FWIW, I tried checking the M3 spec for these new "Sliders" as these are actually called, but the specs don't talk about a maximum number of steps, or about not colouring anything before 1/6.

I see. And I agree, I would be surprised if this is how the new design functioned normally. I don't know what the cause of these issues is.

**Comment by FooIbar** [comment]
https://developer.android.com/jetpack/androidx/releases/compose-material3#1.3.0-alpha02

> Fixed an issue with Slider and RangeSlider on RTL layout
