### ISSUE TITLE
Pause between downloads

### ISSUE THREAD

**Issue by Expakun** [mihonapp/mihon#653]
### Describe your suggested feature

This feature should space out downloads for a few minutes between chapters so that you don't have to worry about harming the source, while being able to download many chapters at once

### Other details

It would be nice if I could download all chapters of a series without harming the source or being rate limited by the source. With this feature, I could just download any manga overnight.

This is the same request as [issue #8080 for the original tachyomi ](https://git.mihon.tech/tachiyomi/tachiyomi/issues/8080)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Extension developers can just set a rate limit in the extension itself. This is what Tachiyomi did in that past when they offered extensions, and would be the responsibility of whoever you're getting your extensions from nowadays.

If a source takes issue with Mihon making too many requests for downloads, it has to take that up with the extension maintainers instead, who are able to define and tighten those rate limits.
