### ISSUE TITLE
Missing download mangga

### ISSUE THREAD

**Issue by eezairi** [mihonapp/mihon#663]
### Steps to reproduce

1 Home page is at download 2 open the bookmark and left it overnight the open download in the morning all my download in library is gone 3 the download  mangga cannot be download in update tab only in the manga home page 4 the missing download manga still can be read on the update page without internet
![Screenshot_2024-04-14-07-02-49-09_55bef12f624c2b805189a6aa783c400d](https://github.com/mihonapp/mihon/assets/42660524/2efebae8-21df-4116-9182-566d4d728dca)
![Screenshot_2024-04-14-07-02-16-35_551f7f0ca926862b368845ce7ee433aa](https://github.com/mihonapp/mihon/assets/42660524/be19d4dd-7e07-4238-b2ab-9ed217499542)

### Expected behavior

The already downloaded manga is in teh library tab

### Actual behavior

The download manga is missing but not deleted

### Mihon version

0.16.5

### Android version

11

### Device

Realme 6 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by eezairi** [comment]
Update the missing mangga

**Comment by MajorTanya** [comment]
> Update the missing mangga

Did the index invalidation solve your issue?
