### ISSUE TITLE
Disable XML file in cbz

### ISSUE THREAD

**Issue by samsja** [mihonapp/mihon#664]
### Describe your suggested feature

Hey, First thanks for the great app.

Is there a way to disable to save the XML file when downloading a chapter into cbz ? See the screenshot attached.

This XML file was not created with tachiomy.

Thanks in advance 
![Screenshot_20240414-010732](https://github.com/mihonapp/mihon/assets/55492238/ba9b4597-6286-42e0-9e0a-53325a2f35a5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment]
The comicinfo.xml is created by mihon when you download a chapter so there's chapter metadata if you ever have the desire to move the files elsewhere and the application supports metadata using that file. It doesn't affect anything so I don't really see a reason that it needs to be disabled.

**Comment by AntsyLich** [comment]
No. It's causing you 0 inconvenience or harm.

**Comment by samsja** [comment]
@AntsyLich it is actually causing me some harm, otherwise I would not be asking.

I am transferring the cbz file to my Kobo reader that cannot read the cbz proprely because of this XML file. Now I have to manually unzip remove the file and zip.


I could understand that this usecases is not very important for mihon that is why I was asking to be able to disable it as an option.

Thanks in advance

**Comment by AntsyLich** [comment]
Have you considered asking the kobo people to ignore ComicInfo.xml as they should for cbz, cbr and any other cb archive file formats?

**Comment by samsja** [comment]
> Have you considered asking the kobo people to ignore ComicInfo.xml as they should for cbz, cbr and any other cb archive file formats?

Unfortunately kobo is a closed source platform there is not so much of asking  there :cry: .
It is definitely a problem on their side and the xml should be totally valid. 

I was just wondering if they were any workaround on mihon side to make it work.

Thanks

**Comment by AntsyLich** [comment]
Email them or something. 

![QpKmmJZ](https://github.com/mihonapp/mihon/assets/59261191/6c4204f4-2efb-41ff-9483-99771f05636c)

**Comment by samsja** [comment]
I am being quite polite 😅 

I am an open source maintainer as well, I am just asking a feature, feel free to just say it is not possible. Not need for weird meme
