### ISSUE TITLE
chapter loading error

### ISSUE THREAD

**Issue by Darkvramp** [mihonapp/mihon#665]
### Steps to reproduce

Commonly happens After 3 chapters
Any exstention.
4th chapter will get into a loading loop.
Extension is reachable in webapp mode, chapter is readable in Web app mode.

To break loop requires moving into further chapter, allowing for first image to load, going back to 4th chapter and loop should be broken.

Clearing cache and cookies did not allow for loop to break.

Tried multiple VPN locations, and speed testing, which was not to cause.

Tried changing the DNS and that did not solve the issue.

### Expected behavior

Chapter should load just like previous chapters, or show error message.

### Actual behavior

Chapter would fail to load predictably on the 4th chapter after starting reading(so starting from chapter 9 it would be chapter 13 would fail to load)
And display the try again button and load in Web app button which does not load to Web app.

### Mihon version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) Android version: 13 (SDK 33; build T1TOS33.33-45-23-12) Device brand: motorola Device manufacturer: motorola Device name: devonn (devonn_g_sys) Device model: moto g power 5G - 2023 WebView: Android System WebView 123.0.6312.99

### Android version

Android 13

### Device

moto g power 5G - 2023

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
I assume by "Web app mode" you mean the WebView?

I cannot reproduce this issue. Maybe try downloading the first two chapters, then turning on Download Ahead in the Download settings?

**Comment by Darkvramp** [comment]
Yes, I meant Web view mode 
Download ahead is turned on.
Failure to load 4rd chapter is present while downloading chapter, causing failure to download chapter.
Occurs regardless of "repository".

**Comment by AntsyLich** [comment]
Join our discord for further support. GitHub is not the best place for troubleshooting
