### ISSUE TITLE
App crashes when reading manhwa

### ISSUE THREAD

**Issue by Levrushka** [mihonapp/mihon#666]
### Steps to reproduce

I experienced this problem on Tachi and here too. Reading any manhwa(with long pages) causes the application to crash. Chapters 10-20 everything goes fine, but after that there is a moment about which the app is "stumbling"

### Expected behavior

A typical reading of a manhwa

### Actual behavior

Initially it crashes to the main menu with mangas, and the second time it crashes from the entire application

### Crash logs

[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14969756/mihon_crash_logs.txt)

### Mihon version

0.16.5

### Android version

10

### Device

Redmi(M2006C3LG)

### Other details

Usually happens in webcomic mode, but if you change it to standard, the problem remains 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Download and read those chapters. They are too large for your device to handle. Downloading splits tall images in smaller pieces.
