### ISSUE TITLE
Read Duration Tracking not working

### ISSUE THREAD

**Issue by SatoX69** [mihonapp/mihon#667]
### Steps to reproduce

I previously used the older version of this app (ifykyk) , and now with the updated version (with everything synced), I have read over 19k chapters. However, on the statistics tab, it only shows "2 days" worth of read duration. Interestingly, another user shared a screenshot of their stats, revealing they've read a total of 12k chapters, considerably less than mine, yet they somehow have 35 days of read duration.

### Expected behavior

The app should accurately track my reading duration. 

### Actual behavior

Doesn't track on my phone, stuck on "2 days" for the last 2 years

Here's an image of my friend's stats with over 50k read chapters:
![Friend 1 Stats](https://github.com/mihonapp/mihon/assets/127420166/fadc4202-4efd-4f0d-8916-d58d9d447e58)
It displays a 7-day read duration.

And here's another friend's stats with significantly fewer total read chapters:
![Friend 2 Stats](https://github.com/mihonapp/mihon/assets/127420166/a7bc662c-71cd-4186-be45-baf9e2580b84)

### Mihon version

0.16.5

### Android version

Android 12

### Device

Redmi 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
If you use some shit source that likes to change chapter urls every other minute of the day the app can't do anything about it. different url = different chapter = you never read it = nothing counted

**Comment by SatoX69** [comment]
> If you use some shit source that likes to change chapter urls every other minute of the day the app can't do anything about it. different url = different chapter = you never read it = nothing counted

I've been using the same source for the last 2 years with same entities, I suppose they change the urls (?).

Is there any way to counter it?

**Comment by AntsyLich** [comment]
The solution is to not use shit sources. Clearly you're friends are not using shit sources.

**Comment by SatoX69** [comment]
> The solution is to not use shit sources. Clearly you're friends are not using shit sources.

Alright, thanks. Appreciate the helpful response

**Comment by MajorTanya** [comment]
1. You can say Tachiyomi, it's literally all over the source code anyway
2. Even Tachiyomi devs knew it had issues with inaccurate reading duration stuff, especially related to backups
3. That screenshot of 53k chapters in 7d 7h would mean something like 300 chapters per hour, which seems like their data is undercounted too
4. I'm not sure if Mihon even touched the code that handles reading duration at this time 
5. For the love of everything under the sun do not put hundreds and thousands of titles into your global updates
