### ISSUE TITLE
FlareSolverr implementation

### ISSUE THREAD

**Issue by Mylloon** [mihonapp/mihon#668]
### Describe your suggested feature

FlareSolverr bypass Cloudflare.

### Other details

SY already have a open PR for this: https://github.com/jobobby04/TachiyomiSY/pull/1124
Here is a reference of implementation for Suwayomi: https://github.com/Suwayomi/Suwayomi-Server/pull/844

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
![image](https://github.com/user-attachments/assets/0be815d8-8a9d-42f8-8b3c-cc4d72bc5097)

**Comment by AntsyLich** [comment]
Another day of finding out some issue that I should've closed months ago 🫠
