### ISSUE TITLE
Not downloading any manga/manhwa 

### ISSUE THREAD

**Issue by rahatbracu** [mihonapp/mihon#67]
### Steps to reproduce

1) Same extension as Tachiyomi 
2) Using Tachiyomi , it downloads 
3) Mihon doesnot

### Expected behavior

Download as expected 

### Actual behavior

Not downloading, just in download queue

### Mihon version

0.16.0

### Android version

Android 10

### Device

Xiaomi Redmi 9C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenwhat68** [comment]
I don't know why and hope you got your problem fix but i say mine is working and i can download any thing, might be a file location problem or space or a extension problem

**Comment by rahatbracu** [comment]
> I don't know why and hope you got your problem fix but i say mine is working and i can download any thing, might be a file location problem or space or a extension problem

Are you able to download from Toonily extension? Please let me know
