### ISSUE TITLE
Store fist page

### ISSUE THREAD

**Issue by Naputt1** [mihonapp/mihon#670]
### Describe your suggested feature

Add an option for specific sorce to cache/store  first/last page to reduce unnecessary loading time

Or even better just remove first/last page

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
What use would it be to cache a specific chapter page?

**Comment by BrutuZ** [comment]
I'm assuming the very edge case of scanlator credit pages that are repeated over several chapters

**Comment by Xori71** [comment]
> I'm assuming the very edge case of scanlator credit pages that are repeated over several chapters

I imagine that would be very difficult to do, because:

1. Scanlators don’t always put the credits page in the beginning/end of the chapter (That usually is the case, but it is not necessarily a given).
2. Mihon would have to analyze the page and search for common elements. Seems like a very taxing algorithm to implement.

**Comment by Naputt1** [comment]
I meant allow user to manually set the  number of first/last pages to skip on certain sources

**Comment by BrutuZ** [comment]
Still too niche to be a app setting, even more so when you take into consideration how the team is against additional settings to the point of replacing existing ones with fixed values (autobackup count, 32-bit reader, ... ) .

Probably best chances of having this implemented as an extension setting. More fitting too as an app setting would apply to every entry regardless of source.
