### ISSUE TITLE
Simple Change Request

### ISSUE THREAD

**Issue by lxymix** [mihonapp/mihon#671]
### Describe your suggested feature

![retouch_2024041521240697](https://github.com/mihonapp/mihon/assets/155837366/68a00dbf-4a12-4925-a632-bd2dae96ce72)

### Other details

Can you make the latest version not (-I--------) but circle (-O--------) like the old version or add in the setting an button that can make it circle or I 

PS:if it's bother I'm sorry because it feel weird that it became an I not circle it feels new to me
you can just ignore this if it's bother to you guys and thank you for this great app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This is not a Mihon decision, it's how the Material Design framework has decided to redesign these components. You'll probably see this type of slider appear in other apps over time too if they use the latest Material Design components.
