### ISSUE TITLE
Even if refreshed, the cover cannot be found

### ISSUE THREAD

**Issue by yaviper** [mihonapp/mihon#672]
### Steps to reproduce

1.Cover lost

2.It can be opened on the web

3.Even after refreshing（advanced setting）, the cover cannot be found

### Expected behavior

Can recognize the cover of resources within the website and display it

### Actual behavior

Even if refreshed, the cover cannot be found

### Mihon version

0.16.5

### Android version

android 14

### Device

iqoo neo 6se

### Other details

I used Tachiyomi's backup， changed network environment ,but  it's useless。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lilaosjdh** [comment]
Is doesn't work so can you fix it

**Comment by AntsyLich** [comment]
We don't provide extension support
