### ISSUE TITLE
incorrect download status indicator progess in the library 

### ISSUE THREAD

**Issue by WeepingClown13** [mihonapp/mihon#678]
### Steps to reproduce

This has been happening for the first time, and all that's been done is try to download the latest chapter (chapter 339) of unOrdinary (mangasee extension)

### Expected behavior

Progress of download is correctly shown everywhere.

### Actual behavior

The download status is shown as full on the download button for unOrdinary chapter 339 once you click unOrdinary in the library. But it is still downloading and only about 80% complete. The downloads section as well as the notification shows the correct progress.

This behaviour does persist upon closing and restarting the app.

![Screenshot_20240418_163630_Mihon](https://github.com/mihonapp/mihon/assets/95921427/708c3e7b-b11b-45fd-94de-6e53338ea923)
![Screenshot_20240418_163633_Mihon](https://github.com/mihonapp/mihon/assets/95921427/f55db142-7621-4eb1-81c6-bc9ff38b7af7)

### Mihon version

0.16.5

### Android version

Android 13

### Device

Samsung Galaxy S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ToxicMushroom** [comment]
I'm also on 0.16.5 and have seen the same issue,
I think the stroke size is just way too big on the download progress indicator, see video:

https://github.com/mihonapp/mihon/assets/32853531/f73e2ba0-1017-44ee-a123-487a4f22cc5d

**Comment by MajorTanya** [comment]
> I'm also on 0.16.5 and have seen the same issue,
> I think the stroke size is just way too big on the download progress indicator, see video:
> 
> https://github.com/mihonapp/mihon/assets/32853531/f73e2ba0-1017-44ee-a123-487a4f22cc5d
> 
> 

That graphical glitch is unrelated to the issue at hand and already solved in the preview of Mihon, just not in stable yet.

**Comment by ToxicMushroom** [comment]
_Sorry, I think I read through it too fast the first time, it looked quite identical to the issue I experienced._ 

I tried reproducing this issue but am failing to do so, all icons and indicators are synced for me when navigating between the manga view/download view/notification.

As for 
> The download status is shown as full on the download button for unOrdinary chapter 339 once you click unOrdinary in the library.

The second screenshot you attached is not full (No checkmark and slight purple on the top left of the icon).

**Comment by WeepingClown13** [comment]
@ToxicMushroom sure, that makes sense. But regardless I'd say it is not moving symmetrically, and nor is the result intuitive (as you can see from how I described it as full).

**Comment by MajorTanya** [comment]
> @ToxicMushroom sure, that makes sense. But regardless I'd say it is not moving symmetrically, and nor is the result intuitive (as you can see from how I described it as full).

The "done" state is always marked with a checkmark in a filled circle, whereas the in-progress download is marked with a slowly filling (clockwise) circle with the download icon on it.

As for the "symmetrical movement" you mention, I think it's difficult to judge whether a linear progress bar and a filling circle are in sync visually, especially with a chapter with many pages. I'm certain the code updating the progress on each of them is linked to the same download process with the same progress data.

The perceived desync might be down to the graphical glitch I mentioned in my previous comment, which is an unfortunate side effect of our rushed update for the Pixel phone crash loop, when we forgot to include the relevant graphical fix in the release as well.

If you're up for it, I'd like you to try the Mihon Preview version and see if the difference in progress marking that you're seeing still persists.

You can get it here: https://github.com/mihonapp/mihon-preview

Use the same source, series, and chapter for best reproduction

**Comment by WeepingClown13** [comment]
@MajorTanya confirmed that it is indeed fixed in the preview. Guess it's the fat stroke size that's the culprit afterall? Anyway, thanks for the update.
