### ISSUE TITLE
Add indication for failed updates on library page

### ISSUE THREAD

**Issue by destroyedData** [mihonapp/mihon#686]
### Describe your suggested feature

**Issue:** When a manga fails to update for some reason (missing/broken source, missing chapters etc) it is difficult to see which entries in the library failed. 

**Current situation:** At this time, the problematic entries are just listed in a txt file which makes it a pain, making users swap between the txt and mihon to find the right library entry, then migrating that.

**My suggested solution:** It would be nice to have some indication on the library page so users can easily see what to migrate. I suggest to add something like a warning sign in the corner similar to the unread chapter count so users can tell at a glance if their favorite manga failed to update. Even better if filtering by these failed entries is possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by yatounoneko** [comment]
After a recent update, I found that version 0.16.5 could not update the missing komga. Even if the smart update is turned off, the status bar prompts the card to be stuck in a certain percentage and disappears. 

If you can add this function, I think it is very useful.

**Comment by AntsyLich** [comment]
I would rather have #132
