### ISSUE TITLE
Selection function for description position

### ISSUE THREAD

**Issue by Yutasj** [mihonapp/mihon#693]
### Describe your suggested feature

I don’t know about others, but I use 10+ extensions, and sometimes it happens that one source delays the release of new chapters.  You have to check each expansion for new chapters, and during this time the descriptions of the works are always in the open position.  You have to either close it or scroll down a little to see the last chapter number.  This requires unnecessary steps and is quite inconvenient when you want to quickly check everything.  Therefore, I think it would not hurt to add a selection function so that the description is always either in the closed position or in the open position.

Correct me if I wrote something incorrectly or somehow conveyed the idea incorrectly (after all, this is not my native language, so I apologize in advance).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Yutasj** [comment]
@Smol-Ame  It turns out that something that was specially made cannot be edited?

**Comment by AntsyLich** [comment]
No wish to change the behavior
