### ISSUE TITLE
Feature to view size of the chapter 

### ISSUE THREAD

**Issue by Whiplash6009** [mihonapp/mihon#695]
### Describe your suggested feature

It should just show  the size of chapter to determine the quality or to save data 

### Other details

I'm really sorry if this feature already exists as the only way I can currently see the size of the chapter is through downloading it and then viewing it in file manager

It will be helpful as sometimes when I'm travelling and have to save data or when I'm at home want to read the best quality/resolution available.
Thank you 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
there is no way to tell the size until you download it, or the source advertises that data.

**Comment by Whiplash6009** [comment]
> there is no way to tell the size until you download it, or the source advertises that data.

So it doesn't know the size of the chapter until it's complete downloaded
