### ISSUE TITLE
Extensions missing after daily update

### ISSUE THREAD

**Issue by itzngga** [mihonapp/mihon#708]
### Steps to reproduce

1. activate daily update for 12 hours
2. wait after update

3. some update error:
![image](https://github.com/mihonapp/mihon/assets/29621457/ac7049e9-9df5-4e73-a2f8-07cf379d878f)

### Expected behavior

update successfuly

### Actual behavior

missing extensions and only local extensions

### Crash logs

[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/15104329/mihon_crash_logs.txt)

### Mihon version

Beta r6648

### Android version

14

### Device

Xiaomi 12s Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by infyProductions** [comment]
That notification (attached in the image) allows you to see why it failed to update. Most of these are source issues based on experience and requires to contacting your extension maintainer instead.

_(Standard disclaimer: Mihon doesn't have, associate, or provide any extensions, nor help with extension/source issues)_

**Comment by itzngga** [comment]
in latest update, i found it rarely
