### ISSUE TITLE
Shortcut for jumping to next chapter

### ISSUE THREAD

**Issue by Nihal621** [mihonapp/mihon#71]
### Describe your suggested feature

In SY and J2K theres a feature while reading with which you can jump to any chapters you want while being in chapter and dont have return to the title menu. I request that feature be included in mihon too.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
It's still 2 click either way
