### ISSUE TITLE
Neither Cloudflare bypass nor WebView working for TCBScans

### ISSUE THREAD

**Issue by moogle19** [mihonapp/mihon#718]
### Steps to reproduce

1. Install TCBScans extension
2. Try to fetch chapters

### Expected behavior

It shoud load the chapters

### Actual behavior

Bypass fails and if I try the WebView I get into a loop. After verifying that im human, it just reloads the site.

### Mihon version

0.16.5

### Android version

14

### Device

Xiaomi Pad 6

### Other details

The site redirects from tcbscans.com to tcb-backup.bihar-mirchi.com. Not sure if this is a problem.
I use Tachimanga on iOS and the Cloudflare bypass does work there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by moogle19** [comment]
Yeah, tried that already. I don't think it is a problem with the extension, but maybe with the webview implementation. I just quickly glanced at the code, but it seems there is some matching with the hostname. Could the redirect to another URL be a problem there?

https://github.com/mihonapp/mihon/assets/792046/7e48b54d-106e-4184-ada8-0d85b151e723

**Comment by Character95** [comment]
In settings / advanced / Default user agent string I add only this sign (*) then go to source and open extension in webview then go back to source and refresh it work for any extension it will bypass cloudflare

**Comment by MajorTanya** [comment]
Standard Cloudflare issue, closing as it's the same thing as all the others and also the same as the one described in the website Troubleshooting FAQs.
