### ISSUE TITLE
Add Komikku Fork to the website 

### ISSUE THREAD

**Issue by AbdelrahmanElnezamy121** [mihonapp/mihon#719]
### Describe your suggested feature

Add Komikku Fork to the website 

### Other details

Add Komikku Fork to the website 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
What even is that? No info provided
If it's just a fork hard coded to a provider (like the cat one) that's probably not gonna happen given the implications
