### ISSUE TITLE
[ **Hide** ] Categories

### ISSUE THREAD

**Issue by Kalip514** [mihonapp/mihon#72]
### Describe your suggested feature

I like to hide my NSFW+18 Manga/Manhwa in the categories.... So that the other's don't know I have them in the categories

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Should probably be a feature of SY as it is Hentai focused.

**Comment by Kalip514** [comment]
VERY FAST to brush it aside but.... Ok.... Thanks.... I'll check over there.....
