### ISSUE TITLE
add option for (remember trust for installed extension in create backup )

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#720]
### Describe your suggested feature

If extensions are reinstalled or updated trust is removed
if added option to remember trusted extension in backup you don't need to manually add trust again for extension when you need for some reason reinstall or update and it demands again
And when you restore backup and there is list of  missing extensions pleaseadd option to add trust for all these extensions if installed...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
That would defeat the purpose, there's no way to know the extension already or newly installed is the same one you once trusted and not an imposter

**Comment by Character95** [comment]
> That would defeat the purpose, there's no way to know the extension already or newly installed is the same one you once trusted and not an imposter

Can it be added option to add trust for all installed extension?
If i install extension i trust that extension if there is issue with the app i revoke trust and remove extension that i last installed...

**Comment by AntsyLich** [comment]
Closing in favor of #320
