### ISSUE TITLE
MyAnimeList HTTP 401

### ISSUE THREAD

**Issue by masdabazz** [mihonapp/mihon#724]
### Steps to reproduce

Click on tracker button for any entry. 

### Expected behavior

Shows tracking data for myAnimeList

### Actual behavior

SHows HTTP Error 401

### Mihon version

0.16.5

### Android version

Andriod 12

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Unlink and relink your MAL, and remember that in Mihon 0.16.5, you have to change the default User-Agent if linking fails.
