### ISSUE TITLE
Extension repo not showing extensions

### ISSUE THREAD

**Issue by Abdulsalam-Selim** [mihonapp/mihon#727]
### Steps to reproduce

Go to extension and get an update but no update.
Go to extension repo to confirm extension repo is working
New extensions are not showing

### Expected behavior

Uninstalled extensions should be showing up and new updates should also be showing 

### Actual behavior

No updates and no uninstalled extensions are showing up. Only installed extension are showing up, all installed extensions are working with no problems 

### Crash logs

Old extensions are working fine and we view is working for all installed extension.
Some extension need update since the source is not working but I can't get an update since there's no new extension is showing up.

### Mihon version

0.16.5

### Android version

Android 11

### Device

Umidigi F3S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Alternatively, you can try to remove the repo in the settings and re-adding them. But as Smol-Ame said, please do remove the repo links.

**Comment by Abdulsalam-Selim** [comment]
I've done that already, I added and removed, I even got a new extension repo. It's still not showing anything

**Comment by Abdulsalam-Selim** [comment]
Also remove the repo links from where

**Comment by MajorTanya** [comment]
> Also remove the repo links from where

your issue text

**Comment by Abdulsalam-Selim** [comment]
Don

> > Also remove the repo links from where
> 
> your issue text
> 
> Thank you

You're welcome, is it a singular problem of just me or is it the repo I'm using that has problems
