### ISSUE TITLE
Reading while manga with oversized images became laggy after the 0.16.5 update

### ISSUE THREAD

**Issue by 2ch-anime** [mihonapp/mihon#729]
### Steps to reproduce

Open any comic with huge pages (Manhwa often have very long pages)

### Expected behavior

0.16.4 works well.
The mihon.app website states that this may be caused by 32-bit color:
![image](https://github.com/mihonapp/mihon/assets/19832807/0e82c5f0-5dc9-4d87-8abc-ca1c778bbdf0)

### Actual behavior

Starting from version 0.16.5, forced 32-bit mode is enabled and it is impossible to avoid performance problems

### Mihon version

0.16.5

### Android version

Android 11

### Device

Motorola G20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FooIbar** [comment]
#692 might solve this if you wanna try.

**Comment by AntsyLich** [comment]
Try out the preview build that'll be released today. Should improve performance.
