### ISSUE TITLE
Add Samsung S-Pen Support for Reader

### ISSUE THREAD

**Issue by SameAsUsually** [mihonapp/mihon#73]
### Describe your suggested feature

Basic features:
Pressing the S-Pen Button will open next page.
Pressing it twice will go to the previous page.

It was already integrated in Tachiyomi. I hope it's ok to say "like in app" since this is a fork of Tachiyomi :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Poopooracoocoo** [comment]
The S Pen gestures work perfectly fine for me. Make sure you've enabled the Air Actions for Mihon in the S Pen settings

**Comment by SameAsUsually** [comment]
Yes, I did not even knew that there were settings like that anymore. Sorry and thanks for the solution 👍
