### ISSUE TITLE
Open downloads in file explorer

### ISSUE THREAD

**Issue by ebarruel** [mihonapp/mihon#730]
### Describe your suggested feature

This feature would allow the user to go to where it is stored on their device after selecting a downloaded chapter (both from a title's chapter list or the updates tab) or using the three dots menu from the chapter list to see all downloads for a title.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Why?

**Comment by ebarruel** [comment]
Purely for convenience. I have some series that I download from extensions and then move to local. This feature would streamline that.

I also just like the idea of having easy access to where each download is specifically. But I get that this isn't a high priority feature or anything, just something I wanted to put out there.

**Comment by AntsyLich** [comment]
Pretty niche use case. Declined.
