### ISSUE TITLE
Entries with downloaded chapters disappear from the library 

### ISSUE THREAD

**Issue by spectre-xenon** [mihonapp/mihon#733]
### Steps to reproduce

- select an entry
- download any chapter 
- notice entry disappearing from library 

### Expected behavior

Entries shouldn't disappear 

### Actual behavior

Entries disappears after downloading any chapter

### Mihon version

1.16.5

### Android version

13

### Device

Samsung S20FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by spectre-xenon** [comment]
No downloads
![Screenshot_20240501_140854_Mihon](https://github.com/mihonapp/mihon/assets/62655598/ed3480b9-e3b4-4a96-ba3d-5d826a0a251c)
Downloaded 1 chapter
![Screenshot_20240501_140945_Mihon](https://github.com/mihonapp/mihon/assets/62655598/18130254-7b4d-4af0-8f81-a7c9289f9138)
After restsrting app it disappeared 
![Screenshot_20240501_140951_Mihon](https://github.com/mihonapp/mihon/assets/62655598/6412a7de-b274-4909-b3e2-84f973178201)

**Comment by MajorTanya** [comment]
1. Do not show source names
2. Settings > Advanced > Invalidate Download Index

**Comment by AntsyLich** [comment]
You have filters on. Make sure you're not filtering out downloaded series
