### ISSUE TITLE
Mihon slowing when reading 

### ISSUE THREAD

**Issue by Key-explanation** [mihonapp/mihon#736]
### Steps to reproduce

1. Select a chapter with a 100 or 200 pages
2. While reading the app slows down as to load the next chapter

### Expected behavior

There should be no lag while moving page to page

### Actual behavior

The app starts lagging when scrolling 

### Crash logs

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z)
Android version: 11 (SDK 30; build RP1A.200720.012 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 1901 (1901)
Device model: vivo 1901
WebView: Android System WebView 123.0.6312.118

--------- beginning of main
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: java.lang.IllegalStateException: Image decoder failed to initialize and get image size
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.Decoder.init(Unknown Source:88)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:8)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:1)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-02 07:55:51.049 16149 23501 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:923)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: java.lang.IllegalStateException: Image decoder failed to initialize and get image size
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.Decoder.init(Unknown Source:88)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:8)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:1)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-02 07:56:53.545 16149 24009 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:923)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: java.lang.IllegalStateException: Image decoder failed to initialize and get image size
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.Decoder.init(Unknown Source:88)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:8)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:1)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-02 07:56:53.546 16149 24007 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:923)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: java.lang.IllegalStateException: Image decoder failed to initialize and get image size
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.Decoder.init(Unknown Source:88)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:8)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SourceFile:1)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-02 08:10:34.205 16149 27866 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:923)
05-02 08:23:23.545 16149 29861 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/app.mihon/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
05-02 08:23:23.545 16149 29861 E chromium: [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
05-02 08:23:35.301 16149 29905 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
05-02 08:23:35.372 16149 29905 E IMGSRV  : :981: HWPerfSetSurfaceInfo: Cannot write HWPerf Surface Parameters. Max RTS IDs (8) reached.
05-02 08:23:38.546 16149 16149 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (29822) crash detected (code -1).

### Mihon version

0.16.5

### Android version

Android 11 

### Device

Vivo 1901

### Other details

It happens usually with specific extension like nhentai and has been occuring for a while now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Can you give the preview build a try? It should improve the performance. If not do comment.
