### ISSUE TITLE
please put a way to download all chapters, regardless if its already read or havent been read before.

### ISSUE THREAD

**Issue by afat123** [mihonapp/mihon#740]
### Describe your suggested feature

when downloading chapters, besides the options of next chapter, next 5, 10, 25, or unread chapters, there should be an "ALL" chapters download.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
there once was but it has been removed and it won't be back. mark the chapters as unread if you are gonna read them anyway

**Comment by afat123** [comment]
> there once was but it has been removed and it won't be back. mark the chapters as unread if you are gonna read them anyway

why it was removed?
marking chapter will take too damn long though......

**Comment by MajorTanya** [comment]
> > there once was but it has been removed and it won't be back. mark the chapters as unread if you are gonna read them anyway
> 
> why it was removed? marking chapter will take too damn long though......

To avoid slamming sources with loads of requests.

I encourage you to explore the alternative settings the app offers, from selections to Download Ahead and Delete After Read.

**Comment by afat123** [comment]
yeah, thats just take more steps. 

the previous app only has 3 steps. 
1. tap title.
2. tap download 
3. select "all" button

thats it. period. thats why i want it back.

**Comment by MajorTanya** [comment]
> yeah, thats just take more steps. 
> 
> the previous app only has 3 steps. 
> 1. tap title.
> 2. tap download 
> 3. select "all" button
> 
> thats it. period. thats why i want it back.
> 

"The previous app" was the one who removed it. It's not coming back. Either figure out an alternate way or better yet, don't bulk download literally everything. Look into Download Ahead in the settings.

Closing this now as its been clearly denied and the discussion isn't going anywhere either.
