### ISSUE TITLE
Failed to get extension list

### ISSUE THREAD

**Issue by limFakson** [mihonapp/mihon#743]
### Steps to reproduce

When you go to browse to download a new extension 

### Expected behavior

It suppose to display extension list i.e manhua sources 

### Actual behavior

Failed to get extension list

### Mihon version

0.16.5

### Android version

Android 8.0

### Device

Oppo A16k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
That screen really could use some sort of explanation along those lines instead of the standard kaomoji error message

**Comment by limFakson** [comment]
Well the first issue to fix now the download link is not working

**Comment by limFakson** [comment]
> Mihon doesn't have, associate, or provide any extensions

So how is it been used

**Comment by BrutuZ** [comment]
It doesn't provide any, never has. If you've been seeing a list there you must've provided your own at some point so just do it again ¯\_(ツ)_/¯

**Comment by limFakson** [comment]
Ok i will read that, also the download link is not working

**Comment by MajorTanya** [comment]
> Ok i will read that, also the download link is not working 

What download link are you talking about? The one in the releases page of the GitHub?

**Comment by limFakson** [comment]
In the release page and website

**Comment by limFakson** [comment]
Check the download link from mobile

**Comment by AntsyLich** [comment]
Please join our Discord GitHub is not the best option for troubleshooting issues
