### ISSUE TITLE
Enable browsing while download filter is on

### ISSUE THREAD

**Issue by IssakFrost** [mihonapp/mihon#747]
### Describe your suggested feature

Can't brows while the download filter is active.
Would recommend to enable browsing while the filter is active.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Yeah makes sense. It should be only applied to in library items.

**Comment by AntsyLich** [comment]
Actually it's already the case. Your issue is non-existent. Please join our Discord to get help troubleshooting the issue
