### ISSUE TITLE
Option to enable/disable app update checking

### ISSUE THREAD

**Issue by minhngoc25a** [mihonapp/mihon#750]
### Describe your suggested feature

The most recent patch update (version 0.16.5) broke some icons and the progress bar due to missed edge cases. Because of Mihon's open-source nature, releasing another stable version might take some time. Users who frequently use the app and prefer the old version might find the update screen, which appears occasionally upon launching the app, annoying. Moreover, it doesn't make sense for an app not to have an option to disable update checks, especially when it isn't tied to a fast-updating schedule like an Electron app such as Discord; therefore, it remains usable even if updated slowly.

For those who might suggest using the nightly build to avoid this issue, I can do that, but not without drawbacks:
- The nightly build has a separate signature, so I have to back up and restore again for it to work.
- When a Mihon extension updates for the first time, it displays a prompt asking for installation approval. From the second time onward, it no longer asks, as it "remembers" the choice for that app (older Android versions may lack this feature). However, since the nightly build has a different signature, it will ask again, which takes time since I have many extensions.
- There is no guarantee that a patch update won't break some of the interfaces (or features) again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. Why? Tachiyomi had multiple users that didn't update for ages.

**Comment by soredake** [comment]
> Why?

I for example update app from Obtainium, because Obtainium does update silently, while mihon is not, so I don't want to receive update popup.

**Comment by AntsyLich** [comment]
Why was the response to my No

**Comment by minhngoc25a** [comment]
Yes, I understand that users of the latest version of Tachiyomi haven't updated it for ages. That's because Tachiyomi was discontinued, and in the final version, the owner removed the update checking capability, so Tachiyomi can no longer check for updates.

For Mihon, of course, I can choose never to update it. However, the user experience is different. If a splash screen prompting me to update appears every now and then when I launch the app, I can click "Not now," but it would enhance the user experience if I could disable that splash screen or disable update checking entirely. When the Tachiyomi project was active, the older versions didn't have a splash screen like that.

**Comment by AntsyLich** [comment]
> that users of the latest version of Tachiyomi haven't updated it for ages
I'm talking about users that were years behind in update complainign in #support why their stuff don't work

> For Mihon, of course, I can choose never to update it.
You choice to not update  my choice to be annoying about it

> When the Tachiyomi project was active, the older versions didn't have a splash screen like that.
It was there for more than a year.... Were you not updating Tachiyomi either lol? No wonder you didn't see it

**Comment by minhngoc25a** [comment]
@AntsyLich Thank you for your insights! It seems there might have been some confusion about the Tachiyomi updates. I was referring to users who, despite using very outdated versions, were surprised by compatibility issues when seeking support. It's definitely a challenge keeping everyone on the same page regarding updates!

Regarding Mihon, I appreciate your perspective. While I prefer to avoid frequent updates, I understand the need to occasionally prompt users to ensure they have the best experience possible.

As for the splash screen in Tachiyomi, perhaps I missed it if it was implemented in the versions I didn't update. Thanks for pointing that out—I'll keep that in mind for future reference and discussions.

I also believe it would be beneficial to keep this issue open for a little longer so that other developers can weigh in on this feature request. It would be great to gather more opinions and ideas to determine whether implementing this feature could enhance the app for everyone.

**Comment by AntsyLich** [comment]
I'm pretty much the only dev overlooking the project atm and the other support staff in Discord also want users to be up to date. We don't give support if you're not up to date either. 

While yes it's inconvenient for you the bigger picture is we want users to be up to date as some major bugs are fixed on new versions (also the reasons we missed some UI bugs on last version since the focus was on some other bugs). 

Also as a side about 40% of the user base are not even on the last stable build (0.16.4)

**Comment by soredake** [comment]
> You choice to not update my choice to be annoying about it

What about my use-case where I do update mihon or tachiyomisy, but I do so using external software and don't want to update the app manually using update prompt?

**Comment by AntsyLich** [comment]
If you're up to date you won't see the prompt....

**Comment by soredake** [comment]
> If you're up to date you won't see the prompt....

I set updating to once a week, so I will see a prompt before obtainium will update it.

**Comment by soredake** [comment]
> well the app only checks every 3 days if I am not mistaken. If you check every 2 days it should stop happening

It that so? Thank you, didn't know about that, I thought that app will check every startup after reading [Tachiyomi v0.15.0](https://git.mihon.tech/tachiyomi/tachiyomi/releases/tag/v0.15.0) changelog.

**Comment by BrutuZ** [comment]
Could be poor wording on the changelog and it meant "while opened", as in no app update checks on the background 🤔
