### ISSUE TITLE
the extensions dont load

### ISSUE THREAD

**Issue by ruuno123** [mihonapp/mihon#76]
### Steps to reproduce

1. in tachi the extensions load, but not in mihon :/

### Expected behavior

 load 

### Actual behavior

didnt loaded

### Mihon version

0.16.0

### Android version

9

### Device

Lenovo TB-7305F

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheColorman** [comment]
Could you provide some more info? e.g. what do you mean by loading? Have you migrated data from Tachiyomi, do you see extension in the Sources and Extensions tabs, are you using an extension repo etc.

**Comment by ruuno123** [comment]
yes i have used back up from tachiyomi,and have repo from discord, i see the extensions and everything, the covers load too in my downloads, but if click to  "latest" or "popular" just load forever. if open in webwiev its working! in my tachi the extension working fine!

**Comment by ruuno123** [comment]
![ta](https://github.com/mihonapp/mihon/assets/66324621/d0f9f855-5729-4730-9baa-892433291147)

**Comment by TheColorman** [comment]
Should work the same as Tachi, try checking if your user agent is the same in Mihon

**Comment by ruuno123** [comment]
thanks a lot! its working now!!! load little slower that tachi but working :D :::... THANKS ...:::

**Comment by GameMaster007** [comment]
I am trying to make it so that will implement another extension system based on miru

**Comment by AntsyLich** [comment]
Mihon does not provide 3rd party extension support.

Also @GameMaster007 before you go around making something huge like a new extension system you should make an issue or discussion

**Comment by ruuno123** [comment]
okay after i said it was okay, i could only use 3 extension  that loaded... reinstalled the app and i know what was my problem i used a older version of tachi not 0.15+ and my something was wrong with my backup, so if u have the same isseue in back up  only use LIBRARY backup (u can select 3 option) or else make your app fail the load. now that i know this just 12h and i can start reading again bc that how much time i wasted 1st XD.
