### ISSUE TITLE
Add Repositories to backup

### ISSUE THREAD

**Issue by molitar** [mihonapp/mihon#762]
### Describe your suggested feature

I would like to see Repos added to the backup. It took me well over an hour to find the Repo that had the Kavita and Komga server extensions.  When I had to wipe and restore app due to extensions would not download to install I lost the repo and another 1 hour hunt for it was started again.

### Other details

Add our repositories to the backup and restore

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
> ~~Pretty sure it's included as part of app settings data (not explicitly listed)
> 
> Try restoring a backup next time (if the backup was made with said repo links set in the app)~~
> 
> Hmm, maybe not anymore with the changes to the repo system, disregard me

I just checked with a full backup without and one with the sensitive data in it, neither restored any repos.

**Comment by Animeboynz** [comment]
Probably been fixed at some point from then to now, but it now can be found in the backups and are also restores properly.
![image](https://github.com/mihonapp/mihon/assets/40583749/967edde1-b07b-4009-b25e-45b209aedfe3)

**Comment by AntsyLich** [comment]
Given that repos are stored in db now don't think they are in the backup

**Comment by Animeboynz** [comment]
Wait Lemme check which version I'm on real quick
