### ISSUE TITLE
 Add an internal browser  

### ISSUE THREAD

**Issue by OtakuArab** [mihonapp/mihon#770]
### Steps to reproduce

1- Access the source 2- View the web 3- The browser must be internal. Example of a T-browser Kotatsu 

### Expected behavior

The browser must be made internal to the application. This will solve the problem (Couldflare) I have sources, noting that most of them contain the Korean website, and verify that you are not a robot.

### Actual behavior

The site does not respond and the problem is not solved because the browser is external to the application (kotatsu) Browser It is easy to verify that I am a human without any problem 

### Mihon version

0.16.5

### Android version

Android 12

### Device

Samsung S10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
WebView is an internal browser
