### ISSUE TITLE
Implement lazy loading (aka precaching pages) in long strip mode

### ISSUE THREAD

**Issue by Nocifer** [mihonapp/mihon#779]
### Describe your suggested feature

I've noticed that in long strip mode, only a single page is ever loaded at any one time, with the next and even the previous pages only beginning to load when they should already be fully loaded and displayed on screen.

Because the pages are seemingly never cached and only (re)load at the last millisecond, this results in the visibly jarring effect of a black "bar" (actually it's the reader's black background) flashing at the bottom or the top of the page every time the user scrolls up or down; and the scrolling doesn't even need to be fast, although faster scrolling does make things worse.

I would suggest that Mihon preloads and caches at least 1, or even better 2 pages (to also cover the case of very small pages that may not even cover the whole screen, like e.g. in a yonkoma), both after _and_ before the currently visible page, so than any scrolling action will always result in a smooth visual flow.

A small video of what I'm talking about:

[screen-20240510-145642.webm](https://github.com/mihonapp/mihon/assets/6195422/68244ff0-ebbe-4d5e-8ba0-73d922e37c3e)

### Other details

1) While searching I found #556, which as far as I can tell describes the exact same problem. It was supposedly fixed with #563, but I honestly fail to understand how an issue of pages not loading fast enough when scrolling can be solved by completely and strictly disabling the decoding of pictures that aren't visible. I would think that the exact opposite (loading more pages before they become visible) would be the solution here.

2) This may not be as much of an issue with newer and/or more powerful devices (mine is a mid-to-high-tier device from 2020) that can load and decode images faster, and it may also be exacerbated by the recent forcing of 32-bit image mode (I've already had issues with it in the past on less powerful devices), but that's the beauty of lazy loading: it disassociates the visual experience from the underlying device's hardware specs.

3) I just now found #696, which is also about the same problem. So it seems that it's a more general issue with the web reader after all? The thing is though, I've never noticed anything like this happening before (at least in preloaded chapters).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FooIbar** [comment]
You misunderstood #563 which didn't disable decoding.
Instead, it fixed the issue that prefetched (recyclerview will do it automatically) images were not decoded.
And #696 is completely different.

**Comment by Nocifer** [comment]
Tested with latest beta and the issue is still present exactly as shown in the attached video. But with a second comic (which is also similarly problematic in 0.16.5) I think I noticed an improvement, so maybe it's been partially solved? Or maybe I'm doing something wrong; or maybe it's two separate issues after all. I'll investigate further (and less hastily) and report back.

Also, sorry if I misunderstood #563. I guess "will prevent the new image from being decoded until it's visible" refers to the original issue, and not to the actual fix like I assumed? My bad, sorry.

And yeah, I just watched the video attached to #696 and it's a completely different issue, so please disregard.

**Comment by Nocifer** [comment]
OK, so: the issue as described in the OP is not the issue reported in #556 after all. That issue is what I was experiencing with the second comic I mentioned, and as far as I can tell it's indeed been fixed in the latest beta (that's why I noticed an improvement with the second comic).

On the other hand, the issue as described in the OP is still present in the beta, but it's only present in some comics. Based on the fact that it only happens (or rather is observable) with comics of higher quality and hence of bigger file size, I think it's indeed a case of pages only loading at the last possible moment and not getting preloaded and cached in advance, which on lower end devices can result in the behavior shown in the attached video (because the pages can't load fast enough). Also, as I've mentioned, this happens on downloaded chapters as well, so it's probably not a case of bad internet.

**Comment by axu2** [comment]
Just adding my thoughts, I'm using a Hisense A9 eink Android smartphone. I am using volume button fixed length scrolling with no animation.

Using the current stable release, and when scrolling using long strip mode, it would look like this. TLDR, the 2nd half of the screen would load in after the first half, not great.

https://www.youtube.com/shorts/5S2sNlovLF0

With the current beta, only a small bar at the bottom of the screen loads in later. This is a MUCH better experience, and would be cool to get the small bar gone as well, but downloading the beta fixes most of the issue for me.

**Comment by axu2** [comment]
I can confirm the new beta fixes even the small bar for me too.

**Comment by axu2** [comment]
The new beta from yesterday completely fixes the issue for me. Here's a recording of the new beta first compared to stable. 

https://github.com/user-attachments/assets/03334b5d-f77b-4fb0-a214-b555be76af9c
