### ISSUE TITLE
Sources fail to update and alert you that package conflicts. 

### ISSUE THREAD

**Issue by Infernos1s** [mihonapp/mihon#78]
### Steps to reproduce

1. Download source update.
2. Click on downloaded file
3. Click update on pop-up.
4. Be notified of failure
![Screenshot_20240117_064215_Package installer](https://github.com/mihonapp/mihon/assets/156915683/1683721d-d029-4283-a247-748f57a73461)

### Expected behavior

Source should update.

### Actual behavior

Source does not update and gives failure.

### Mihon version

0 16 0

### Android version

Android 12

### Device

S21 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
This seems like an extension issue, which Mihon doesn't provide help with.

**Comment by TheColorman** [comment]
This usually happens if you've installed the same source from two different repos. Try uninstalling it first.

**Comment by Infernos1s** [comment]
I dont believe it stems from the extension since it works within tachiyomi. I believe it's something under mihon. I also think it'd be nice to update the extensions without needing to click the downloaded file to do so. Like how tachiyomi does originally.

**Comment by MajorTanya** [comment]
Mihon hasn't had any code changes from Tachiyomi that would cause this. It sounds similar to an issue from back when Tachiyomi was active and people would add 3rd party extensions to get extensions Tachiyomi wasn't offering (anymore). This issue stems from adding such 3rd party extensions.

**Comment by Infernos1s** [comment]
Uninstalling these extensions and reinstalling them was able to solve this for now. Thank you for responses.
