### ISSUE TITLE
App crashes when global-text-search

### ISSUE THREAD

**Issue by gothsome** [mihonapp/mihon#780]
### Steps to reproduce

I can searching in the pinned repo, but when i switch to all the App chrashes:

### Expected behavior

No crash

### Actual behavior

App chrashes when searching with Text in all repos.

### Crash logs

App version: 0.16.5-6674 (standard, dbcc4a7d7, 7, 2024-05-04T21:34:28Z)
Android version: 13 (SDK 33; build TKQ1.221013.002 test-keys)
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: nabu (nabu_eea)
Device model: 21051182G
WebView: Android System WebView 124.0.6367.123

java.lang.Throwable: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/MultipartBody$Builder; or its super classes (declaration of 'okhttp3.MultipartBody$Builder' appears in base.apk!classes3.dex)
	at eu.kanade.tachiyomi.extension.en.digitalcomicmuseum.DigitalComicMuseum.searchMangaRequest(DigitalComicMuseum.kt:72)
	at eu.kanade.tachiyomi.source.online.HttpSource$$ExternalSyntheticLambda5.call(Unknown Source:27)
	at rx.internal.operators.OnSubscribeDefer.call(SourceFile:2)
	at rx.internal.operators.OnSubscribeDefer.call(SourceFile:1)
	at rx.Observable.unsafeSubscribe(Unknown Source:9)
	at rx.internal.operators.OnSubscribeMap.call(SourceFile:4)
	at rx.internal.operators.OnSubscribeMap.call(SourceFile:1)
	at rx.internal.operators.OnSubscribeLift.call(SourceFile:4)
	at rx.internal.operators.OnSubscribeLift.call(SourceFile:1)
	at rx.Observable.subscribe(SourceFile:24)
	at tachiyomi.core.common.util.lang.RxCoroutineBridgeKt.awaitSingle(Unknown Source:27)
	at eu.kanade.tachiyomi.source.online.HttpSource.getSearchManga(Unknown Source:4)
	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.SearchScreenModel$search$3$1$1$page$1.invokeSuspend(Unknown Source:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(Screen#691dc89e-b45b-491a-b3a8-1477f83eb89e:eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchScreenModel:default), StandaloneCoroutine{Cancelling}@762db04, Dispatchers.IO]

--------- beginning of system
05-10 14:20:14.075 27703 27703 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
05-10 14:20:37.747 27711 27711 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is nabu
--------- beginning of main
05-10 15:39:08.884 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:09.047 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:09.087 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.119 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.160 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.178 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.193 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.201 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.209 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.221 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.229 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.235 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.244 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.253 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.261 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.269 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.276 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.287 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.293 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.303 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.310 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.320 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.328 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.335 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.345 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.354 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.361 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.369 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.379 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.387 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:09.393 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.
05-10 15:39:11.577 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:11.668 27711 27711 E FileUtils: err write to mi_exception_log
05-10 15:39:11.692 27711 21351 E FrameEvents: updateAcquireFence: Did not find frame.

### Mihon version

Beta R6647

### Android version

13

### Device

Mi Pad 5

### Other details

I have removed all repos i dont use and cleared the App Cache.
I cant add the full log it is too big and cant add a File.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
That's an issue with that "DigitalComicMuseum" extension you have installed. Go ask your repo maintainer for help with this issue as Mihon itself has nothing to do with extension development.

Closing as not related to Mihon.

**Comment by gothsome** [comment]
Tank you @MajorTanya !
Good that i didnt have anything  fromm this extension and could Just delete it.

Thank you very much!!

**Comment by MajorTanya** [comment]
> Tank you @MajorTanya !
> Good that i didnt have anything  fromm this extension and could Just delete it.
> 
> Thank you very much!!

Would still be nice if you could report the issue to the repo maintainers so other people won't have the crash too.

**Comment by gothsome** [comment]
Yeah i did, didnt Had in mind that  the "default"repo was not integrated anymore since the fork.
