### ISSUE TITLE
Add filter by extension repository

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#786]
### Describe your suggested feature

Filtering extensions by repository...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
I see no point
