### ISSUE TITLE
A new way to read on the small screen

### ISSUE THREAD

**Issue by bearcloney** [mihonapp/mihon#787]
### Describe your suggested feature

I hope to add a long press to zoom in function. While pressing and holding, move your finger slightly to shift the view. Release your hand to return to normal display, with customized area magnification and movement speed. 

### Other details

This function is very friendly for one-handed use, because the text of some comics is too small, and most users use mobile phones, so I think it is very necessary. You can refer to NeeView (PC) or 可达漫画 (ios). They have similar functions. I hope the author can adopt it

https://github.com/mihonapp/mihon/assets/51289114/e0224e55-dd62-4191-9a02-7c0246cc119b

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Double tap to zoom where you want, navigate around, double tap again to zoom out

https://github.com/mihonapp/mihon/assets/7104931/9297ba90-7c14-4bc1-bb5e-7a627f81ce16

**Comment by bearcloney** [comment]
> 您还可以双击以缩放到所需位置

 The main reason for this approach is that double-clicking to zoom is too inefficient.
 If you hold your phone in your right hand and need to zoom in on the text in the upper left corner, either it's too far away for your finger to point to, or you can double-tap to zoom in and slide to double-tap to zoom out, making the steps too cumbersome!
 
The problem of being occupied can be divided into the upper and lower ab areas of the screen.
the upper half of the a maintain the original function, the lower half of the b changed to Tap and hold to zoom in.

**Comment by bearcloney** [comment]
> Tap and hold already has the page context menu assigned (Save, Share, Set as Cover). You can also already Double tap to zoom where you want, navigate around, double tap again to zoom out
> 
>  Screen_Recording_20240512_151637_TachiyomiSY.mp4

 The main reason for this approach is that double-clicking to zoom is too inefficient.
 If you hold your phone in your right hand and need to zoom in on the text in the upper left corner, either it's too far away for your finger to point to, or you can double-tap to zoom in and slide to double-tap to zoom out, making the steps too cumbersome!
 
The problem of being occupied can be divided into the upper and lower ab areas of the screen.
the upper half of the a maintain the original function, the lower half of the b changed to Tap and hold to zoom in.

**Comment by AntsyLich** [comment]
install a dedicated magnification app to use alongside Mihon
