### ISSUE TITLE
Mangadex won't load chapters for certain manhwa

### ISSUE THREAD

**Issue by shogunreaper** [mihonapp/mihon#789]
### Steps to reproduce

So it might be others too but i tried a bunch of random mangas and they all worked fine.

But for The beginning after the end [this one](https://mangadex.org/title/4ada20eb-085a-491a-8c49-477ab42014d7/the-beginning-after-the-end) it won't load any chapters, it just give the No chapters found pop up.

i also tried it on both tachiyomi and tachij2k also and both had the same issue with it.

I know it has chapters because you can open it in the browser and see them.

### Expected behavior

it should load the chapters

### Actual behavior

it doesn't load the chapters.

### Mihon version

0.16.5

### Android version

Android 11

### Device

lenovo tab p11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Mihon doesn't provide any extensions itself, you will have to take this to whoever is maintaining that extension (your repo provider).
