### ISSUE TITLE
Settings > Library: "Mark new duplicate chapter as read" enabled by default

### ISSUE THREAD

**Issue by NameLessGO** [mihonapp/mihon#790]
### Describe your suggested feature

It can be irksome to manually delete duplicated old chapters. It would be advantageous for new users to have this option toggled by default, as it would prevent false updates of "new chapters."

When the user gets notified about new chapters, they want the newest ones from the manga, not old ones from scans groups or official releases that usually take longer to come out.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
