### ISSUE TITLE
Per Category settings for Filter

### ISSUE THREAD

**Issue by SatoX69** [mihonapp/mihon#792]
### Describe your suggested feature

Can the devs consider adding this option to the library settings, similar to the option shown in the screenshot ![Screenshot_2024-05-15-21-17-17-230_app mihon-edit](https://github.com/mihonapp/mihon/assets/127420166/a24307ba-432f-4afe-8ff0-d7e94abe191e)? It would work like this: if I toggle "per Category settings for Filter" on and have 2 categories, "Downloaded" and "Finished," with other settings set to default, then when I update the library, I want the "Downloaded" tab to show only the entries with downloaded chapters. When I switch to the "Finished" tab, I want it to display all entries without having to adjust the filters
![Screenshot_2024-05-15-21-25-45-768_app mihon-edit](https://github.com/mihonapp/mihon/assets/127420166/6bfa3dda-54d5-4817-97ab-8c9012af99b5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
previously it was per category sort and display settings. and it was messy. display settings was removed and only sort has been kept. filter is much more complex than display setting. as such no.

**Comment by SatoX69** [comment]
Oh, alright.
