### ISSUE TITLE
I would like to see the ideas in the update column adopted

### ISSUE THREAD

**Issue by 008s** [mihonapp/mihon#799]
### Describe your suggested feature

After the update, can you add an option to delete the comic in the update bar, for example, you can swipe left and right to add bookmarks, read, like in the table of contents. If you press and hold it, you will have an additional delete option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Are you talking about the Updates screen? What's keeping you from navigating to the title by clicking the cover, then (multi)selecting the chapter(s) you want to delete there?

**Comment by 008s** [comment]
> Are you talking about the Updates screen? What's keeping you from navigating to the title by clicking the cover, then (multi)selecting the chapter(s) you want to delete there?

![F259923BAD66790CC4752D5EB8BEC41A](https://github.com/mihonapp/mihon/assets/121275187/0cfd9d6f-444c-4b4e-9780-b93661fcbd21)

**Comment by MajorTanya** [comment]
That exists though? ![IMG_20240517_132943.jpg](https://github.com/mihonapp/mihon/assets/39014446/2cf122e8-5c80-4256-9f20-dc5450a76390)

Or are you looking for "Mark as Read"? Because that's the symbol with two checkmarks in it in your image

**Comment by 008s** [comment]
Why didn't I delete it?

https://github.com/mihonapp/mihon/assets/121275187/17174f00-4b73-4957-9a18-ee760ac105a6

**Comment by 008s** [comment]
I'm using version 0.16.5

**Comment by MajorTanya** [comment]
> Why didn't I delete it?
> 
> https://github.com/mihonapp/mihon/assets/121275187/17174f00-4b73-4957-9a18-ee760ac105a6
> 
> 

What I showed you is in the title view. You cannot remove chapter entries from the updates screen. They turn grey when you've read them, that's it.

**Comment by 008s** [comment]
Can't you consider adding a delete button in this place? If it's only grayed out, you still have to choose when many comics are updated. I think manual deletion will make the new and updated comic chapters more eye-catching.

**Comment by 008s** [comment]
![IMG_20240517_201042.jpg](https://github.com/mihonapp/mihon/assets/121275187/f1c022c2-84c5-407c-9f85-67f9307a8c87)
