### ISSUE TITLE
update extension

### ISSUE THREAD

**Issue by Jhondeivis12** [mihonapp/mihon#806]
### Steps to reproduce

The "ikigai mangas" extension has changed its web address to: nocbro.xyz

### Expected behavior

all the mangas in the extension should load my pages

### Actual behavior

But now it tells me that there are no pages found in any manga of the extension

### Mihon version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) Android version: 13 (SDK 33; build LH7n-H894JKLM-T-GL-240313V1715) Device brand: TECNO Device manufacturer: TECNO Device name: TECNO-LH7n (LH7n-GL) Device model: TECNO LH7n WebView: Android System WebView 124.0.6367.123

### Android version

Android 13

### Device

Tecno LH7n

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by PennyJim** [comment]
Mihon doesn't have, associate, or provide any extensions, go ask whoever maintains your extensions instead
