### ISSUE TITLE
add invalidate download index to drop down menu

### ISSUE THREAD

**Issue by Turhvjbufv** [mihonapp/mihon#811]
### Describe your suggested feature

There's the three dots in the top right when on library tab, please add the invalidate download index option there, much easier to access than needing to go into settings and such

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. If you need to invalidate index that often we are better off fixing the issue.
