### ISSUE TITLE
Sync Manga Progress across different devices

### ISSUE THREAD

**Issue by pavonismc** [mihonapp/mihon#812]
### Describe your suggested feature

I simply wish I could read on one device and have my progress update across Multiple devices

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
>   * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.

Lies! ò_ó

**Comment by deadpyxel** [comment]
I also would like to see this, I alternate between reading on my phone and tablet and needing to find what I have already read or not. If there's already some implementation or issue open on this, please link it here @BrutuZ so we can keep an eye out.

I just found this #40 and I am not sure what was made of it.

**Comment by deadpyxel** [comment]
I did try a setup using syncthing and the autobackups feature it just feels "clunky", but I'll give that a try. I don't understand much of app development, but I may try to see if there's a good way to use some of the sync features from a service like google drive or the google play stuff.

thanks for the clarification.

**Comment by AntsyLich** [comment]
Closing in favor of #1432
