### ISSUE TITLE
Bugged "read" color for Date/Scanlator in chapter list

### ISSUE THREAD

**Issue by Smol-Ame** [mihonapp/mihon#822]
### Steps to reproduce

1) Open a title to view chapter list
2) Read chapters might appear correctly colored
3) After scrolling far enough, "read" chapters are incorrectly colored (only date & scanlator portion)
4) Doubling back makes any "correctly" colored read chapters incorrectly colored

https://github.com/mihonapp/mihon/assets/155411819/1ff3a3bd-f9ff-40f4-91a3-97831eb7f821

### Expected behavior

"Read" chapter colors should be dimmer/stay dimmed

### Actual behavior

"Read" chapters colors don't stay dimmed

### Mihon version

Mihon Preview r6697

### Android version

Android 14

### Device

Samsung S22 Ultra

### Other details

Noted by about three people in Discord support channel so far

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Reproduced on my side as well. Fwiw, here is [a similar bug](https://git.mihon.tech/tachiyomi/tachiyomi/issues/9043) from the past which was fixed by e458de5
