### ISSUE TITLE
Unable to view downloaded chapters offline (can't open InputStream)

### ISSUE THREAD

**Issue by prismacolorgold** [mihonapp/mihon#828]
### Steps to reproduce

location is in android's download sub folder (I have also tried other folders outside of the download)
download chapter from MangaSee
once downloaded, i got an error: can't open InputStream
I cannot view the download chapter offline (both cbz and png).

### Expected behavior

i should be able to view the downloaded chapters offline

### Actual behavior

I browse into the download folder, both the folders and .cbz has a _tmp at the end. I tried manually remove the _tmp but it didn't work

when i open the chapter, i get this error: Unable to resolve hose "mangasee123.com": No address associated with hostname

### Mihon version

0.16.5

### Android version

Andorid 13

### Device

Samsung Tab S8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
`_tmp` suffix means it's not fully downloaded, the app won't read from those files.
If you manually rename them, make sure to at least invalidate the download index.
