### ISSUE TITLE
Chapter images won't load if it's too long on long strip mode

### ISSUE THREAD

**Issue by null2264** [mihonapp/mihon#830]
### Steps to reproduce

If you try to read a chapter with images longer than GL texture size limit (4096x4096 on my device) on long strip mode it'll complains that "Bitmap too large to be uploaded into a texture". Seems to be caused by GH-692.

### Expected behavior

Load the images.

### Actual behavior

Images doesn't want to load with `OpenGLRenderer: Bitmap too large to be uploaded into a texture (690x31200, max=4096x4096)` spam on logcat.

### Mihon version

Preview r6674

### Android version

Android 8.1

### Device

Vivo 1820

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
`Split Tall Images` setting?

**Comment by null2264** [comment]
Just regular long strip.

**Comment by Palloxin** [comment]
I hope it gets fixed, cant read manhwas decently

**Comment by null2264** [comment]
Fixed by commit https://github.com/mihonapp/mihon/commit/c5655e8803bc32d0931657f0b7bc6afeab70feaf.
