### ISSUE TITLE
Add feature (Show last chapter when searching manga...)

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#835]
### Describe your suggested feature

When you search sources for manga it will be easy to find source with biggest number of chapters for that manga

### Other details

You don't need to load source to check last chapter number you can see it from search...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Character95** [comment]
![Screenshot_2024-05-27-17-46-45-092_app mihon debug](https://github.com/mihonapp/mihon/assets/25694091/b37b3077-e0e9-472e-a389-fc6017d6d695)
![IMG_20240527_174032_1](https://github.com/mihonapp/mihon/assets/25694091/8a3e78d6-305c-48cf-86d1-39c9d861a814)
exsample for adding feature

**Comment by BrutuZ** [comment]
> You don't need to load source to check last chapter number you can see it from search...
Except you do. The app still have to make at least another call - often more, depending on pagination - for each entry to get the chapter list.

**Comment by AntsyLich** [comment]
So one extra call for every entry (that you may or may not read) at once....... No
