### ISSUE TITLE
Cannot save anything, including backups and logs ("java.lang.ArrayIndexOutOfBoundsException")

### ISSUE THREAD

**Issue by cyagon** [mihonapp/mihon#838]
### Steps to reproduce

1. Choose any location via file picker
2. Try to create a backup 
3. The error "java.lang.ArrayIndexOutOfBoundsException" comes

### Expected behavior

It should save backups normally

### Actual behavior

The error "java.lang.ArrayIndexOutOfBoundsException" comes and it doesnt save anything

### Crash logs

[log_2024_05_27_08_15_26.log](https://github.com/mihonapp/mihon/files/15472233/log_2024_05_27_08_15_26.log)

### Mihon version

0.16.5

### Android version

Android 14 (LineageOS)

### Device

Xiaomi Poco X3 NFC

### Other details

After upgrading to Android 14, Mihon (and other Tachiyomi forks) seem to be unable to save anything. During the initial setup, the usual 3 folders are created, but when you try to save anything afterwards, this specific error comes up and it refuses to save anything.
Since even logs could not be saved, the attached log is from a logcat.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Do you actually have entries in your library?

**Comment by cyagon** [comment]
I installed with both and without, i reinstalled multiple times, and like i said, not even logs got saved.

**Comment by Seishirou101** [comment]
java.lang.ArrayIndexOutOfBoundsException is usually when you have no entries in your library i believe and logs aren't saved to those folders but the cache of the app, since backups can't be made to that folder you chose you will have to check permissions if you do have entries in your library

**Comment by cyagon** [comment]
I now reinstalled Mihon and with Library entries now it seems to save backups now. But it still cannot save logs (?)

**Comment by Seishirou101** [comment]
as i said, logs are saved in the cache which generally you can't access with a file manager, i believe currently when you share logs it puts it in a share dialog. closing as the issue specified is fixed, you can ask on discord for more help for logs
