### ISSUE TITLE
MihonApp icon in .svg

### ISSUE THREAD

**Issue by NameLessGO** [mihonapp/mihon#839]
### Describe your suggested feature

Would like to replace current .png icon with .svg in crowdsourced websites such as alternativeto
https://alternativeto.net/software/mihon/about/

Currently, only .png is provided https://github.com/mihonapp/mihon/tree/main/.idea

And the website icon .svg is different from app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Well I'm not too sure if a full logo SVG exists but if you really want it, you can recreate it from the SVG for the `mi` character.
https://github.com/mihonapp/mihon/blob/main/app/src/main/res/drawable/ic_mihon.xml

```
<svg width="148" height="141">
  <path d="M20.3,27.59L19.22,2.63C22.47,3.25 26.35,3.41 35.18,3.41C45.87,3.41 59.97,2.79 67.26,1.86C70.36,1.55 71.6,1.08 73.61,0L90.35,14.26C88.8,16.43 88.34,17.36 86.63,21.7C85.24,25.11 78.88,44.79 76.4,53.16C87.87,55.48 94.22,57.19 102.9,60.75C103.99,53.16 104.14,49.13 104.14,35.33C104.14,31.77 103.99,29.75 103.52,26.5L130.49,27.43C129.71,31.15 129.56,32.7 129.4,38.74C128.78,53.31 128.16,60.28 126.61,70.82C137.31,76.25 137.31,76.25 142.73,79.19C145.52,80.74 146.14,81.05 148,81.67L139.01,110.65C134.67,106.78 128.63,102.59 119.79,97.63C112.05,116.07 99.18,129.56 79.66,140.25C73.15,131.57 68.19,126.3 60.28,120.11C71.75,114.68 77.02,111.27 83.07,105.54C88.96,99.8 92.83,94.22 96.55,85.86C86.63,81.36 80.28,79.35 69.27,77.02C62.92,95.93 57.81,108.02 53.31,115.3C47.27,125.06 39.05,130.18 29.6,130.18C22.32,130.18 14.88,126.92 9.45,121.35C3.25,114.99 0,106.16 0,95.93C0,80.74 7.28,67.57 19.99,59.35C28.21,54.09 36.88,51.76 50.68,50.99C53.47,41.84 55.79,33.94 57.96,25.11C51.14,25.73 42.62,26.19 32.23,26.66C26.66,26.81 24.8,26.97 20.3,27.59ZM43.86,74.7C36.57,75.94 32.23,78.26 28.36,83.22C25.42,86.63 24.02,90.66 24.02,95C24.02,99.8 26.35,103.37 29.29,103.37C32.85,103.37 36.88,95.31 43.86,74.7Z" stroke="black" fill="black"/>
</svg>

```

**Comment by krisu5** [comment]
This is IMO 99% accurate vector recreation of the icon. Thanks for Animeboynz pointing out logo vector location.

There's few imperfections because (in my experience) it's almost impossible to recreate 100% accurate vector from bitmap image. So that's why I say it's 99% accurate.

I used Mihon's [X / Twitter](https://x.com/mihonapp/photo) profile pic as reference point, because it had biggest official bitmap image.

[SVG - Mihon icon with whitespace (rectangle)](https://github.com/mihonapp/mihon/assets/3540275/83218222-a071-48a8-816e-45d651cd169f)
![SVG - Mihon icon with whitespace (ellipse)](https://github.com/mihonapp/mihon/assets/3540275/dbc2ac3d-97ff-43cf-bbd7-48ba3c3c00ca)
![SVG - Mihon icon without whitespace](https://github.com/mihonapp/mihon/assets/3540275/bd583639-627a-4ccc-95dd-bc7189303b8a)
[AI - Mihon icon recreation project file with references](https://github.com/user-attachments/files/16115811/Mihon.icon.recreation.zip)

**Comment by MajorTanya** [comment]
Or you know, check what the SVG paths used by the app icon are in the resources folders?

**Comment by krisu5** [comment]
> What a roundabout way to do it, find the font and it will be 100% and way easier

That's not good idea. Outlined vector is faster and better way. Also it doesn't change the fact icon base is vector.

> Or you know, check what the SVG paths used by the app icon are in the resources folders?

Okay, but where.

**Comment by MajorTanya** [comment]
> > What a roundabout way to do it, find the font and it will be 100% and way easier
> 
> That's not good idea. Outlined vector is faster and better way. Also it doesn't change the fact icon base is vector, not a font for sure.
> 
> > Or you know, check what the SVG paths used by the app icon are in the resources folders?
> 
> Okay, but where exactly.
> 
> ---
> 
> I think you guys didn't understand what I did. I didn't recreate **the logo**, I did used [the SVG path that Animeboynz pointed out.](https://github.com/mihonapp/mihon/issues/839#issuecomment-2207183223) I just recreated the icon base (meaning the circle around the logo) and added colors. It's recreation of the Android icon.

https://github.com/mihonapp/mihon/blob/main/app%2Fsrc%2Fmain%2Fres%2Fdrawable%2Fic_launcher_foreground.xml

I'm on mobile right now so I can't see a preview or something in Android Studio, but I'm 95% sure this is the exact file Mihon uses for its app icon and all the other places as well.

**Comment by AntsyLich** [comment]
Here: 
![mihon-app-icon](https://github.com/mihonapp/mihon/assets/59261191/d1e3e60c-5b6b-4596-8522-fbc210c1a386)
