### ISSUE TITLE
Captions in the navigation bar

### ISSUE THREAD

**Issue by Yutasj** [mihonapp/mihon#840]
### Describe your suggested feature

In one application I saw a nice feature, namely the ability to change whether the signature will be shown in the navigation bar or not or only when selected.   Although this is not a significant cosmetic change, I think the appearance of this in Mihon will be very cool
![Screenshot_20240528-233126_ShikiWatch~01](https://github.com/mihonapp/mihon/assets/164043688/6a4e695d-6c7d-437e-bd3a-9e17b62d8573)
![Screenshot_20240528-232952_ShikiWatch~01](https://github.com/mihonapp/mihon/assets/164043688/bbfd3b84-f727-403f-ad03-1ac027f248da)
![Screenshot_20240528-232939_ShikiWatch~01~01~01](https://github.com/mihonapp/mihon/assets/164043688/418b432c-f87c-40d4-9569-90db21031ac8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No

**Comment by Yutasj** [comment]
@AntsyLich Why?

**Comment by AntsyLich** [comment]
More choice = more headache
