### ISSUE TITLE
Problems Reading on Long Strip

### ISSUE THREAD

**Issue by DollynDeveloper** [mihonapp/mihon#841]
### Steps to reproduce

This is a problem with the long strip reading mode. The same apparently occurs with high-scale pages as cited in this previous [issue](https://github.com/mihonapp/mihon/issues/830).

When using the long pages dialog settings, the problem is resolved, however, only if the chapter is downloaded. If you're anything like me, you'll face problems once you read the chapters online.
![Screenshot_20240528-213553_Mihon](https://github.com/mihonapp/mihon/assets/72720834/05f713e8-4b4f-4233-a648-635f73b4329e)

### Expected behavior

That the pages were loaded normally at the start of the reader, loaded them in a long strip. 

### Actual behavior

Pages become "empty" because their content has not been loaded.

### Crash logs

No crash logs. 

### Mihon version

0.16.5-6698 

### Android version

Android 10

### Device

Samsung J8

### Other details

Other details for review. 

App version: 0.16.5-6698 (standard, 0cb1794a4, 7, 2024-05-25T21:16:11Z)
Android version: 10 (SDK 29; build QP1A.190711.020.J810MUBU3CUH1)
Device brand: samsung
Device manufacturer: samsung
Device name: j8y18lte (j8y18lteub)
Device model: SM-J810M
WebView: Android System WebView 125.0.6422.53

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Does this issue still occur on the latest preview?

**Comment by doudoud82** [comment]
@AntsyLich it seems that with this new build, it gets fixed when enabling SSIV for decoding long-strip images device is a Samsung S7 android 8. r7043
I think the discussion has moved to this newer thread after it broke again https://github.com/mihonapp/mihon/issues/1558
