### ISSUE TITLE
Can't view chapters in incremented folder

### ISSUE THREAD

**Issue by AkaiZeroX** [mihonapp/mihon#850]
### Steps to reproduce

I download these "[Poster] Mei" chapters with individual images and the folder it creates in download folder are incremented folder, and when I view it, all the chapter that have the same name only show the first chapter "[Poster] Mei" that I download (doesn't have increment number).
![image_2024-05-31_003441579](https://github.com/mihonapp/mihon/assets/141337490/8b6e9a39-1423-416e-a443-1fc5a8dcde5d)
![image_2024-05-31_003510289](https://github.com/mihonapp/mihon/assets/141337490/421a1416-1b36-4643-a3b4-85071df9e29f)

### Expected behavior

All chapters should show individual image, even when the chapter name is the same.

### Actual behavior

If I download chapters with the same name, then these chapters view the same image from the folder that doesn't have an increment number, even when the images from both chapters are different.

### Mihon version

Stable 0.16.5

### Android version

Android 11

### Device

Samsung Galaxy A80

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you most likely will have to contact the repo you got that extension from, as there is nothing the app can do if the provided information doesn't have numbering
