### ISSUE TITLE
Adding library for bypass devtool check 

### ISSUE THREAD

**Issue by Karutovn** [mihonapp/mihon#852]
### Describe your suggested feature

Some manga website have devtool check and it's have some Annoying for user who using mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Ok and? Mihon doesn't provide any "website" so it's not our problem. And I personally haven't faced such issues nor do I know anyone (other than you) that has so it's not a Mihon issue either. Leave a comment if you can reproduce it on normal Mihon
