### ISSUE TITLE
Biometrics app crash bug

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#854]
### Steps to reproduce

When you have biometrics on your phone and add biometrics in app then change biometrics on your phone and you dont change (turn off and on again in app after you change biometrics on your phone) app start to crash on startup

### Expected behavior

Without startup bugs

### Actual behavior

App stops working on startup

### Mihon version

0.16.5

### Android version

Android 11

### Device

Redmi note 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
you will need to provide crash logs for any kind of help

**Comment by Character95** [comment]
crash log

App version: 0.16.5-6710 (standard, 8632ba85e, 7, 2024-06-01T21:18:31Z)
Android version: 11 (SDK 30; build RP1A.200720.011)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia (begonia_eea)
Device model: Redmi Note 8 Pro
WebView: Android System WebView 126.0.6478.26

java.lang.Throwable: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f8b97c7 u0 app.mihon.debug/androidx.work.impl.foreground.SystemForegroundService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by Character95** [comment]
![Screenshot_2024-06-05-18-47-46-943_app.mihon.debug.jpg](https://github.com/mihonapp/mihon/assets/25694091/8f3a50fd-1369-4f76-9bd0-599a14039a7a)
