### ISSUE TITLE
Option to display Time & Remaining Battery

### ISSUE THREAD

**Issue by dvdmtw98** [mihonapp/mihon#861]
### Describe your suggested feature

An option that would allow displaying the time and remaining battery with the page count at the bottom of the screen.  
This feature would allow users to check the time and remaining battery without having to swipe from the top of the screen to show the notification bar.

### Other details

The requested feature is a functionality that is present in e-book reader apps like Moon+ Reader.

<img src="https://github.com/mihonapp/mihon/assets/31100937/55fc90cf-659e-4ff1-bde3-0cd47b6b75cc" width="560" />

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
inb4 Antsy's standard "Don't be lazy" response because it only takes a single tap on the screen or disabling the FullScreen Mode setting to see that information xD
