### ISSUE TITLE
Feature Request - Google Sheets Tracking

### ISSUE THREAD

**Issue by U53R3RR0R** [mihonapp/mihon#862]
### Describe your suggested feature

I would like to be able to connect mihon to Google sheets and automatically update a spreadsheet when I read a chapter.

It doesn't need to be fancy. A simple list of read chapters would work fine.

Is there any support for this idea?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
why not just use a tracker?

**Comment by U53R3RR0R** [comment]
Because I use mihon for more than just manga and I don't have a server that
I can install Komga on.

**Comment by AntsyLich** [comment]
use anilist or something
