### ISSUE TITLE
Different edges of the form showing the number of chapters

### ISSUE THREAD

**Issue by Yutasj** [mihonapp/mihon#863]
### Steps to reproduce

Some of the titles have rounded and straight corners in the shapes indicating the number of downloaded and unread chapters (I spent an hour trying to figure out how to cause or manifest this problem and still can't figure it out, so I apologize for that and would be glad if someone could help me find the cause)
![Screenshot_20240603-203611_Mihon~01~01](https://github.com/mihonapp/mihon/assets/164043688/fe1d49d8-b419-4650-ae89-e0f900eff01f)
![Screenshot_20240603-203634_Mihon~01](https://github.com/mihonapp/mihon/assets/164043688/c8315a35-3ada-412e-a108-57530e314870)

### Expected behavior

All shapes must have the same angles

### Actual behavior

Some shapes have different angles than others

### Mihon version

0.16.5-6710

### Android version

Android 14

### Device

OnePlus 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Does this still happen for you on the latest Mihon Preview version? I just tried to trigger this issue again & wasn't able to anymore.

**Comment by Yutasj** [comment]
@Smol-Ame Yes, this problem has disappeared for me too
