### ISSUE TITLE
Thumbnails for chapters

### ISSUE THREAD

**Issue by YanagiSen** [mihonapp/mihon#872]
### Describe your suggested feature

When there are a lot of chapters（ e.g. 240 chapters in Beelzebub by Ryuhei Tamura）,it would be a pain to find a specific chapter only by the chapter number. 
A thumbnail for chapters would be a help for finding.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
That's 240 http calls for a single series. No
