### ISSUE TITLE
Crash while exiting from reader

### ISSUE THREAD

**Issue by Cultsonfire** [mihonapp/mihon#882]
### Steps to reproduce

**_Firstly it was a very random crash and occured to me the first time, it may or may not be reproducible for other devices or users_**
Steps:-
• Reader is open for a while and you need to enter app for some stuff so you switch to another app and then go back to reader, hmm read enough now you need to exit the app so you go one step back by clicking ⬅️ button (you may use swipe gesture or navigation buttons of the phone itself) and then the app crashes.

### Expected behavior

The expected behavior would normally be you end up on the information/title/chapter screen

### Actual behavior

When I exited just from the reader interface, the app crashed just be able to show that the app crashed and these are the logs.

### Crash logs

[mihon_crash_logs.txt](https://github.com/user-attachments/files/15764553/mihon_crash_logs.txt)

### Mihon version

Beta r6723 (6a80305d6)

### Android version

Android 13

### Device

Samsung Galaxy S20 FE SM-G781N

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
it's likely that an image somehow got corrupted or something. closing as it's an obscure error and unlikely to happen again.
