### ISSUE TITLE
Automated Trust: Simplifying Repository and Source Trust Settings

### ISSUE THREAD

**Issue by MarshMeadow** [mihonapp/mihon#884]
### Describe your suggested feature

Enable automatic trust settings for repositories or book/manga sources, allowing them to be trusted upon download. Or Could Additionally, include a 'Trust All' button at the top or within the menu options to simplify the process and alleviate any inconvenience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
something already was implementated #320 #570
