### ISSUE TITLE
Group 

### ISSUE THREAD

**Issue by Delmarcop52** [mihonapp/mihon#886]
### Describe your suggested feature

Source, categories,tag, status, ungrouping for the library to the home screen on the app just like on anime forks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Couldn't be arsed to elaborate the request. Just assumed someone will read your mind?

**Comment by AntsyLich** [comment]
A big fat no

> Couldn't be arsed to elaborate the request. Just assumed someone will read your mind?

Learn some mind reading smh.
