### ISSUE TITLE
Non-Manga Tracking System

### ISSUE THREAD

**Issue by Jangle-Klown** [mihonapp/mihon#887]
### Describe your suggested feature

While tracking manga works great, it doesn't have anything for Non-Manga Tracking (i.e. Marvel, DC, Image, etc). While this isn't detrimental, with the ability to add Non-Manga sources, it would be nice to be able to track my other type of comics I read as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
If you know of a tracking service for such content with a free public API then toss it in the description, otherwise there's nothing to go on here.

**Comment by Jangle-Klown** [comment]
I was requesting hoping that someone knew of something I may not have. I have been able to find a couple of APIs with metadata for comics, but I'm pretty sure that'd only be one part of what is needed for tracking. I personally use Comic Geeks app to track the comics I read, but I couldn't seem to find an API to connect to it. The closest thing I could find was [here on GitHub](https://github.com/alistairjcbrown/leagueofcomicgeeks) but I'm not sure that would be what is needed. 

(Disclaimer: I'm not a Developer. Just a Technical Business Analyst with development ideas)

**Comment by AntsyLich** [comment]
Make a new request when you find an comic tracking site with api (plus point if you ask in our discord first)
