### ISSUE TITLE
Add ability to view next expected update date. 

### ISSUE THREAD

**Issue by THElegend5** [mihonapp/mihon#89]
### Describe your suggested feature

Now that update manga in expected period is merged it seems like tachiyomi knows when a library might have an update available but shows it in the form of update period.

What I am suggesting is being able to view this data in a more relative form and being able to view in some way the dates when an entry update may be available instead of just a period and not knowing how far along in that update period you are.

### Other details

References: https://github.com/tachiyomiorg/tachiyomi/issues/9793

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
You can see this information when tapping the hourglass. It shows when (in days) Mihon next expects the new chapter(s) as well as the current interval (in days) it has calculated.

Or were you referring to something other than this info view?
