### ISSUE TITLE
Filter page not updating when selecting filter params

### ISSUE THREAD

**Issue by thecompassmaker** [mihonapp/mihon#893]
### Steps to reproduce

Enter Browse tab
Select filterable source
Tap filter
Change any param

### Expected behavior

changing any param should update the screen to reflect the selection

### Actual behavior

param does not update 

### Mihon version

r6723

### Android version

android 13

### Device

pixel 7 pro

### Other details

the filter page does update when the filter is sent (when the filter button on the filter page is tapped) and before the results are returned. the results coming back from the source do appear to correct. it seems to be a visual bug as when a checkbox is double tapped and the filter is sent, the checkbox is in the same state as it was before sending the filter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by deeplyarnab** [comment]
So, I've found that the parameters with checkboxes do get updated but no visual confirmation is shown (for both whitelist & blacklist options).
Any text fields just don't work, be it typing or copy pasting.

**Comment by thecompassmaker** [comment]
fwiw problem persists as of r6735

**Comment by amayra** [comment]
out of curiosity, what libraries is to blame for this bug, or is this a developer mistake ?

i couldn't find commit by developer that may result of this bug

**Comment by FooIbar** [comment]
> out of curiosity, what libraries is to blame for this bug, or is this a developer mistake ?
> 
> i couldn't find commit by developer that may result of this bug

Here 46003ec25139319079abc9fde89b3afd344a1a11
