### ISSUE TITLE
Downloads Remover option 

### ISSUE THREAD

**Issue by VigNesHReddy213** [mihonapp/mihon#897]
### Describe your suggested feature

We need the option remove all downloads and read downloads when we were downloaded chapters . 
It's so hard to remove each and every download everytime 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
I'm not sure what you're talking about, but you can delete downloaded chapters by selecting a title in your category (long press), then selecting any other series you may want to delete downloads of, and then tapping the deletion icon. You can also use the Select All icon at the top to select everything in the category.

You may also want to look into the "Download Ahead" and "Delete after Read" functionalities Mihon offers.

**Comment by VigNesHReddy213** [comment]
Yeah , i got to know those after I suggested this but , if we just put an option like delete all or delete read to select manually in the manhwa chapters section if possible, in case if we want to read again it'll be time saving.

**Comment by MajorTanya** [comment]
You can just filter to show read & downloaded chapters, select all, and delete those though?

**Comment by VigNesHReddy213** [comment]
Yeah we can , maybe i have been using tachij2k till now and I got used to it and found it easy compared to the method you said , is there a possibility of adding?

**Comment by Smol-Ame** [comment]
Closing in favor of #565 (more detailed & somewhat of a newer discussion)
