### ISSUE TITLE
Ease of Global search 

### ISSUE THREAD

**Issue by VigNesHReddy213** [mihonapp/mihon#898]
### Describe your suggested feature

When I am using global search, it will only show me pinned  results default but if we just give all search continuing normally, and we can all tap pinne search for pinned extensions, 
It depends on user but personally we should put a option like that in settings for which pinned or all extensions search 

### Other details

![Screenshot_2024-06-13-16-31-06-45_551f7f0ca926862b368845ce7ee433aa](https://github.com/mihonapp/mihon/assets/93344765/9f3cee93-873b-4e8a-82e0-a39dc18df2ee)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
The setting for that has also been denied repeatedly. It'll stay on Pinned by default.
