### ISSUE TITLE
PC App

### ISSUE THREAD

**Issue by rayyeras** [mihonapp/mihon#90]
### Describe your suggested feature

can we finally have a legitimate tachiyomi/mihon app for Pc

### Other details

the lack of options to read manga on pc absolutely shocks me, mihon PC is a MUST

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Maybe in the far future
