### ISSUE TITLE
Send to Kindle Feature for downloaded chapters

### ISSUE THREAD

**Issue by Rachit-Gandhi** [mihonapp/mihon#900]
### Describe your suggested feature

Ability to select multiple downloaded chapters and send them to Kindle app, 2 options possible
1. Using Share to Kindle Feature with Kindle app installed on android (Issue: Only one file at a time allowed as a document)
2. Using Calibre's technique of sending through mail to the registered kindle mail id. (Issue: Requires approval)

### Other details

Future development could be to add in app features like adjusting borders and for the kindle size variations and bundling volumes or chapters for efficient sending.
I understand it is detrimental for a reading app to redirect to a diff app or hardware, so this is just to understand what the community thinks of it.

Also I plan to develop it on my own so anyone who wants such a feature can join me, I will be having a fork for same. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Rachit-Gandhi** [comment]
To add to this feature, kindle doesn't accept cbz format hence cbz needs to be converted to a more convenient format, as it is a bunch of images zipped together, removing color or compressing them for space makes sense too

**Comment by AntsyLich** [comment]
You're basically looking for a downloader for your kindle. Mihon is not intended to be used that way. Thus making this an unnecessary feature. Tho in the future (no eta) I do plan to make a downloader so people can harness the power of extensions more.

P.S. If someone else makes I'll be happy to make it a part of the Mihon project.
