### ISSUE TITLE
Signup and login features to store our settings and libraries 

### ISSUE THREAD

**Issue by VigNesHReddy213** [mihonapp/mihon#906]
### Describe your suggested feature

Signup via Google, Facebook because of multiple devices sync and without worrying of backup file getting lost 
Whenever we login it will have all our data in the app like settings, history, libraries, 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
Another #40 callback

**Comment by AntsyLich** [comment]
If you want to pay $/month for it sure.
