### ISSUE TITLE
Option to change Open in Webview to Open in Browser

### ISSUE THREAD

**Issue by hpershdzy** [mihonapp/mihon#910]
### Describe your suggested feature

Toggle that removes the webview option and replaces it with the option to open the webpage in the default browser app instead

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No. WebView is important part of the app.
