### ISSUE TITLE
[Feature request] secure individual tabs

### ISSUE THREAD

**Issue by KairuDeibisu** [mihonapp/mihon#919]
### Describe your suggested feature

I should be able to open the app without biometrics but on opening a specific tab get a prompt to either sign into my phone with my password, or use my biometrics. 

In the menu where you manage your tabs. There would be a lock icon on each tab to mark it as protected or not. 

### Other details

Right now biometrics is only for locking the entire app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
No
