### ISSUE TITLE
add a check for extension updates button

### ISSUE THREAD

**Issue by MarshMeadow** [mihonapp/mihon#925]
### Describe your suggested feature

add a check for extension updates button so that if it dose not check automatically that you can do it manually that would be nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
You can already do that by pulling to refresh on the extension list.
