### ISSUE TITLE
Improved History

### ISSUE THREAD

**Issue by VirYouth** [mihonapp/mihon#930]
### Describe your suggested feature

Right now the way history works in Mihon is this:

• You read a manga 
• The app will record it to the history
• You read the manga again on another day
• The app will overwrite the previous history and record it to the day you resumed 

So you will have no way to track it when you first started reading the manga, as well as track the manga if it somehow got removed in your library and the one record of it's history

The Improved History should work like this:

• You read a manga
• The app will record the history
• You read the manga on another day 
• The app will record another history for that day **WITHOUT** overwriting the previous history 

Thank you for reading this...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Imagine you read a Manga with hundreds of chapters and your history page has an row for each chapter you read. That's just going to I be insanely cluttered.

Also, from what I know thats not how it records history. The history does not get overwritten, but the app will only display the last change for eg. If you read chapter 100 it's not going to show chapter 99 in the history as well. But it's history information is infact stored.

For each chapter, it records the timestamp of when you started to read it and how long you read it for. But of course the only way you can get this granular information is to decode the backup file. 

_Shameless plug. Me and a few others are working on a tool to retrieve all this information from the backup in a user friendly way, you'll probably see progress updates on the discord server._

**Comment by VirYouth** [comment]
Sorry, I didn't mean that all the chapters you read should be shown in the history, what I meant was that the last chapter you read for that day
 for example:
 June 30 
[Title of manga] last chapter read...

 July 2
[Same manga] latest chapter read.... 

It's not like you would read 1 chapter per day of a manga that has hundreds of chapters and if someone do there's still the fact that they can search the specific title of the mange they want to find

**Comment by AntsyLich** [comment]
> So you will have no way to track it when you first started reading the manga,

Why does it even matter?

> as well as track the manga if it somehow got removed in your library and the one record of it's history

If one gets removed all will be removed. And you don't accidentally remove manga and it's corresponding history.

**Comment by VirYouth** [comment]
> > Why does it even matter?
> 
> Yeah it serves little purpose, but I'm just asking if its possible to add the feature because maybe it will help the users use the history more conveniently
>
> > If one gets removed all will be removed. And you don't accidentally remove manga and it's corresponding history.
>
> I didn't know that it all gets removed, But I don't accidentally nor purposely remove both the manga and it's history, there's time when I stopped reading a manga to wait for an update, the manga just disappear from the library, history, and it's hard to know if its gone when you have thousands of manga in your library and even when I get it back from the same extension the chapters are no longer highlighted as read.

Again, it's just a suggestion, I know you have many other things to do aside fulfilling feature request and in the end it's up to you guys to decide whether to add this or not and I respect that. You guys have done so much already so that we can enjoy reading manga and I appreciate that.

**Comment by AntsyLich** [comment]
> and the manga just disappears from the library

no it doesn't

> history

shitty website changing chapter url is not mihon's fault
