### ISSUE TITLE
button to force update trackers chapter count

### ISSUE THREAD

**Issue by holy-mother-I-am-drunk** [mihonapp/mihon#931]
### Describe your suggested feature

I would really like to have a button in advanced settings of the app.
Just like force recheck downloads, it forces the trachers to update chapter counts for all entries with a tracker enabled.

### Other details

When trackers stop working (like MAL does) and the chapter count gets stuck/stagnates, I have to manually update each entry once the tracking starts working again.
That's why I would really like a way to force all of them to be Synced

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment]
I can almost guarantee that's not gonna happen as it would enable users to bombard the trackers with requests, which would at best cause a temporary block on the user for hitting a rate-limit, and at worst a ban or even them blocking the app altogether
