### ISSUE TITLE
Add an option to exclude every scanlator of a Manga

### ISSUE THREAD

**Issue by MiiJack** [mihonapp/mihon#943]
### Describe your suggested feature

There should be an option near the reset button to exclude every scanlators in case a manga got several groups. Or add option to only include a few groups instead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
> Or add option to only include a few groups instead.
Not adding this but I'll consider the first part
