### ISSUE TITLE
An extension Alternative

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [mihonapp/mihon#950]
### Describe your suggested feature

Like in the video.

https://github.com/mihonapp/mihon/assets/169121286/51cf3e98-29bf-4aa7-bf17-830c05af492f

can be referred [Legado](https://github.com/gedoor/legado/blob/master/English.md)>Sources management>Import online> 
```https://raw.githubusercontent.com/Zig-Rust-Odin/pixel9/main/comicsSource.json```

# Expansion flaws
Once the comic changes URLs, the extension apk won't work, it's a pain in the ass to change URLs, it needs to be compiled into an apk, it needs to be installed, and it's a pain in the ass to change URLs.

You can't install 100 extensions apk.
* json can have 100-10000 comic sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Zig-Rust-Odin** [comment]
> Sure you make your json work with 1000+ different websites, this is a legal app though so...

mihon doesn't have a built-in json comic source, which should be legal.

**Comment by AntsyLich** [comment]
I still don't understand your request.

**Comment by MajorTanya** [comment]
The problem with this request is that a lot of sources don't have a standardised API for apps like Mihon to use. There are a lot of extensions floating around that have some kind of custom handling of the source in them when you check their source code. I don't see a way of making that possible with a json file, which would probably only list the base URLs of the sources.

**Comment by AntsyLich** [comment]
Make an source that parse that json and provides content to mihon.

And you can have a million source in one extensions
