### ISSUE TITLE
Create Backup On Exit

### ISSUE THREAD

**Issue by MohamadTaher** [mihonapp/mihon#954]
### Describe your suggested feature

I have succeeded in syncing between two devices by using Syncthing. But unfortunately, it is not perfect yet.

I need to create a backup manually before exiting the app every time.

I want to automate the process by automatically creating a backup when I exist the app.

The option is already present in the backend. Just a simple modification in "Automatic Backup Frequency" will do it.

Can you please add an option? Here is a picture of what I'm talking about.

![Screenshot 2024-06-26 000650](https://github.com/mihonapp/mihon/assets/67930481/b83ae28d-c904-4c8a-84ab-7e87d66849be)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Very niche feature. No from me.

**Comment by AntsyLich** [comment]
Run this [worker](https://github.com/mihonapp/mihon/blob/main/app/src/main/java/eu/kanade/tachiyomi/data/backup/create/BackupCreateJob.kt)
