### ISSUE TITLE
Error 400 bad request

### ISSUE THREAD

**Issue by Veer-1709** [mihonapp/mihon#961]
### Steps to reproduce

1. Im pretty well aware of the automatic tracking feature of the mihon app and ive been a very big fan of it since its original version. But here, after getting a new mobile(of samsung) whenever i try to link my MAL account to mihon for the tracking, it redirects me to the webpage of MAL even though i already have its app as well.
2. There whenever i then try to link the account with mihon using the allow button after logging into my MAL account the error occurs
3. That error is that the web page with MAL's interface shows me the message error 400 bad request and under it is written that your request produced an error, try again etc. but no matter how
 many times i try i just cant get my MAL account connected to mihon. Here's a picture of the error page im seeing

![Screenshot_20240627_103048_Chrome](https://github.com/mihonapp/mihon/assets/147521478/3b18dc7b-e4c5-4ab8-8f73-80dd338aa57c)

### Expected behavior

After allowing from the webpage of MAL my MAL should have gotten connected to mihon and tracking should have been made available to me to track any manga i want

### Actual behavior

My MAL account is not getting connected to Mihon no matter how many times i try

### Mihon version

0.16.5

### Android version

Android 14

### Device

Samsung galaxy A15 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Hazzardousgamer** [comment]
> Log out of MAL in your browser & close any MAL-related tabs, then make sure your browser can redirect/open in apps, and try linking again
> 
> Just in case, as a reminder, to link MAL on Mihon, you need to be using 0.16.5 and you need to replace the default user-agent in the app with a different user-agent (Mihon Settings > Advanced)

I for one have my account linked, but I'm only getting error 401 when trying to use the tracker recently
