### ISSUE TITLE
Add framework for background music

### ISSUE THREAD

**Issue by knorke3** [mihonapp/mihon#970]
### Describe your suggested feature

Many Webtoons comics have background music set to start/stop playing on certain pages in the comic. I'd love to see a framework for this functionality so archiving this can be implemented in the relevant source.

### Other details

For an example, see 'Dreamwalker' by 'Magikfire'

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
literally 2 site has it and none of them let you play music without their app.

**Comment by knorke3** [comment]
I just tried it on the Webtoons website and their online reader plays music without problems, so it should be scrapeable. With how big Webtoons is, I do feel that it would be worth it.

**Comment by AntsyLich** [comment]
No means no and like having Kakao on the back wasn't enough
