### ISSUE TITLE
Add custom themes

### ISSUE THREAD

**Issue by isabella-almeidaa** [mihonapp/mihon#973]
### Describe your suggested feature

Add a way to make custom themes (selectable colors etc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment]
Would be cool but I feel like barely anyone would use it.
If you really want a custom theme desperately just reference [this](https://github.com/Animeboynz/tachiyomi/commit/c9b2082e2a42e99bf3b06a0fdd1c70a7c498b11e) and build it yourself.

**Comment by AntsyLich** [comment]
You need to select well over 20 colors to make an actual theme. i see no point behind this.
