### ISSUE TITLE
Sync Local Data with Anilist

### ISSUE THREAD

**Issue by mkoge** [mihonapp/mihon#979]
### Describe your suggested feature

Syncing progressing across devices using a sync local data option would be helpful. I saw these feature integrated with an ios app called Aidoku, think it would be really nice to have on android.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Duplicate of #531
