### ISSUE TITLE
add a setting to uninstall the extension apk while disable a source

### ISSUE THREAD

**Issue by gjguo** [mihonapp/mihon#980]
### Describe your suggested feature

Please add a setting to uninstall the extension apk while disable a source, and marked not to install as new extension. Maybe someone needs it, like me, I don't need a extension apk is still installed in my phone after I have disabled it. Thanks you all, Mihon is a great and convenient tool for manga lovers. There are so many extensions in my phone, I only need some of them. I have tried to uninstall many extensions I don't want, but when new extensions appear ready to install, they are all mixed up and I can't distinguish from them. Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by gjguo** [comment]
Thanks your Information.
There are something to say
1. I know how to uninstall extension apk form mihon or system
2. Extension name in source tab and extension tab are not always the same, like attachment pictures. The order are not the same, too.
3. After I uninstalled an extension I don't want, if the extension have new update version, It appears in the extension tab waiting to install. I had uninstalled many extensions, and I don't want maintain a list to check.
4. So I have to keep all extensions installed and set disable to what extensions I don't want. But it slow down my phone when I check phone system safety, and occupied spaces.
Thanks all your help.
![Screenshot_2024-07-04-17-16-28-469_app mihon-edit](https://github.com/mihonapp/mihon/assets/1726094/4b1bdad4-2b69-4bc5-a604-63a26404690f)
![Screenshot_2024-07-04-17-16-00-627_app mihon-edit](https://github.com/mihonapp/mihon/assets/1726094/2f1c3bfe-68ae-4ebc-bad2-5fc4fd51e566)

**Comment by gjguo** [comment]
Thanks again.
I tried below:
1. uninstall what I don't want, as first pic
2. They appear immediately as "waiting to install" as second pic
3. If there are other new extensions, they are all mixed
That's what I don't want to see

![Screenshot_2024-07-04-18-34-04-205_app mihon](https://github.com/mihonapp/mihon/assets/1726094/0c55819d-8d1d-406b-aa32-c2a23fdec0e9)
![Screenshot_2024-07-04-18-37-37-062_app mihon](https://github.com/mihonapp/mihon/assets/1726094/be438fd5-567e-4257-880b-d751ea332cac)

**Comment by gjguo** [comment]
Thanks your help
If there are new(not updated) extensions, they will appear between the extensions I uninstalled already in extension tab, and I can't distinguish them apart.

**Comment by BrutuZ** [comment]
Why would you need to?

**Comment by gjguo** [comment]
> Why would you need to?

Thanks reply.
I need to pick up new(not update) extensions to install to see if I need it's manga.
And I don't want install extensions which I had uninstalled.
Now I can't separate them in extension tag
Thank your attention.
