### ISSUE TITLE
Add private installer from preview to standard version

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#982]
### Describe your suggested feature

Example: "It should work like this..."
Private installer by default
![Screenshot_2024-07-04-17-47-49-538_app mihon debug](https://github.com/mihonapp/mihon/assets/25694091/6be4e1ee-3945-48ba-8c93-4957cef6a285)

### Other details

Best installer

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
I will when I see fit
