### ISSUE TITLE
assign filters to categories

### ISSUE THREAD

**Issue by BPplays** [mihonapp/mihon#986]
### Describe your suggested feature

i would like to be able to assign a filter or multiple to a category that will automatically add or remove content from a source based on the filter.

for example i would like to set the category 漫画 to automatically add or remove content based on whats in `Kavita (1) > Libraries > 漫画`, which would essentially make the category a mirror of the kavita library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The app doesn't work that way and never will.
