### ISSUE TITLE
Allow the use of fingerprint sensor to switch pages

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [mihonapp/mihon#995]
### Describe your suggested feature

Simply tapping the sensor would change to the next page, similar to volume buttons. Especially useful with phones like Redmi Note 7 where the fingerprint sensor is at the back.

### Other details

Would be nice if that was a setting. Also for devices that have the fingerprint on the power button like Redmi Note 12 Pro Plus, a setting to not switch the page if the power button is pressed would be great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
I don't think this is even possible? The fingerprint reader is a biometric interface. It's not a normal button/interactable thing as far as I'm aware.

**Comment by vetleledaal** [comment]
https://developer.android.com/reference/android/accessibilityservice/FingerprintGestureController ?
Seem to require some invasive permissions
